### ISSUE TITLE
A problem on OnePlus5T with Android 9.0,It doesn't work.

### ISSUE THREAD

**Issue by chunyuong** [openstf/stf#1000]
2018-12-26T02:55:10.572Z IMP/device:plugins:group 169 [d5644650] Now owned by "admin@qq.com"
2018-12-26T02:55:10.573Z INF/device:plugins:group 169 [d5644650] Subscribing to group channel "+TyItKJURCWhYJ2cuJ1NhQ=="
2018-12-26T02:55:10.637Z INF/device:plugins:screen:stream 169 [d5644650] Setting frame producer projection to 778x778
2018-12-26T02:55:10.638Z INF/device:plugins:screen:stream 169 [d5644650] Requesting frame producer to start
2018-12-26T02:55:10.639Z INF/device:plugins:screen:stream 169 [d5644650] Launching screen service
2018-12-26T02:55:10.639Z INF/device:plugins:screen:stream 169 [d5644650] ++++++ Launching screen service +++++++
2018-12-26T02:55:10.658Z INF/device:plugins:screen:stream 169 [d5644650] minicap says: "CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": "/data/local/tmp/minicap.so" is 32-bit instead of 64-bit"
2018-12-26T02:55:10.659Z WRN/device:plugins:screen:stream 169 [d5644650] Shell keeping minicap running ended unexpectedly
2018-12-26T02:55:10.699Z IMP/device:plugins:connect 169 [d5644650] Remote Connect Started for device "d5644650" at "10.10.10.10:11053"
2018-12-26T02:55:12.647Z INF/device:plugins:screen:stream 169 [d5644650] Disconnecting from minicap service
2018-12-26T02:55:12.647Z INF/device:plugins:screen:stream 169 [d5644650] Stopping minicap service
2018-12-26T02:55:12.648Z FTL/device:plugins:screen:stream 169 [d5644650] Frame producer had an error TimeoutError: operation timed out
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
From previous event:
    at FrameProducer._waitForPid (/app/lib/units/device/plugins/screen/stream.js:273:10)
    at FrameProducer.<anonymous> (/app/lib/units/device/plugins/screen/stream.js:80:27)
    at FrameProducer.tryCatcher (/app/node_modules/._bluebird@2.9.34@bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/._bluebird@2.9.34@bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/app/node_modules/._bluebird@2.9.34@bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/app/node_modules/._bluebird@2.9.34@bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/app/node_modules/._bluebird@2.9.34@bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/node_modules/._bluebird@2.9.34@bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/app/node_modules/._bluebird@2.9.34@bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
2018-12-26T02:55:12.648Z FTL/util:lifecycle 169 [d5644650] Shutting down due to fatal error
2018-12-26T02:55:12.649Z INF/util:lifecycle 169 [d5644650] Winding down for graceful exit
2018-12-26T02:55:12.650Z INF/device:plugins:screen:stream 169 [d5644650] Requesting frame producer to stop
2018-12-26T02:55:12.650Z INF/device:plugins:screen:stream 169 [d5644650] Requesting frame producer to stop
2018-12-26T02:55:12.655Z INF/provider 1 [*] Cleaning up device worker "d5644650"
2018-12-26T02:55:12.655Z ERR/provider 1 [*] Device worker "d5644650" died with code 1
2018-12-26T02:55:12.655Z INF/provider 1 [*] Restarting device worker "d5644650"

**Comment by sorccu** [comment]
Have you modified the source code or built minicap yourself?

**Comment by chunyuong** [comment]
> Have you modified the source code or built minicap yourself?
I don't have, what I use is the official

**Comment by thinkhy** [comment]
@chunyuong Did this problem occur on other devices upgraded to Android 9.0?

**Comment by chunyuong** [comment]
I have already solved this problem, because I was using an old version of STF, the new version of stf  do not have this problem.thanks!

**Comment by csdaa** [comment]
> I have already solved this problem, because I was using an old version of STF, the new version of stf do not have this problem.thanks!

hi guys,which version
