### ISSUE TITLE
Screen transmission is very slow

### ISSUE THREAD

**Issue by scvjx** [openstf/stf#1001]
Hello , we find  client in local network(intranet) visit STF, it  work very well. But the client in internet visit STF, the phone screen transmission is very slow  and STF console return error:

Why it does not work in internet?   We check the client network rate is no problem. What can we do?

 Unhandled rejection Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
From previous event:
    at send (/usr/local/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:508:20)
    at Object.wsFrameNotifier [as onFrame] (/usr/local/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:546:20)
    at /usr/local/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:490:43
    at Array.map (<anonymous>)
    at FrameProducer.next (/usr/local/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:489:49)
    at FrameProducer.emit (/usr/local/lib/node_modules/stf/node_modules/eventemitter3/index.js:115:35)
    at FrameProducer._maybeEmitReadable (/usr/local/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:413:14)
    at FrameProducer._readableListener (/usr/local/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:419:12)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

**Comment by sorccu** [comment]
I think we need to fix something here but overall STF was not designed for a high latency scenario. It seems to me like it may be trying to send frames too quickly.

**Comment by scvjx** [comment]
Thank you for answer, what can I do for this issue?  Can I  reduce minicap picture resolution or picture file size ?  Can I reduce send  frames?....etc

**Comment by alvarofagner** [comment]
Hi, we have the same problem now that we need to work from home and our STF is at the office. Is there a way to make minicap to work a more lightweight way? Even if that means worse resolution.

**Comment by scvjx** [comment]
> Hi, we have the same problem now that we need to work from home and our STF is at the office. Is there a way to make minicap to work a more lightweight way? Even if that means worse resolution.

You can modify the code yourself, and the minicap startup command can set the scale of the picture.

You can also try my own remote control project,https://github.com/scvjx/PhoneRemoteControlPlatform   ：)
