### ISSUE TITLE
Illegal value for Message.Field

### ISSUE THREAD

**Issue by renguoliang** [openstf/stf#1007]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by renguoliang** [comment]
Unhandled rejection Error: Illegal value for Message.Field .DeviceIntroductionMessage.status of type enum: undefined (not a valid enum value)
    at Field.<anonymous> (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2738:25)
    at MessagePrototype.set (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1799:63)
    at new Message (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1728:42)
    at /home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:165:29
    at /home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:161:22
    at Tracker.<anonymous> (/home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:144:16)
    at emitOne (events.js:125:13)
    at Tracker.emit (events.js:221:7)
    at Tracker.update (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:62:14)
    at /home/lianjia/nom-global/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:38:15
    at runCallback (timers.js:800:20)
Unhandled rejection Error: Illegal value for Message.Field .DeviceIntroductionMessage.status of type enum: undefined (not a valid enum value)
    at Field.<anonymous> (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2738:25)
    at MessagePrototype.set (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1799:63)
    at new Message (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1728:42)
    at /home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:165:29
    at /home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:161:22
    at Tracker.<anonymous> (/home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:144:16)
    at emitOne (events.js:125:13)
    at Tracker.emit (events.js:221:7)
    at Tracker.update (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:62:14)
    at /home/lianjia/nom-global/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:38:15
    at runCallback (timers.js:800:20)
Unhandled rejection Error: Illegal value for Message.Field .DeviceIntroductionMessage.status of type enum: undefined (not a valid enum value)
    at Field.<anonymous> (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2738:25)
    at MessagePrototype.set (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1799:63)
    at new Message (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1728:42)
    at /home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:165:29
    at /home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:161:22
    at Tracker.<anonymous> (/home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:144:16)
    at emitOne (events.js:125:13)
    at Tracker.emit (events.js:221:7)
    at Tracker.update (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:62:14)
    at /home/lianjia/nom-global/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:38:15
    at runCallback (timers.js:800:20)
Unhandled rejection Error: Illegal value for Message.Field .DeviceIntroductionMessage.status of type enum: undefined (not a valid enum value)
    at Field.<anonymous> (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2738:25)
    at MessagePrototype.set (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1799:63)
    at new Message (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1728:42)
    at /home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:165:29
    at /home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:161:22
    at Tracker.<anonymous> (/home/lianjia/nom-global/lib/node_modules/stf/lib/units/provider/index.js:144:16)
    at emitOne (events.js:125:13)
    at Tracker.emit (events.js:221:7)
    at Tracker.update (/home/lianjia/nom-global/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:62:14)
    at /home/lianjia/nom-global/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:38:15
    at runCallback (timers.js:800:20)
