### ISSUE TITLE
getting error in running  npm install -g stf

### ISSUE THREAD

**Issue by jaiswalshubham84** [openstf/stf#1020]
getting error in running  npm install -g stf
node -v
v8.15.0
npm -v
6.4.1

[2019-02-21T09_19_08_494Z-debug.log](https://github.com/openstf/stf/files/2888952/2019-02-21T09_19_08_494Z-debug.log)

**Comment by koral--** [comment]
Is it also reproducible on 8.14.0?

**Comment by NaveenGovindraj** [comment]
Hello,

PS C:\WINDOWS\system32> node -v
v8.14.0
PS C:\WINDOWS\system32> npm -v
6.4.1

Trying to setup STF on Windows 7 and I am facing the below error:

Any help will be highly appreciated. Let me know if any more information is required.

PS C:\WINDOWS\system32> npm install -g stf
npm WARN deprecated @slack/client@3.16.0: v3.x and lower are no longer supported. see migration guide: https://github.co
m/slackapi/node-slack-sdk/wiki/Migration-Guide-for-v4
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated ejs@0.8.8: Critical security bugs fixed in 2.5.5
C:\Users\govinna\AppData\Roaming\npm\stf -> C:\Users\govinna\AppData\Roaming\npm\node_modules\stf\bin\stf

> dtrace-provider@0.8.7 install C:\Users\govinna\AppData\Roaming\npm\node_modules\stf\node_modules\dtrace-provider
> node-gyp rebuild || node suppress-error.js


C:\Users\govinna\AppData\Roaming\npm\node_modules\stf\node_modules\dtrace-provider>if not defined npm_config_node_gyp (n
ode "C:\Users\govinna\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\govinna\AppData\Roaming\npm\node_modules\npm\node_modules\node-
gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\govinna\AppData\Roaming\npm\node_modules\stf\node_modules\dtrace-provider\build\DTraceProviderStub.vcxproj(20,
3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <I
mport> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\govinna\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\l
ib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\govinna\\AppData\\Roaming\\npm\\node_modules\\npm\\no
de_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\govinna\AppData\Roaming\npm\node_modules\stf\node_modules\dtrace-provider
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> bufferutil@1.3.0 install C:\Users\govinna\AppData\Roaming\npm\node_modules\stf\node_modules\bufferutil
> node-gyp rebuild


C:\Users\govinna\AppData\Roaming\npm\node_modules\stf\node_modules\bufferutil>if not defined npm_config_node_gyp (node "
C:\Users\govinna\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-g
yp\bin\node-gyp.js" rebuild )  else (node "C:\Users\govinna\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\b
in\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\govinna\AppData\Roaming\npm\node_modules\stf\node_modules\bufferutil\build\bufferutil.vcxproj(20,3): error MSB
4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declar
ation is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\govinna\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\l
ib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\govinna\\AppData\\Roaming\\npm\\node_modules\\npm\\no
de_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\govinna\AppData\Roaming\npm\node_modules\stf\node_modules\bufferutil
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\govinna\AppData\Roaming\npm-cache\_logs\2019-03-27T20_37_50_197Z-debug.log

**Comment by ArthurMaroulier** [comment]
Same error on Mac OS with node v10.16.0 and node v12.4.0.
Don't know how to solve this.
And no, deleting the node_modules didn't solve the problem...

**Comment by helloranger** [comment]
My stf modules in these version：
node： 8.14.0
python：2.7.17

**Comment by kiminox** [comment]
Hi,
Same error for Mac OS X 10.15 Catalina.
node : v8.17.0
npm : 6.13.4
I followed the installation guide https://github.com/openstf/stf with installation of :
- Node.js 8.x required (some dependencies don't support newer versions) : download version 8 here : https://nodejs.org/dist/latest-v8.x/node-v8.17.0.pkg
- ADB : install with the commande "brew cask install android-platform-tools"
The following components have been installed with 
brew install rethinkdb graphicsmagick zeromq protobuf yasm pkg-config

- RethinkDB >= 2.2
- GraphicsMagick (for resizing screenshots)
- ZeroMQ libraries installed
- Protocol Buffers libraries installed
- yasm installed (for compiling embedded libjpeg-turbo)
- pkg-config so that Node.js can find the libraries

Everything was fine.
But the final command to install stf didn't work : 
npm install -g stf (with or without sudo)

A lot of warning deprecated messages from npm : 
![image](https://user-images.githubusercontent.com/1988672/79317181-abac9600-7f05-11ea-8a59-94d430b8625e.png)

Then error messages : 
![image](https://user-images.githubusercontent.com/1988672/79317269-ce3eaf00-7f05-11ea-9710-44be8a62af59.png)

Any idea?
Thank you

**Comment by kiminox** [comment]
The log file :

[2020-04-15T08_41_00_963Z-debug.log](https://github.com/openstf/stf/files/4480064/2020-04-15T08_41_00_963Z-debug.log)
