### ISSUE TITLE
LDAP auth problem

### ISSUE THREAD

**Issue by paulvelzeboer** [openstf/stf#1021]
Im using the ldap authentication for our config. its running on a Mac pro. running local with mock no problems but when turning LDAP auth on i get the following error:

``` 
2019-02-21T12:59:17.545Z ERR/auth-ldap 56466 [::ffff:127.0.0.1] Unexpected error TimeoutError: request timeout (client interrupt)
    at Timeout.onRequestTimeout (/usr/local/lib/node_modules/stf/node_modules/ldapjs/lib/client/client.js:1435:10)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
Unhandled rejection TimeoutError: request timeout (client interrupt)
    at Timeout.onRequestTimeout (/usr/local/lib/node_modules/stf/node_modules/ldapjs/lib/client/client.js:1435:10)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5) 
```

starting STF with the following command:

stf local --public-ip='$PUBLIC_IP' --allow-remote --auth-type ldap

and having set the following variables:

export STF_AUTH_LDAP_APP_URL="http://$PUBLIC_IP"
#export STF_AUTH_LDAP_LDAP_BIND_CREDENTIALS=
export STF_AUTH_LDAP_LDAP_BIND_DN="cn=###,ou=Teams,ou=###,ou=Services,ou=Groups,o=###"
#export STF_AUTH_LDAP_LDAP_SEARCH_CLASS=
export STF_AUTH_LDAP_LDAP_SEARCH_DN="ou=People,o=###"
export STF_AUTH_LDAP_LDAP_SEARCH_FIELD="uid"
#export STF_AUTH_LDAP_LDAP_SEARCH_SCOPE=
#export STF_AUTH_LDAP_LDAP_TIMEOUT=
export STF_AUTH_LDAP_LDAP_URL="ldap://prod.###.intranet:636"
export STF_AUTH_LDAP_LDAP_USERNAME_FIELD="uid"
#export STF_AUTH_LDAP_PORT=

###= masked data 

If i look in the chrome browser console i have the following error:
```
3.16f08148f286d4b28c8f.chunk.js:12270 POST http://localhost:7100/auth/api/v1/ldap 500 (Internal Server Error)
```

**Please run `stf doctor` and paste the output here.**

2019-02-21T13:07:36.979Z INF/cli:doctor 56577 [*] OS Arch: x64
2019-02-21T13:07:36.981Z INF/cli:doctor 56577 [*] OS Platform: darwin
2019-02-21T13:07:36.981Z INF/cli:doctor 56577 [*] OS Platform: 17.7.0
2019-02-21T13:07:36.981Z INF/cli:doctor 56577 [*] Using Node 9.5.0
2019-02-21T13:07:36.999Z INF/cli:doctor 56577 [*] Using ZeroMQ 4.3.1
2019-02-21T13:07:37.017Z INF/cli:doctor 56577 [*] Using GraphicsMagick 1.3.31
2019-02-21T13:07:37.022Z INF/cli:doctor 56577 [*] Using ProtoBuf 3.6.1
2019-02-21T13:07:37.028Z INF/cli:doctor 56577 [*] Using ADB 1.0.39
2019-02-21T13:07:37.032Z INF/cli:doctor 56577 [*] Using RethinkDB 2.3.6

**Comment by sorccu** [comment]
Your ldap server is not responding. Perhaps the URL is wrong or there’s a firewall.

**Comment by paulvelzeboer** [comment]
> Your ldap server is not responding. Perhaps the URL is wrong or there’s a firewall.

you are right my mistake. tried the right LDAP server  but get a certificate chain error but thats not related to stf.

```
2019-02-21T13:32:02.566Z INF/db 57104 [*] Connecting to 127.0.0.1:28015
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1041:34)
    at TLSSocket.emit (events.js:160:13)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)
2019-02-21T13:32:16.484Z ERR/poorxy 57109 [*] Proxy had an error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at Socket.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
2019-02-21T13:32:16.485Z FTL/cli:local 57094 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
```

**Comment by paulvelzeboer** [comment]
if i use export NODE_TLS_REJECT_UNAUTHORIZED=0 its fixed...

thanks for the help will close this issue
