### ISSUE TITLE
Can't take screenshot on MAC OS X 10.11

### ISSUE THREAD

**Issue by AnikiKun** [openstf/stf#103]
Hi,

```
stf -V
1.0.10
```

when I click,
![5802f33a-f899-42eb-b0c6-2962bf2d54f5](https://cloud.githubusercontent.com/assets/5791692/10384774/3669aff6-6e73-11e5-988c-832fecab3d37.png)

then,
![4da2c1d8-69c3-49ba-9f24-a2d52e47d098](https://cloud.githubusercontent.com/assets/5791692/10384777/415ec608-6e73-11e5-959a-8a58789d891b.png)

log:
```bash
NF/device:plugins:group 64490 [3190de0d] Subscribing to group channel "mUID/6efQI6QkUp3n9mv4A=="
WRN/util:datautil 64482 [*] Device database does not have a match for device "3190de0d" (model "HM NOTE 1S"/"gucci")
INF/device:plugins:screen:stream 64490 [3190de0d] Setting frame producer projection to 486x810
INF/device:plugins:screen:stream 64490 [3190de0d] Requesting frame producer to start
INF/device:plugins:screen:stream 64490 [3190de0d] Launching screen service
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "PID: 17457"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: Using projection 720x1280@456x810/0"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:255) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 64490 [3190de0d] Connecting to minicap service
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:258) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:265) Creating virtual display"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:271) Creating buffer queue"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:278) Creating CPU consumer"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:284) Creating frame waiter"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:288) Publishing virtual display"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection"
INF/device:plugins:screen:stream 64490 [3190de0d] Reading minicap banner
INF/provider 64480 [*] Providing all 3 device(s)
INF/device:plugins:screen:stream 64490 [3190de0d] Requesting frame producer to stop
INF/device:plugins:screen:stream 64490 [3190de0d] Disconnecting from minicap service
INF/device:plugins:screen:stream 64490 [3190de0d] Stopping minicap service
INF/device:plugins:screen:stream 64490 [3190de0d] Sending SIGTERM to minicap
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (jni/minicap/minicap.cpp:512) Closing client connection"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (jni/minicap/minicap.cpp:196) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:303) Destroying virtual display"
INF/device:plugins:screen:stream 64490 [3190de0d] Keeping 486x810 as current frame producer projection
INF/device:plugins:screen:stream 64490 [3190de0d] Requesting frame producer to start
INF/device:plugins:screen:stream 64490 [3190de0d] Launching screen service
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "PID: 17465"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: Using projection 720x1280@456x810/0"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:255) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:258) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:265) Creating virtual display"
INF/device:plugins:screen:stream 64490 [3190de0d] Connecting to minicap service
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:271) Creating buffer queue"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:278) Creating CPU consumer"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:284) Creating frame waiter"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:288) Publishing virtual display"
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
INF/device:plugins:screen:stream 64490 [3190de0d] Reading minicap banner
INF/device:plugins:screen:stream 64490 [3190de0d] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection"
INF/device:plugins:screen:capture 64490 [3190de0d] Capturing screenshot
INF/storage:temp 64484 [*] Uploaded "3190de0d.jpg" to "/var/folders/80/xbm17qz14j1_2_0_y1s3dgpr0000gn/T/upload_8fae0bbbc02ef9974098de898824f310"
INF/device:support:storage 64490 [3190de0d] Uploaded to "/s/image/30bc148e-5f9c-4f8e-9ffd-dc4aec992089/3190de0d.jpg"
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn gm ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
ERR/poorxy 64487 [*] Proxy had an error Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at Socket.socketOnEnd (_http_client.js:300:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
FTL/cli:local 64473 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
INF/cli:local 64473 [*] Shutting down all child processes
INF/util:lifecycle 64475 [app001] Winding down for graceful exit
INF/util:lifecycle 64477 [proc001] Winding down for graceful exit
INF/util:lifecycle 64476 [dev001] Winding down for graceful exit
INF/util:lifecycle 64478 [proc002] Winding down for graceful exit
INF/util:lifecycle 64479 [reaper001] Winding down for graceful exit
INF/util:lifecycle 64480 [*] Winding down for graceful exit
INF/util:lifecycle 64482 [*] Winding down for graceful exit
INF/util:lifecycle 64481 [*] Winding down for graceful exit
INF/util:lifecycle 64483 [*] Winding down for graceful exit
```

Can you help?
thx!

**Comment by sorccu** [comment]
It's because you didn't install GraphicsMagick. You need to have all the requirements installed or it's not going to work.

**Comment by AnikiKun** [comment]
yep, thx.

I installed GraphicsMagick by Macports at first,  it dosn't work.

It must use Homebrew.

**Comment by sorccu** [comment]
Well, technically you can use method you want, as long as the `gm` binary can be found in your `$PATH`.
