### ISSUE TITLE
adb keygen no longer generates the public key

### ISSUE THREAD

**Issue by clementcontet** [openstf/stf#1033]
**What is the issue or idea you have?**
When using STF, I have to enter my adb public key.
But since this commit (https://android.googlesource.com/platform/system/core/+/2dc4cabe0639c71014d729dd92eff19289429c89), adb keygen no longer generates the public key.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
N/A

**Please provide the steps to reproduce the issue.**
adb keygen toto => generates toto but not toto.pub

**What is the expected behavior?**
Though question... Make STF usable without any public key?

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
N/A

**Please run `stf doctor` and paste the output here.**
N/A

**Comment by denis99999** [comment]
Hello @clementcontet 

In fact, I found a private ADB command while browsing the github source, this is the `adb pubkey` command, it seems it waits for the private key generated from the `adb keygen` command.

So I tried this:
```
# adb keygen toto
# adb pubkey toto > toto.pub
```
If I try to manually add `toto.pub` as a key into my STF account, it is not recognized by STF, except if I append to the key a space + a name (i.e. the one to fill into the device field), knowing in this case it can't work anymore because there is a mismatch between the private key and the public key!

In any case, while trying to `adb connect` to a device, the provided private key is not recognized by STF which display the following error at provider side:

```
2019-04-02T17:09:03.232Z INF/device:plugins:connect 802 [CB512EDDM1] New remote ADB connection from ::ffff:10.193.13.55
2019-04-02T17:09:03.277Z FTL/util:lifecycle 802 [CB512EDDM1] Remote ADB had an error Error: Unrecognizable public key format
at /app/node_modules/adbkit/lib/adb/auth.js:69:23
at tryCatcher (/app/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
at Promise._resolveFromResolver (/app/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:476:31)
at new Promise (/app/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:69:37)
at Function.Auth.parsePublicKey (/app/node_modules/adbkit/lib/adb/auth.js:62:12)
at Socket._handleAuthPacket (/app/node_modules/adbkit/lib/adb/tcpusb/socket.js:168:21)
at /app/node_modules/adbkit/lib/adb/tcpusb/socket.js:109:26
at tryCatcher (/app/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
at Function.Promise.attempt.Promise.try (/app/node_modules/adbkit/node_modules/bluebird/js/main/method.js:31:24)
at Socket._handle (/app/node_modules/adbkit/lib/adb/tcpusb/socket.js:95:26)
at emitOne (events.js:116:13)
at PacketReader.emit (events.js:211:7)
at PacketReader._tryRead (/app/node_modules/adbkit/lib/adb/tcpusb/packetreader.js:45:16)
at emitNone (events.js:106:13)
at Socket.emit (events.js:208:7)
at emitReadable_ (_stream_readable.js:513:10)
at emitReadable (_stream_readable.js:507:7)
at addChunk (_stream_readable.js:274:7)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:594:20)
2019-04-02T17:09:03.290Z FTL/util:lifecycle 802 [CB512EDDM1] Shutting down due to fatal error
2019-04-02T17:09:03.327Z INF/provider 1 [*] Cleaning up device worker "CB512EDDM1"
2019-04-02T17:09:03.331Z ERR/provider 1 [*] Device worker "CB512EDDM1" died with code 1
2019-04-02T17:09:03.334Z INF/provider 1 [*] Restarting device worker "CB512EDDM1"
...
```
While looking into the code of `auth.js` file, it seems this is the matching with the regex ` /^((?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?)\0? (.*)\s*$/` which fails!

**Comment by koral--** [comment]
This issue is already reported and tracked here: https://github.com/openstf/stf/issues/1030
Let's continue discussion there.
