### ISSUE TITLE
A Problem of Connect SamSung A6s from Stfserver

### ISSUE THREAD

**Issue by saint228** [openstf/stf#1040]
I buy a new phone-SamSung A6s and I want to use it at my STF。
But when I connect this device to STF，it's show “perparing” for a moment and turn to “disconnect”.
I am sure that I have enabled the "Developer options" &"Usb debugging".
And I have downloaded another StfServer.apk and installed it into my phone,but it doesnot work.

logs of STF:
2019-04-30T04:36:48.847Z FTL/util:lifecycle 9611 [54c5ca91a5] Shutting down due to fatal error
2019-04-30T04:36:48.853Z INF/provider 42 [] Cleaning up device worker "54c5ca91a5"
2019-04-30T04:36:48.853Z ERR/provider 42 [] Device worker "54c5ca91a5" died with code 1
2019-04-30T04:36:48.853Z INF/provider 42 [*] Restarting device worker "54c5ca91a5"
2019-04-30T04:36:49.749Z INF/device:support:push 9623 [54c5ca91a5] Sending output to "tcp://127.0.0.1:7116"
2019-04-30T04:36:49.753Z INF/device 9623 [54c5ca91a5] Preparing device
2019-04-30T04:36:50.090Z INF/device:support:sub 9623 [54c5ca91a5] Receiving input from "tcp://127.0.0.1:7114"
2019-04-30T04:36:50.092Z INF/device:support:sub 9623 [54c5ca91a5] Subscribing to permanent channel "*ALL"
2019-04-30T04:36:50.159Z INF/device:support:properties 9623 [54c5ca91a5] Loading properties
2019-04-30T04:36:50.205Z INF/device:support:sdk 9623 [54c5ca91a5] Supports SDK 27
2019-04-30T04:36:50.206Z INF/device:support:abi 9623 [54c5ca91a5] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2019-04-30T04:36:50.495Z INF/device:resources:minicap 9623 [54c5ca91a5] Installing "/app/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
2019-04-30T04:36:50.496Z INF/device:resources:minicap 9623 [54c5ca91a5] Installing "/app/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-27/minicap.so" as "/data/local/tmp/minicap.so"
2019-04-30T04:36:50.609Z INF/device:resources:service 9623 [54c5ca91a5] Checking whether we need to install STFService
2019-04-30T04:36:51.048Z INF/device:resources:service 9623 [54c5ca91a5] Running version check
2019-04-30T04:36:51.492Z INF/device:resources:service 9623 [54c5ca91a5] STFService up to date
2019-04-30T04:36:51.494Z INF/device:plugins:service 9623 [54c5ca91a5] Launching agent
2019-04-30T04:36:52.183Z INF/device:plugins:service 9623 [54c5ca91a5] Agent says: "Listening on @stfagent"
2019-04-30T04:36:52.220Z INF/device:plugins:service 9623 [54c5ca91a5] Launching service
2019-04-30T04:36:52.227Z INF/device:plugins:service 9623 [54c5ca91a5] Agent says: "InputClient started"
2019-04-30T04:36:52.320Z FTL/device 9623 [54c5ca91a5] Setup had an error Error: Service had an error: "Error: Not found; no service started."
at /app/lib/units/device/plugins/service.js:101:23
From previous event:
at /app/lib/units/device/plugins/service.js:76:14
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)

So,How to connect SamSung A6s from stfserver?

**Comment by loneyao** [comment]
是不是手机上的stf服务没有启动，你手动开启下看看。
Activity也启动下

**Comment by loneyao** [comment]
adb shell am start -n jp.co.cyberagent.stf/.IdentityActivity
adb   shell am startservice -n jp.co.cyberagent.stf/.Service

**Comment by saint228** [comment]
OK，this problem has been solved profectly，thank you very much.
