### ISSUE TITLE
xiaomi iphone stf  error  Setup had an error Error: Failed more than 3 times in 10000ms

### ISSUE THREAD

**Issue by scvjx** [openstf/stf#1041]
2019-04-30T06:21:53.709Z FTL/device 5373 [2464492e] Setup had an error Error: Failed more than 3 times in 10000ms
    at TouchConsumer._failLimitExceeded (/home/dell/stf/lib/units/device/plugins/touch/index.js:230:26)
    at FailCounter.emit (/home/dell/stf/node_modules/eventemitter3/index.js:117:35)
    at FailCounter.inc (/home/dell/stf/lib/util/failcounter.js:29:10)
    at TouchConsumer._outputEnded (/home/dell/stf/lib/units/device/plugins/touch/index.js:223:24)
    at RiskyStream.emit (/home/dell/stf/node_modules/eventemitter3/index.js:115:35)
    at RiskyStream.<anonymous> (/home/dell/stf/lib/util/riskystream.js:14:12)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
From previous event:
    at startConsumer (/home/dell/stf/lib/units/device/plugins/touch/index.js:511:14)
    at /home/dell/stf/lib/units/device/plugins/touch/index.js:526:12
    at SerialSyrup.ParallelSyrup.invoke (/home/dell/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /home/dell/stf/node_modules/stf-syrup/lib/serial.js:43:33
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2019-04-30T06:21:53.709Z FTL/util:lifecycle 5373 [2464492e] Shutting down due to fatal error

**Comment by sorccu** [comment]
Let’s try to search before posting issues.

https://github.com/openstf/stf/issues/603
