### ISSUE TITLE
Issue with uploads - not related to permissions or save-dir

### ISSUE THREAD

**Issue by TychoSchenkeveld** [openstf/stf#1058]
**What is the issue or idea you have?**
Screenshots and file uploads fail. Everything else works perfectly as installed per the "DEPLOYMENT" guide.

I already checked the following:
- The latest version of storage module with save-dir implemented as referenced in https://github.com/openstf/stf/issues/548
- Write access to data directory granted to all users (777) (just to be sure :) as I read in other issue reports that this was an issue).

Still, I see the following in the logs:

```
Jun 12 17:54:33 openstf docker[13188]: 2019-06-12T17:54:33.043Z INF/device:plugins:screen:capture 85 [39V7N18A25000351] Capturing screenshot

< ... 1 minute passes ... >

Jun 12 17:55:40 openstf docker[13188]: 2019-06-12T17:55:40.280Z ERR/device:support:storage 85 [39V7N18A25000351] Upload to "https://x.x.x.x/s/upload/image" failed Error: socket hang up
Jun 12 17:55:40 openstf docker[13188]:     at TLSSocket.onHangUp (_tls_wrap.js:1124:19)
Jun 12 17:55:40 openstf docker[13188]:     at TLSSocket.g (events.js:292:16)
Jun 12 17:55:40 openstf docker[13188]:     at emitNone (events.js:91:20)
Jun 12 17:55:40 openstf docker[13188]:     at TLSSocket.emit (events.js:185:7)
Jun 12 17:55:40 openstf docker[13188]:     at endReadableNT (_stream_readable.js:974:12)
Jun 12 17:55:40 openstf docker[13188]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
Jun 12 17:55:40 openstf docker[13188]:     at process._tickCallback (internal/process/next_tick.js:104:9)
Jun 12 17:55:40 openstf docker[13188]: 2019-06-12T17:55:40.328Z ERR/device:plugins:screen:capture 85 [39V7N18A25000351] Screen capture failed Error: socket hang up
Jun 12 17:55:40 openstf docker[13188]:     at TLSSocket.onHangUp (_tls_wrap.js:1124:19)
Jun 12 17:55:40 openstf docker[13188]:     at TLSSocket.g (events.js:292:16)
Jun 12 17:55:40 openstf docker[13188]:     at emitNone (events.js:91:20)
Jun 12 17:55:40 openstf docker[13188]:     at TLSSocket.emit (events.js:185:7)
Jun 12 17:55:40 openstf docker[13188]:     at endReadableNT (_stream_readable.js:974:12)
Jun 12 17:55:40 openstf docker[13188]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
Jun 12 17:55:40 openstf docker[13188]:     at process._tickCallback (internal/process/next_tick.js:104:9)
```

I use the recommended ports, so stf-storage-temp is running at port 3500. If I connect to the mentioned URL (/s/upload/image) I get the message "Cannot GET /s/upload/image"). This seems to come from port 3500 directly (e.g. it's not actually a browser error message, it actually comes from the running storage module because I see it too when I use telnet).

So it seems to be running but for some reason it hangs when I try to upload a file.

I use pretty much unmodified versions of the nginx.conf and unit files in the DEPLOYMENT guide, except the things that are relevant to my configuration of course.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

No, all devices

**Please provide the steps to reproduce the issue.**

Press the screenshot button, nothing happens (but those logs above).

**What is the expected behavior?**

Screenshots to work (and much more importantly: APK uploads :) )

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
I use the docker version, deployed as per deployment, it's not a local deployment

**Please run `stf doctor` and paste the output here.**
It's installed inside docker, which container should I run this in? Is this relevant for non-local installs?

**Comment by TychoSchenkeveld** [comment]
PS This is not so much a bug - I'm sure I'm doing something wrong! Just not sure what :)

**Comment by TychoSchenkeveld** [comment]
Update: I tried to run the stf storage module locally without docker but it doesn't seem to make any difference. I also tried to run netcat in listen mode on port 3500 but I see nothing coming in. So I think whatever comes before this is not working. The storage plugin modules are running though. For example the image one: 
```
[Unit]
Description=STF image storage plugin
After=docker.service
Requires=docker.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
Restart=always
ExecStartPre=/usr/bin/docker pull openstf/stf:latest
ExecStartPre=-/usr/bin/docker kill %p-%i
ExecStartPre=-/usr/bin/docker rm %p-%i
ExecStart=/usr/bin/docker run --rm \
  --name %p-%i \
  -p %i:3000 \
  -e "NODE_TLS_REJECT_UNAUTHORIZED=0" \
  openstf/stf:latest \
  stf storage-plugin-image --port 3000 \
    --storage-url https://x.x.x.x/
ExecStop=-/usr/bin/docker stop -t 10 %p-%i
```
All the other services work configured just like this.. Very strange, will advise here if I find the cause as it might help others looking for this issue.

**Comment by TychoSchenkeveld** [comment]
Ok have been looking at the code, so it looks like what happens next is it tries to upload to the specified URL by POST request. I tried to POST something and it worked fine.. Looks like the docker containers can't reach NGINX somehow. Strange because they can talk to each other just fine. It must be either the processor or the storage plugin trying to make this connection? (From the logs I can't see which docker container generates the error).

I don't really know much about docker, this is the one part of the setup I'm not very well versed in. But I've set everything up as suggested in the deployment guide.

Anyway like I said any help would be appreciated :)
