### ISSUE TITLE
Error During installation ubuntu Failed at the jpeg-turbo@0.4.0

### ISSUE THREAD

**Issue by poisonivy0** [openstf/stf#1066]
**Nearly there in trying to install Openstf

got an error on the last bit.

I ran command below**
#OpenSTF
cd
mkdir openstf
cd openstf/
git clone https://github.com/openstf/stf.git
cd stf
sudo npm install -g stf --unsafe-perm

**And got this error:**
> dtrace-provider@0.8.7 install /usr/local/lib/node_modules/stf/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

make: Entering directory '/usr/local/lib/node_modules/stf/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/usr/local/lib/node_modules/stf/node_modules/dtrace-provider/build'

> jpeg-turbo@0.4.0 install /usr/local/lib/node_modules/stf/node_modules/jpeg-turbo
> node-pre-gyp install --fallback-to-build

/usr/bin/env: ‘node’: No such file or directory
/usr/local/lib
└── (empty)

npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "stf" "--unsafe-perm"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! jpeg-turbo@0.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the jpeg-turbo@0.4.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jpeg-turbo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jpeg-turbo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jpeg-turbo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/noface/openstf/stf/npm-debug.log

**Can anyone help or see the problem.**

**Comment by poisonivy0** [comment]
installed lastest version of node. now i have a new set of errors:

> dtrace-provider@0.8.7 install /usr/local/lib/node_modules/stf/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack SyntaxError: Unexpected token ...
gyp ERR! stack     at exports.runInThisContext (vm.js:53:16)
gyp ERR! stack     at Module._compile (module.js:374:25)
gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
gyp ERR! stack     at Module.load (module.js:344:32)
gyp ERR! stack     at Function.Module._load (module.js:301:12)
gyp ERR! stack     at Module.require (module.js:354:17)
gyp ERR! stack     at require (internal/module.js:12:17)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (/usr/local/lib/node_modules/node-gyp/lib/node-gyp.js:42:14)
gyp ERR! stack     at run (/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js:79:30)
gyp ERR! stack     at nextTickCallbackWith0Args (node.js:419:9)
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/stf/node_modules/dtrace-provider
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v5.0.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

> jpeg-turbo@0.4.0 install /usr/local/lib/node_modules/stf/node_modules/jpeg-turbo
> node-pre-gyp install --fallback-to-build

[jpeg-turbo] Success: "/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/lib/binding/node-v46-linux-x64/jpegturbo.node" is installed via remote

> bufferutil@1.3.0 install /usr/local/lib/node_modules/stf/node_modules/bufferutil
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack SyntaxError: Unexpected token ...
gyp ERR! stack     at exports.runInThisContext (vm.js:53:16)
gyp ERR! stack     at Module._compile (module.js:374:25)
gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
gyp ERR! stack     at Module.load (module.js:344:32)
gyp ERR! stack     at Function.Module._load (module.js:301:12)
gyp ERR! stack     at Module.require (module.js:354:17)
gyp ERR! stack     at require (internal/module.js:12:17)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (/usr/local/lib/node_modules/node-gyp/lib/node-gyp.js:42:14)
gyp ERR! stack     at run (/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js:79:30)
gyp ERR! stack     at nextTickCallbackWith0Args (node.js:419:9)
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/stf/node_modules/bufferutil
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v5.0.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
/usr/local/lib
└── (empty)

npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "stf"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the bufferutil@1.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bufferutil
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/noface/openstf/stf/npm-debug.log
npm ERR! code 1

**Comment by zi-l** [comment]
The same issue `Failed at the jpeg-turbo@0.4.0 install script 'node-pre-gyp install --fallback-to-build'.` when i just executed command `sudo npm install -g stf`

**Comment by zi-l** [comment]
> The same issue `Failed at the jpeg-turbo@0.4.0 install script 'node-pre-gyp install --fallback-to-build'.` when i just executed command `sudo npm install -g stf`

platform: ubuntu18.04

**Comment by zi-l** [comment]
Refer to: [#950 ](https://github.com/openstf/stf/issues/950), [#1015 ](https://github.com/openstf/stf/issues/1015)
Use [nvm](https://github.com/nvm-sh/nvm#git-install) to install node 8.x, and `npm install -g stf` without `sudo`, everything goes well.
Node 10.x seems to be not compatible yet.
