### ISSUE TITLE
Unable to redirect to STF home page after login Okta SAML app

### ISSUE THREAD

**Issue by zi-l** [openstf/stf#1083]
**Info**
Ubuntu18.04 with docker

**What is the issue or idea you have?**
- Unable to redirect to STF home page after login SAML app on Okta
- STF could not recognize cert file

**Please provide the steps to reproduce the issue.**

- Created SAML app and added user to this app on Okta, here's the configuration:

![saml-settings](https://user-images.githubusercontent.com/25576713/62508349-d3594380-b839-11e9-9c74-4577d226854d.png)
![samlfinish](https://user-images.githubusercontent.com/25576713/62508465-4f538b80-b83a-11e9-9611-e86ca3d5aef2.png)

- Executed command:

`docker run -d --name stfsaml --net host openstf/stf stf local --auth-type saml2 --auth-options '["--saml-id-provider-entry-point-url", "https://dev-764063.okta.com/app/freedev764063_openstfsaml_1/exk12408naFKuy8Vh357/sso/saml", "--saml-id-provider-issuer", "http://www.okta.com/exk12408naFKuy8Vh357","--saml-id-provider-callback-url","http://localhost:7100/auth/saml/callback"]'`

- After filling out the login info, it's always loading signing page and reflashing it:

![loading](https://user-images.githubusercontent.com/25576713/62508524-89249200-b83a-11e9-8c24-5fd5134bf963.png)

- Tried to use this cert:
![cert](https://user-images.githubusercontent.com/25576713/62508774-6777da80-b83b-11e9-8a70-7d7408256f42.png)

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

However, `okta.cert` could not be found by STF:

```
bl@bl-VirtualBox:~$ docker logs -f stfsaml

2019-08-06T02:25:12.721Z INF/util:procutil 1 [*] Forking "/app/lib/cli migrate"

2019-08-06T02:25:13.148Z INF/db 11 [*] Connecting to 127.0.0.1:28015

2019-08-06T02:25:13.173Z INF/db:setup 11 [*] Database "stf" already exists

2019-08-06T02:25:13.183Z INF/db:setup 11 [*] Table "users" already exists

2019-08-06T02:25:13.183Z INF/db:setup 11 [*] Table "accessTokens" already exists

2019-08-06T02:25:13.183Z INF/db:setup 11 [*] Table "vncauth" already exists

2019-08-06T02:25:13.184Z INF/db:setup 11 [*] Table "devices" already exists

2019-08-06T02:25:13.184Z INF/db:setup 11 [*] Table "logs" already exists

2019-08-06T02:25:13.204Z INF/db:setup 11 [*] Index "users"."adbKeys" already exists

2019-08-06T02:25:13.204Z INF/db:setup 11 [*] Index "accessTokens"."email" already exists

2019-08-06T02:25:13.204Z INF/db:setup 11 [*] Index "vncauth"."response" already exists

2019-08-06T02:25:13.204Z INF/db:setup 11 [*] Index "vncauth"."responsePerDevice" already exists

2019-08-06T02:25:13.204Z INF/db:setup 11 [*] Index "devices"."owner" already exists

2019-08-06T02:25:13.205Z INF/db:setup 11 [*] Index "devices"."present" already exists

2019-08-06T02:25:13.205Z INF/db:setup 11 [*] Waiting for index "users"."adbKeys"

2019-08-06T02:25:13.206Z INF/db:setup 11 [*] Waiting for index "accessTokens"."email"

2019-08-06T02:25:13.206Z INF/db:setup 11 [*] Waiting for index "vncauth"."response"

2019-08-06T02:25:13.207Z INF/db:setup 11 [*] Waiting for index "vncauth"."responsePerDevice"

2019-08-06T02:25:13.208Z INF/db:setup 11 [*] Waiting for index "devices"."owner"

2019-08-06T02:25:13.208Z INF/db:setup 11 [*] Waiting for index "devices"."present"

2019-08-06T02:25:13.213Z INF/db:setup 11 [*] Index "devices"."providerChannel" already exists

2019-08-06T02:25:13.214Z INF/db:setup 11 [*] Index "users"."adbKeys" is ready

2019-08-06T02:25:13.214Z INF/db:setup 11 [*] Index "accessTokens"."email" is ready

2019-08-06T02:25:13.214Z INF/db:setup 11 [*] Index "vncauth"."response" is ready

2019-08-06T02:25:13.214Z INF/db:setup 11 [*] Index "vncauth"."responsePerDevice" is ready

2019-08-06T02:25:13.214Z INF/db:setup 11 [*] Waiting for index "devices"."providerChannel"

2019-08-06T02:25:13.217Z INF/db:setup 11 [*] Index "devices"."owner" is ready

2019-08-06T02:25:13.217Z INF/db:setup 11 [*] Index "devices"."present" is ready

2019-08-06T02:25:13.218Z INF/db:setup 11 [*] Index "devices"."providerChannel" is ready

2019-08-06T02:25:13.226Z INF/util:procutil 1 [*] Forking "/app/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"

2019-08-06T02:25:13.230Z INF/util:procutil 1 [*] Forking "/app/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"

2019-08-06T02:25:13.232Z INF/util:procutil 1 [*] Forking "/app/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"

2019-08-06T02:25:13.234Z INF/util:procutil 1 [*] Forking "/app/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"

2019-08-06T02:25:13.246Z INF/util:procutil 1 [*] Forking "/app/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"

2019-08-06T02:25:13.254Z INF/util:procutil 1 [*] Forking "/app/lib/cli provider --name bl-VirtualBox --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"

2019-08-06T02:25:13.262Z INF/util:procutil 1 [*] Forking "/app/lib/cli auth-saml2 --port 7120 --secret kute kittykat --app-url http://localhost:7100/ --saml-id-provider-entry-point-url https://dev-764063.okta.com/app/freedev764063_openstfsaml_1/exk12408naFKuy8Vh357/sso/saml --saml-id-provider-issuer http://www.okta.com/exk12408naFKuy8Vh357 --saml-id-provider-callback-url http://localhost:7100/auth/saml/callback --saml-id-provider-cert-path /etc/okta.cert"

2019-08-06T02:25:13.278Z INF/util:procutil 1 [*] Forking "/app/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/saml/ --websocket-url http://localhost:7110/"

2019-08-06T02:25:13.286Z INF/util:procutil 1 [*] Forking "/app/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"

2019-08-06T02:25:13.302Z INF/util:procutil 1 [*] Forking "/app/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"

2019-08-06T02:25:13.318Z INF/util:procutil 1 [*] Forking "/app/lib/cli storage-temp --port 7102"

2019-08-06T02:25:13.334Z INF/util:procutil 1 [*] Forking "/app/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"

2019-08-06T02:25:13.354Z INF/util:procutil 1 [*] Forking "/app/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"

2019-08-06T02:25:13.362Z INF/util:procutil 1 [*] Forking "/app/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"

2019-08-06T02:25:14.966Z INF/triproxy 18 [dev001] PUB socket bound on tcp://127.0.0.1:7114

2019-08-06T02:25:14.975Z INF/triproxy 18 [dev001] DEALER socket bound on tcp://127.0.0.1:7115

2019-08-06T02:25:14.985Z INF/triproxy 18 [dev001] PULL socket bound on tcp://127.0.0.1:7116

2019-08-06T02:25:15.155Z INF/triproxy 17 [app001] PUB socket bound on tcp://127.0.0.1:7111

2019-08-06T02:25:15.166Z INF/triproxy 17 [app001] DEALER socket bound on tcp://127.0.0.1:7112

2019-08-06T02:25:15.167Z INF/triproxy 17 [app001] PULL socket bound on tcp://127.0.0.1:7113

2019-08-06T02:25:15.752Z INF/db 24 [*] Connecting to 127.0.0.1:28015

2019-08-06T02:25:15.744Z INF/db 30 [*] Connecting to 127.0.0.1:28015

2019-08-06T02:25:15.763Z INF/poorxy 90 [*] Listening on port 7100

2019-08-06T02:25:15.835Z INF/processor 30 [proc002] App dealer connected to "tcp://127.0.0.1:7112"

2019-08-06T02:25:15.842Z INF/processor 24 [proc001] App dealer connected to "tcp://127.0.0.1:7112"

2019-08-06T02:25:15.843Z INF/processor 30 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"

2019-08-06T02:25:15.844Z INF/processor 24 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"

2019-08-06T02:25:15.900Z INF/reaper 36 [reaper001] Subscribing to permanent channel "*ALL"

2019-08-06T02:25:15.915Z INF/reaper 36 [reaper001] Reaping devices with no heartbeat

2019-08-06T02:25:15.919Z INF/db 36 [reaper001] Connecting to 127.0.0.1:28015

2019-08-06T02:25:15.953Z INF/reaper 36 [reaper001] Receiving input from "tcp://127.0.0.1:7111"

2019-08-06T02:25:15.954Z INF/reaper 36 [reaper001] Sending output to "tcp://127.0.0.1:7116"

2019-08-06T02:25:16.261Z INF/provider 42 [*] Subscribing to permanent channel "vuQCy1eQSxKBAc7+VxC00A=="

2019-08-06T02:25:16.276Z INF/provider 42 [*] Sending output to "tcp://127.0.0.1:7116"

2019-08-06T02:25:16.279Z INF/provider 42 [*] Receiving input from "tcp://127.0.0.1:7114"

2019-08-06T02:25:16.296Z INF/provider 42 [*] Tracking devices

2019-08-06T02:25:16.300Z INF/storage:plugins:apk 84 [*] Listening on port 7104

2019-08-06T02:25:16.472Z INF/storage:temp 72 [*] Listening on port 7102

lib/cli auth-saml2




Options:

  -h, --help                          Show help.                       [boolean]

  -V, --version                       Show version.                    [boolean]

  --app-url, -a                       URL to the app unit.   [string] [required]

  --port, -p                          The port to bind to.

                                                        [number] [default: 7120]

  --saml-id-provider-entry-point-url  SAML 2.0 identity provider URL.

                                                             [string] [required]

  --saml-id-provider-issuer           SAML 2.0 identity provider issuer.

                                                             [string] [required]

  --saml-id-provider-cert-path        SAML 2.0 identity provider certificate

                                      file path.                        [string]

  --saml-id-provider-callback-url     SAML 2.0 identity provider callback URL in

                                      the form of

                                      scheme://host[:port]/auth/saml/callback.

                                                                        [string]

  --secret, -s                        The secret to use for auth JSON Web

                                      Tokens. Anyone who knows this token can

                                      freely enter the system if they want, so

                                      keep it safe.          [string] [required]

  --ssid, -i                          The name of the session ID cookie.

                                                      [string] [default: "ssid"]




Each option can be be overwritten with an environment variable by converting the

option to uppercase, replacing dashes with underscores and prefixing it with

`STF_AUTH_SAML2_` (e.g. `STF_AUTH_SAML2_SECRET`). Legacy environment variables

like SAML_ID_PROVIDER_ISSUER are still accepted, too, but consider them

deprecated.




ENOENT: no such file or directory, open '/etc/okta.cert'

2019-08-06T02:25:16.619Z FTL/cli:local 1 [*] Child process had an error ExitError: Exit code "1"

    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)

    at emitTwo (events.js:106:13)

    at ChildProcess.emit (events.js:191:7)

    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

2019-08-06T02:25:16.619Z INF/cli:local 1 [*] Shutting down all child processes

2019-08-06T02:25:16.631Z INF/util:lifecycle 17 [app001] Winding down for graceful exit

2019-08-06T02:25:16.631Z INF/util:lifecycle 18 [dev001] Winding down for graceful exit

2019-08-06T02:25:16.644Z INF/util:lifecycle 24 [proc001] Winding down for graceful exit

2019-08-06T02:25:16.644Z INF/util:lifecycle 30 [proc002] Winding down for graceful exit

2019-08-06T02:25:16.649Z WRN/db 24 [proc001] Connection closed

2019-08-06T02:25:16.653Z WRN/db 30 [proc002] Connection closed

2019-08-06T02:25:16.654Z INF/util:lifecycle 36 [reaper001] Winding down for graceful exit

2019-08-06T02:25:16.656Z INF/util:lifecycle 42 [*] Winding down for graceful exit

2019-08-06T02:25:16.658Z WRN/db 36 [reaper001] Connection closed

2019-08-06T02:25:16.706Z INF/app 54 [*] Using pre-built resources

2019-08-06T02:25:16.728Z INF/app 54 [*] Listening on port 7105

2019-08-06T02:25:16.730Z INF/util:lifecycle 54 [*] Winding down for graceful exit

2019-08-06T02:25:16.733Z INF/db 54 [*] Connecting to 127.0.0.1:28015

2019-08-06T02:25:17.013Z INF/websocket 66 [*] Subscribing to permanent channel "*ALL"

2019-08-06T02:25:17.023Z INF/websocket 66 [*] Listening on port 7110

2019-08-06T02:25:17.026Z INF/util:lifecycle 66 [*] Winding down for graceful exit

2019-08-06T02:25:17.030Z INF/db 66 [*] Connecting to 127.0.0.1:28015

```

**Comment by sudhalucky** [comment]
Try the below on your OKTA application setup

Single Sign On URL: https://localhost:7100/auth/saml/callback
Recipient URL: https://localhost:7100/auth/saml/callback
Destination URL: https://localhost:7100/auth/saml/callback
Audience Restriction: https://localhost:7100/

**Comment by zi-l** [comment]
@sudhalucky works! many thanks for your help!

**Comment by marouj** [comment]
Hi I have the same problem. Can you help me ?
