### ISSUE TITLE
zmq function Invalid argument error

### ISSUE THREAD

**Issue by channingbreeze** [openstf/stf#109]
i pull the newest code from master, and run npm install successfully
but when i run stf, i find the error below
how can i fix it?

/home/zhuxun/COMPANY/stf/newstf/node_modules/zmq/lib/index.js:252
  this._zmq.setsockopt(opts[opt] || opt, val);
            ^
Error: Invalid argument
    at Error (native)
    at Socket.setsockopt (/home/zhuxun/COMPANY/stf/newstf/node_modules/zmq/lib/index.js:252:13)
    at Object.module.exports.socket (/home/zhuxun/COMPANY/stf/newstf/lib/util/zmqutil.js:11:8)
    at module.exports (/home/zhuxun/COMPANY/stf/newstf/lib/units/triproxy/index.js:19:21)
    at Command.<anonymous> (/home/zhuxun/COMPANY/stf/newstf/lib/cli.js:306:32)
    at Command.listener (/home/zhuxun/COMPANY/stf/newstf/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/home/zhuxun/COMPANY/stf/newstf/node_modules/commander/index.js:610:12)
    at Command.parse (/home/zhuxun/COMPANY/stf/newstf/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/home/zhuxun/COMPANY/stf/newstf/lib/cli.js:1166:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
FTL/cli:local 19744 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/home/zhuxun/COMPANY/stf/newstf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
INF/cli:local 19744 [*] Shutting down all child processes
/home/zhuxun/COMPANY/stf/newstf/node_modules/zmq/lib/index.js:252
  this._zmq.setsockopt(opts[opt] || opt, val);
            ^
Error: Invalid argument
    at Error (native)
    at Socket.setsockopt (/home/zhuxun/COMPANY/stf/newstf/node_modules/zmq/lib/index.js:252:13)
    at Object.module.exports.socket (/home/zhuxun/COMPANY/stf/newstf/lib/util/zmqutil.js:11:8)
    at module.exports (/home/zhuxun/COMPANY/stf/newstf/lib/units/triproxy/index.js:19:21)
    at Command.<anonymous> (/home/zhuxun/COMPANY/stf/newstf/lib/cli.js:306:32)
    at Command.listener (/home/zhuxun/COMPANY/stf/newstf/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/home/zhuxun/COMPANY/stf/newstf/node_modules/commander/index.js:610:12)
    at Command.parse (/home/zhuxun/COMPANY/stf/newstf/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/home/zhuxun/COMPANY/stf/newstf/lib/cli.js:1166:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

**Comment by sorccu** [comment]
Is it possible that your zeromq library might be super old? 3.x or 4.x should work fine.

**Comment by vbanthia** [comment]
I also confirmed. Working okay on my machine.

**Comment by sorccu** [comment]
If you're on Ubuntu 12.04, they only seem to have an old version available. On newer versions you should be using libzmq3-dev (or similar on different distributions). While we could catch and ignore the exception thrown by the old version, I'm not sure if we care enough about supporting ancient software.

**Comment by sorccu** [comment]
The keepalive options have now been made optional, so this should be "fixed" as well. However, what I said earlier still stands. Ubuntu 12.04 is simply too old, we're not going to spend much time fixing it.
