### ISSUE TITLE
LG G8ThinQ fails to show screen and is disconnected

### ISSUE THREAD

**Issue by meggleton** [openstf/stf#1090]
**What is the issue or idea you have?**
When using the G8ThinQ the device is disconnected and the "Someone stole your device screen" is displayed

**Please provide the steps to reproduce the issue.**
1. Plug in a LG G8ThinQ to a STF farm running the latest released code.
2. Click the use button for the LG G8ThinQ device on the device list screen.
 
**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
Aug 30 09:25:17 OSTFPROD docker[22646]: 2019-08-30T13:25:17.720Z INF/device:plugins:group 4125 [LMG888AA88a88a88] Subscribing to group channel "BJCOgdPWR2utXth3jrgjdw=="
Aug 30 09:25:17 OSTFPROD docker[22646]: 2019-08-30T13:25:17.916Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] Setting frame producer projection to 843x843
Aug 30 09:25:17 OSTFPROD docker[22646]: 2019-08-30T13:25:17.917Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] Requesting frame producer to start
Aug 30 09:25:17 OSTFPROD docker[22646]: 2019-08-30T13:25:17.918Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] Launching screen service
Aug 30 09:25:17 OSTFPROD docker[22646]: 2019-08-30T13:25:17.980Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] minicap says: "PID: 29866"
Aug 30 09:25:17 OSTFPROD docker[22646]: 2019-08-30T13:25:17.980Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] minicap says: "INFO: Using projection 1080x2340@389x843/0"
Aug 30 09:25:17 OSTFPROD docker[22646]: 2019-08-30T13:25:17.980Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient"
Aug 30 09:25:17 OSTFPROD docker[22646]: 2019-08-30T13:25:17.981Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] Connecting to minicap service
Aug 30 09:25:17 OSTFPROD docker[22646]: 2019-08-30T13:25:17.983Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check"
Aug 30 09:25:17 OSTFPROD docker[22646]: 2019-08-30T13:25:17.983Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display"
Aug 30 09:25:18 OSTFPROD docker[24140]: 10.135.40.69 - - [30/Aug/2019:13:25:18 +0000] "GET /api/v1/devices/LMG888AA88a88a88 HTTP/1.1" 200 1507 "https://ostfprod.domain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
Aug 30 09:25:18 OSTFPROD docker[22646]: 2019-08-30T13:25:18.047Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue"
Aug 30 09:25:18 OSTFPROD docker[22646]: 2019-08-30T13:25:18.048Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options"
Aug 30 09:25:18 OSTFPROD docker[22646]: 2019-08-30T13:25:18.048Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer"
Aug 30 09:25:18 OSTFPROD docker[22646]: 2019-08-30T13:25:18.048Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter"
Aug 30 09:25:18 OSTFPROD docker[22646]: 2019-08-30T13:25:18.048Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display"
Aug 30 09:25:18 OSTFPROD docker[22646]: 2019-08-30T13:25:18.049Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] minicap says: "Vector<> have different types (this=0x7fdb41cb60, rhs=0x7fdb41cc80)"
Aug 30 09:25:18 OSTFPROD docker[24140]: 10.135.40.69 - - [30/Aug/2019:13:25:18 +0000] "GET /api/v1/devices/LMG888AA88a88a88 HTTP/1.1" 304 0 "https://ostfprod.domain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
Aug 30 09:25:18 OSTFPROD docker[22646]: 2019-08-30T13:25:18.111Z WRN/device:plugins:screen:stream 4125 [LMG888AA88a88a88] Shell keeping minicap running ended unexpectedly
Aug 30 09:25:18 OSTFPROD docker[22646]: 2019-08-30T13:25:18.823Z IMP/device:plugins:connect 4125 [LMG888AA88a88a88] Remote Connect Started for device "LMG888AA88a88a88" at "10.42.200.34:16409"
Aug 30 09:25:19 OSTFPROD docker[22646]: 2019-08-30T13:25:19.513Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] Disconnecting from minicap service
Aug 30 09:25:19 OSTFPROD docker[22646]: 2019-08-30T13:25:19.514Z INF/device:plugins:screen:stream 4125 [LMG888AA88a88a88] Stopping minicap service
Aug 30 09:25:19 OSTFPROD docker[22646]: 2019-08-30T13:25:19.516Z FTL/device:plugins:screen:stream 4125 [LMG888AA88a88a88] Frame producer had an error FailError: Failure: 'closed'
Aug 30 09:25:19 OSTFPROD docker[22646]:     at /app/node_modules/adbkit/lib/adb/parser.js:183:29
Aug 30 09:25:19 OSTFPROD docker[22646]:     at runCallback (timers.js:672:20)
Aug 30 09:25:19 OSTFPROD docker[22646]:     at tryOnImmediate (timers.js:645:5)
Aug 30 09:25:19 OSTFPROD docker[22646]:     at processImmediate [as _immediateCallback] (timers.js:617:5)
Aug 30 09:25:19 OSTFPROD docker[22646]: 2019-08-30T13:25:19.517Z FTL/util:lifecycle 4125 [LMG888AA88a88a88] Shutting down due to fatal error
Aug 30 09:25:19 OSTFPROD docker[24140]: 10.135.40.69 - - [30/Aug/2019:13:25:19 +0000] "GET /d/pv1/LMG888AA88a88a88/16408/ HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
Aug 30 09:25:19 OSTFPROD docker[22646]: 2019-08-30T13:25:19.521Z INF/provider 1 [*] Cleaning up device worker "LMG888AA88a88a88"
Aug 30 09:25:19 OSTFPROD docker[22646]: 2019-08-30T13:25:19.521Z ERR/provider 1 [*] Device worker "LMG888AA88a88a88" died with code 1
Aug 30 09:25:19 OSTFPROD docker[22646]: 2019-08-30T13:25:19.521Z INF/provider 1 [*] Restarting device worker "LMG888AA88a88a88"
Aug 30 09:25:20 OSTFPROD docker[22646]: 2019-08-30T13:25:20.360Z INF/device:support:push 4149 [LMG888AA88a88a88] Sending output to "tcp://ostfprod.domain.com:7270"
Aug 30 09:25:20 OSTFPROD docker[22646]: 2019-08-30T13:25:20.363Z INF/device 4149 [LMG888AA88a88a88] Preparing device
Aug 30 09:25:20 OSTFPROD docker[22646]: 2019-08-30T13:25:20.650Z INF/device:support:sub 4149 [LMG888AA88a88a88] Receiving input from "tcp://ostfprod.domain.com:7250"
Aug 30 09:25:20 OSTFPROD docker[22646]: 2019-08-30T13:25:20.651Z INF/device:support:sub 4149 [LMG888AA88a88a88] Subscribing to permanent channel "*ALL"
Aug 30 09:25:20 OSTFPROD docker[22646]: 2019-08-30T13:25:20.714Z INF/device:support:properties 4149 [LMG888AA88a88a88] Loading properties
Aug 30 09:25:20 OSTFPROD docker[22646]: 2019-08-30T13:25:20.750Z INF/device:support:sdk 4149 [LMG888AA88a88a88] Supports SDK 28
Aug 30 09:25:20 OSTFPROD docker[22646]: 2019-08-30T13:25:20.751Z INF/device:support:abi 4149 [LMG888AA88a88a88] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
Aug 30 09:25:20 OSTFPROD docker[22646]: 2019-08-30T13:25:20.903Z INF/device:resources:minicap 4149 [LMG888AA88a88a88] Installing "/app/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
Aug 30 09:25:20 OSTFPROD docker[22646]: 2019-08-30T13:25:20.904Z INF/device:resources:minicap 4149 [LMG888AA88a88a88] Installing "/app/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-28/minicap.so" as "/data/local/tmp/minicap.so"
Aug 30 09:25:20 OSTFPROD docker[22646]: 2019-08-30T13:25:20.989Z INF/device:resources:service 4149 [LMG888AA88a88a88] Checking whether we need to install STFService
Aug 30 09:25:21 OSTFPROD docker[22646]: 2019-08-30T13:25:21.040Z INF/device:resources:service 4149 [LMG888AA88a88a88] Running version check
Aug 30 09:25:21 OSTFPROD docker[22646]: 2019-08-30T13:25:21.301Z INF/device:resources:service 4149 [LMG888AA88a88a88] STFService up to date
Aug 30 09:25:21 OSTFPROD docker[22646]: 2019-08-30T13:25:21.304Z INF/device:plugins:service 4149 [LMG888AA88a88a88] Launching agent
Aug 30 09:25:21 OSTFPROD docker[22646]: 2019-08-30T13:25:21.675Z INF/device:plugins:service 4149 [LMG888AA88a88a88] Agent says: "Listening on @stfagent"
Aug 30 09:25:21 OSTFPROD docker[22646]: 2019-08-30T13:25:21.771Z INF/device:plugins:service 4149 [LMG888AA88a88a88] Launching service
Aug 30 09:25:21 OSTFPROD docker[22646]: 2019-08-30T13:25:21.773Z INF/device:plugins:service 4149 [LMG888AA88a88a88] Agent says: "InputClient started"
Aug 30 09:25:21 OSTFPROD docker[22646]: 2019-08-30T13:25:21.836Z INF/device:plugins:display 4149 [LMG888AA88a88a88] Reading display info
Aug 30 09:25:21 OSTFPROD docker[22646]: 2019-08-30T13:25:21.885Z INF/device:plugins:phone 4149 [LMG888AA88a88a88] Fetching phone info
Aug 30 09:25:21 OSTFPROD docker[22646]: 2019-08-30T13:25:21.903Z INF/device:plugins:identity 4149 [LMG888AA88a88a88] Solving identity
Aug 30 09:25:21 OSTFPROD docker[22646]: 2019-08-30T13:25:21.905Z INF/device:plugins:solo 4149 [LMG888AA88a88a88] Subscribing to permanent channel "6VttilVFTc8erALVqGOARYLm99w="
Aug 30 09:25:21 OSTFPROD docker[22646]: 2019-08-30T13:25:21.908Z INF/device:plugins:screen:stream 4149 [LMG888AA88a88a88] Starting WebSocket server on port 16416
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.060Z INF/device:resources:minitouch 4149 [LMG888AA88a88a88] Installing "/app/node_modules/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch" as "/data/local/tmp/minitouch"
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.108Z WRN/device:plugins:data 4149 [LMG888AA88a88a88] Unable to find device data { serial: 'LMG888AA88a88a88',
Aug 30 09:25:22 OSTFPROD docker[22646]:   platform: 'Android',
Aug 30 09:25:22 OSTFPROD docker[22646]:   manufacturer: 'LGE',
Aug 30 09:25:22 OSTFPROD docker[22646]:   operator: null,
Aug 30 09:25:22 OSTFPROD docker[22646]:   model: 'LM-G820',
Aug 30 09:25:22 OSTFPROD docker[22646]:   version: '9',
Aug 30 09:25:22 OSTFPROD docker[22646]:   abi: 'arm64-v8a',
Aug 30 09:25:22 OSTFPROD docker[22646]:   sdk: '28',
Aug 30 09:25:22 OSTFPROD docker[22646]:   product: 'alphalm_lao_com',
Aug 30 09:25:22 OSTFPROD docker[22646]:   cpuPlatform: 'msmnile',
Aug 30 09:25:22 OSTFPROD docker[22646]:   openGLESVersion: '3.2',
Aug 30 09:25:22 OSTFPROD docker[22646]:   display:
Aug 30 09:25:22 OSTFPROD docker[22646]:    { id: 0,
Aug 30 09:25:22 OSTFPROD docker[22646]:      width: 1080,
Aug 30 09:25:22 OSTFPROD docker[22646]:      height: 2340,
Aug 30 09:25:22 OSTFPROD docker[22646]:      xdpi: 422.03021240234375,
Aug 30 09:25:22 OSTFPROD docker[22646]:      ydpi: 424.5427551269531,
Aug 30 09:25:22 OSTFPROD docker[22646]:      fps: 60.000003814697266,
Aug 30 09:25:22 OSTFPROD docker[22646]:      density: 2.625,
Aug 30 09:25:22 OSTFPROD docker[22646]:      rotation: 0,
Aug 30 09:25:22 OSTFPROD docker[22646]:      secure: true,
Aug 30 09:25:22 OSTFPROD docker[22646]:      size: 6.0769116941916055,
Aug 30 09:25:22 OSTFPROD docker[22646]:      url: 'wss://ostfprod.domain.com/d/pv1/LMG888AA88a88a88/16416/' },
Aug 30 09:25:22 OSTFPROD docker[22646]:   phone: { imei: '123456789012345', network: 'UNKNOWN' } }
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.112Z INF/device:plugins:touch 4149 [LMG888AA88a88a88] Touch origin is top left
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.112Z INF/device:plugins:touch 4149 [LMG888AA88a88a88] Requesting touch consumer to start
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.113Z INF/device:plugins:touch 4149 [LMG888AA88a88a88] Launching touch service
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.121Z INF/device:plugins:touch 4149 [LMG888AA88a88a88] Connecting to minitouch service
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.162Z INF/device:plugins:touch 4149 [LMG888AA88a88a88] minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.162Z INF/device:plugins:touch 4149 [LMG888AA88a88a88] minitouch says: "Type B touch device touch_dev (1439x3119 with 10 contacts) detected on /dev/input/event4 (score 23127)"
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.229Z INF/device:plugins:touch 4149 [LMG888AA88a88a88] Reading minitouch banner
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.231Z INF/device:plugins:touch 4149 [LMG888AA88a88a88] minitouch says: "Connection established"
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.285Z INF/device:plugins:vnc 4149 [LMG888AA88a88a88] Starting VNC server on port 16418
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.288Z INF/device:plugins:browser 4149 [LMG888AA88a88a88] Loading browser list
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.304Z INF/device:plugins:browser 4149 [LMG888AA88a88a88] Updating browser list
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.306Z INF/device:plugins:mute 4149 [LMG888AA88a88a88] Will not mute master volume
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.498Z INF/device:resources:minirev 4149 [LMG888AA88a88a88] Installing "/app/vendor/minirev/arm64-v8a/minirev" as "/data/local/tmp/minirev"
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.550Z INF/device:plugins:forward 4149 [LMG888AA88a88a88] Launching reverse port forwarding service
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.561Z INF/device:plugins:forward 4149 [LMG888AA88a88a88] Connecting to reverse port forwarding service
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.788Z INF/device:plugins:connect 4149 [LMG888AA88a88a88] Listening on port 16417
Aug 30 09:25:22 OSTFPROD docker[22646]: 2019-08-30T13:25:22.794Z INF/device 4149 [LMG888AA88a88a88] Fully operational

**Comment by varunkumarct** [comment]
Hi @meggleton  please follow the link 
https://github.com/openstf/minicap/issues/169

**Comment by varundtsfi** [comment]
Hi @meggleton  please follow the below link

https://github.com/openstf/stf/issues/1090
