### ISSUE TITLE
Error in starting stf locally on Mac

### ISSUE THREAD

**Issue by sanjay222joshi** [openstf/stf#1116]
Unexpected token ...
2019-10-17T17:43:39.936Z FTL/cli:local 62527 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by radekstasiak** [comment]
started getting this issue after successful update to v3.4.1

**Comment by viktorgogulenko** [comment]
@sanjay222joshi what is your node version? STF doesn't work for me with node v.11 on Mac, but works fine with 8.9.3.
