### ISSUE TITLE
got fatel error on installing openSTF in ubuntu 16.04 on executing stf local command

### ISSUE THREAD

**Issue by siva89r** [openstf/stf#1122]
i got the following FTL issue, when executing **stf local** command.
**OS Verions:** ubuntu 16.04 LTS.
**Following the instructions in the page:** ['https://github.com/openstf/stf/issues/732'](https://github.com/openstf/stf/issues/732)

```
siva@siva-Inspiron-1564:~$ stf local
2019-10-28T10:51:59.525Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli migrate"
2019-10-28T10:52:00.181Z INF/db 21629 [*] Connecting to 127.0.0.1:28015
2019-10-28T10:52:00.250Z INF/db:setup 21629 [*] Database "stf" created
2019-10-28T10:52:03.480Z INF/db:setup 21629 [*] Table "users" created
2019-10-28T10:52:03.580Z INF/db:setup 21629 [*] Table "devices" created
2019-10-28T10:52:03.585Z INF/db:setup 21629 [*] Table "vncauth" created
2019-10-28T10:52:03.585Z INF/db:setup 21629 [*] Table "logs" created
2019-10-28T10:52:03.586Z INF/db:setup 21629 [*] Table "accessTokens" created
2019-10-28T10:52:03.753Z INF/db:setup 21629 [*] Index "users"."adbKeys" created
2019-10-28T10:52:03.753Z INF/db:setup 21629 [*] Waiting for index "users"."adbKeys"
2019-10-28T10:52:03.777Z INF/db:setup 21629 [*] Index "devices"."owner" created
2019-10-28T10:52:03.777Z INF/db:setup 21629 [*] Waiting for index "devices"."owner"
2019-10-28T10:52:03.778Z INF/db:setup 21629 [*] Index "vncauth"."response" created
2019-10-28T10:52:03.778Z INF/db:setup 21629 [*] Index "accessTokens"."email" created
2019-10-28T10:52:03.779Z INF/db:setup 21629 [*] Waiting for index "vncauth"."response"
2019-10-28T10:52:03.779Z INF/db:setup 21629 [*] Waiting for index "accessTokens"."email"
2019-10-28T10:52:04.084Z INF/db:setup 21629 [*] Index "devices"."present" created
2019-10-28T10:52:04.085Z INF/db:setup 21629 [*] Waiting for index "devices"."present"
2019-10-28T10:52:04.129Z INF/db:setup 21629 [*] Index "vncauth"."responsePerDevice" created
2019-10-28T10:52:04.129Z INF/db:setup 21629 [*] Waiting for index "vncauth"."responsePerDevice"
2019-10-28T10:52:04.537Z INF/db:setup 21629 [*] Index "devices"."providerChannel" created
2019-10-28T10:52:04.537Z INF/db:setup 21629 [*] Waiting for index "devices"."providerChannel"
2019-10-28T10:52:05.312Z INF/db:setup 21629 [*] Index "users"."adbKeys" is ready
2019-10-28T10:52:05.343Z INF/db:setup 21629 [*] Index "devices"."owner" is ready
2019-10-28T10:52:05.344Z INF/db:setup 21629 [*] Index "vncauth"."response" is ready
2019-10-28T10:52:05.346Z INF/db:setup 21629 [*] Index "accessTokens"."email" is ready
2019-10-28T10:52:07.288Z INF/db:setup 21629 [*] Index "vncauth"."responsePerDevice" is ready
2019-10-28T10:52:07.699Z INF/db:setup 21629 [*] Index "devices"."providerChannel" is ready
2019-10-28T10:52:10.448Z INF/db:setup 21629 [*] Index "devices"."present" is ready
2019-10-28T10:52:10.467Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2019-10-28T10:52:10.474Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2019-10-28T10:52:10.481Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2019-10-28T10:52:10.485Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2019-10-28T10:52:10.496Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2019-10-28T10:52:10.500Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli provider --name siva-Inspiron-1564 --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"
2019-10-28T10:52:10.512Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
2019-10-28T10:52:10.524Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
2019-10-28T10:52:10.562Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
2019-10-28T10:52:10.583Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2019-10-28T10:52:10.604Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli storage-temp --port 7102"
2019-10-28T10:52:10.616Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2019-10-28T10:52:10.644Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2019-10-28T10:52:10.671Z INF/util:procutil 21623 [*] Forking "/home/siva/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
2019-10-28T10:52:13.041Z INF/triproxy 21635 [app001] PUB socket bound on tcp://127.0.0.1:7111
2019-10-28T10:52:13.041Z INF/triproxy 21641 [dev001] PUB socket bound on tcp://127.0.0.1:7114
2019-10-28T10:52:13.046Z INF/triproxy 21641 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
2019-10-28T10:52:13.046Z INF/triproxy 21635 [app001] DEALER socket bound on tcp://127.0.0.1:7112
2019-10-28T10:52:13.047Z INF/triproxy 21641 [dev001] PULL socket bound on tcp://127.0.0.1:7116
2019-10-28T10:52:13.047Z INF/triproxy 21635 [app001] PULL socket bound on tcp://127.0.0.1:7113
2019-10-28T10:52:13.341Z INF/db 21647 [*] Connecting to 127.0.0.1:28015
2019-10-28T10:52:13.341Z INF/db 21648 [*] Connecting to 127.0.0.1:28015
2019-10-28T10:52:13.405Z INF/processor 21647 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
2019-10-28T10:52:13.407Z INF/processor 21647 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
2019-10-28T10:52:13.408Z INF/processor 21648 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
2019-10-28T10:52:13.409Z INF/processor 21648 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
2019-10-28T10:52:13.603Z INF/reaper 21654 [reaper001] Subscribing to permanent channel "*ALL"
2019-10-28T10:52:13.608Z INF/reaper 21654 [reaper001] Reaping devices with no heartbeat
2019-10-28T10:52:13.614Z INF/db 21654 [reaper001] Connecting to 127.0.0.1:28015
2019-10-28T10:52:13.626Z INF/reaper 21654 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
2019-10-28T10:52:13.627Z INF/reaper 21654 [reaper001] Sending output to "tcp://127.0.0.1:7116"
2019-10-28T10:52:15.611Z INF/provider 21660 [*] Subscribing to permanent channel "1A6EQPiARumT+ZvrxO6tDA=="
2019-10-28T10:52:15.633Z INF/provider 21660 [*] Sending output to "tcp://127.0.0.1:7116"
2019-10-28T10:52:15.636Z INF/provider 21660 [*] Receiving input from "tcp://127.0.0.1:7114"
2019-10-28T10:52:15.649Z INF/provider 21660 [*] Tracking devices
2019-10-28T10:52:16.055Z INF/storage:plugins:image 21691 [*] Listening on port 7103
stf/lib/cli websocket

Options:
  -h, --help          Show help.                                       [boolean]
  -V, --version       Show version.                                    [boolean]
  --connect-push, -c  App-side ZeroMQ PULL endpoint to connect to.
                                                              [array] [required]
  --connect-sub, -u   App-side ZeroMQ PUB endpoint to connect to.
                                                              [array] [required]
  --port, -p          The port to bind to.              [number] [default: 7110]
  --secret, -s        The secret to use for auth JSON Web Tokens. Anyone who
                      knows this token can freely enter the system if they want,
                      so keep it safe.                       [string] [required]
  --ssid, -i          The name of the session ID cookie.
                                                      [string] [default: "ssid"]
  --storage-url, -r   URL to the storage unit.               [string] [required]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_WEBSOCKET_` (e.g. `STF_WEBSOCKET_STORAGE_URL`).

Unexpected token ...
2019-10-28T10:52:16.645Z FTL/cli:local 21623 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/home/siva/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
2019-10-28T10:52:16.645Z INF/cli:local 21623 [*] Shutting down all child processes
2019-10-28T10:52:16.675Z INF/util:lifecycle 21635 [app001] Winding down for graceful exit
2019-10-28T10:52:16.677Z INF/util:lifecycle 21641 [dev001] Winding down for graceful exit
2019-10-28T10:52:16.696Z INF/util:lifecycle 21647 [proc001] Winding down for graceful exit
2019-10-28T10:52:16.701Z INF/util:lifecycle 21648 [proc002] Winding down for graceful exit
2019-10-28T10:52:16.706Z WRN/db 21647 [proc001] Connection closed
2019-10-28T10:52:16.710Z WRN/db 21648 [proc002] Connection closed
2019-10-28T10:52:16.711Z INF/util:lifecycle 21654 [reaper001] Winding down for graceful exit
2019-10-28T10:52:16.712Z INF/util:lifecycle 21660 [*] Winding down for graceful exit
2019-10-28T10:52:16.719Z WRN/db 21654 [reaper001] Connection closed

```

on executing **stf doctor** command

```
siva@siva-Inspiron-1564:~$ stf doctor
2019-10-28T11:16:55.888Z INF/cli:doctor 21942 [*] OS Arch: x64
2019-10-28T11:16:55.891Z INF/cli:doctor 21942 [*] OS Platform: linux
2019-10-28T11:16:55.892Z INF/cli:doctor 21942 [*] OS Platform: 4.15.0-45-generic
2019-10-28T11:16:55.892Z INF/cli:doctor 21942 [*] Using Node 6.11.0
2019-10-28T11:16:55.958Z INF/cli:doctor 21942 [*] Using ZeroMQ 4.2.1
2019-10-28T11:16:56.082Z INF/cli:doctor 21942 [*] Using RethinkDB 2.3.6~0xenial
2019-10-28T11:16:56.083Z INF/cli:doctor 21942 [*] Using ADB 1.0.41
2019-10-28T11:16:56.248Z INF/cli:doctor 21942 [*] Using ProtoBuf 3.2.0
2019-10-28T11:16:56.505Z INF/cli:doctor 21942 [*] Using GraphicsMagick 1.3.23

```
i have attached the complete logs of my installation here. can sone one help me resolving the issue in installing openSTF in my ubuntu 16.04 LTS. 
[openSTF_Install.docx](https://github.com/openstf/stf/files/3778427/openSTF_Install.docx)

Let me know if you need additional information

**Comment by Grohden** [comment]
running on mac, upgraded the node version to 8.16 fixed:

https://github.com/openstf/stf/issues/1106#issuecomment-539901849
