### ISSUE TITLE
Encounter stream error when uploading .apk files.

### ISSUE THREAD

**Issue by cheneyxwong** [openstf/stf#1126]
**What is the issue or idea you have?**
Server shuts down when uploading an .apk file.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
No.

**Please provide the steps to reproduce the issue.**
To upload an app.

**What is the expected behavior?**
Upload successful.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
2019-10-30T03:00:57.238Z INF/storage:temp 55161 [*] Uploaded "应用.apk" to "/var/folders/pz/3wvgx55j6f9c0y02h8rgh9mm0000gp/T/upload_76ac3d0c10077561f0d5de712b546150"
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:344:15)
    at Socket.socketOnEnd (_http_client.js:436:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
2019-10-30T03:00:57.313Z ERR/poorxy 55164 [*] Proxy had an error Error: socket hang up
    at createHangUpError (_http_client.js:344:15)
    at Socket.socketOnEnd (_http_client.js:436:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
2019-10-30T03:00:57.315Z FTL/cli:local 55147 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/Users/wangweiqing/.nvm/versions/node/v8.1.1/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
2019-10-30T03:00:57.315Z INF/cli:local 55147 [*] Shutting down all child processes

**Please run `stf doctor` and paste the output here.**

**Comment by cheneyxwong** [comment]
Got it. When the filename contains Chinese characters the problem happens. I think it is a minor bug.

**Comment by koral--** [comment]
Superseded by https://github.com/openstf/stf/issues/1186
