### ISSUE TITLE
Unable to detect any device

### ISSUE THREAD

**Issue by Amrkamel1** [openstf/stf#1129]
im totally new with stf, i just installed the env and able to navigate to stf using the local host, but i cant see any device, im not sure if im missing some config or something

adb devices -l
192.168.1.2:5555       device product:d2sxx model:SM_N975F device:d2s transport_id:1

stf doctor log : 
```
2019-11-02T00:57:26.183Z INF/cli:doctor 17938 [*] OS Arch: x64
2019-11-02T00:57:26.184Z INF/cli:doctor 17938 [*] OS Platform: linux
2019-11-02T00:57:26.184Z INF/cli:doctor 17938 [*] OS Platform: 5.0.0-32-generic
2019-11-02T00:57:26.184Z INF/cli:doctor 17938 [*] Using Node 8.16.2
2019-11-02T00:57:26.191Z INF/cli:doctor 17938 [*] Using ZeroMQ 4.2.5
2019-11-02T00:57:26.198Z INF/cli:doctor 17938 [*] Using GraphicsMagick 1.3.33
2019-11-02T00:57:26.198Z INF/cli:doctor 17938 [*] Using ProtoBuf 3.11.0
2019-11-02T00:57:26.198Z INF/cli:doctor 17938 [*] Using ADB 1.0.41
2019-11-02T00:57:26.200Z INF/cli:doctor 17938 [*] Using RethinkDB 2.3.7~0bionic
```
rethinkdb log
```
hjjjh@warrior:~/Desktop/Practices$ rethinkdb --bind all
Running rethinkdb 2.3.7~0bionic (CLANG 6.0.0 (tags/RELEASE_600/final))...
Running on Linux 5.0.0-32-generic x86_64
Loading data from directory /home/amrka/Desktop/Practices/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, 192.168.122.1, 192.168.1.6, ::1, fe80::2d9a:b06e:32f6:5d36%3
Listening on driver addresses: 127.0.0.1, 192.168.122.1, 192.168.1.6, ::1, fe80::2d9a:b06e:32f6:5d36%3
Listening on http addresses: 127.0.0.1, 192.168.122.1, 192.168.1.6, ::1, fe80::2d9a:b06e:32f6:5d36%3
Server ready, "warrior_i9e" e2466c88-1d28-8989-8b0b-293a8e7b199f
```

stf local log
```
2019-11-02T00:51:45.933Z INF/db 16705 [*] Connecting to 127.0.0.1:28015
2019-11-02T00:51:45.966Z INF/storage:plugins:image 16731 [*] Listening on port 7103
2019-11-02T00:51:46.014Z INF/websocket 16718 [*] Subscribing to permanent channel "*ALL"
2019-11-02T00:51:46.017Z INF/websocket 16718 [*] Listening on port 7110
2019-11-02T00:51:46.025Z INF/db 16718 [*] Connecting to 127.0.0.1:28015
2019-11-02T00:51:46.028Z INF/websocket 16718 [*] Sending output to "tcp://127.0.0.1:7113"
2019-11-02T00:51:46.028Z INF/websocket 16718 [*] Receiving input from "tcp://127.0.0.1:7111"
2019-11-02T00:51:46.166Z INF/api 16712 [*] Subscribing to permanent channel "*ALL"
2019-11-02T00:51:46.189Z INF/api 16712 [*] Listening on port 7106
2019-11-02T00:51:46.193Z INF/api 16712 [*] Sending output to "tcp://127.0.0.1:7113"
2019-11-02T00:51:46.194Z INF/api 16712 [*] Receiving input from "tcp://127.0.0.1:7111"
2019-11-02T00:51:46.275Z INF/db 16712 [*] Connecting to 127.0.0.1:28015
2019-11-02T00:52:03.102Z INF/auth-mock 16698 [::ffff:127.0.0.1] Authenticated "ygjgh@yhjn.com"
```

![chrome-capture](https://user-images.githubusercontent.com/32042806/68063851-af13e280-fd14-11e9-80ab-df6e70a510ca.jpg)

**Comment by Amrkamel1** [comment]
i connected phone directly using usb 
and getting this 
`FTL/device 20990 [RF8M82EDL8Y] Setup had an error Error: Service had an error: "Error: Not found; no service started."
    at /home/amrka/Desktop/Practices/stf/lib/units/device/plugins/service.js:101:23
From previous event:
    at /home/amrka/Desktop/Practices/stf/lib/units/device/plugins/service.js:76:14
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2019-11-02T01:20:58.820Z FTL/util:lifecycle 20990 [RF8M82EDL8Y] Shutting down due to fatal error
2019-11-02T01:20:58.828Z INF/provider 19614 [*] Cleaning up device worker "RF8M82EDL8Y"
2019-11-02T01:20:58.828Z ERR/provider 19614 [*] Device worker "RF8M82EDL8Y" died with code 1
2019-11-02T01:20:58.828Z INF/provider 19614 [*] Restarting device worker "RF8M82EDL8Y"
2019-11-02T01:20:59.502Z INF/device:support:push 21002 [RF8M82EDL8Y] Sending output to "tcp://127.0.0.1:7116"
2019-11-02T01:20:59.504Z INF/device 21002 [RF8M82EDL8Y] Preparing device
2019-11-02T01:20:59.693Z INF/device:support:sub 21002 [RF8M82EDL8Y] Receiving input from "tcp://127.0.0.1:7114"
2019-11-02T01:20:59.694Z INF/device:support:sub 21002 [RF8M82EDL8Y] Subscribing to permanent channel "*ALL"
2019-11-02T01:20:59.755Z INF/device:support:properties 21002 [RF8M82EDL8Y] Loading properties
2019-11-02T01:20:59.804Z INF/device:support:sdk 21002 [RF8M82EDL8Y] Supports SDK 28
2019-11-02T01:20:59.806Z INF/device:support:abi 21002 [RF8M82EDL8Y] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2019-11-02T01:20:59.995Z INF/device:resources:minicap 21002 [RF8M82EDL8Y] Installing "/home/amrka/Desktop/Practices/stf/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
`
and device appear disconnected
