### ISSUE TITLE
Can't locate bindings file

### ISSUE THREAD

**Issue by luciusdyaliv** [openstf/stf#1138]
Command: stf local
Could not find bindings file.

2019-11-22T18:52:05.642Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli migrate"
2019-11-22T18:52:05.809Z INF/db 10295 [*] Connecting to 127.0.0.1:28015
2019-11-22T18:52:05.822Z INF/db:setup 10295 [*] Database "stf" already exists
2019-11-22T18:52:05.826Z INF/db:setup 10295 [*] Table "users" already exists
2019-11-22T18:52:05.827Z INF/db:setup 10295 [*] Table "accessTokens" already exists
2019-11-22T18:52:05.827Z INF/db:setup 10295 [*] Table "vncauth" already exists
2019-11-22T18:52:05.827Z INF/db:setup 10295 [*] Table "devices" already exists
2019-11-22T18:52:05.827Z INF/db:setup 10295 [*] Table "logs" already exists
2019-11-22T18:52:05.834Z INF/db:setup 10295 [*] Index "users"."adbKeys" already exists
2019-11-22T18:52:05.834Z INF/db:setup 10295 [*] Index "accessTokens"."email" already exists
2019-11-22T18:52:05.834Z INF/db:setup 10295 [*] Index "vncauth"."response" already exists
2019-11-22T18:52:05.834Z INF/db:setup 10295 [*] Index "vncauth"."responsePerDevice" already exists
2019-11-22T18:52:05.834Z INF/db:setup 10295 [*] Waiting for index "users"."adbKeys"
2019-11-22T18:52:05.835Z INF/db:setup 10295 [*] Waiting for index "accessTokens"."email"
2019-11-22T18:52:05.835Z INF/db:setup 10295 [*] Waiting for index "vncauth"."response"
2019-11-22T18:52:05.835Z INF/db:setup 10295 [*] Waiting for index "vncauth"."responsePerDevice"
2019-11-22T18:52:05.838Z INF/db:setup 10295 [*] Index "devices"."owner" already exists
2019-11-22T18:52:05.838Z INF/db:setup 10295 [*] Index "devices"."present" already exists
2019-11-22T18:52:05.838Z INF/db:setup 10295 [*] Index "devices"."providerChannel" already exists
2019-11-22T18:52:05.838Z INF/db:setup 10295 [*] Index "users"."adbKeys" is ready
2019-11-22T18:52:05.838Z INF/db:setup 10295 [*] Waiting for index "devices"."owner"
2019-11-22T18:52:05.838Z INF/db:setup 10295 [*] Waiting for index "devices"."present"
2019-11-22T18:52:05.839Z INF/db:setup 10295 [*] Waiting for index "devices"."providerChannel"
2019-11-22T18:52:05.840Z INF/db:setup 10295 [*] Index "accessTokens"."email" is ready
2019-11-22T18:52:05.840Z INF/db:setup 10295 [*] Index "vncauth"."response" is ready
2019-11-22T18:52:05.840Z INF/db:setup 10295 [*] Index "vncauth"."responsePerDevice" is ready
2019-11-22T18:52:05.842Z INF/db:setup 10295 [*] Index "devices"."owner" is ready
2019-11-22T18:52:05.843Z INF/db:setup 10295 [*] Index "devices"."present" is ready
2019-11-22T18:52:05.843Z INF/db:setup 10295 [*] Index "devices"."providerChannel" is ready
2019-11-22T18:52:05.848Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2019-11-22T18:52:05.850Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2019-11-22T18:52:05.852Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2019-11-22T18:52:05.854Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2019-11-22T18:52:05.856Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2019-11-22T18:52:05.867Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli provider --name lucius --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"
2019-11-22T18:52:05.878Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
2019-11-22T18:52:05.892Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
2019-11-22T18:52:05.898Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
2019-11-22T18:52:05.907Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2019-11-22T18:52:05.916Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli storage-temp --port 7102"
2019-11-22T18:52:05.931Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2019-11-22T18:52:05.939Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2019-11-22T18:52:05.963Z INF/util:procutil 10289 [*] Forking "/home/lucius/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
stf/lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                                    [string] [default: "lucius"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

stf/lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                                    [string] [default: "lucius"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Could not locate the bindings file. Tried:
 → /home/lucius/stf/node_modules/zmq/build/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/out/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/out/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/default/zmq.node
 → /home/lucius/stf/node_modules/zmq/compiled/8.16.2/linux/x64/zmq.node
Could not locate the bindings file. Tried:
 → /home/lucius/stf/node_modules/zmq/build/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/out/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/out/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/default/zmq.node
 → /home/lucius/stf/node_modules/zmq/compiled/8.16.2/linux/x64/zmq.node
2019-11-22T18:52:06.853Z FTL/cli:local 10289 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/home/lucius/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2019-11-22T18:52:06.853Z INF/cli:local 10289 [*] Shutting down all child processes
stf/lib/cli processor [name]

Options:
  -h, --help                Show help.                                 [boolean]
  -V, --version             Show version.                              [boolean]
  --connect-app-dealer, -a  App-side ZeroMQ DEALER endpoint to connect to.
                                                              [array] [required]
  --connect-dev-dealer, -d  Device-side ZeroMQ DEALER endpoint to connect to.
                                                              [array] [required]
  --name                    An easily identifiable name for log output.
                                                    [string] [default: "lucius"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_PROCESSOR_` (e.g. `STF_PROCESSOR_CONNECT_APP_DEALER`).

Could not locate the bindings file. Tried:
 → /home/lucius/stf/node_modules/zmq/build/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/out/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/out/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/default/zmq.node
 → /home/lucius/stf/node_modules/zmq/compiled/8.16.2/linux/x64/zmq.node

**Please run `stf doctor` and paste the output here.**

2019-11-22T18:53:28.299Z INF/cli:doctor 10388 [*] OS Arch: x64
2019-11-22T18:53:28.301Z INF/cli:doctor 10388 [*] OS Platform: linux
2019-11-22T18:53:28.301Z INF/cli:doctor 10388 [*] OS Platform: 5.3.0-23-generic
2019-11-22T18:53:28.301Z INF/cli:doctor 10388 [*] Using Node 8.16.2
2019-11-22T18:53:28.324Z ERR/cli:doctor 10388 [*] Unexpected error checking ZeroMQ: Error: Could not locate the bindings file. Tried:
 → /home/lucius/stf/node_modules/zmq/build/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/out/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/Debug/zmq.node
 → /home/lucius/stf/node_modules/zmq/out/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/Release/zmq.node
 → /home/lucius/stf/node_modules/zmq/build/default/zmq.node
 → /home/lucius/stf/node_modules/zmq/compiled/8.16.2/linux/x64/zmq.node
2019-11-22T18:53:28.325Z INF/cli:doctor 10388 [*] Using GraphicsMagick 1.4
2019-11-22T18:53:28.326Z INF/cli:doctor 10388 [*] Using ProtoBuf 3.6.1
2019-11-22T18:53:28.327Z ERR/cli:doctor 10388 [*] RethinkDB version cannot be detected
2019-11-22T18:53:28.327Z ERR/cli:doctor 10388 [*] ADB version cannot be detected
2019-11-22T18:53:28.327Z ERR/cli:doctor 10388 [*] Unexpected error checking GraphicsMagick: TypeError: Invalid Version: 1.4

**Comment by koral--** [comment]
It looks like you don't have dependencies installed: https://github.com/openstf/stf#requirements

**Comment by rakib-amin** [comment]
instead of brew, use `npm install zmq`
