### ISSUE TITLE
Error Unexpected token u in JSON at position 0 - OAuth2 with Google Account

### ISSUE THREAD

**Issue by bellierjonathan** [openstf/stf#1156]
Hello, 

I got this error when using OAuth2 with Google. Do you have an idea why?

`stf local --public-ip farm.example.com --auth-type oauth2 --auth-options '["--oauth-authorization-url","https://accounts.google.com/o/oauth2/auth","--oauth-token-url","https://oauth2.googleapis.com/token","--oauth-userinfo-url","https://www.googleapis.com/auth/userinfo.email","--oauth-client-id","XXX","--oauth-client-secret","XXXX","--oauth-callback-url","farm.example.com:7100/auth/oauth/callback","--oauth-scope","openid email"]'`

When I try to log, I got Google account suggestion, I click on my account and I got this error :
`SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/node_modules/stf/lib/units/auth/oauth2/strategy.js:23:34
    at passBackControl (/usr/lib/node_modules/stf/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/stf/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)`

**Comment by bellierjonathan** [comment]
Ok I didn't see there is a duplicated post here : 
https://github.com/openstf/stf/issues/311
