### ISSUE TITLE
Multiple touch in manipulating smart phone page causes an error

### ISSUE THREAD

**Issue by att55** [openstf/stf#1180]
**What is the issue or idea you have?**

multiple touch in manipulating smart phone page causes an error.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

No, this error occurs any devices.

**Please provide the steps to reproduce the issue.**

pre-condtion: Use Surface or Tablet to touch display.

1. Open the manipulating smart phone page. (after chose a smart phone from a list)
2. Touch a smart phone area.
3. At the same time, touch the area other than a smart phone. (like upload application)
4. The error occurs.

**What is the expected behavior?**

Does not occur the error.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

The error log is following.

```
/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641
                    throw Error("Illegal value for "+this.toString(true)+" of type "+this.type.name+": "+val+" ("+msg+")");
                    ^

Error: Illegal value for Message.Field .TouchMoveMessage.contact of type uint32: undefined (not an integer)
    at Field.<anonymous> (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2675:29)
    at MessagePrototype.set (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1799:63)
    at new Message (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1728:42)
    at Socket.<anonymous> (/usr/lib/node_modules/stf/lib/units/websocket/index.js:466:31)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at /usr/lib/node_modules/stf/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

This error occurred in protobufjs.
I think the version of protobuffjs in STF is too old... 🤔

- package.json
https://github.com/openstf/stf/blob/master/package.json#L75

- releases of protobufjs
https://github.com/protobufjs/protobuf.js/releases

**Comment by koral--** [comment]
Thanks for the report. Regarding protobuf version, there is a PR for that: https://github.com/openstf/stf/pull/1161
Dependencies will be updated soon.

**Comment by att55** [comment]
@koral-- Thank you SO much for your reply !! 😄
I added comment to this issue report. Please check when you can 🙏 

```
After the error, STF always returns the error unless the STF process is restarted...
```

Do you think the cause, STF or protobufjs?

**Comment by att55** [comment]
- FYI

I tried to start stf after changed protobufjs to latest version.
But an error occurred as below... 😓 

```
ProtoBuf.loadProtoFile is not a function
/Users/atyamash/Create/github.com/stf/node_modules/bluebird/js/main/promise.js:680
```

It seems that the structure of protobufjs has been changed significantly.

**Comment by att55** [comment]
@koral-- Hi,  if PR#1180 released, this issue will be resolved.
Should I close this issue?

**Comment by koral--** [comment]
Autobuild including that PR should be available.
I woul leave this issue open for now. 
Just catching an exception does not look like a final solution.

**Comment by att55** [comment]
> I would leave this issue open for now.

OK, let's do so 👍
