### ISSUE TITLE
Tracker had an error Error: Connection closed

### ISSUE THREAD

**Issue by kotini** [openstf/stf#1183]
I keep getting this error in latest master code .

Only one device connected in stf provider .

```
2020-02-20T13:08:33.308Z FTL/util:lifecycle 1 [*] Tracker had an error Error: Connection closed
    at /app/node_modules/adbkit/lib/adb/tracker.js:21:13
    at tryCatcher (/app/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/app/node_modules/adbkit/node_modules/bluebird/js/main/catch_filter.js:40:36)
    at CatchFilter.tryCatcher (/app/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/app/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/app/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/app/node_modules/adbkit/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/node_modules/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/app/node_modules/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by kotini** [comment]
@koral--  any update on this ?

**Comment by kotini** [comment]
@sorccu  and team any idea about this issue ?
i am running provider as docker .

`2020-03-05T06:41:02.932Z FTL/util:lifecycle 23 [emulator-5554] Forward shell ended; we shall share its fate
2020-03-05T06:41:02.932Z FTL/util:lifecycle 23 [emulator-5554] Shutting down due to fatal error
2020-03-05T06:41:02.933Z FTL/util:lifecycle 18 [emulator-5556] Forward shell ended; we shall share its fate
2020-03-05T06:41:02.934Z FTL/util:lifecycle 18 [emulator-5556] Shutting down due to fatal error
2020-03-05T06:41:02.938Z FTL/util:lifecycle 1 [*] Tracker had an error Error: Connection closed
    at /app/node_modules/adbkit/lib/adb/tracker.js:21:13
    at tryCatcher (/app/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/app/node_modules/adbkit/node_modules/bluebird/js/main/catch_filter.js:40:36)
    at CatchFilter.tryCatcher (/app/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/app/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/app/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/app/node_modules/adbkit/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/node_modules/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/app/node_modules/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)`

**Comment by koral--** [comment]
Sorry for the delay.
Does it happen only with emulator?

**Comment by kotini** [comment]
@koral-- it happens with emulator and device both . 
when i run provider in one machine and stf server other machine .

**Comment by denis99999** [comment]
@kotini android emulator is not fully supported by STF, the logs show an error using emulators, please remove emulators and let us know if you meet the same issue using only a physical device. If yes please fill the bug report providing in particular full logs.

**Comment by kotini** [comment]
@denis99999 latest code working fine for emulator and device

**Comment by denis99999** [comment]
@kotini ,

Great ! 
Do you really able to remote control an emulator (i.e. display, keyboard, ...) through STF as a real device ? If yes, what kind of emulator do you use ?
