### ISSUE TITLE
Redmi Note8 keeps connected and disconnect constantly

### ISSUE THREAD

**Issue by KevinChann** [openstf/stf#1187]
**What is the issue or idea you have?**
Redmi Note8 keeps connected and disconnect constantly.
It connect normally on devices.But when I try to remote control and click the phone icon, it just disconnect me and told me **Device was disconnected**, **Someone tole your device**.
I click *Try to reconnect* and it keeps the same situation.

**My env:**
```
macOS version: 10.14.5
stf version: 3.4.1
phone info: Xiaomi Redmi Note8, Android 9, MIUI 11.0.4 stable
```

**Here's the log:**
```
2020-02-21T02:14:22.371Z FTL/device:plugins:screen:stream 46209 [a0938e2b] Frame producer had an error FailError: Failure: 'closed'
    at /Users/kevinchan/CKL/stf/stf/node_modules/adbkit/lib/adb/parser.js:183:29
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2020-02-21T02:14:22.371Z FTL/util:lifecycle 46209 [a0938e2b] Shutting down due to fatal error
2020-02-21T02:14:22.376Z INF/provider 46058 [*] Cleaning up device worker "a0938e2b"
2020-02-21T02:14:22.376Z ERR/provider 46058 [*] Device worker "a0938e2b" died with code 1
2020-02-21T02:14:22.377Z INF/provider 46058 [*] Restarting device worker "a0938e2b"
2020-02-21T02:14:23.103Z INF/device:support:push 46225 [a0938e2b] Sending output to "tcp://127.0.0.1:7116"
2020-02-21T02:14:23.105Z INF/device 46225 [a0938e2b] Preparing device
2020-02-21T02:14:23.397Z INF/device:support:sub 46225 [a0938e2b] Receiving input from "tcp://127.0.0.1:7114"
2020-02-21T02:14:23.398Z INF/device:support:sub 46225 [a0938e2b] Subscribing to permanent channel "*ALL"
2020-02-21T02:14:23.454Z INF/device:support:properties 46225 [a0938e2b] Loading properties
2020-02-21T02:14:23.511Z INF/device:support:sdk 46225 [a0938e2b] Supports SDK 28
2020-02-21T02:14:23.512Z INF/device:support:abi 46225 [a0938e2b] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2020-02-21T02:14:23.781Z INF/device:resources:minicap 46225 [a0938e2b] Installing "/Users/kevinchan/CKL/stf/stf/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
2020-02-21T02:14:23.781Z INF/device:resources:minicap 46225 [a0938e2b] Installing "/Users/kevinchan/CKL/stf/stf/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/lib/android-28/minicap.so" as "/data/local/tmp/minicap.so"
2020-02-21T02:14:23.856Z INF/device:resources:service 46225 [a0938e2b] Checking whether we need to install STFService
2020-02-21T02:14:23.908Z INF/device:resources:service 46225 [a0938e2b] Running version check
2020-02-21T02:14:24.464Z INF/device:resources:service 46225 [a0938e2b] STFService up to date
2020-02-21T02:14:24.465Z INF/device:plugins:service 46225 [a0938e2b] Launching agent
2020-02-21T02:14:25.214Z INF/device:plugins:service 46225 [a0938e2b] Agent says: "Listening on @stfagent"
2020-02-21T02:14:25.238Z INF/device:plugins:service 46225 [a0938e2b] Launching service
2020-02-21T02:14:25.239Z INF/device:plugins:service 46225 [a0938e2b] using 'start-foreground-service' command for API 28
2020-02-21T02:14:25.249Z INF/device:plugins:service 46225 [a0938e2b] Agent says: "InputClient started"
2020-02-21T02:14:25.331Z INF/device:plugins:display 46225 [a0938e2b] Reading display info
2020-02-21T02:14:25.348Z INF/device:plugins:phone 46225 [a0938e2b] Fetching phone info
2020-02-21T02:14:25.393Z INF/device:plugins:identity 46225 [a0938e2b] Solving identity
2020-02-21T02:14:25.397Z INF/device:plugins:solo 46225 [a0938e2b] Subscribing to permanent channel "N2PMWZ76m++3UiBkRw6MRbR4BU8="
2020-02-21T02:14:25.398Z INF/device:plugins:screen:stream 46225 [a0938e2b] Starting WebSocket server on port 7428
2020-02-21T02:14:25.646Z INF/device:resources:minitouch 46225 [a0938e2b] Installing "/Users/kevinchan/CKL/stf/stf/node_modules/minitouch-prebuilt-beta/prebuilt/arm64-v8a/bin/minitouch" as "/data/local/tmp/minitouch"
2020-02-21T02:14:25.725Z WRN/device:plugins:data 46225 [a0938e2b] Unable to find device data { serial: 'a0938e2b',
  platform: 'Android',
  manufacturer: 'XIAOMI',
  operator: ',',
  model: 'Redmi Note 8',
  version: '9',
  abi: 'arm64-v8a',
  sdk: '28',
  product: 'ginkgo',
  cpuPlatform: 'trinket',
  openGLESVersion: '3.2',
  marketName: 'Redmi Note 8',
  display: 
   { id: 0,
     width: 1080,
     height: 2340,
     xdpi: 409.4320068359375,
     ydpi: 409.90301513671875,
     fps: 60.000003814697266,
     density: 2.75,
     rotation: 0,
     secure: true,
     size: 6.288630704837173,
     url: 'ws://localhost:7428' },
  phone: { imei: '864086040059234', network: 'UNKNOWN' } }
2020-02-21T02:14:25.729Z INF/device:plugins:touch 46225 [a0938e2b] Touch origin is top left
2020-02-21T02:14:25.729Z INF/device:plugins:touch 46225 [a0938e2b] Requesting touch consumer to start
2020-02-21T02:14:25.730Z INF/device:plugins:touch 46225 [a0938e2b] Launching touch service
2020-02-21T02:14:25.739Z INF/device:plugins:touch 46225 [a0938e2b] Connecting to minitouch service
2020-02-21T02:14:25.758Z INF/device:plugins:touch 46225 [a0938e2b] minitouch says: "Type B touch device NVTCapacitiveTouchScreen (1079x2339 with 10 contacts) detected on /dev/input/event2 (score 22597)"
2020-02-21T02:14:25.851Z INF/device:plugins:touch 46225 [a0938e2b] Reading minitouch banner
2020-02-21T02:14:25.855Z INF/device:plugins:touch 46225 [a0938e2b] minitouch says: "Connection established"
2020-02-21T02:14:25.857Z INF/device:plugins:vnc 46225 [a0938e2b] Starting VNC server on port 7430
2020-02-21T02:14:25.858Z INF/device:plugins:browser 46225 [a0938e2b] Loading browser list
2020-02-21T02:14:25.866Z INF/device:plugins:browser 46225 [a0938e2b] Updating browser list
2020-02-21T02:14:25.868Z INF/device:plugins:mute 46225 [a0938e2b] Will not mute master volume
2020-02-21T02:14:26.113Z INF/device:resources:minirev 46225 [a0938e2b] Installing "/Users/kevinchan/CKL/stf/stf/vendor/minirev/arm64-v8a/minirev" as "/data/local/tmp/minirev"
2020-02-21T02:14:26.172Z INF/device:plugins:forward 46225 [a0938e2b] Launching reverse port forwarding service
2020-02-21T02:14:26.186Z INF/device:plugins:forward 46225 [a0938e2b] Connecting to reverse port forwarding service
2020-02-21T02:14:26.400Z INF/device 46225 [a0938e2b] Fully operational
2020-02-21T02:14:38.301Z IMP/device:plugins:group 46225 [a0938e2b] Now owned by "ckl@ckl.ckl"
2020-02-21T02:14:38.301Z INF/device:plugins:group 46225 [a0938e2b] Subscribing to group channel "Ms2YsTSuT9iobBvWN2oLaA=="
2020-02-21T02:14:38.359Z INF/device:plugins:screen:stream 46225 [a0938e2b] Setting frame producer projection to 843x843
2020-02-21T02:14:38.360Z INF/device:plugins:screen:stream 46225 [a0938e2b] Requesting frame producer to start
2020-02-21T02:14:38.360Z INF/device:plugins:screen:stream 46225 [a0938e2b] Launching screen service
2020-02-21T02:14:38.454Z INF/device:plugins:screen:stream 46225 [a0938e2b] minicap says: "PID: 8336"
2020-02-21T02:14:38.454Z INF/device:plugins:screen:stream 46225 [a0938e2b] minicap says: "INFO: Using projection 1080x2340@389x843/0"
2020-02-21T02:14:38.455Z INF/device:plugins:screen:stream 46225 [a0938e2b] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient"
2020-02-21T02:14:38.455Z INF/device:plugins:screen:stream 46225 [a0938e2b] Connecting to minicap service
2020-02-21T02:14:38.463Z INF/device:plugins:screen:stream 46225 [a0938e2b] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check"
2020-02-21T02:14:38.463Z INF/device:plugins:screen:stream 46225 [a0938e2b] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display"
2020-02-21T02:14:38.463Z INF/device:plugins:screen:stream 46225 [a0938e2b] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue"
2020-02-21T02:14:38.463Z INF/device:plugins:screen:stream 46225 [a0938e2b] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options"
2020-02-21T02:14:38.464Z INF/device:plugins:screen:stream 46225 [a0938e2b] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer"
2020-02-21T02:14:38.464Z INF/device:plugins:screen:stream 46225 [a0938e2b] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter"
2020-02-21T02:14:38.464Z INF/device:plugins:screen:stream 46225 [a0938e2b] minicap says: "INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display"
2020-02-21T02:14:38.464Z INF/device:plugins:screen:stream 46225 [a0938e2b] minicap says: "Vector<> have different types (this=0x7ffd104af0, rhs=0x7ffd104c10)"
2020-02-21T02:14:38.475Z INF/device:plugins:connect 46225 [a0938e2b] Listening on port 7429
2020-02-21T02:14:38.476Z IMP/device:plugins:connect 46225 [a0938e2b] Remote Connect Started for device "a0938e2b" at "localhost:7429"
2020-02-21T02:14:38.539Z WRN/device:plugins:screen:stream 46225 [a0938e2b] Shell keeping minicap running ended unexpectedly
2020-02-21T02:14:39.987Z INF/device:plugins:screen:stream 46225 [a0938e2b] Disconnecting from minicap service
2020-02-21T02:14:39.988Z INF/device:plugins:screen:stream 46225 [a0938e2b] Stopping minicap service
2020-02-21T02:14:39.988Z FTL/device:plugins:screen:stream 46225 [a0938e2b] Frame producer had an error FailError: Failure: 'closed'
    at /Users/kevinchan/CKL/stf/stf/node_modules/adbkit/lib/adb/parser.js:183:29
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2020-02-21T02:14:39.989Z FTL/util:lifecycle 46225 [a0938e2b] Shutting down due to fatal error
2020-02-21T02:14:39.994Z INF/provider 46058 [*] Cleaning up device worker "a0938e2b"
2020-02-21T02:14:39.994Z ERR/provider 46058 [*] Device worker "a0938e2b" died with code 1
2020-02-21T02:14:39.994Z INF/provider 46058 [*] Restarting device worker "a0938e2b"
```

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
Yes. It only happends on Xiaomi Redmi Note 8, as I known.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
No.

**Please run `stf doctor` and paste the output here.**
```
2020-02-21T03:39:50.997Z INF/cli:doctor 47774 [*] OS Arch: x64
2020-02-21T03:39:50.999Z INF/cli:doctor 47774 [*] OS Platform: darwin
2020-02-21T03:39:50.999Z INF/cli:doctor 47774 [*] OS Platform: 18.6.0
2020-02-21T03:39:50.999Z INF/cli:doctor 47774 [*] Using Node 8.14.0
2020-02-21T03:39:51.010Z INF/cli:doctor 47774 [*] Using ZeroMQ 4.3.2
2020-02-21T03:39:51.021Z INF/cli:doctor 47774 [*] Using GraphicsMagick 1.3.34
2020-02-21T03:39:51.022Z INF/cli:doctor 47774 [*] Using ADB 1.0.41
2020-02-21T03:39:51.030Z INF/cli:doctor 47774 [*] Using ProtoBuf 3.11.4
2020-02-21T03:39:51.031Z INF/cli:doctor 47774 [*] Using RethinkDB 2.4.0
```

**Comment by sawchen** [comment]
@KevinChann
As i known ,it happened on the  all xiaomi phone with MIUI 11 system. I have xiaomi 8, xiaomi 8 se devices with MIUI 11, they all happened.But redmi note 6 with MIUI 10 and note 4x with MIUI 10 Can operate normally.

**Comment by KevinChann** [comment]
@sawchen Yes. I tried MI 10 with MIUI 11.0.4 stable. It's the same situation!

**Comment by xd2006** [comment]
The same for MI 9 lite with MIUI 12 and Redmi Note 7 with MIUI 11. Virtual screen is not displayed for these devices as well.
![2020-09-18_19-41-22](https://user-images.githubusercontent.com/6172381/93623558-99b8ad00-f9e7-11ea-8200-48faae36bcf2.png)
