### ISSUE TITLE
Child process had an error ExitError: Exit code "1" -despite attempts to solve the problem, stf does not work

### ISSUE THREAD

**Issue by RafalDyck** [openstf/stf#1197]
Hi,

I've been fighting my problem for about 1.5 months. I try my best, but I have encountered an obstacle and would ask for tips on what I can do.

Installs everything as instructed. I start rethinkdb in a new window stf local. I have a problem all the time. I know that similar topics have already been discussed, but no solution has had any effect. Maybe my situation is different? all log and stf doctor is pasted below.

```
**Mac-mini-serwis:~ sa01404$ stf local**
2020-03-02T10:56:01.883Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli migrate"
2020-03-02T10:56:02.489Z INF/db 2854 [*] Connecting to 127.0.0.1:28015
2020-03-02T10:56:02.515Z INF/db:setup 2854 [*] Database "stf" already exists
2020-03-02T10:56:02.528Z INF/db:setup 2854 [*] Table "users" already exists
2020-03-02T10:56:02.529Z INF/db:setup 2854 [*] Table "accessTokens" already exists
2020-03-02T10:56:02.529Z INF/db:setup 2854 [*] Table "vncauth" already exists
2020-03-02T10:56:02.529Z INF/db:setup 2854 [*] Table "devices" already exists
2020-03-02T10:56:02.529Z INF/db:setup 2854 [*] Table "logs" already exists
2020-03-02T10:56:02.547Z INF/db:setup 2854 [*] Index "users"."adbKeys" already exists
2020-03-02T10:56:02.547Z INF/db:setup 2854 [*] Index "accessTokens"."email" already exists
2020-03-02T10:56:02.547Z INF/db:setup 2854 [*] Index "vncauth"."response" already exists
2020-03-02T10:56:02.548Z INF/db:setup 2854 [*] Index "vncauth"."responsePerDevice" already exists
2020-03-02T10:56:02.548Z INF/db:setup 2854 [*] Index "devices"."owner" already exists
2020-03-02T10:56:02.548Z INF/db:setup 2854 [*] Index "devices"."present" already exists
2020-03-02T10:56:02.548Z INF/db:setup 2854 [*] Index "devices"."providerChannel" already exists
2020-03-02T10:56:02.548Z INF/db:setup 2854 [*] Waiting for index "users"."adbKeys"
2020-03-02T10:56:02.549Z INF/db:setup 2854 [*] Waiting for index "accessTokens"."email"
2020-03-02T10:56:02.549Z INF/db:setup 2854 [*] Waiting for index "vncauth"."response"
2020-03-02T10:56:02.550Z INF/db:setup 2854 [*] Waiting for index "vncauth"."responsePerDevice"
2020-03-02T10:56:02.552Z INF/db:setup 2854 [*] Waiting for index "devices"."owner"
2020-03-02T10:56:02.552Z INF/db:setup 2854 [*] Waiting for index "devices"."present"
2020-03-02T10:56:02.553Z INF/db:setup 2854 [*] Waiting for index "devices"."providerChannel"
2020-03-02T10:56:02.558Z INF/db:setup 2854 [*] Index "users"."adbKeys" is ready
2020-03-02T10:56:02.558Z INF/db:setup 2854 [*] Index "accessTokens"."email" is ready
2020-03-02T10:56:02.558Z INF/db:setup 2854 [*] Index "vncauth"."response" is ready
2020-03-02T10:56:02.559Z INF/db:setup 2854 [*] Index "vncauth"."responsePerDevice" is ready
2020-03-02T10:56:02.560Z INF/db:setup 2854 [*] Index "devices"."providerChannel" is ready
2020-03-02T10:56:02.561Z INF/db:setup 2854 [*] Index "devices"."present" is ready
2020-03-02T10:56:02.561Z INF/db:setup 2854 [*] Index "devices"."owner" is ready
2020-03-02T10:56:02.570Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2020-03-02T10:56:02.574Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2020-03-02T10:56:02.576Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2020-03-02T10:56:02.580Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2020-03-02T10:56:02.584Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2020-03-02T10:56:02.602Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli provider --name Mac-mini-serwis.local --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"
2020-03-02T10:56:02.628Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
2020-03-02T10:56:02.671Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
2020-03-02T10:56:02.730Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
2020-03-02T10:56:02.737Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2020-03-02T10:56:02.743Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli storage-temp --port 7102"
2020-03-02T10:56:02.750Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2020-03-02T10:56:02.757Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2020-03-02T10:56:02.763Z INF/util:procutil 2851 [*] Forking "/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
2020-03-02T10:56:05.570Z INF/triproxy 2855 [app001] PUB socket bound on tcp://127.0.0.1:7111
2020-03-02T10:56:05.571Z INF/reaper 2859 [reaper001] Subscribing to permanent channel "*ALL"
2020-03-02T10:56:05.575Z INF/triproxy 2855 [app001] DEALER socket bound on tcp://127.0.0.1:7112
2020-03-02T10:56:05.572Z INF/db 2857 [*] Connecting to 127.0.0.1:28015
2020-03-02T10:56:05.575Z INF/triproxy 2855 [app001] PULL socket bound on tcp://127.0.0.1:7113
2020-03-02T10:56:05.573Z INF/triproxy 2856 [dev001] PUB socket bound on tcp://127.0.0.1:7114
2020-03-02T10:56:05.578Z INF/reaper 2859 [reaper001] Reaping devices with no heartbeat
2020-03-02T10:56:05.578Z INF/triproxy 2856 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
2020-03-02T10:56:05.579Z INF/triproxy 2856 [dev001] PULL socket bound on tcp://127.0.0.1:7116
2020-03-02T10:56:05.572Z INF/db 2858 [*] Connecting to 127.0.0.1:28015
2020-03-02T10:56:05.584Z INF/db 2859 [reaper001] Connecting to 127.0.0.1:28015
2020-03-02T10:56:05.593Z INF/reaper 2859 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
2020-03-02T10:56:05.595Z INF/reaper 2859 [reaper001] Sending output to "tcp://127.0.0.1:7116"
2020-03-02T10:56:05.607Z INF/processor 2857 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
2020-03-02T10:56:05.609Z INF/processor 2857 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
2020-03-02T10:56:05.610Z INF/processor 2858 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
2020-03-02T10:56:05.612Z INF/processor 2858 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
2020-03-02T10:56:12.134Z INF/poorxy 2868 [*] Listening on port 7100
2020-03-02T10:56:12.650Z INF/provider 2860 [*] Subscribing to permanent channel "l4UWUQI8Ri2Rz13eyrvleg=="
2020-03-02T10:56:13.045Z INF/provider 2860 [*] Sending output to "tcp://127.0.0.1:7116"
2020-03-02T10:56:13.047Z INF/provider 2860 [*] Receiving input from "tcp://127.0.0.1:7114"
2020-03-02T10:56:19.563Z INF/storage:temp 2865 [*] Listening on port 7102
2020-03-02T10:56:19.691Z INF/auth-mock 2861 [*] Listening on port 7120
2020-03-02T10:56:20.014Z INF/storage:plugins:image 2866 [*] Listening on port 7103
2020-03-02T10:56:21.263Z INF/provider 2860 [*] Tracking devices
2020-03-02T10:56:21.434Z INF/storage:plugins:apk 2867 [*] Listening on port 7104
.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/cli websocket

Opcje:
  -h, --help          Show help.                                       [boolean]
  -V, --version       Show version.                                    [boolean]
  --connect-push, -c  App-side ZeroMQ PULL endpoint to connect to.
                                                            [tablica] [wymagany]
  --connect-sub, -u   App-side ZeroMQ PUB endpoint to connect to.
                                                            [tablica] [wymagany]
  --port, -p          The port to bind to.             [liczba] [domyślny: 7110]
  --secret, -s        The secret to use for auth JSON Web Tokens. Anyone who
                      knows this token can freely enter the system if they want,
                      so keep it safe.                  [ciąg znaków] [wymagany]
  --ssid, -i          The name of the session ID cookie.
                                                [ciąg znaków] [domyślny: "ssid"]
  --storage-url, -r   URL to the storage unit.          [ciąg znaków] [wymagany]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_WEBSOCKET_` (e.g. `STF_WEBSOCKET_STORAGE_URL`).

Unexpected token ...
2020-03-02T10:56:24.268Z FTL/cli:local 2851 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/Users/sa01404/.nvm/versions/node/v8.0.0/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
2020-03-02T10:56:24.268Z INF/cli:local 2851 [*] Shutting down all child processes
2020-03-02T10:56:24.273Z INF/util:lifecycle 2855 [app001] Winding down for graceful exit
2020-03-02T10:56:24.274Z INF/util:lifecycle 2856 [dev001] Winding down for graceful exit
2020-03-02T10:56:24.274Z INF/util:lifecycle 2857 [proc001] Winding down for graceful exit
2020-03-02T10:56:24.275Z INF/util:lifecycle 2858 [proc002] Winding down for graceful exit
2020-03-02T10:56:24.278Z INF/util:lifecycle 2859 [reaper001] Winding down for graceful exit
2020-03-02T10:56:24.281Z INF/util:lifecycle 2860 [*] Winding down for graceful exit
2020-03-02T10:56:24.282Z INF/util:lifecycle 2861 [*] Winding down for graceful exit
2020-03-02T10:56:24.282Z INF/auth-mock 2861 [*] Waiting for client connections to end
2020-03-02T10:56:24.295Z WRN/db 2858 [proc002] Connection closed
2020-03-02T10:56:24.296Z WRN/db 2857 [proc001] Connection closed
2020-03-02T10:56:24.303Z WRN/db 2859 [reaper001] Connection closed
2020-03-02T10:56:24.876Z INF/app 2862 [*] Using pre-built resources
2020-03-02T10:56:24.922Z INF/app 2862 [*] Listening on port 7105
2020-03-02T10:56:24.924Z INF/util:lifecycle 2862 [*] Winding down for graceful exit
2020-03-02T10:56:24.927Z INF/db 2862 [*] Connecting to 127.0.0.1:28015
**Mac-mini-serwis:~ sa01404$ stf doctor**
2020-03-02T10:59:59.204Z INF/cli:doctor 2918 [*] OS Arch: x64
2020-03-02T10:59:59.206Z INF/cli:doctor 2918 [*] OS Platform: darwin
2020-03-02T10:59:59.207Z INF/cli:doctor 2918 [*] OS Platform: 18.7.0
2020-03-02T10:59:59.207Z INF/cli:doctor 2918 [*] Using Node 8.0.0
2020-03-02T10:59:59.331Z INF/cli:doctor 2918 [*] Using ZeroMQ 4.3.2
2020-03-02T10:59:59.510Z INF/cli:doctor 2918 [*] Using ADB 1.0.41
2020-03-02T10:59:59.655Z INF/cli:doctor 2918 [*] Using RethinkDB 2.4.0
2020-03-02T11:00:00.012Z INF/cli:doctor 2918 [*] Using ProtoBuf 3.11.4
2020-03-02T11:00:00.074Z INF/cli:doctor 2918 [*] Using GraphicsMagick 1.3.35
Mac-mini-serwis:~ sa01404$ 
```

**Comment by denis99999** [comment]
may be you should upgrade to a newer version of node and npm..

**Comment by koral--** [comment]
That's correct.
Current node version in Dockerfile is 8.9.3.
