### ISSUE TITLE
I build from the source, app upload failed, and screenshot no response

### ISSUE THREAD

**Issue by chenchengyuan** [openstf/stf#1198]
Hello, my steps here, thank you
node v8.16.2
## build & start stf
```
git clone
cd stf
cnpm install
rethinkdb &
./bin/stf local
```

## app upload
```
Request URL: http://192.168.0.101:7100/s/apk/0604874d-c76a-438b-b72a-0fa558a2d964/ADBKeyboard.apk/manifest
Resp :  {"success":false}

log:
ERR/storage:plugins:apk 32776 [*] Unable to read manifest of "7b4c8d74-5bfc-44f2-b467-7e70f72fd427" Error: end of central directory record signature not found
    at /Users/chenchengyuan/git/stf/node_modules/_yauzl@2.10.0@yauzl/index.js:187:14
    at Immediate.<anonymous> (/Users/chenchengyuan/git/stf/node_modules/_yauzl@2.10.0@yauzl/index.js:624:38)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

## screenshot
when I click the screenshot button, no response in the web
```
log:
2020-03-03T10:07:50.514Z INF/device:plugins:screen:capture 32779 [emulator-5554] Capturing screenshot
2020-03-03T10:07:51.619Z ERR/device:support:storage 32779 [emulator-5554] Upload to "http://localhost:7100/s/upload/image" failed: HTTP 503
2020-03-03T10:07:51.640Z ERR/device:plugins:screen:capture 32779 [emulator-5554] Screen capture failed Error: Upload to "http://localhost:7100/s/upload/image" failed: HTTP 503
    at Request._callback (/Users/chenchengyuan/git/stf/lib/units/device/support/storage.js:29:27)
    at Request.self.callback (/Users/chenchengyuan/git/stf/node_modules/_request@2.88.2@request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/chenchengyuan/git/stf/node_modules/_request@2.88.2@request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/chenchengyuan/git/stf/node_modules/_request@2.88.2@request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by chenchengyuan** [comment]
My bad, I use proxy when `stf local`, lol
