### ISSUE TITLE
'UiAutomation not connected' error when run Android UI Automator tests from STF's web shell

### ISSUE THREAD

**Issue by pavelnazimok** [openstf/stf#1206]
**What is the issue or idea you have?**
I try to run Android Instrumentation tests from the STF's web shell. In my tests, I have user actions automated with both Espresso and Android UI Automator (UIA). 

I have both my app `.apk` and test `.apk` already uploaded on the target device. Then I go to STF's web interface in Chrome, open the device, go to the Dashboard tab and execute a shell command to run tests here:
![1](https://user-images.githubusercontent.com/26544034/77042654-a899b500-69ee-11ea-93ec-bdc5c9d78122.jpg)

Then this is what happens: Espresso steps in test execute fine, but all the UIA steps throw this error:
```
java.lang.IllegalStateException: UiAutomation not connected!
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:971)
	at android.app.UiAutomation.waitForIdle(UiAutomation.java:577)
	at androidx.test.uiautomator.QueryController.waitForIdle(QueryController.java:532)
	at androidx.test.uiautomator.QueryController.waitForIdle(QueryController.java:523)
	at androidx.test.uiautomator.UiDevice.waitForIdle(UiDevice.java:621)
```

And there is no such exception when I run the same tests with remote debug `adb connect` feature.

**Does it only happen on a specific device?**
I tried to run it on another device — the same result.

The same tests run fine on local devices from Android Studio.
The same tests run fine on Firebase Test Lab devices.

**Please run `stf doctor` and paste the output here.**

```
stf doctor
2020-03-18T13:39:39.501Z INF/cli:doctor 2989 [*] OS Arch: x64
2020-03-18T13:39:39.502Z INF/cli:doctor 2989 [*] OS Platform: linux
2020-03-18T13:39:39.502Z INF/cli:doctor 2989 [*] OS Platform: 5.3.0-42-generic
2020-03-18T13:39:39.502Z INF/cli:doctor 2989 [*] Using Node 8.14.0
2020-03-18T13:39:39.511Z INF/cli:doctor 2989 [*] Using ZeroMQ 4.2.5
2020-03-18T13:39:39.519Z INF/cli:doctor 2989 [*] Using ADB 1.0.39
2020-03-18T13:39:39.528Z INF/cli:doctor 2989 [*] Using RethinkDB 2.4.0~0bionic
2020-03-18T13:39:39.530Z INF/cli:doctor 2989 [*] Using ProtoBuf 3.0.0
2020-03-18T13:39:39.540Z INF/cli:doctor 2989 [*] Using GraphicsMagick 1.3.28
```

**P.S.**
I understand this is a rare case when someone wants to run tests from the STF's web interface. And I'm happy tests run fine from remote debugging so I can run them from CI. I just wanted to highlight the possible bug with a web shell.

**Comment by denis99999** [comment]
Hi @pavelnazimok ,

Inspecting code, it seems a shell command through UI have to be fulfilled within 10 seconds otherwise an exception is raised, perhaps you met this case ? It would explain why it works fine using `adb connect` feature.

Can you provide logs at provider side ? If it is well the case, we should see a message like that: `Shell command ... failed`

**Comment by pavelnazimok** [comment]
@denis99999 Couldn't find this message in logs after reproducing the issue. But it seems I'm actually facing the case you mentioned. Thanks for your insight!
