### ISSUE TITLE
ForbiddenError: invalid csrf token

### ISSUE THREAD

**Issue by ViolenceAesthetics** [openstf/stf#1209]
/auth/api/v1/mock
{name: "****", email: "****@****"}

log:

ForbiddenError: invalid csrf token
    at csrf (/usr/local/node/lib/node_modules/stf/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/usr/local/node/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/node/lib/node_modules/stf/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/node/lib/node_modules/stf/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/node/lib/node_modules/stf/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/node/lib/node_modules/stf/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/node/lib/node_modules/stf/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/usr/local/node/lib/node_modules/stf/node_modules/raw-body/index.js:224:16)
    at done (/usr/local/node/lib/node_modules/stf/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/usr/local/node/lib/node_modules/stf/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by ViolenceAesthetics** [comment]
Cookie are not disabled

**Comment by denis99999** [comment]
@ViolenceAesthetics ,

Remove the cookie associated to your STF web site in your browser, then retry.

**Comment by ViolenceAesthetics** [comment]
> @ViolenceAesthetics，
> 
> 在浏览器中删除与STF网站关联的cookie，然后重试。


我是通过一个iframe标签嵌入的stf首页，清理chrome浏览器cookie没有起作用，但是更换为 firefox 就可以，我不确定chrome哪里有问题，我都是默认的chrome设置
我是通过一个iframe标签嵌入的stf首页，清理chrome浏览器cookie没有起作用，但是更换为 firefox 就可以，我不确定chrome哪里有问题，我都是默认的chrome设置
I use the STF home page embedded in an iframe tag to clean up Chrome browser cookies. It doesn't work, but it can be replaced with Firefox. I'm not sure where there is a problem with chrome. I'm the default chrome setting

**Comment by denis99999** [comment]
Can you share the way you embed the STF home page in an iFrame tag in order I test that from my side ?
Did you simply remove cookies from the settings tab ?

**Comment by ommikadam** [comment]
hi iam also facing the same issue, is there any fix I've tried this with deployment.md file 

ForbiddenError: invalid csrf token
    at csrf (/app/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at /app/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
    at done (/app/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
