### ISSUE TITLE
Error disable clean-up plugin

### ISSUE THREAD

**Issue by FRodero** [openstf/stf#1254]
**What is the issue or idea you have?**
I need to disable clean-up plugin because It's necessary to keep apps on smartphones. The issue has produced to execute --no-cleanup command and plugin is not disable.

**Please provide the steps to reproduce the issue.**
1.- >> docker exec -it stfdocker_stf-local_1 bash
2.- >> stf local --no-cleanup

**What is the expected behavior?**
 Disable the cleanup plugin.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
stf@30df6e383b5d:/app$ stf local --no-cleanup
2020-07-10T09:25:23.194Z INF/util:procutil 537 [*] Forking "/app/lib/cli migrate"
2020-07-10T09:25:23.681Z INF/db 543 [*] Connecting to 172.17.0.3:28015
2020-07-10T09:25:23.707Z INF/db:setup 543 [*] Database "stf" already exists
2020-07-10T09:25:23.715Z INF/db:setup 543 [*] Table "users" already exists
2020-07-10T09:25:23.715Z INF/db:setup 543 [*] Table "accessTokens" already exists
2020-07-10T09:25:23.715Z INF/db:setup 543 [*] Table "vncauth" already exists
2020-07-10T09:25:23.715Z INF/db:setup 543 [*] Table "devices" already exists
2020-07-10T09:25:23.715Z INF/db:setup 543 [*] Table "logs" already exists
2020-07-10T09:25:23.715Z INF/db:setup 543 [*] Table "groups" already exists
2020-07-10T09:25:23.731Z INF/db:setup 543 [*] Index "users"."adbKeys" already exists
2020-07-10T09:25:23.731Z INF/db:setup 543 [*] Index "accessTokens"."email" already exists
2020-07-10T09:25:23.731Z INF/db:setup 543 [*] Index "vncauth"."response" already exists
2020-07-10T09:25:23.731Z INF/db:setup 543 [*] Waiting for index "users"."adbKeys"
2020-07-10T09:25:23.732Z INF/db:setup 543 [*] Waiting for index "accessTokens"."email"
2020-07-10T09:25:23.732Z INF/db:setup 543 [*] Waiting for index "vncauth"."response"
2020-07-10T09:25:23.757Z INF/db:setup 543 [*] Index "vncauth"."responsePerDevice" already exists
2020-07-10T09:25:23.758Z INF/db:setup 543 [*] Index "devices"."owner" already exists
2020-07-10T09:25:23.758Z INF/db:setup 543 [*] Index "devices"."logs_enabled" already exists
2020-07-10T09:25:23.758Z INF/db:setup 543 [*] Index "devices"."present" already exists
2020-07-10T09:25:23.758Z INF/db:setup 543 [*] Index "devices"."providerChannel" already exists
2020-07-10T09:25:23.758Z INF/db:setup 543 [*] Index "devices"."group" already exists
2020-07-10T09:25:23.758Z INF/db:setup 543 [*] Index "groups"."privilege" already exists
2020-07-10T09:25:23.758Z INF/db:setup 543 [*] Index "groups"."owner" already exists
2020-07-10T09:25:23.758Z INF/db:setup 543 [*] Index "groups"."startTime" already exists
2020-07-10T09:25:23.759Z INF/db:setup 543 [*] Waiting for index "vncauth"."responsePerDevice"
2020-07-10T09:25:23.759Z INF/db:setup 543 [*] Waiting for index "devices"."owner"
2020-07-10T09:25:23.760Z INF/db:setup 543 [*] Waiting for index "devices"."logs_enabled"
2020-07-10T09:25:23.760Z INF/db:setup 543 [*] Waiting for index "devices"."present"
2020-07-10T09:25:23.760Z INF/db:setup 543 [*] Waiting for index "devices"."providerChannel"
2020-07-10T09:25:23.761Z INF/db:setup 543 [*] Waiting for index "devices"."group"
2020-07-10T09:25:23.761Z INF/db:setup 543 [*] Waiting for index "groups"."privilege"
2020-07-10T09:25:23.762Z INF/db:setup 543 [*] Waiting for index "groups"."owner"
2020-07-10T09:25:23.762Z INF/db:setup 543 [*] Waiting for index "groups"."startTime"
2020-07-10T09:25:23.764Z INF/db:setup 543 [*] Index "users"."adbKeys" is ready
2020-07-10T09:25:23.765Z INF/db:setup 543 [*] Index "accessTokens"."email" is ready
2020-07-10T09:25:23.765Z INF/db:setup 543 [*] Index "vncauth"."response" is ready
2020-07-10T09:25:23.767Z INF/db:setup 543 [*] Index "vncauth"."responsePerDevice" is ready
2020-07-10T09:25:23.769Z INF/db:setup 543 [*] Index "devices"."owner" is ready
2020-07-10T09:25:23.770Z INF/db:setup 543 [*] Index "devices"."logs_enabled" is ready
2020-07-10T09:25:23.770Z INF/db:setup 543 [*] Index "devices"."present" is ready
2020-07-10T09:25:23.771Z INF/db:setup 543 [*] Index "devices"."providerChannel" is ready
2020-07-10T09:25:23.772Z INF/db:setup 543 [*] Index "devices"."group" is ready
2020-07-10T09:25:23.772Z INF/db:setup 543 [*] Index "groups"."privilege" is ready
2020-07-10T09:25:23.772Z INF/db:setup 543 [*] Index "groups"."owner" is ready
2020-07-10T09:25:23.772Z INF/db:setup 543 [*] Index "groups"."startTime" is ready
2020-07-10T09:25:24.794Z INF/util:procutil 537 [*] Forking "/app/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2020-07-10T09:25:24.799Z INF/util:procutil 537 [*] Forking "/app/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2020-07-10T09:25:24.804Z INF/util:procutil 537 [*] Forking "/app/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2020-07-10T09:25:24.808Z INF/util:procutil 537 [*] Forking "/app/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2020-07-10T09:25:24.812Z INF/util:procutil 537 [*] Forking "/app/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2020-07-10T09:25:24.818Z INF/util:procutil 537 [*] Forking "/app/lib/cli provider --name 30df6e383b5d --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never --no-cleanup"
2020-07-10T09:25:24.822Z INF/util:procutil 537 [*] Forking "/app/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
2020-07-10T09:25:24.827Z INF/util:procutil 537 [*] Forking "/app/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
2020-07-10T09:25:24.833Z INF/util:procutil 537 [*] Forking "/app/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111 --connect-push-dev tcp://127.0.0.1:7116 --connect-sub-dev tcp://127.0.0.1:7114"
2020-07-10T09:25:24.849Z INF/util:procutil 537 [*] Forking "/app/lib/cli groups-engine --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111 --connect-push-dev tcp://127.0.0.1:7116 --connect-sub-dev tcp://127.0.0.1:7114"
2020-07-10T09:25:24.861Z INF/util:procutil 537 [*] Forking "/app/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2020-07-10T09:25:24.877Z INF/util:procutil 537 [*] Forking "/app/lib/cli storage-temp --port 7102"
2020-07-10T09:25:24.901Z INF/util:procutil 537 [*] Forking "/app/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2020-07-10T09:25:24.929Z INF/util:procutil 537 [*] Forking "/app/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2020-07-10T09:25:24.949Z INF/util:procutil 537 [*] Forking "/app/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                              [string] [default: "30df6e383b5d"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Address already in use
2020-07-10T09:25:25.212Z FTL/cli:local 537 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2020-07-10T09:25:25.212Z INF/cli:local 537 [*] Shutting down all child processes

**Please run `stf doctor` and paste the output here.**
stf@30df6e383b5d:/app$ stf doctor
2020-07-10T09:30:07.719Z INF/cli:doctor 641 [*] OS Arch: x64
2020-07-10T09:30:07.722Z INF/cli:doctor 641 [*] OS Platform: linux
2020-07-10T09:30:07.723Z INF/cli:doctor 641 [*] OS Platform: 5.4.0-26-generic
2020-07-10T09:30:07.723Z INF/cli:doctor 641 [*] Using Node 8.9.3
2020-07-10T09:30:07.754Z INF/cli:doctor 641 [*] Using ZeroMQ 4.1.4
2020-07-10T09:30:07.787Z ERR/cli:doctor 641 [*] RethinkDB is not installed (`rethinkdb` is missing)
2020-07-10T09:30:07.787Z ERR/cli:doctor 641 [*] ProtoBuf is not installed (`protoc` is missing)
2020-07-10T09:30:07.787Z ERR/cli:doctor 641 [*] ADB is not installed (`adb` is missing)
2020-07-10T09:30:07.788Z INF/cli:doctor 641 [*] Using GraphicsMagick 1.3.23

**Comment by koral--** [comment]
`Address already in use`
It seems that you have some resources conflict. Maybe something is running on the same port?

**Comment by FRodero** [comment]
I have used that command on docker-compose.yml and It's working properly right now.

Thanks!
