### ISSUE TITLE
Android 11 on Pixel 3 not working on OpenSTF

### ISSUE THREAD

**Issue by habeebshk** [openstf/stf#1267]
**What is the issue or idea you have?**
Android 11 on Pixel 3 is not connecting to Openstf and failing with the following error:
`Setup had an error Error: At least one of these paths should exist: /app/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi-v7a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi-v7a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi/lib/android-30/minicap.so`

I am using the latest version of openstf, android 10 on pixel 3 was working fine but when I uploaded it to android 11 I started getting the above error.
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by swtrustly** [comment]
Can confirm the issue. Pixel 4 with Android 11 and getting the same error.

```
2020-10-06T19:59:54.670Z FTL/device 130297 [9B011FFAZ0037N] Setup had an error Error: At least one of these paths should exist: /app/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi-v7a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi-v7a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi/lib/android-30/minicap.so
```

**Comment by stehlikr** [comment]
v3.5.0 supports Android 11. Check README.md for further info where to find it.

**Comment by douyunqian** [comment]
can confirm the issue,OPPO SDK 30 and getting the same error.
2020-11-30T12:22:48.769Z FTL/device 4220 [58ad97d1] Setup had an error Error: At least one of these paths should exist: /app/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi-v7a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi-v7a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi/lib/android-30/minicap.so
    at Object.module.exports.requiredMatch (/app/lib/util/pathutil.js:33:9)
    at /app/lib/units/device/resources/minicap.js:41:23
    at SerialSyrup.ParallelSyrup.invoke (/app/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /app/node_modules/stf-syrup/lib/serial.js:43:33
    at tryCatch1 (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2020-11-30T12:22:48.770Z FTL/util:lifecycle 4220 [58ad97d1] Shutting down due to fatal error
2020-11-30T12:22:48.777Z INF/provider 45 [*] Cleaning up device worker "58ad97d1"
2020-11-30T12:22:48.777Z ERR/provider 45 [*] Device worker "58ad97d1" died with code 1
2020-11-30T12:22:48.777Z INF/provider 45 [*] Restarting device worker "58ad97d1"
2020-11-30T12:22:49.576Z INF/device:support:push 4228 [58ad97d1] Sending output to "tcp://127.0.0.1:7116"
2020-11-30T12:22:49.579Z INF/device 4228 [58ad97d1] Preparing device
2020-11-30T12:22:49.960Z INF/device:support:sub 4228 [58ad97d1] Receiving input from "tcp://127.0.0.1:7114"
2020-11-30T12:22:49.961Z INF/device:support:sub 4228 [58ad97d1] Subscribing to permanent channel "*ALL"
2020-11-30T12:22:50.026Z INF/device:support:properties 4228 [58ad97d1] Loading properties
2020-11-30T12:22:50.052Z INF/device:support:sdk 4228 [58ad97d1] Supports SDK 30
2020-11-30T12:22:50.053Z INF/device:support:abi 4228 [58ad97d1] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2020-11-30T12:22:50.056Z FTL/device 4228 [58ad97d1] Setup had an error Error: At least one of these paths should exist: /app/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/arm64-v8a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi-v7a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi-v7a/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi/lib/android-30/minicap.so, /app/node_modules/minicap-prebuilt-beta/prebuilt/armeabi/lib/android-30/minicap.so
    at Object.module.exports.requiredMatch (/app/lib/util/pathutil.js:33:9)
    at /app/lib/units/device/resources/minicap.js:41:23
    at SerialSyrup.ParallelSyrup.invoke (/app/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /app/node_modules/stf-syrup/lib/serial.js:43:33
    at tryCatch1 (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2020-11-30T12:22:50.057Z FTL/util:lifecycle 4228 [58ad97d1] Shutting down due to fatal error
2020-11-30T12:22:50.065Z INF/provider 45 [*] Cleaning up device worker "58ad97d1"
2020-11-30T12:22:50.065Z ERR/provider 45 [*] Device worker "58ad97d1" died with code 1

**Comment by risinek** [comment]
You are running outdated version of STF. See README for further information. This repository was abandoned and you should use [DeviceFarmer fork](https://github.com/DeviceFarmer/stf) where Android 11 support was already introduced in [v3.5.0](https://github.com/DeviceFarmer/stf/releases/tag/v3.5.0)
