### ISSUE TITLE
Openstf server can't connect over 75 devices

### ISSUE THREAD

**Issue by curtis1215** [openstf/stf#1281]
I build openstf service on Cent os 7 with docker, then all device conmect over ip, it was successful connect and use for all devices untill number 76device, it can connect when i type adb connect commend, but in the openstf ui, the other device status always been preparing, doesn't change status to use, how can i fix this problem

**Comment by curtis1215** [comment]
2021-01-20T11:26:53.287Z INF/device:plugins:phone 4493 [10.34.11.215:5555] Fetching phone info
2021-01-20T11:26:53.306Z INF/device:plugins:display 4499 [10.34.11.212:5555] Reading display info
2021-01-20T11:26:53.331Z INF/device:plugins:identity 4493 [10.34.11.215:5555] Solving identity
2021-01-20T11:26:53.342Z INF/device:plugins:solo 4493 [10.34.11.215:5555] Subscribing to permanent channel "untfoPsRJL9Q+e8sDLZcv9tuNuE="
2021-01-20T11:26:53.346Z INF/device:plugins:screen:stream 4493 [10.34.11.215:5555] Starting WebSocket server on port NaN
2021-01-20T11:26:53.352Z FTL/device 4493 [10.34.11.215:5555] Setup had an error RangeError: "port" argument must be >= 0 and < 65536
    at Server.listen (net.js:1467:13)
    at new WebSocketServer (/app/node_modules/ws/lib/WebSocketServer.js:76:20)
    at createServer (/app/lib/units/device/plugins/screen/stream.js:425:17)
    at /app/lib/units/device/plugins/screen/stream.js:449:12
    at SerialSyrup.ParallelSyrup.invoke (/app/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /app/node_modules/stf-syrup/lib/serial.js:43:33
    at tryCatch1 (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/app/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2021-01-20T11:26:53.353Z FTL/util:lifecycle 4493 [10.34.11.215:5555] Shutting down due to fatal error
2021-01-20T11:26:53.370Z INF/device:plugins:phone 4499 [10.34.11.212:5555] Fetching phone info
2021-01-20T11:26:53.383Z INF/provider 43 [*] Cleaning up device worker "10.34.11.215:5555"

**Comment by caramelmeimei** [comment]
Hi have you got this to work?
