### ISSUE TITLE
Devices are not connected/shown on STF UI

### ISSUE THREAD

**Issue by abhinavagarwalInfo** [openstf/stf#1353]
*I am using latest devicefarmer/stf:latest docker image*

**Devices are not connected/shown on STF UI**

**The steps to reproduce the issue.**
Start Docker
        1. Start Docker and check dashboard
Pull Docker Images
	1. sudo docker pull rethinkdb
        2. sudo docker pull devicefarmer/stf:latest
Create Folder For Rethinkdb
	1. mkdir /home/<YOUR USER>/RethinkDB
	2. export RETHINK_DB=/home/<YOUR USER>/RethinkDB
Start Containers
        1. docker network create df-network
        2. docker run -d --network=df-network --name rethinkdb -p 28015:28015 -v $RETHINK_DB:/data rethinkdb rethinkdb --bind all --cache-size 8192 --http-port 8090
        3. adb start-server
        4. docker run --network=df-network -e RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015 -p 7100:7100 -p 7110:7110 -p 7400:7400 -p 7408:7408 -p 7404:7404 -it devicefarmer/stf:latest stf local --adb-host docker.for.mac.localhost --public-ip <IP>
        5. Device was already connected in debug mode and reflect on executing **adb devices** command, but on stf ui **http://localhost:7100/#!/devices** it is not showing with active status.

**Error logs:**
2024-12-25 18:52:43 2024-12-25T13:22:43.388Z INF/device:resources:service 1879 [35101FDH2002RF] Installing STFService
2024-12-25 18:52:43 2024-12-25T13:22:43.394Z FTL/device 1879 [35101FDH2002RF] Setup had an error TypeError: adb.uninstall(...).timeout(...).then(...).progressed is not a function
2024-12-25 18:52:43     at /app/lib/units/device/resources/service.js:92:14
2024-12-25 18:52:43     at tryCatcher (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/util.js:16:23)
2024-12-25 18:52:43     at Promise._settlePromiseFromHandler (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:547:31)
2024-12-25 18:52:43     at Promise._settlePromise (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:604:18)
2024-12-25 18:52:43     at Promise._settlePromise0 (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:649:10)
2024-12-25 18:52:43     at Promise._settlePromises (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:725:18)
2024-12-25 18:52:43     at _drainQueueStep (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:93:12)
2024-12-25 18:52:43     at _drainQueue (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:86:9)
2024-12-25 18:52:43     at Async._drainQueues (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:102:5)
2024-12-25 18:52:43     at Async.drainQueues (/app/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:15:14)
2024-12-25 18:52:43     at process.processImmediate (node:internal/timers:491:21)
2024-12-25 18:52:43 2024-12-25T13:22:43.395Z FTL/util:lifecycle 1879 [35101FDH2002RF] Shutting down due to fatal error
2024-12-25 18:52:43 2024-12-25T13:22:43.415Z INF/provider 29 [*] Cleaning up device worker "35101FDH2002RF"
2024-12-25 18:52:43 2024-12-25T13:22:43.415Z ERR/provider 29 [*] Device worker "35101FDH2002RF" died with code 1
2024-12-25 18:52:43 2024-12-25T13:22:43.415Z INF/provider 29 [*] Restarting device worker "35101FDH2002RF"

**NOTE** : I tested by restarted containers / Devices ...etc. but getting same error. May be it look like lib compatibility issue.
PLEASE HELP

**Comment by candy69** [comment]
Hello? Did you managed to fix the error. Unfortunately have same thing

**Comment by liangchuanan** [comment]
Me too. Who can resolve the issue.

**Comment by VitaliySohatskiy** [comment]
I have the same problem with huawei devices

**Comment by nova-source** [comment]
same error here

**Comment by erdncyz** [comment]
Hi all

You use below repo. And create issue 

https://github.com/zebrunner/mcloud

Also join telegram group 

https://t.me/zebrunner
