### ISSUE TITLE
 ./stf local

### ISSUE THREAD

**Issue by hemant4524** [openstf/stf#146]
module.js:339
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/software/Downloads/stf-master/lib/cli.js:4:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

I installed all module and run ./stf local in mac os X give me above error.

**Comment by sorccu** [comment]
If you follow the README it will work just fine.

**Comment by hemant4524** [comment]
Can you provide me for installation video tutorial for mac os?

**Comment by sorccu** [comment]
Yeeeeah nope. It's all in the README. Good luck though.
