### ISSUE TITLE
Cannot find module 'zmq'

### ISSUE THREAD

**Issue by hemant4524** [openstf/stf#149]
I installed all module:
![screen shot 2015-10-23 at 9 57 30 am](https://cloud.githubusercontent.com/assets/12729083/10684598/b1a6f882-796c-11e5-9302-a3e2cb80fdb8.png)

module.js:339
    throw err;
    ^

Error: Cannot find module 'zmq'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/software/Downloads/Device Test/stf-master/lib/util/zmqutil.js:7:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/software/Downloads/Device Test/stf-master/lib/units/triproxy/index.js:3:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
FTL/cli:local 40746 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/Users/software/Downloads/Device Test/stf-master/lib/util/procutil.js:49:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
INF/cli:local 40746 [*] Shutting down all child processes

**Comment by sorccu** [comment]
Look, just do it EXACTLY like the README tells you to do. Your setup looks like you did something way, way different. For OS X there's even a oneliner that installs all the dependencies (as long as you've got homebrew installed).

**Comment by gunta** [comment]
Can you post at least the version of your software and also how you installed `node/npm`?

```
node -v 
npm -v 
brew -v
sw_vers
```

**Comment by hemant4524** [comment]
node -v : v4.2.1
npm -v : 2.14.7
brew -v : Homebrew 0.9.5
sw_vers : ProductName:	Mac OS X
ProductVersion:	10.11
BuildVersion:	15A284

**Comment by hemant4524** [comment]
I solve this error used this command

$ npm install zmq
https://github.com/JustinTulloss/zeromq.node

**Comment by sorccu** [comment]
Seriously, if you need to install from source, this is all you need to do:

```bash
brew install rethinkdb graphicsmagick zeromq protobuf yasm pkg-config
git clone https://github.com/openstf/stf.git
cd stf
npm install
```

Now open a new shell and start rethinkdb with:

```bash
# run in the "stf" folder
rethinkdb
```

If it complains that port 8080 is already being used, try:

```bash
# run in the "stf" folder
rethinkdb --http-port 8090
```

And then simply:

```bash
# run in the "stf" folder
bin/stf local
```

Or if you don't want to type `bin/stf` all the time:

```bash
# run in the "stf" folder
npm link
```

And now you can run this from anywhere:

```bash
stf local
```

**Comment by hemant4524** [comment]
Thank you for reply,
I install rethinkdb and run in browser 
http://localhost:8080/
when run 
$ stf local
Following url type in browser
http://localhost:7100
but nothing display in browser (http://localhost:7100/auth/mock/)

**Comment by NareshJain91** [comment]
@hemant4524 anyupdate on issue but nothing display in browser (http://localhost:7100/auth/mock/)

**Comment by sorccu** [comment]
Sounds like your installation failed. Please follow the instructions in the README exactly. Alternatively, network errors during installation can break the it.

**Comment by mateng0915** [comment]
I solve this problem following the commands
1.brew install zeromq
it will solve can not find libzmq problem when just run npm install zmq
2.npm install zmq
