### ISSUE TITLE
STF cannot install apk error

### ISSUE THREAD

**Issue by Tierney0115** [openstf/stf#199]
I can not install apk and the console shows following error:

INF/storage:temp 14483 [] Uploaded "com.eg.android.AlipayGphone.1512041827.apk" to "/tmp/upload_4661586ca7a0226fcb7ee3f55b9db4ad"
Dec 07 14:11:55 odroid stf[14427]: ERR/storage:plugins:apk 14493 [] Unable to read manifest of "8d25b9bd-5f9a-4498-9f74-cfa46d549ee7" Error: Invalid or unsupported zip format. No END header found
Dec 07 14:11:55 odroid stf[14427]: at new ApkReader (/root/STF/node_modules/adbkit-apkreader/lib/apkreader.js:27:17)
Dec 07 14:11:55 odroid stf[14427]: at Function.ApkReader.readFile (/root/STF/node_modules/adbkit-apkreader/lib/apkreader.js:16:14)
Dec 07 14:11:55 odroid stf[14427]: at /root/STF/lib/units/storage/plugins/apk/task/manifest.js:9:30
Dec 07 14:11:55 odroid stf[14427]: at doNTCallback0 (node.js:408:9)
Dec 07 14:11:55 odroid stf[14427]: at process._tickCallback (node.js:337:13)

Thanks.

**Comment by sorccu** [comment]
Any chance you could provide a test `.apk` file that fails?

I've been suspecting for a while now that the installation may be losing an initial chunk of data, but I've never been able to reproduce it myself. I've seen it happen a few times in the error logs, and yours may or may not be one of those cases. I've checked the code quite a few times in the past, but I haven't seen any obvious spot where it could happen. If the same file works when someone else is trying to use it, possibly on a local STF installation, then that's most likely what's happening. If it doesn't work locally either, then it should be something fairly easy to fix.

**Comment by Tierney0115** [comment]
Thank you for the answer. I have tried many different apk packages and all have the same error. I also tried the released old version of STF. Still the same problem. Do you think does it relate to my local file system or the npm dependency of the APKreader? Thanks.
