### ISSUE TITLE
can't open

### ISSUE THREAD

**Issue by drogjh** [openstf/stf#203]
wget http://127.0.0.1:7100

```ERR/poorxy 2369 [*] Proxy had an error Error: connect ECONNREFUSED 127.0.0.1:7105
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)```

**Comment by vbanthia** [comment]
@drogjh 
Can you provide more info about your problem.
