### ISSUE TITLE
Doesn't register Nexus 5

### ISSUE THREAD

**Issue by argelaes** [openstf/stf#209]
Hi,

I'm trying to setup dev environment with STF and after following all the installation steps, start of the DB with "sudo rethinkdb", "sudo adb start-server" and then "sudo stf local" I still receive this error in the console:

FTL/device 59845 [0657234af0ea3cf3] Setup had an error Error: At least one of these paths should exist: /usr/local/lib/node_modules/stf/vendor/minicap/shared/android-6.0.1/armeabi-v7a/minicap.so, /usr/local/lib/node_modules/stf/vendor/minicap/shared/android-23/armeabi-v7a/minicap.so, /usr/local/lib/node_modules/stf/vendor/minicap/shared/android-6.0.1/armeabi/minicap.so, /usr/local/lib/node_modules/stf/vendor/minicap/shared/android-23/armeabi/minicap.so
    at Object.module.exports.requiredMatch (/usr/local/lib/node_modules/stf/lib/util/pathutil.js:33:9)
    at /usr/local/lib/node_modules/stf/lib/units/device/resources/minicap.js:35:23
    at SerialSyrup.ParallelSyrup.invoke (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /usr/local/lib/node_modules/stf/node_modules/stf-syrup/lib/serial.js:43:33
    at tryCatch1 (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
    at process._tickCallback (node.js:355:11)
FTL/util:lifecycle 59845 [0657234af0ea3cf3] Shutting down due to fatal error
INF/provider 59745 [*] Cleaning up device worker "0657234af0ea3cf3"
ERR/provider 59745 [*] Device worker "0657234af0ea3cf3" died with code 1
INF/provider 59745 [*] Restarting device worker "0657234af0ea3cf3"

I would like to ask does STF support Nexus 5 and arm ABI? How could I fix that?

**Comment by sorccu** [comment]
Like the README says, you have to build from master if you want Android 6.0 support. We're trying to release a new version as soon as we have time.

**Comment by argelaes** [comment]
Thanks, now it works fine.
