### ISSUE TITLE
STF Authentication

### ISSUE THREAD

**Issue by romitincedoinc** [openstf/stf#240]
HI,

I have been trying to connect stf through its ldap Module. I am passing all the req. parametres but still not able to connect.
Below is the command 

stf local --public-ip 10.11.215.37 --auth-type ldap --auth-options '["--ldap-url","10.11.200.201","--port","3268","--ldap-search-dn"," CN=Users,DC=ibtechnology,DC=com","--ldap-bind-dn","DC=ibtechnology,DC=com","--app-url","Mail.incedoinc.com"]'

and after firing this I'm getting  follwoing error...

/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:324
    throw err;
          ^

/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:324
    throw err;
          ^
Error: Address already in use
    at Socket.bindSync (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:322:15)
    at module.exports (/usr/local/lib/node_modules/stf/lib/units/triproxy/index.js:21:7)
    at Command.program.command.description.option.option.option.option.option.option.option.option.option.option.option.option.action.require.port (/usr/local/lib/node_modules/stf/lib/cli.js:282:32)
    at Command.listener (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:301:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/lib/cli.js:1134:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
Error: Address already in use
    at Socket.bindSync (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:322:15)
    at module.exports (/usr/local/lib/node_modules/stf/lib/units/triproxy/index.js:21:7)
    at Command.program.command.description.option.option.option.option.option.option.option.option.option.option.option.option.action.require.port (/usr/local/lib/node_modules/stf/lib/cli.js:282:32)
    at Command.listener (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:301:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/lib/cli.js:1134:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
FTL/cli:local 3995 [*] Child process had an error ExitError: Exit code "8"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
INF/c

**Comment by sorccu** [comment]
Looks to me like you already have one `stf local` running. Are you perhaps trying to run the command you posted in addition to `stf local`? Because that would be wrong, you only need to run the command you posted above. Alternatively, you may want to check if some node processes were accidentally left behind somehow from a previous run.

**Comment by sorccu** [comment]
Also, don't set the `--port` option. Your `--ldap-url` should be `ldap://10.11.200.201:3268`.

**Comment by romitincedoinc** [comment]
HI Sorccu

Now have update the command:

stf local --public-ip 10.11.215.37 --auth-type ldap --auth-options '["--ldap-url","ldap://10.11.200.201:3268","--ldap-search-dn"," CN=Users,DC=ibtechnology,DC=com","--ldap-bind-dn","DC=ibtechnology,DC=com","--app-url","Mail.incedoinc.com"]'

Still no success:




/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:324
    throw err;
          ^
Error: Address already in use
    at Socket.bindSync (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:322:15)
    at module.exports (/usr/local/lib/node_modules/stf/lib/units/triproxy/index.js:21:7)
    at Command.program.command.description.option.option.option.option.option.option.option.option.option.option.option.option.action.require.port (/usr/local/lib/node_modules/stf/lib/cli.js:282:32)
    at Command.listener (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:301:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/lib/cli.js:1134:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
FTL/cli:local 4115 [*] Child process had an error ExitError: Exit code "8"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
INF/cli:local 4115 [*] Shutting down all child processes

/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:324
    throw err;
          ^
Error: Address already in use
    at Socket.bindSync (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:322:15)
    at module.exports (/usr/local/lib/node_modules/stf/lib/units/triproxy/index.js:21:7)
    at Command.program.command.description.option.option.option.option.option.option.option.option.option.option.option.option.action.require.port (/usr/local/lib/node_modules/stf/lib/cli.js:282:32)
    at Command.listener (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:301:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/lib/cli.js:1134:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
root@ronit-HCL-Desktop:/home/ronit# stf local --public-ip 10.11.215.37 --auth-type ldap --auth-options '["--ldap-url","ldap://10.11.200.201:3268","--ldap-search-dn"," CN=Users,DC=ibtechnology,DC=com","--ldap-bind-dn","DC=ibtechnology,DC=com","--app-url","Mail.incedoinc.com"]'
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js migrate"
INF/db 4151 [*] Connecting to 127.0.0.1:28015
INF/db:setup 4151 [*] Database "stf" already exists
INF/db:setup 4151 [*] Table "users" already exists
INF/db:setup 4151 [*] Table "devices" already exists
INF/db:setup 4151 [*] Table "logs" already exists
INF/db:setup 4151 [*] Index "users"."adbKeys" already exists
INF/db:setup 4151 [*] Index "devices"."owner" already exists
INF/db:setup 4151 [*] Index "devices"."present" already exists
INF/db:setup 4151 [*] Index "devices"."providerChannel" already exists
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js provider --name ronit-HCL-Desktop --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip 10.11.215.37 --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js auth-ldap --port 7120 --secret kute kittykat --app-url http://10.11.215.37:7100/ --ldap-url ldap://10.11.200.201:3268 --ldap-search-dn  CN=Users,DC=ibtechnology,DC=com --ldap-bind-dn DC=ibtechnology,DC=com --app-url Mail.incedoinc.com"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js app --port 7105 --secret kute kittykat --auth-url http://10.11.215.37:7100/auth/ldap/ --websocket-url http://10.11.215.37:7110/"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-temp --port 7102"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 4149 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"

/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:324
    throw err;
          ^
Error: Address already in use
    at Socket.bindSync (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:322:15)
    at module.exports (/usr/local/lib/node_modules/stf/lib/units/triproxy/index.js:21:7)
    at Command.program.command.description.option.option.option.option.option.option.option.option.option.option.option.option.action.require.port (/usr/local/lib/node_modules/stf/lib/cli.js:282:32)
    at Command.listener (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:301:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/lib/cli.js:1134:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:324
    throw err;
          ^
FTL/cli:local 4149 [*] Child process had an error ExitError: Exit code "8"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
Error: Address already in use
    at Socket.bindSync (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:322:15)
    at module.exports (/usr/local/lib/node_modules/stf/lib/units/triproxy/index.js:21:7)
    at Command.program.command.description.option.option.option.option.option.option.option.option.option.option.option.option.action.require.port (/usr/local/lib/node_modules/stf/lib/cli.js:282:32)
    at Command.listener (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:301:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/lib/cli.js:1134:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
INF/cli:local 4149 [*] Shutting down all child processes

**Comment by sorccu** [comment]
Even if stf local says it's shutting down everything, there can be a bug.
Overall stf local is not meant to be very reliable since it's supposed to
be for development only. You need to check your running processes somehow
(with ps maybe) and kill any unexpected stf node processes. It doesn't
usually happen but seems to have happened anyway in this case.

**Comment by romitincedoinc** [comment]
HI


 now am able to connect to ldap but when i try n login it is giving an assertion error



ERR/auth-ldap 2497 [127.0.0.1] Unexpected error AssertionError: options.attribute (string) is required
    at EqualityFilter (/usr/local/lib/node_modules/stf/node_modules/ldapjs/node_modules/ldap-filter/lib/equality_filter.js:15:12)
    at new EqualityFilter (/usr/local/lib/node_modules/stf/node_modules/ldapjs/lib/filters/equality_filter.js:16:26)
    at tryFind (/usr/local/lib/node_modules/stf/lib/util/ldaputil.js:55:15)
    at /usr/local/lib/node_modules/stf/lib/util/ldaputil.js:108:12
From previous event:
    at Object.module.exports.login (/usr/local/lib/node_modules/stf/lib/util/ldaputil.js:107:23)
    at requtil.validate.then.then.jwtutil.encode.payload.email (/usr/local/lib/node_modules/stf/lib/units/auth/ldap.js:71:29)
    at process._tickCallback (node.js:415:13)
From previous event:
    at /usr/local/lib/node_modules/stf/lib/units/auth/ldap.js:70:12
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:271:10)
    at /usr/local/lib/node_modules/stf/lib/units/auth/ldap.js:50:5
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:312:13)
    at /usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:271:10)
    at /usr/local/lib/node_modules/stf/node_modules/express-validator/lib/express_validator.js:228:5
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:312:13)
    at /usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:330:12)

**Comment by sorccu** [comment]
Looks like you should set `--ldap-search-field` to the LDAP field that contains the username, and you may also need to change `--ldap-search-scope` and `--ldap-search-class` if the [defaults](https://github.com/openstf/stf/blob/b9fd290da8e87679972dea4c430bb6f71bd82c84/lib/cli.js#L351) aren't good for you.

**Comment by romitincedoinc** [comment]
HI

Can you help me what things i need to pass in search field and search scope

**Comment by sorccu** [comment]
No. It depends entirely on your LDAP server.

**Comment by tadesushilgithub** [comment]
Hi @sorccu 
I am getting below error while authenticating via ldap server (**got STF ldap UI**).

ERR/auth-ldap 4170 [::ffff:127.0.0.1] Unexpected error AssertionError: options.attribute (string) is required
    at EqualityFilter (/usr/local/lib/node_modules/stf/node_modules/ldap-filter/lib/equality_filter.js:15:12)
    at new EqualityFilter (/usr/local/lib/node_modules/stf/node_modules/ldapjs/lib/filters/equality_filter.js:16:26)
    at tryFind (/usr/local/lib/node_modules/stf/lib/util/ldaputil.js:55:15)
    at /usr/local/lib/node_modules/stf/lib/util/ldaputil.js:108:12

**Comment by sorccu** [comment]
In that case you are missing one of the required properties. Check `stf auth-ldap --help` for the available options.

**Comment by tadesushilgithub** [comment]
Hi @sorccu ,

I am running below command,

stf local --public-ip <stf_server_ip_address> --auth-type ldap --auth-options '["--ldap-url","<ldap_server_ip>","--port","ldap_port","--ldap-search-dn","CN=Users,DC=organization,DC=com","--ldap-bind-dn","DC=organization,DC=com","--app-url","organization.com"]'

**Comment by sorccu** [comment]
Looks like you're missing `--ldap-search-field`.

**Comment by tadesushilgithub** [comment]
Thanks so much @sorccu. Your suggestions work for me :+1: 
stf local --auth-type ldap --auth-options '["--ldap-url","ldap://ip:port","--ldap-search-dn","OU=inner_ou,OU=inner_ou,DC=inner_dc,DC=inner_dc,DC=com","--ldap-bind-dn","CN=username,OU=inner_ou,OU=inner_ou,DC=inner_dc,DC=inner_dc,DC=com","--ldap-bind-credentials","username_actual_credential>","--ldap-search-field","sAMAccountName"]'

**Comment by xell66** [comment]
I get the error message:

` missing requirere argument '--secret'`

When I just add '--secret' it starts with no errors but I cant reach stf.
I used @tadesushilgithub example.
And I'am not sure what I need in  --ldap-search-field. 
Any Ideas?

**Comment by tadesushilgithub** [comment]
@xell66 use "--ldap-search-field","sAMAccountName" as it is if your LDAP uses Microsoft server Active Directory. If you uses master branch code base it won't ask you for --secret. Send me your command and mentioned the step how you running it?

**Comment by xell66** [comment]
I installed STF via npm so it is 1.1.1 and I'am running on Ubuntu. So I gues I need another search-field entry. I`am not very familiar with ldap. So I used this command:

stf local --public-ip 172.18.92.157 --auth-type ldap --auth-options '["--ldap-url","ldap://127.0.0.1:389","--ldap-search-dn","CN=iue,DC=selen","ldap-bind-dn","DC=selen","--ldap-search-field","sAMAccountName"]'

I'am also not sure about the port. I configured ldap via phpldapadmin.

**Comment by HellDima** [comment]
Hello,
tried to run stf local with LDAP, but our ldap connecting is https
so i run connect with: 

["--ldap-url","ldaps://ip:port","--ldap-search-dn","OU=inner_ou,OU=inner_ou,DC=inner_dc,DC=inner_dc,DC=com","--ldap-bind-dn","CN=user,OU=inner_ou,OU=inner_ou,DC=inner_dc,DC=inner_dc,DC=com","--ldap-bind-credentials","password","--ldap-search-field","sAMAccountName"]

but after connecting attempt in LDAP UI i got this error:
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Hostname/IP doesn't match certificate's altnames: "IP: 172.17.17.2 is not in the cert's list: "
    at Object.checkServerIdentity (tls.js:191:15)
    at TLSSocket.<anonymous> (_tls_wrap.js:1006:29)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:567:8)
ERR/poorxy 83 [*] Proxy had an error Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at Socket.socketOnEnd (_http_client.js:288:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
FTL/cli:local 13 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

any help what is wrong?

**Comment by sorccu** [comment]
The error message says exactly what's wrong. `Error: Hostname/IP doesn't match certificate's altnames: "IP: 172.17.17.2 is not in the cert's list: "` You connected using the IP address, but the certificate is for a hostname. Or perhaps has no value set at all since the value is empty? Either way, the certificate doesn't match and it can't connect. Figure out what the hostname is supposed to be and use that instead. Alternatively you can try using `export NODE_TLS_REJECT_UNAUTHORIZED=0` before running STF, although I'm not sure if it applies to this issue, and is of course a security risk.

**Comment by HellDima** [comment]
found a solution for that, my ldaps can talk with nginx by hhtps and to stf by http.
but after the Authentication, i;m rederected to work on http, and secound attempt to go to https page, results in error:

ixed Content: The page at 'https://stf.ironsrc.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://stf.ironsrc.com:7110/socket.io/?uip=172.17.7.193&EIO=3&transport=websocket'. This request has been blocked; this endpoint must be available over WSS.WS.doOpen @ 1.8bed18f….chunk.js:50487
1.8bed18f….chunk.js:13713 Error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Error (native)
    at WS.doOpen (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:50487:33)
    at WS.Transport.open (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:48574:11)
    at Socket.open (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:47194:14)
    at new Socket (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:47075:9)
    at Socket (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:47001:42)
    at Manager.open.Manager.connect (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:46591:18)
    at new Manager (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:46445:31)
    at Manager (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:46414:43)
    at lookup (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:44017:20)
    at Object.SocketFactory (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:43916:17)
    at Object.invoke (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:4714:20)
    at Object.enforcedReturnValue [as $get] (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:4553:38)
    at Object.invoke (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:4714:20)
    at https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:4513:38
    at getService (https://stf.ironsrc.com/static/app/build/1.8bed18f555f9bd501fe6.chunk.js:4660:40)

Is there a way to run all stf over https, to skip this problem?

**Comment by sorccu** [comment]
Yes, we have written the [deployment guide](https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md) for that. `stf local` is for development use only. Unfortunately the `--websocket-url` option is not configurable for `stf local` right now at all.

**Comment by xell66** [comment]
So has anyone an idea about the `--secret` error?  How is this argument suposed to use?

**Comment by sorccu** [comment]
It's a required argument. It's a signing secret used to verify the authentication token. If someone knows your `--secret`, they can create a valid token and log in to your system. You must give the same `--secret` to your auth, app and websocket units or they won't be able to work together. For `stf local` it defaults to `'kute kittykat'`, which is why you don't need to set it.

**Comment by xell66** [comment]
I think for `openldap` you need to use `uid` instead of `sAMAccountName`.
At least with this config I get an incorrect login message in the gui when I use a incorrect login, but when I use a correct login I just get an empty page in the browser (about:blank) and the stf server says: 
`INF/auth-ldap 6671 [::ffff:127.0.0.1] Authenticated "undefined"`

**Comment by xell66** [comment]
I figured out that the problem with the empty page resulted from the fact that my IP changed. So I used the command `stf local --public-ip 172.18.92.157 --auth-type ldap --auth-options '["--ldap-url","ldap://127.0.0.1:389","--ldap-search-dn","OU=ou1,OU=ou2,DC=dc1,DC=dc2","--ldap-bind-dn","CN=admin,DC=dc1,DC=dc2","--ldap-bind-credentials","PASSWORD","--ldap-search-field","uid"]'`
I still can reach STF despite the fact that I used a wrong IP. But I needed to use the url `PCNAME:7100/aut/ldap/`

Anyways I still have the problem that I get this error when I "successfully" login.
```
INF/auth-ldap 11940 [::ffff:127.0.0.1] Authenticated "undefined"
ReqlDriverCompileError: Argument 1 to get may not be `undefined`.
    at ReqlDriverCompileError.ReqlError [as constructor] (/usr/local/lib/node_modules/stf/node_modules/rethinkdb/errors.js:23:13)
    at ReqlDriverCompileError.ReqlCompileError [as constructor] (/usr/local/lib/node_modules/stf/node_modules/rethinkdb/errors.js:35:51)
    at new ReqlDriverCompileError (/usr/local/lib/node_modules/stf/node_modules/rethinkdb/errors.js:46:57)
    at Get.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/rethinkdb/ast.js:1462:17)
    at Get.RDBOp [as constructor] (/usr/local/lib/node_modules/stf/node_modules/rethinkdb/ast.js:1466:8)
    at new Get (/usr/local/lib/node_modules/stf/node_modules/rethinkdb/ast.js:1846:38)
    at /usr/local/lib/node_modules/stf/node_modules/rethinkdb/ast.js:1068:43
    at Table.RDBVal.get (/usr/local/lib/node_modules/stf/node_modules/rethinkdb/ast.js:1070:7)
    at dbapi.saveUserAfterLogin (/usr/local/lib/node_modules/stf/lib/db/api.js:22:34)
    at /usr/local/lib/node_modules/stf/lib/units/app/middleware/auth.js:14:15
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:312:13)
    at /usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:271:10)
    at _cookieSession (/usr/local/lib/node_modules/stf/node_modules/cookie-session/index.js:124:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:312:13)
    at /usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/local/lib/node_modules/stf/node_modules/express/lib/router/index.js:271:10)
    at favicon (/usr/local/lib/node_modules/stf/node_modules/serve-favicon/index.js:72:7)
```

Is maybe something wrong with my LDAP structure?

**Comment by xell66** [comment]
Has no one an idea what could be wrong? I tried a lot of configurations with my LDAP Server but nothing worked.

**Comment by sorccu** [comment]
Sounds like it can't find the email field of your user. One of [these](https://github.com/openstf/stf/blob/48d621b1940058b5a4d979e35dc5eb2132c52946/lib/util/ldaputil.js#L120) is required.

Currently STF requires an email address to use as a primary key. If your LDAP doesn't have email addresses, you'll have to add them somehow.

**Comment by xell66** [comment]
Your suggestion worked. Thank you!
The User Object has to have the ObjectClass inetOrgPerson, then it is possible to add an email adress.

**Comment by xiaobeiying** [comment]
Hi guys, 
I have one simply question: before using STF‘s ldap module, should I deploy the ldap service?

**Comment by sorccu** [comment]
This issue is very old and has been resolved.
