### ISSUE TITLE
stf local error

### ISSUE THREAD

**Issue by zhaoming1222** [openstf/stf#250]
npm install goes well
npm link goes well

stf local error

log:
INF/cli:local 26886 [*] Shutting down all child processes
/Users/gaoman/Documents/openstf/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/gaoman/Documents/openstf/stf/node_modules/zmq/build/zmq.node
 → /Users/gaoman/Documents/openstf/stf/node_modules/zmq/build/Debug/zmq.node
 → /Users/gaoman/Documents/openstf/stf/node_modules/zmq/build/Release/zmq.node
 → /Users/gaoman/Documents/openstf/stf/node_modules/zmq/out/Debug/zmq.node
 → /Users/gaoman/Documents/openstf/stf/node_modules/zmq/Debug/zmq.node
 → /Users/gaoman/Documents/openstf/stf/node_modules/zmq/out/Release/zmq.node
 → /Users/gaoman/Documents/openstf/stf/node_modules/zmq/Release/zmq.node
 → /Users/gaoman/Documents/openstf/stf/node_modules/zmq/build/default/zmq.node
 → /Users/gaoman/Documents/openstf/stf/node_modules/zmq/compiled/5.4.0/darwin/x64/zmq.node
    at bindings (/Users/gaoman/Documents/openstf/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/gaoman/Documents/openstf/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/gaoman/Documents/openstf/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/gaoman/Documents/openstf/stf/lib/util/zmqutil.js:7:11)

need help!!!

**Comment by sorccu** [comment]
If you're using an older version of Node with NPM 2, you're probably hitting npm/npm#5400. You can try running `npm rebuild zmq` if you don't want to upgrade, but I would strongly recommend using Node 5.x instead.

Please close the ticket if this solves your issue.

**Comment by tobecrazy** [comment]
Got the same error message , is this issue be resolved?

**Comment by sorccu** [comment]
rm -rf node_modules && npm install

**Comment by tobecrazy** [comment]
@sorccu sorccu Thanks ， it works！
