### ISSUE TITLE
stf local error

### ISSUE THREAD

**Issue by zhaoming1222** [openstf/stf#251]
```
INF/device 28851 [e1f2ffd] Preparing device
FTL/device 28851 [e1f2ffd] Setup had an error Error: Cannot find module '/Users/gaoman/Documents/openstf/stf/node_modules/jpeg-turbo/lib/binding/node-v47-darwin-x64/jpegturbo.node'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/gaoman/Documents/openstf/stf/node_modules/jpeg-turbo/index.js:5:18)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/gaoman/Documents/openstf/stf/lib/units/device/plugins/vnc/index.js:8:12)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/gaoman/Documents/openstf/stf/lib/units/device/index.js:23:21
    at SerialSyrup.ParallelSyrup.invoke (/Users/gaoman/Documents/openstf/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /Users/gaoman/Documents/openstf/stf/node_modules/stf-syrup/lib/serial.js:43:33
    at tryCatch1 (/Users/gaoman/Documents/openstf/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
FTL/util:lifecycle 28851 [e1f2ffd] Shutting down due to fatal error
INF/provider 28798 [*] Cleaning up device worker "e1f2ffd"
```

**Comment by labolado** [comment]
I got the error two. I've installed jpeg-turbo successfully.

My System is MacOS 10.11.3

```
INF/device 14593 [64a6515b7803] Preparing device
FTL/device 14593 [64a6515b7803] Setup had an error Error: Cannot find module '/usr/local/lib/node_modules/stf/node_modules/jpeg-turbo/lib/binding/node-v47-darwin-x64/jpegturbo.node'
    at Function.Module._resolveFilename (module.js:339:15)
```

**Comment by sorccu** [comment]
How did you install stf?

**Comment by dpn** [comment]
I ran into this earlier. Turns out jpeg-turbo was failing to build due to lack of [http://yasm.tortall.net](yasm). I'd suggest using your favorite package manager to install yasm, then re-building openstf.

**Comment by sorccu** [comment]
Super old issue but @dpn's answer is good. Closing.
