### ISSUE TITLE
Logs and websocket is broken

### ISSUE THREAD

**Issue by miss0110** [openstf/stf#271]
I'm using Samsung Galaxy S6 Edge(Android 6.0.1) in STF
Logs and websocket is broken

The following error message

```
Error: Unprocessable entry data 'uardUpdateMonito'
    at Binary._processEntry (/Users/nhnent/git/openstf/stf/node_modules/adbkit/node_modules/adbkit-logcat/lib/logcat/parser/binary.js:69:26)
    at Binary.parse (/Users/nhnent/git/openstf/stf/node_modules/adbkit/node_modules/adbkit-logcat/lib/logcat/parser/binary.js:46:14)
    at LineTransform.<anonymous> (/Users/nhnent/git/openstf/stf/node_modules/adbkit/node_modules/adbkit-logcat/lib/logcat/reader.js:82:31)
    at LineTransform.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at LineTransform.Readable.push (_stream_readable.js:126:10)
    at LineTransform.Transform.push (_stream_transform.js:140:32)
    at LineTransform._transform (/Users/nhnent/git/openstf/stf/node_modules/adbkit/lib/adb/linetransform.js:40:14)
    at LineTransform.Transform._read
```
```

            ^
Error: Unprocessable entry data 'uardUpdateMonito'
    at Binary._processEntry (/Users/nhnent/git/openstf/stf/node_modules/adbkit/node_modules/adbkit-logcat/lib/logcat/parser/binary.js:69:26)
    at Binary.parse (/Users/nhnent/git/openstf/stf/node_modules/adbkit/node_modules/adbkit-logcat/lib/logcat/parser/binary.js:46:14)
    at LineTransform.<anonymous> (/Users/nhnent/git/openstf/stf/node_modules/adbkit/node_modules/adbkit-logcat/lib/logcat/reader.js:82:31)
    at LineTransform.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at LineTransform.Readable.push (_stream_readable.js:126:10)
    at LineTransform.Transform.push (_stream_transform.js:140:32)
    at LineTransform._transform (/Users/nhnent/git/openstf/stf/node_modules/adbkit/lib/adb/linetransform.js:40:14)
    at LineTransform.Transform._read (_stream_transform.js:179:10)
    at LineTransform.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at LineTransform.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
```

![image](https://cloud.githubusercontent.com/assets/4638075/13565799/bc0b7bb0-e495-11e5-81e7-86978ffd376b.png)

**Comment by capasky** [comment]
I meet the same situation.
And found issues  in the adbkit-logcat project:
https://github.com/openstf/adbkit-logcat/issues/1 
https://github.com/openstf/adbkit-logcat/issues/4

**Comment by miss0110** [comment]
Thanks @capasky 
I apply ```feature/android-L``` branch in adbkit-logcat
Test results, Logs normally is printed in both ```Galaxy S3(4.4.4)``` and ```Galaxy S6 Edge(6.0.1)```
OS 5.x did not tested yet
because it operates well in OS6.0.1 it seems to work well on OS 5.x.

[stf_new_4.4.4.txt](https://github.com/openstf/stf/files/162658/stf_new_4.4.4.txt)
[stf_new_6.0.1.txt](https://github.com/openstf/stf/files/162659/stf_new_6.0.1.txt)
