### ISSUE TITLE
STF local is not starting up

### ISSUE THREAD

**Issue by tadesushilgithub** [openstf/stf#296]
Hi,

Today I have installed the STF local but I am getting below error  "Received an unsupported protocol version. This port is for RethinkDB queries"
Rethinkdb version is : rethinkdb 2.2.5 (CLANG 7.0.2 (clang-700.1.81)). Can you please tell me what is wrong. Please find attached snapshot for more details,
![screen shot 2016-04-07 at 7 33 08 pm](https://cloud.githubusercontent.com/assets/17309586/14357230/8695be18-fd05-11e5-8af0-ae0e5fca091c.png)

**Comment by viecode09** [comment]
Hi There, I got the same issue as here..

Could please help me how to fix it?

Cheers,

**Comment by myqqai** [comment]
I met the same problem.
Could you tell me how do you solve

**Comment by myqqai** [comment]
the same issue
Could please help me how to fix it?

**Comment by gunta** [comment]
Can you paste the output of `stf doctor` ?

**Comment by viecode09** [comment]
```
Users/lutvirosyady/stf/node_modules/zmq/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/lutvirosyady/stf/node_modules/zmq/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/lutvirosyady/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

```

**Comment by sorccu** [comment]
You updated node and didn't run 'nom rebuild' to rebuild native extensions.
This is like the 5th time this exact same question has been asked in the
last 1-2 weeks.

**Comment by viecode09** [comment]
My apologize @sorccu.. It's been fixed when I upgrade rethinkdb version to latest version..

Thanks...

**Comment by sorccu** [comment]
Ok, so it looks like `npm rebuild` alone is not enough on Node 6.x. For future reference, if it still doesn't work, I would recommend simply doing `rm -rf node_modules` followed by `npm install`. It should then work as usual.
