### ISSUE TITLE
screenshots feature working on MacBook

### ISSUE THREAD

**Issue by Lubricy** [openstf/stf#321]
Hi there,

I'm trying to get STF working on my MacBook. I have tried it on a linux VM before and it works pretty awesome. It's now running on OS X, but I met a challenge: screenshots feature is not working.

I'm using `bin/stf local --public-ip <my-IP>`, and console shows following error when screenshot button is clicked:
```bash
INF/device:plugins:screen:capture 37409 [03157df39da5dc05] Capturing screenshot
INF/device:plugins:screen:stream 37409 [03157df39da5dc05] Requesting frame producer to stop
INF/device:plugins:screen:stream 37409 [03157df39da5dc05] Disconnecting from minicap service
INF/device:plugins:screen:stream 37409 [03157df39da5dc05] Stopping minicap service
INF/device:plugins:screen:stream 37409 [03157df39da5dc05] Sending SIGTERM to minicap
INF/device:plugins:screen:stream 37409 [03157df39da5dc05] minicap says: "INFO: (jni/minicap/minicap.cpp:196) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 37409 [03157df39da5dc05] minicap says: "INFO: (jni/minicap/minicap.cpp:512) Closing client connection"
INF/device:plugins:screen:stream 37409 [03157df39da5dc05] minicap says: "INFO: (external/MY_minicap/src/minicap_21.cpp:284) Destroying virtual display"
ERR/device:support:storage 37409 [03157df39da5dc05] Upload to "http://localhost:7100/s/upload/image" failed: HTTP 301
ERR/device:plugins:screen:capture 37409 [03157df39da5dc05] Screen capture failed Error: Upload to "http://localhost:7100/s/upload/image" failed: HTTP 301
    at Request._callback (/Users/Me/Projects/stf/lib/units/device/support/storage.js:30:27)
    at Request.self.callback (/Users/Me/Projects/stf/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Me/Projects/stf/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Me/Projects/stf/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I noticed that minicap service stopped after each time I trigger a screenshot, but I don't know why this is happening 

here's the `stf doctor` output:

``` bsah
INF/util:doctor 39181 [*] OS Arch: x64
INF/util:doctor 39181 [*] OS Platform: darwin
INF/util:doctor 39181 [*] OS Platform: 15.4.0
INF/util:doctor 39181 [*] Using Node 6.1.0
INF/util:doctor 39181 [*] Using RethinkDB client 2.3.1
INF/util:doctor 39181 [*] Using ZeroMQ 4.1.4
INF/util:doctor 39181 [*] ProtoBuf 2.6.1
INF/util:doctor 39181 [*] GraphicsMagick 1.3.23
INF/util:doctor 39181 [*] Local RethinkDB server 2.3.2
INF/util:doctor 39181 [*] Local ADB 1.0.32
```
The `stf -V` is `1.1.1` with git hash `commit b61df410f72505367728c4d05ef53449eadd4d69`

Any thoughts/suggestions to help me overcome this issue?

**Comment by joaopedroms22** [comment]
hi @Lubricy,

Did you already solve this issue? 
I'm with a similar problem , but in my case the MiniCap works perfectly , at least openstf stderr shows no error , but the screenshot is not shown in openstf web interface . Follow the log openSTF and managed to open the image without problems , so the problem is not in taking the screenshot but the referral to the openSTF interface.
Any suggestion @sorccu ?

I'm using OS X as well, with El Captain 10.11.5.

Regards

**Comment by sorccu** [comment]
You probably didn't install graphicsmagick.

**Comment by joaopedroms22** [comment]
I have all installed dependancy . I had before the openstf housed in a machine with Linux , and screenshots working properly , only since I moved to OS X is no longer functioning properly .
I leave here a screenshot of the interface and openSTF as appears screenshot:
http://imgur.com/KEUI1CV

Thanks for your help.

**Comment by sorccu** [comment]
So far every single time the screen has looked like that, graphicsmagick
hasn't been installed. Could you check that the gm command works?

**Comment by joaopedroms22** [comment]
yes, graphicsmagick commands works. 
This is the output of gm version command:

```
userpc:/var/folders/xs/gk3f7hg178199sxhr68728k80000gn/T$ gm version
GraphicsMagick 1.3.24 2016-05-30 Q16 http://www.GraphicsMagick.org/
Copyright (C) 2002-2016 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.

Feature Support:
  Native Thread Safe       yes
  Large Files (> 32 bit)   yes
  Large Memory (> 32 bit)  yes
  BZIP                     yes
  DPS                      no
  FlashPix                 no
  FreeType                 yes
  Ghostscript (Library)    no
  JBIG                     no
  JPEG-2000                no
  JPEG                     yes
  Little CMS               no
  Loadable Modules         yes
  OpenMP                   no
  PNG                      yes
  TIFF                     yes
  TRIO                     no
  UMEM                     no
  WebP                     no
  WMF                      no
  X11                      no
  XML                      yes
  ZLIB                     yes

Host type: x86_64-apple-darwin15.5.0

Configured using the command:
  ./configure  '--prefix=/usr/local/Cellar/graphicsmagick/1.3.24' '--disable-dependency-tracking' '--enable-shared' '--disable-static' '--with-modules' '--disable-openmp' '--with-quantum-depth=16' '--without-gslib' '--with-gs-font-dir=/usr/local/share/ghostscript/fonts' '--without-x' '--without-lcms2' 'CC=clang' 'CXX=clang++'

Final Build Parameters:
  CC       = clang
  CFLAGS   = -g -O2 -Wall -D_THREAD_SAFE
  CPPFLAGS = -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2
  CXX      = clang++
  CXXFLAGS = -D_THREAD_SAFE
  LDFLAGS  = -L/usr/local/Cellar/freetype/2.6.3/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib
  LIBS     = -lfreetype -lbz2 -lz -lltdl -lm -lpthread
```

**Comment by Lubricy** [comment]
Hi @joaopedroms22,
In my case I found that there is a firewall on my macbook blocking all incoming connections even they're from localhost. After I turned it off everything goes well.
Not sure if this helps ...

**Comment by jlopezinc** [comment]
When using homebrew to install graphicsmagick gm binary is located at ``/usr/local/bin`` (actually, it's symlinked).
So make sure that your ``PATH`` env contains that folder when launching stf. That was the problem that I and @joaopedroms22 had.
