### ISSUE TITLE
STF is not starting after installed

### ISSUE THREAD

**Issue by viecode09** [openstf/stf#337]
Hi There,

I got this issue when installing STF and running `stf local` the error something like this :

```
INF/util:procutil 1899 [*] Forking "/Users/lutvirosyady/stf/lib/cli.js migrate"
INF/db 1900 [*] Connecting to 127.0.0.1:28015
undefined:1
ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?
^

SyntaxError: Unexpected token E in JSON at position 0
    at Object.parse (native)
    at Socket.handshake_callback (/Users/lutvirosyady/stf/node_modules/rethinkdb/net.js:624:35)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)

/Users/lutvirosyady/stf/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/Users/lutvirosyady/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

For you detail information when I run `stf doctor` I got result like this as follow :

```
Users/lutvirosyady/stf/node_modules/zmq/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/lutvirosyady/stf/node_modules/zmq/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/lutvirosyady/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

Could you please help with this, so I can start to use STF.. :-)
Much appreciated for all your help here..

Cheers,

**Comment by sorccu** [comment]
You upgraded node without doing 'npm rebuild' to recompile native
extensions.

**Comment by 0x88l** [comment]
You can try to reinstall stf and another version of rethinkdb that I was doing.
link:  http://download.rethinkdb.com/apt
Choose a suitable one 
![image](https://cloud.githubusercontent.com/assets/18346467/15671309/d35cd3c2-275c-11e6-99d3-2bd304fdabba.png)

I hope that can help you.

**Comment by viecode09** [comment]
It's been fixed, It just need to upgrade rethinkdb version to latest version..

Thanks @0x88l @sorccu  for all your supports
