### ISSUE TITLE
Screenshots  capture a empty file

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#349]
Browser:Chrome(ch_zn,win 8)
STF server: ubuntu 16.04
Err feature:screenshots
Operating: 
1. choose one of device
2. click the tap of screenshots,and click buttom of screenshots.

result:
The pic that screen shot was empty.
![image](https://cloud.githubusercontent.com/assets/18346467/16065077/def0bef0-32d9-11e6-82d5-9f9bda6126ed.png)

log output:
INF/device:plugins:screen:capture 30486 [F8UDU15131003748] Capturing screenshot
INF/storage:temp 30424 [*] Uploaded "F8UDU15131003748.jpg" to "/tmp/upload_363625db7cbb670e950ce248c921fd78"
INF/device:support:storage 30486 [F8UDU15131003748] Uploaded to "/s/image/59653267-52dc-416f-9c9d-3f6eb82b0ee1/F8UDU15131003748.jpg"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Requesting frame producer to stop
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Disconnecting from minicap service
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Stopping minicap service
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Sending SIGTERM to minicap
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (jni/minicap/minicap.cpp:196) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (jni/minicap/minicap.cpp:512) Closing client connection"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:303) Destroying virtual display"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Keeping 574x804 as current frame producer projection
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Requesting frame producer to start
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Launching screen service
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "PID: 18722"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: Using projection 1080x1920@452x804/0"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:255) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:258) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:265) Creating virtual display"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Connecting to minicap service
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:271) Creating buffer queue"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:278) Creating CPU consumer"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:284) Creating frame waiter"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:288) Publishing virtual display"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 6268932 bytes for JPG encoder"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Reading minicap banner
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Requesting frame producer to stop
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Disconnecting from minicap service
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Stopping minicap service
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] Sending SIGTERM to minicap
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (jni/minicap/minicap.cpp:196) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (jni/minicap/minicap.cpp:512) Closing client connection"
INF/device:plugins:screen:stream 30486 [F8UDU15131003748] minicap says: "INFO: (external/MY_minicap/src/minicap_19.cpp:303) Destroying virtual display"

It's this a bug?

**Comment by joaopedroms22** [comment]
I got the same issue as well but in OS X.

**Comment by joaopedroms22** [comment]
I think issue could be here
`INF/device:support:storage 30486 [F8UDU15131003748] Uploaded to "/s/image/59653267-52dc-416f-9c9d-3f6eb82b0ee1/F8UDU15131003748.jpg"`

the /s/image directory does not exists...

**Comment by 0x88l** [comment]
I don't really find where is the problem. The screen cature is fine ,maybe it was err when tranfer process or  write file.
The core maybe err at the lib/device/screen/cature.js  50 line.But  I'm still not quite understand nodejs .It take me some time to learn nodejs and angularjs.

.......
          return adb.pull(options.serial, file)
            .then(function(transfer) {
              return storage.store('image', transfer, {
                filename: util.format('%s.jpg', options.serial)
              , contentType: 'image/jpeg'
              , knownLength: stats.size

**Comment by sorccu** [comment]
Based on the bug reports over time, we probably do have a known problem with streaming somewhere, but it's unclear where it is. Could be adbkit. We have not been able to reproduce the issue or make a test case for it.

**Comment by joaopedroms22** [comment]
I tested now in my setup on Linux , and the screenshots problem is not found , so probably the problem may be related to OS X.

**Comment by 0x88l** [comment]
May I see your "stf doctor" info?

**Comment by joaopedroms22** [comment]
I don't have "stf doctor" don't know why.
My "stf ''help" shows this:

```
user@test-lab-mac-01:~$ stf --help

  Usage: stf [options] [command]


  Commands:

    provider [options] [serial...]          start provider
    device [options] <serial>               start device worker
    processor [options] <name>              start processor
    reaper [options] <name>                 start reaper
    triproxy [options] <name>               start triproxy
    auth-ldap [options]                     start LDAP auth client
    auth-oauth2 [options]                   start OAuth 2.0 auth client
    auth-saml2 [options]                    start SAML 2.0 auth client
    auth-mock [options]                     start mock auth client
    notify-hipchat [options]                start HipChat notifier
    log-rethinkdb [options]                 start a rethinkdb log recorder
    poorxy [options]                        start a poor reverse proxy for local development
    app [options]                           start app
    websocket [options]                     start web socket
    storage-temp [options]                  start temp storage
    storage-s3 [options]                    start s3 storage
    storage-plugin-image [options]          start storage image plugin
    storage-plugin-apk [options]            start storage ask plugin
    migrate                                 migrates the database to the latest version
    generate-fake-device [options] [model]  generates a fake device for testing
    local [options] [serial...]             start everything locally

  Options:

    -h, --help     output usage information
    -V, --version  output the version number

user@test-lab-mac-01:~$ stf --version
1.1.1

```

**Comment by 0x88l** [comment]
@sorccu  I have catch the wrong message.That is "http404". Why  is my website not found?But my stf'site have been running

log:
2016-07-14 17:12:40 ERR/storage:plugins:image 24061 [*] Unable to transform resource "4ac8ea9d-2a5e-45d4-b621-7e4f2feceb3c" Error: HTTP 404
    at Request.<anonymous> (/opt/stf/lib/units/storage/plugins/image/task/get.js:15:18)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestResponse (/opt/stf/node_modules/request/request.js:977:10)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:458:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at Socket.socketOnData (_http_client.js:348:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
From previous event:
    at module.exports (/opt/stf/lib/units/storage/plugins/image/task/get.js:9:10)
    at /opt/stf/lib/units/storage/plugins/image/index.js:31:14
    at maybeNext (/opt/stf/lib/util/requtil.js:38:15)
    at /opt/stf/lib/util/requtil.js:49:5
    at Layer.handle [as handle_request] (/opt/stf/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/stf/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/opt/stf/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/stf/node_modules/express/lib/router/layer.js:95:5)
    at /opt/stf/node_modules/express/lib/router/index.js:277:22
    at param (/opt/stf/node_modules/express/lib/router/index.js:349:14)
    at param (/opt/stf/node_modules/express/lib/router/index.js:365:14)
    at param (/opt/stf/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/opt/stf/node_modules/express/lib/router/index.js:410:3)
    at next (/opt/stf/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/opt/stf/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/opt/stf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/stf/node_modules/express/lib/router/index.js:312:13)
    at /opt/stf/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/stf/node_modules/express/lib/router/index.js:330:12)
2016-07-14 17:13:05 INF/device:plugins:screen:stream 24104 [F8UDU15131003748] Requesting frame producer to stop
2016-07-14 17:13:05 INF/device:plugins:screen:stream 24104 [F8UDU15131003748] Disconnecting from minicap service
2016-07-14 17:13:05 INF/device:plugins:screen:stream 24104 [F8UDU15131003748] Stopping minicap service
2016-07-14 17:13:05 INF/device:plugins:screen:stream 24104 [F8UDU15131003748] Sending SIGTERM to minicap
