### ISSUE TITLE
Galaxy J1 Mini SM-J105H does not work

### ISSUE THREAD

**Issue by sorccu** [openstf/stf#366]
## What's the problem (or question)?

Galaxy J1 Mini SM-J105H reportedly does not work due to a minicap failure, as can be seen in the logs below.

```
INF/device:plugins:screen:stream 36181 [xxxxxxxxxxxxxxxx] Reading minicap banner
INF/device:plugins:screen:stream 36181 [xxxxxxxxxxxxxxxx] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection"
WRN/device:plugins:screen:stream 36181 [xxxxxxxxxxxxxxxx] Connection to minicap ended unexpectedly
INF/device:plugins:screen:stream 36181 [xxxxxxxxxxxxxxxx] Disconnecting from minicap service
FTL/device:plugins:screen:stream 36181 [xxxxxxxxxxxxxxxx] Frame producer had an error Error: Failed more than 3 times in 10000ms
    at FrameProducer._failLimitExceeded (/usr/local/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:220:26)
    at FailCounter.emit (/usr/local/lib/node_modules/stf/node_modules/eventemitter3/index.js:73:35)
    at FailCounter.inc (/usr/local/lib/node_modules/stf/lib/util/failcounter.js:29:10)
    at FrameProducer._socketEnded (/usr/local/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:207:24)
    at RiskyStream.emit (/usr/local/lib/node_modules/stf/node_modules/eventemitter3/index.js:71:35)
    at RiskyStream.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/riskystream.js:14:12)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
FTL/util:lifecycle 36181 [xxxxxxxxxxxxxxxx] Shutting down due to fatal error
INF/provider 36173 [*] Cleaning up device worker "xxxxxxxxxxxxxxxx"
ERR/provider 36173 [*] Device worker "xxxxxxxxxxxxxxxx" died with code 1
INF/provider 36173 [*] Restarting device worker "xxxxxxxxxxxxxxxx"
```
## What should have happened?

It should have been operable like any other device.
## Do you have an idea for a solution?

Need to search for a fix or workaround in minicap.
## How can we reproduce the issue?

- [x] 1. Buy a Galaxy J1 Mini SM-J105H 
- [ ] 2. Connect it to STF
## Please tell us details about your environment.

Known to be irrelevant in this particular case.

**Comment by sorccu** [comment]
More details about the exact model:

```
WRN/device:plugins:data 36183 [xxxxxxxxxxxxxxxx] Unable to find device data { serial: 'xxxxxxxxxxxxxxxx',
  platform: 'Android',
  manufacturer: 'SAMSUNG',
  operator: 'Robi',
  model: 'SM-J105H',
  version: '5.1.1',
  abi: 'armeabi-v7a',
  sdk: '22',
  product: 'j1mini3gxx',
```

**Comment by sorccu** [comment]
Ordered with donation funds for ~$105 incl. shipping. This has the potential to fix many other Samsung devices as well.

**Comment by sorccu** [comment]
Device arrived... it may have been stolen. The seal had been broken and the device is locked, asking for the previous owner's Google account. Very unexpected considering the eBay seller had nearly 7000 feedback with 99.2% positive rating.

Initiating claim process.

**Comment by vbanthia** [comment]
Checked other samsung devices, Working fine with followings:
- Samsung Galaxy S7 Edge
- Samsung Galaxy S6
- Samsung Galaxy A5 2016

Not working with:
- [Samsung Galaxy A7 2016](http://www.samsung.com/in/consumer/mobile-devices/smartphones/galaxy-a/SM-A710FZDFINS)

More Info:
```
  platform: 'Android',
  manufacturer: 'SAMSUNG',
  model: 'SM-A710F',
  version: '5.1.1',
  abi: 'armeabi-v7a',
  sdk: '22',
  product: 'a7xeltexx',
  display:
   { id: 0,
     width: 1080,
     height: 1920,
     xdpi: 403.4110107421875,
     ydpi: 403.0409851074219,
     fps: 59,
     density: 3,
     rotation: 0,
     secure: true,
     size: 5.464510452525597 },
 }
```

**Comment by vbanthia** [comment]
After OS update to 6.0, Samsung Galaxy A7 2016 is working fine.

**Comment by sorccu** [comment]
Hmm, that's very interesting...

**Comment by miss0110** [comment]
I found other samsung device

### Not working
* Samsung Galaxy A8(v5.1.1)

### working fine with followings:
* Samsung Galaxy A5(v5.0.2)
* Samsung Galaxy A7(v5.0.2)

After OS update to 6.0.1, Samsung Galaxy A8 is working fine.
Maybe cause seems to be Android 5.1.1

More Info

```json
"abi":  "armeabi-v7a" ,
"airplaneMode": false ,
"battery": {
"health":  "good" ,
"level": 100 ,
"scale": 100 ,
"source":  "usb" ,
"status":  "full" ,
"temp": 26.2 ,
"voltage": 4.402
} ,
"display": {
"density": 3 ,
"fps": 59 ,
"height": 1920 ,
"id": 0 ,
"rotation": 0 ,
"secure": true ,
"xdpi": 422.0299987792969 ,
"ydpi": 424.0690002441406
} ,
"manufacturer":  "SAMSUNG" ,
"model":  "SM-A800S" ,
"network": {
"connected": true ,
"failover": false ,
"roaming": false ,
"subtype":  "" ,
"type":  "WIFI"
} ,
"operator": null ,
"owner": null ,
"platform":  "Android" ,

"present": false ,
"product":  "a8elteskt" ,
"provider": {
"ready": true ,
"reverseForwards": [ ],
"sdk":  "22" ,
"status": 3 ,
"version":  "5.1.1"
```

**Comment by sorccu** [comment]
These should all work in STF 2.2.0 :)
