### ISSUE TITLE
Device disconnects, device worker dies with "Error: read ECONNRESET" in STF Provider log.

### ISSUE THREAD

**Issue by rseek** [openstf/stf#376]
## What's the problem (or question)?

Hi there!
Sometimes during remote connection (adb connect) device just unexpectedly disconnects, and becomes "Free" in STF web-interface (and is fully operational), and in STF Provider log I see such error:
```
IMP/device:plugins:group 9702 [E9OKBC204913] Now owned by "example@email.com"
INF/device:plugins:group 9702 [E9OKBC204913] Subscribing to group channel "uaOSQl83TCyTLdCKZZBjgw=="
IMP/device:plugins:connect 9702 [E9OKBC204913] Remote Connect Started for device "E9OKBC204913" at "10.154.18.75:7545"
INF/device:plugins:connect 9702 [E9OKBC204913] New remote ADB connection from ::ffff:10.54.25.49
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:849:11)
    at TCP.onread (net.js:544:26)
INF/provider 1 [*] Cleaning up device worker "E9OKBC204913"
ERR/provider 1 [*] Device worker "E9OKBC204913" died with code 1
INF/provider 1 [*] Restarting device worker "E9OKBC204913"
```
It happens with different devices and it's hard to reproduce.

1. Get adb connect string from remoteConnect API method
2. Connect device via adb connect string
3. Run appium UI tests
4. Wait
 
If I skip step 3 (Run appium tests) I can't reproduce the problem, but it seems appium itself has nothing to do with the problem, maybe pushing big files during tests cause the problem.

### Environment:

* **full deployment**

STF-Provider on desktop host with devices connected and all other STF services on virtual machine

* **v2.0.0-beta docker image** from docker hub

* **nodejs v4.1.2**

* **ubuntu 14.04** on all nodes

I will continue to experiment to find the specific conditions to reproduce the problem, but I want to ask for help in the investigation of this problem from error in the STF Provider log - it seems that something just unexpectedly drops some TCP connection (maybe ADB server?), and I don't know how to determine what TCP connection drops and what else can I do about it (maybe get some TCP dumps)

Thank you!

**Comment by sorccu** [comment]
Just sometimes or always?

**Comment by rseek** [comment]
Usually it works fine, we run a lot of tests on several devices, but sometimes one of devices unexpectedly disconnects with such error.

It doesn't affect other connections with other devices and device become fully operational just after worker restarts

**Comment by skyline-gleb** [comment]
@sorccu hi!
Now on openstf/stf:v2.3.0 we getting this error. Sometimes, but often - 4 of 5 disconnected.
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)
```

**Comment by skyline-gleb** [comment]
Problem with Nexus 5X with direct connection to PC (USB 2.0 port). Checked on two different PC.

**Comment by sorccu** [comment]
You could try https://github.com/mattinsler/longjohn to get a more usable stack trace. Might be a bit annoying to do with the docker deployment, though. Unfortunately the current units pull the image before running it (which is a bit of a mistake, I'm using a different method now), so even a `docker commit` wouldn't apply your changes reliably. Might have to either modify the units or run from the cloned repo.

**Comment by skyline-gleb** [comment]
okay, I'll try it

**Comment by sorccu** [comment]
Could possibly be a TCP timeout, and therefore perhaps related to #100.

**Comment by skyline-gleb** [comment]
@sorccu i had an extended stack trace, using `require('longjohn')` instead `Promise.longStackTraces()` in `lib/cli.js`
```
IMP/device:plugins:connect 26 [00ec0ea6616e95c8] Remote Connect Started for device "00ec0ea6616e95c8" at "10.154.8.17:7405"
INF/device:plugins:connect 26 [00ec0ea6616e95c8] New remote ADB connection from ::ffff:10.54.25.49
Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:687:35)
    at Connection.connect (/app/node_modules/adbkit/lib/adb/connection.js:51:17)
    at Client.connection (/app/node_modules/adbkit/lib/adb/client.js:118:8)
    at Client.transport (/app/node_modules/adbkit/lib/adb/client.js:255:17)
    at Service._handleOpenPacket (/app/node_modules/adbkit/lib/adb/tcpusb/service.js:80:24)
    at /app/node_modules/adbkit/lib/adb/tcpusb/service.js:59:26
    at tryCatcher (/app/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/app/node_modules/adbkit/node_modules/bluebird/js/main/method.js:31:24)
    at Service.handle (/app/node_modules/adbkit/lib/adb/tcpusb/service.js:55:26)
    at /app/node_modules/adbkit/lib/adb/tcpusb/socket.js:216:24
    at tryCatcher (/app/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/app/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/app/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:69:37)
    at Socket._handleOpenPacket (/app/node_modules/adbkit/lib/adb/tcpusb/socket.js:210:12)
    at /app/node_modules/adbkit/lib/adb/tcpusb/socket.js:103:26
    at tryCatcher (/app/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/app/node_modules/adbkit/node_modules/bluebird/js/main/method.js:31:24)
    at Socket._handle (/app/node_modules/adbkit/lib/adb/tcpusb/socket.js:95:26)
    at emitOne (events.js:96:13)
    at PacketReader.emit (events.js:188:7)
INF/provider 1 [*] Cleaning up device worker "00ec0ea6616e95c8"
ERR/provider 1 [*] Device worker "00ec0ea6616e95c8" died with code 1
```

**Comment by sorccu** [comment]
That's super useful. Perhaps we should include longjohn by default... might have a bit of a performance penalty, though, so would need to study the code.

**Comment by gunta** [comment]
Nice. Perhaps using it only when DEBUG is true (if there is a performance penalty) would be useful too.

**Comment by skyline-gleb** [comment]
Probably, stf-provider is a victim.
We have succeeded in establishing bad adb command. Her trace looks like this:
```
12:43:44             main:  2120:4147975936 | Handling commandline()
12:43:44  adb_commandline:  2120:4147975936 | interactive shell loop. cmd=shell:getprop emu.uuid
12:43:44     _adb_connect:  2120:4147975936 | _adb_connect: host:version
12:43:44   WriteFdExactly:  2120:4147975936 | writex: fd=3 len=4: 30303063 000c
12:43:44   WriteFdExactly:  2120:4147975936 | writex: fd=3 len=12: 686f73743a76657273696f6e host:version
12:43:44    ReadFdExactly:  2120:4147975936 | readx: fd=3 wanted=4
12:43:44    ReadFdExactly:  2120:4147975936 | readx: fd=3 wanted=4 got=4
12:43:44 4f4b4159 OKAY
12:43:44     _adb_connect:  2120:4147975936 | _adb_connect: return fd 3
12:43:44      adb_connect:  2120:4147975936 | adb_connect: service shell:getprop emu.uuid
12:43:44    ReadFdExactly:  2120:4147975936 | readx: fd=3 wanted=4
12:43:44    ReadFdExactly:  2120:4147975936 | readx: fd=3 wanted=4 got=4
12:43:44 30303034 0004
12:43:44    ReadFdExactly:  2120:4147975936 | readx: fd=3 wanted=4
12:43:44    ReadFdExactly:  2120:4147975936 | readx: fd=3 wanted=4 got=4
12:43:44 30303230 0020
12:43:44     _adb_connect:  2120:4147975936 | _adb_connect: shell:getprop emu.uuid
12:43:44   WriteFdExactly:  2120:4147975936 | writex: fd=3 len=4: 30303166 001f
12:43:44   WriteFdExactly:  2120:4147975936 | writex: fd=3 len=31: 686f73743a7472616e73706f72743a31 host:transport:1
12:43:44 switch_socket_transport:  2120:4147975936 | Switch transport in progress
12:43:44    ReadFdExactly:  2120:4147975936 | readx: fd=3 wanted=4
12:43:44    ReadFdExactly:  2120:4147975936 | readx: fd=3 wanted=4 got=4
12:43:44 4f4b4159 OKAY
12:43:44 switch_socket_transport:  2120:4147975936 | Switch transport success
12:43:44   WriteFdExactly:  2120:4147975936 | writex: fd=3 len=4: 30303136 0016
12:43:44   WriteFdExactly:  2120:4147975936 | writex: fd=3 len=22: 7368656c6c3a67657470726f7020656d shell:getprop em
12:43:44    ReadFdExactly:  2120:4147975936 | readx: fd=3 wanted=4
12:43:44    ReadFdExactly:  2120:4147975936 | readx: fd=3 disconnected
12:43:44      adb_connect:  2120:4147975936 | _adb_connect error: protocol fault (couldn't read status): Success     adb_connect:  2120:4147975936 | adb_connect: return fd -1
12:43:44 error: protocol fault (couldn't read status): Success
12:43:44  adb_commandline:  2120:4147975936 | interactive shell loop. return r=-1
```

But we don't exactly know why this happens. Device trouble, maybe.

**Comment by rstalekar** [comment]
I too get the same issue for Android handsets wherein adb disconnects from the device with ECONNRESET when Appium executes the tests. How can we make adb connect back to the device.

**Comment by weamylady2** [comment]
I got the same error sometimes, this is the longjohn log:
`2019-6-4 08:58:45 INF/device:plugins:screen:stream 4915 [N8K7N17206007791] Requesting frame producer to stop
2019-6-4 08:58:45 INF/device:plugins:screen:stream 4915 [N8K7N17206007791] Disconnecting from minicap service
Error: read ECONNRESET
    at TCP.onread (net.js:602:25)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:784:35)
    at Ultron.on (/Users/waterhuang/Downloads/stf/node_modules/ws/node_modules/ultron/index.js:42:11)
    at WebSocket.setSocket (/Users/waterhuang/Downloads/stf/node_modules/ws/lib/WebSocket.js:131:18)
    at WebSocket.initAsServerClient (/Users/waterhuang/Downloads/stf/node_modules/ws/lib/WebSocket.js:465:8)
    at new WebSocket (/Users/waterhuang/Downloads/stf/node_modules/ws/lib/WebSocket.js:70:26)
    at WebSocketServer.completeUpgrade (/Users/waterhuang/Downloads/stf/node_modules/ws/lib/WebSocketServer.js:275:20)
    at WebSocketServer.handleUpgrade (/Users/waterhuang/Downloads/stf/node_modules/ws/lib/WebSocketServer.js:227:10)
    at Server.WebSocketServer._ultron.on (/Users/waterhuang/Downloads/stf/node_modules/ws/lib/WebSocketServer.js:86:14)
    at Server.emit (events.js:180:13)
    at onParserExecuteCommon (_http_server.js:531:14)
    at onParserExecute (_http_server.js:479:3)
---------------------------------------------
    at Ultron.on (/Users/waterhuang/Downloads/stf/node_modules/ws/node_modules/ultron/index.js:42:11)
    at new WebSocketServer (/Users/waterhuang/Downloads/stf/node_modules/ws/lib/WebSocketServer.js:85:20)
    at createServer (/Users/waterhuang/Downloads/stf/lib/units/device/plugins/screen/stream.js:425:17)
    at /Users/waterhuang/Downloads/stf/lib/units/device/plugins/screen/stream.js:449:12
    at SerialSyrup.ParallelSyrup.invoke (/Users/waterhuang/Downloads/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /Users/waterhuang/Downloads/stf/node_modules/stf-syrup/lib/serial.js:43:33
    at tryCatch1 (/Users/waterhuang/Downloads/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/Users/waterhuang/Downloads/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/waterhuang/Downloads/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/waterhuang/Downloads/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (/Users/waterhuang/Downloads/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/waterhuang/Downloads/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/Users/waterhuang/Downloads/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
    at process._tickCallback (internal/process/next_tick.js:176:11)
`
