### ISSUE TITLE
stf doctor some error occured

### ISSUE THREAD

**Issue by yuqlabson** [openstf/stf#393]
information:
CentOS Linux 2.6.32-431.el6.x86_64
node v0.12.12
npm  v3.10.5

[root@root local]# npm install -g stf
npm WARN deprecated slack-client@2.0.6: Use @slack/client instead, this package is no longer maintained
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
/usr/local/node/bin/stf -> /usr/local/node/lib/node_modules/stf/bin/stf
/usr/local/node/lib
└─┬ stf@2.0.1 
  ├─┬ adbkit@2.4.1
  │ └── node-forge@0.6.42 
  ├── aws-sdk@2.4.13 
  ├─┬ gm@1.23.0 
  │ └─┬ cross-spawn@4.0.0 
  │   ├─┬ lru-cache@4.0.1 
  │   │ ├── pseudomap@1.0.2 
  │   │ └── yallist@2.0.0 
  │   └─┬ which@1.2.10 
  │     └── isexe@1.1.2 
  ├─┬ jade@1.11.0
  │ └─┬ uglify-js@2.7.0
  │   └─┬ yargs@3.10.0
  │     └─┬ cliui@2.1.0
  │       └─┬ center-align@0.1.3
  │         └─┬ align-text@0.1.4
  │           └─┬ kind-of@3.0.4 
  │             └── is-buffer@1.1.4 
  ├─┬ markdown-serve@0.3.2
  │ └── marked@0.3.6 
  ├─┬ request@2.74.0
  │ └─┬ http-signature@1.1.1
  │   └── sshpk@1.9.2 
  └─┬ swagger-express-mw@0.6.0
    └─┬ swagger-node-runner@0.6.16
      ├── multer@1.2.0 
      └─┬ sway@0.6.0
        └─┬ z-schema@3.17.0
          └── lodash.get@4.4.1 

[root@root local]# stf doctor
/usr/local/node/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /usr/local/node/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/node/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/node/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/node/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/node/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/node/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/node/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/node/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/node/lib/node_modules/stf/node_modules/zmq/compiled/0.12.12/linux/ia32/zmq.node
    at bindings (/usr/local/node/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/stf/lib/util/doctor.js:5:11)

run the command stf doctor failed....
need help!!!

**Comment by tadesushilgithub** [comment]
Check zmq folder is available inside /usr/local/node/lib/node_modules/stf/node_modules/
if not present run brew install zeromq.

**Comment by yuqlabson** [comment]
@tadesushilgithub  command brew in CentOS does not work!

**Comment by sorccu** [comment]
If you're on Linux, it would be very easy to just use the docker image
which has all the necessary deps.

**Comment by jerry117** [comment]
I have also encountered the same problem.I'm on OSX.how can I  fix it.

**Comment by JcmeLs** [comment]
I'm on Mac OS.I also have this problem.And I rm node_modules but also get this problem....How can i fix it...
