### ISSUE TITLE
support --debug option

### ISSUE THREAD

**Issue by perfectspr** [openstf/stf#401]
I got below error when run stf with --debug option:
```
peter@lab:~/projects/stf$ **node --debug bin/stf local**
Debugger listening on [::]:5858
INF/util:procutil 10693 [*] Forking "/home/peter/projects/stf/lib/cli.js migrate"
Error: listen EADDRINUSE :::5858
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at Agent.Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at net.js:1398:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Root cause is child processes will be started with --debug if the parent was started with --debug and the children will get the same port number as parent's port number. 

Solution:
https://github.com/fastest963/child-process-debug

**Comment by chenhengjie123** [comment]
@perfectspr Have you try this solution?

I tried by changing codes like below:

```
diff --git a/lib/cli.js b/lib/cli.js
index 0af3aff..621ba7e 100644
--- a/lib/cli.js
+++ b/lib/cli.js
@@ -98,7 +98,7 @@ program
       }
     , allowRemote: options.allowRemote
     , fork: function(device, ports) {
-        var fork = require('child_process').fork
+        var fork = require('child-process-debug').fork
         return fork(__filename, [
           'device', device.id
         , '--provider', options.name
diff --git a/lib/util/procutil.js b/lib/util/procutil.js
index 25421f1..c1cea95 100644
--- a/lib/util/procutil.js
+++ b/lib/util/procutil.js
@@ -1,5 +1,5 @@
 var util = require('util')
-var cp = require('child_process')
+var cpd = require('child-process-debug')

 var Promise = require('bluebird')

@@ -23,7 +23,7 @@ module.exports.fork = function(filename, args) {
   log.info('Forking "%s %s"', filename, args.join(' '))

   var resolver = Promise.defer()
-  var proc = cp.fork.apply(cp, arguments)
+  var proc = cpd.fork.apply(cpd, arguments)

   function sigintListener() {
     proc.kill('SIGINT')
diff --git a/package.json b/package.json
index f901fba..e2f241f 100644
--- a/package.json
+++ b/package.json
@@ -143,7 +143,8 @@
     "then-jade": "^2.4.1",
     "url-loader": "^0.5.7",
     "webpack": "^1.12.11",
-    "webpack-dev-server": "^1.14.1"
+    "webpack-dev-server": "^1.14.1",
+    "child-process-debug": "^0.0.7"
   },
   "engineStrict": true,
   "engines": {
```

However, when using `node --debug bin/stf local` command, messages like below occurs:

```
Debugger listening on [::]:5858
INF/util:procutil 3168 [*] Forking "/Users/chenhengjie/Projects/ppmoney/tools/stf/lib/cli.js migrate"
Debugger listening on [::]:5859

  error: unknown option `--debug'


/Users/chenhengjie/Projects/ppmoney/tools/stf/node_modules/.2.11.0@bluebird/js/main/promise.js:680
            throw e;
            ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/Users/chenhengjie/Projects/ppmoney/tools/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```
