### ISSUE TITLE
Running stf local throws Unhandled 'error' Error: listen EADDRINUSE :::7100

### ISSUE THREAD

**Issue by jeevaeastpoint** [openstf/stf#414]
```
INF/poorxy 25327 [*] Listening on port 7100
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::7100
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at module.exports (/Users/jeeva/stf/lib/units/poorxy/index.js:67:10)
    at Command.<anonymous> (/Users/jeeva/stf/lib/cli.js:802:30)
    at Command.listener (/Users/jeeva/stf/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/Users/jeeva/stf/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/jeeva/stf/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/jeeva/stf/lib/cli.js:1446:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
FTL/cli:local 25312 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/Users/jeeva/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```
I have tried to build the project locally and getting an error message: I am on Mac.

ERROR in ./bower_components/angular-ladda/src/angular-ladda.js
Module not found: Error: Cannot resolve module 'ladda' in /Users/jeeva/stf/bower_components/angular-ladda/src
 @ ./bower_components/angular-ladda/src/angular-ladda.js 13:4-41

Any suggestion .... 

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* Are you using `stf local` or a [full deployment](doc/DEPLOYMENT.md): 
* Version used (git hash or `stf -V`): 
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version: 
* If there was a problem with a specific device, run `adb devices -l` and paste the relevant row here:

**Comment by sorccu** [comment]
It says what the error is, you already have something running on port 7100.

**Comment by jeevaeastpoint** [comment]
Thanks found out that Airserver is using port 7100. after that went on launch the application but with an empty screen. In console log i get below errors

"1.99eccb4….chunk.js:84169 Uncaught Error: Cannot find module "ladda"webpackMissingModule @ 1.99eccb4….chunk.js:84169moduleName @ 1.99eccb4….chunk.js:84169(anonymous function) @ 1.99eccb4….chunk.js:84177__webpack_require__ @ commons.entry.js:51(anonymous function) @ 1.99eccb4….chunk.js:84145__webpack_require__ @ commons.entry.js:51(anonymous function) @ 1.99eccb4….chunk.js:84085__webpack_require__ @ commons.entry.js:51(anonymous function) @ 1.99eccb4….chunk.js:84069__webpack_require__ @ commons.entry.js:51(anonymous function) @ 1.99eccb4….chunk.js:82937__webpack_require__ @ commons.entry.js:51(anonymous function) @ app.entry.js:17webpackJsonpCallback @ commons.entry.js:19(anonymous function) @ 1.99eccb4….chunk.js:1
2016-09-04 12:58:34.266 1.99eccb4….chunk.js:73 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=app
    at http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:73:13
    at http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:2087:18
    at ensure (http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:2011:39)
    at module (http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:2085:15)
    at http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:4622:23
    at forEach (http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:326:21)
    at loadModules (http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:4606:6)
    at createInjector (http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:4528:20)
    at doBootstrap (http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:1763:21)
    at bootstrap (http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:1784:13)
    at angularInit (http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:1669:6)
    at http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:31768:6
    at trigger (http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:3212:8)
    at defaultHandlerWrapper (http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:3502:12)
    at eventHandler (http://localhost:7100/static/app/build/1.99eccb444e4fce9c089d.chunk.js:3490:10)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=app&p1=Error%3A%20%…A7100%2Fstatic%2Fapp%2Fbuild%2F1.99eccb444e4fce9c089d.chunk.js%3A3490%3A10)"
