### ISSUE TITLE
HUAWEI G730-U00 does not work

### ISSUE THREAD

**Issue by jonqchk** [openstf/stf#429]
Got minicap failure when connecting HUAWEI G730-U00, may be similar with #404 :

INF/util:datautil 42021 [*] Device database does not have an entry for "IJVKTSDQQGTOJVQ4" (model " G730-U00"/"G730-U00"). This is not an error, it only means that we don't have data for it yet.
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] Setting frame producer projection to 645x849
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] Requesting frame producer to start
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] Launching screen service
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] minicap says: "PID: 14659"
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] minicap says: "INFO: Using projection 540x960@478x849/0"
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:239) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:242) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:249) Creating virtual display"
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:255) Creating CPU consumer"
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] Connecting to minicap service
IMP/device:plugins:connect 42027 [IJVKTSDQQGTOJVQ4] Remote Connect Started for device "IJVKTSDQQGTOJVQ4" at "localhost:7401"
WRN/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] Disconnecting from minicap service
INF/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] Stopping minicap service
FTL/device:plugins:screen:stream 42027 [IJVKTSDQQGTOJVQ4] Frame producer had an error FailError: Failure: 'closed'
    at /usr/local/lib/node_modules/stf/node_modules/adbkit/lib/adb/parser.js:228:29
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FTL/util:lifecycle 42027 [IJVKTSDQQGTOJVQ4] Shutting down due to fatal error
INF/provider 42018 [*] Cleaning up device worker "IJVKTSDQQGTOJVQ4"
ERR/provider 42018 [*] Device worker "IJVKTSDQQGTOJVQ4" died with code 1
INF/provider 42018 [*] Restarting device worker   ##"IJVKTSDQQGTOJVQ4"

<img width="1119" alt="screen shot 2016-09-20 at 11 44 17 am" src="https://cloud.githubusercontent.com/assets/6373277/18656892/c3a3aa5a-7f27-11e6-9628-aab4cfeb9219.png">

**Comment by sorccu** [comment]
Thanks for the report and log output.

I can't find a place to buy a G730-U00, so I'd say the chances of this issue getting looked into are very slim. However, perhaps fixing some other Huawei device that's easier to buy would fix this one as well.

**Comment by jonqchk** [comment]
Thanks for the quick response. HUAWEI uses its own CPU(named Haisi), not sure whether it is relevant to the minicap issue. I think it is a appropriate way to do so. if you fix some other Huawei device for similar issue, please update comment on this ticket, i will keep monitoring and then try if it also works

**Comment by sorccu** [comment]
Let's keep this issue open so that it's easier to find if someone else searches for it.

**Comment by jonqchk** [comment]
ok, actually i close it by mistake. I just thought "Close and comment" means close the page. :0

**Comment by codeskyblue** [comment]
@sorccu I know some device not working well with minicap. So is this solution OK. Try to find another screenshot method if minicap not supported.
But as far as I know, the default android tool screenshot is too slow, do you know some other tools that can make screenshot a litter faster? Thanks any way.

**Comment by sorccu** [comment]
I have an idea that will probably make most devices work. But no time to do it right now.

**Comment by codeskyblue** [comment]
Maybe I can do it, just need ideas.

**Comment by codeskyblue** [comment]
@sorccu I have tried with servel methods.

- screencap   about 1.0s
- uiautomator screenshot about 0.7s
- use the outside camera, can reach 30fps, but the image quality is very low.

**Comment by codeskyblue** [comment]
@sorccu waiting your ideas....

**Comment by sorccu** [comment]
I'm not 100% decided if I would want to open source that method or not yet.

Perhaps you could try `screenrecord -o raw-frames`.

**Comment by codeskyblue** [comment]
Maybe your idea is like <https://chrome.google.com/webstore/detail/vysor/gidgenkbbabolejbgbpnhbimgjbffefm> I guess.

**Comment by sorccu** [comment]
Perhaps it is similar, I have not looked at Vysor's source code. But we are aware of Vysor, yes.

**Comment by codeskyblue** [comment]
```java
try {
    Method screenshot = Surface.class.getMethod("screenshot", new Class[] { int.class,
                        int.class });
    screenshot.setAccessible(true);
    mScreenBitmap = (Bitmap) screenshot.invoke(Surface.class.newInstance(),
        new Object[]{(int) dims[0], (int) dims[1]});
} catch (Exception e) {
    e.printStackTrace();
}
```

googled out this method, recorded here. But I have to say I really do not like java.

**Comment by sorccu** [comment]
Sorry can we start a new issue about this? This issue is for this specific device only, it's kind of getting mixed with many other things.

**Comment by chanchifan** [comment]
what is the device's system version? MT6582 or MT6592 CPU with 4.2.2 is always failed.

**Comment by sorccu** [comment]
@jonqchk I can see from your log that your device was running Android 4.2. We've just pushed a fix for many 4.2 devices in STF 2.3.0. Please try it and report back if it works.
