### ISSUE TITLE
ZUK Z1 fails on minitouch

### ISSUE THREAD

**Issue by sorccu** [openstf/stf#436]
Moved from #407:

```
INF/device:plugins:touch 14966 [c806b880] Touch origin is top left
INF/device:plugins:touch 14966 [c806b880] Requesting touch consumer to start
INF/device:plugins:touch 14966 [c806b880] Launching screen service
INF/device:plugins:touch 14966 [c806b880] Connecting to minitouch service
INF/device:plugins:touch 14966 [c806b880] minitouch says: "/system/bin/sh: /data/local/tmp/minitouch: can't execute: Permission denied"
WRN/device:plugins:touch 14966 [c806b880] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 14966 [c806b880] Disconnecting from minitouch service
INF/device:plugins:touch 14966 [c806b880] Stopping minitouch service
INF/device:plugins:touch 14966 [c806b880] Launching screen service
INF/device:plugins:touch 14966 [c806b880] Connecting to minitouch service
INF/device:plugins:touch 14966 [c806b880] minitouch says: "/system/bin/sh: /data/local/tmp/minitouch: can't execute: Permission denied"
WRN/device:plugins:touch 14966 [c806b880] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 14966 [c806b880] Disconnecting from minitouch service
INF/device:plugins:touch 14966 [c806b880] Stopping minitouch service
INF/device:plugins:touch 14966 [c806b880] Launching screen service
INF/device:plugins:touch 14966 [c806b880] Connecting to minitouch service
INF/device:plugins:touch 14966 [c806b880] minitouch says: "/system/bin/sh: /data/local/tmp/minitouch: can't execute: Permission denied"
INF/device:support:push 14990 [LE67A06180224872] Sending output to "tcp://10.241.54.16:7270"
INF/device 14990 [LE67A06180224872] Preparing device
WRN/device:plugins:touch 14966 [c806b880] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 14966 [c806b880] Disconnecting from minitouch service
INF/device:plugins:touch 14966 [c806b880] Stopping minitouch service
INF/device:plugins:touch 14966 [c806b880] Launching screen service
INF/device:plugins:touch 14966 [c806b880] Connecting to minitouch service
INF/device:plugins:touch 14966 [c806b880] minitouch says: "/system/bin/sh: /data/local/tmp/minitouch: can't execute: Permission denied"
WRN/device:plugins:touch 14966 [c806b880] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 14966 [c806b880] Disconnecting from minitouch service
WRN/device:plugins:touch 14966 [c806b880] Will not apply desired state due to too many failures
INF/device:plugins:touch 14966 [c806b880] Stopping minitouch service
FTL/device 14966 [c806b880] Setup had an error Error: Failed more than 3 times in 10000ms
    at TouchConsumer._failLimitExceeded (/app/lib/units/device/plugins/touch/index.js:230:26)
    at FailCounter.emit (/app/node_modules/eventemitter3/index.js:117:35)
    at FailCounter.inc (/app/lib/util/failcounter.js:29:10)
    at TouchConsumer._outputEnded (/app/lib/units/device/plugins/touch/index.js:223:24)
    at RiskyStream.emit (/app/node_modules/eventemitter3/index.js:115:35)
    at RiskyStream.<anonymous> (/app/lib/util/riskystream.js:14:12)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
From previous event:
    at startConsumer (/app/lib/units/device/plugins/touch/index.js:511:14)
    at /app/lib/units/device/plugins/touch/index.js:526:12
    at SerialSyrup.ParallelSyrup.invoke (/app/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /app/node_modules/stf-syrup/lib/serial.js:43:33
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
FTL/util:lifecycle 14966 [c806b880] Shutting down due to fatal error
INF/provider 1 [*] Cleaning up device worker "c806b880"
ERR/provider 1 [*] Device worker "c806b880" died with code 1
```

**Comment by sorccu** [comment]
I actually happen to have a ZUK Z1 and can confirm that this issue happens. It seems like the system does not allow file in /data/local/tmp to be executable, making it potentially impossible to place binaries there.

```
shell@k9:/data/local/tmp $ touch a
shell@k9:/data/local/tmp $ ls -Z a
-rw-rw-rw- shell    shell             u:object_r:shell_data_file:s0 a
shell@k9:/data/local/tmp $ chmod 0777 a
shell@k9:/data/local/tmp $ ls -Z a
-rw-rw-rw- shell    shell             u:object_r:shell_data_file:s0 a
```

If so, not sure if there's an easy fix.

**Comment by xiaweixing** [comment]
I also tried to chmod via adb, also no effect at all :(
Seems this phone is kind of SPECIAL...

**Comment by dkw72n** [comment]
We manage to solve this issue by turning minicap/minitouch into dynamic libraries, and loading them from Java. Jars need no +x permission to be executed. An extra benefit is that we dont have to deal with the PIE problem.

**Comment by sorccu** [comment]
Yeah that's one option. So do you have a rooted device or did you use the `app_process` trick?

**Comment by dkw72n** [comment]
No need to root, but have to create an extra shell script to make it run, extractly how /system/bin/pm and other java-based cmdline tools work. Is this the app_process trick you mentioned?

**Comment by sorccu** [comment]
Yeah, that's the one.

**Comment by liuang68** [comment]
@dkw72n hello，when i use zuk z1 and adb devices, it shows'no permission',i want to know how to solove this problem and what is the shell script you mentioned

**Comment by sorccu** [comment]
I'm working on a workaround for this but no promises on when it'll be ready.

**Comment by liuang68** [comment]
@sorccu thanks,i'm trying```

**Comment by dkw72n** [comment]
@liuang68 
1. build a JNI version  `minicap/minitouch`
2. make a java CLI wrapper that loads the JNI lib which was built in step 1

To run the java CLI wrapper, take a look at https://github.com/openstf/RotationWatcher.apk
the script is just those commands bundle together

**Comment by dkw72n** [comment]
This issue is gone on my ZUK z2 plus after an official update to `Android N`.

also i have theory theoretical work-around for the `Android M` Zuk, with no code modification needed:
simply change every `/data/local/tmp` to `/data/data/com.android.shell`, too shame i can't verify that.

**Comment by sorccu** [comment]
Hmm that's a good idea, I had been thinking about installing a separate app for that (or possibly reusing STFService but it may possibly not have worked due to dependency ordering, not 100% sure).

**Comment by sorccu** [comment]
I can verify that the change does work on my Z1.

**Comment by sorccu** [comment]
This is now fixed in master. It tries to install to `/data/local/tmp` first, but if the installed file doesn't have the executable bits after installation, it uses `/data/data/com.android.shell` instead. Works on my Z1.
