### ISSUE TITLE
Android 7.1 support

### ISSUE THREAD

**Issue by sorccu** [openstf/stf#448]
Tested STF with the new Android 7.1 Developer Preview (NPF10C) on a Nexus 5X and can confirm that it does NOT work. The issues are:

- [x] `adb shell pm uninstall jp.co.cyberagent.stf` returns unexpected output (see below). Either wait it out (since I do believe it's a bug in the preview) or work with the new, buggy output.
- [x] `minicap` needs to be recompiled for API 25, simply copying the libs does not work this time as the symbols have changed. However, the AOSP source does not seem to be available yet. Have to wait till it's available.

Here's the weird uninstall output:

```

Exception occurred while dumping:
java.lang.IllegalArgumentException: Unknown package: jp.co.cyberagent.stf
	at com.android.server.pm.Settings.isOrphaned(Settings.java:4134)
	at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:18066)
	at com.android.server.pm.PackageManagerService.deletePackage(PackageManagerService.java:15483)
	at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:888)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:765)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:113)
	at android.os.ShellCommand.exec(ShellCommand.java:94)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:18324)
	at android.os.Binder.shellCommand(Binder.java:468)
	at android.os.Binder.onTransact(Binder.java:367)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2387)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3019)
	at android.os.Binder.execTransact(Binder.java:565)
```

**Comment by sorccu** [comment]
Had to do some horrible hacks but it works now. Just released 2.1.0 with 7.1 Developer Preview support.
