### ISSUE TITLE
run stf docker images error

### ISSUE THREAD

**Issue by bgcelite** [openstf/stf#454]
i pull openstf.stf docker images to local computer,
have a error when i  run stf local command

Unhandled rejection Error: spawn adb ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by sorccu** [comment]
You're not using it correctly. It's meant to be combined with other images. See the deployment docs, there are links in the README.
