### ISSUE TITLE
An error occurred while starting stf

### ISSUE THREAD

**Issue by ythinker** [openstf/stf#458]
```
➜  / stf local —allow-remote                         
INF/util:procutil 8185 [*] Forking "/usr/local/lib/node_modules/.stf_npminstall/node_modules/.2.1.0@stf/lib/cli.js migrate"
INF/db 8186 [*] Connecting to 127.0.0.1:28015
INF/db 8186 [*] Unable to connect to 127.0.0.1:28015
FTL/db 8186 [*] No hosts left to try
FTL/util:lifecycle 8186 [*] Shutting down due to fatal error

/usr/local/lib/node_modules/.stf_npminstall/node_modules/.2.11.0@bluebird/js/main/promise.js:680
            throw e;
            ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/.stf_npminstall/node_modules/.2.1.0@stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

Is this what is the problem ?

**Comment by sorccu** [comment]
You don't have rethinkdb running. Read the README.

**Comment by ythinker** [comment]
@sorccu    Rethinkdb has started successfully
```

➜  / sudo rethinkdb --port-offset 1                  
Running rethinkdb 2.3.5 (CLANG 7.3.0 (clang-703.0.31))...
Running on Darwin 16.0.0 x86_64
Loading data from directory /rethinkdb_data
warn: Cache size does not leave much memory for server and query overhead (available memory: 595 MB).
warn: Cache size is very low and may impact performance.
Listening for intracluster connections on port 29016
Listening for client driver connections on port 28016
Listening for administrative HTTP connections on port 8081
Listening on cluster addresses: 127.0.0.1, ::1
Listening on driver addresses: 127.0.0.1, ::1
Listening on http addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "ACA80F71_ipt_aol_com_sg2" cce7c577-0f19-454e-b
```

**Comment by sorccu** [comment]
Why did you use the port offset flag? Now everything's running on the wrong
port. You can see from the log messages that the ports are different.

**Comment by ythinker** [comment]
@sorccu  Thank you, i can
