### ISSUE TITLE
[Screen shot] The image is broken when use screenshot 

### ISSUE THREAD

**Issue by onlinesen** [openstf/stf#460]
![imagebroken](https://cloud.githubusercontent.com/assets/5802333/20028055/f5e0ba5e-a361-11e6-98bc-b68cf224cb71.png)
![shootscreen](https://cloud.githubusercontent.com/assets/5802333/20028056/f9d903b4-a361-11e6-9d6f-3f4103834dfa.png)

android@ubuntu:~$ stf doctor
INF/util:doctor 6287 [*] OS Arch: x64
INF/util:doctor 6287 [*] OS Platform: linux
INF/util:doctor 6287 [*] OS Platform: 3.13.0-101-generic
INF/util:doctor 6287 [*] Using Node 5.0.0
INF/util:doctor 6287 [*] Using RethinkDB client 2.3.3
INF/util:doctor 6287 [*] Using ZeroMQ 4.1.5
INF/util:doctor 6287 [*] Local ADB 1.0.31
INF/util:doctor 6287 [*] ProtoBuf 3.1.0
ERR/util:doctor 6287 [*] Current ProtoBuf version is not supported, it has to be ~2
INF/util:doctor 6287 [*] GraphicsMagick 1.3.25
INF/util:doctor 6287 [*] Local RethinkDB server 2.3.5~0precise
/usr/local/lib/node_modules/.stf_npminstall/node_modules/.5.3.0@semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 2.3.5~0precise
    at new SemVer (/usr/local/lib/node_modules/.stf_npminstall/node_modules/.5.3.0@semver/semver.js:293:11)
    at Range.test (/usr/local/lib/node_modules/.stf_npminstall/node_modules/.5.3.0@semver/semver.js:1036:15)
    at Function.satisfies (/usr/local/lib/node_modules/.stf_npminstall/node_modules/.5.3.0@semver/semver.js:1085:16)
    at unsupportedVersion (/usr/local/lib/node_modules/.stf_npminstall/node_modules/.2.1.0@stf/lib/util/doctor.js:13:15)
    at /usr/local/lib/node_modules/.stf_npminstall/node_modules/.2.1.0@stf/lib/util/doctor.js:95:7
    at /usr/local/lib/node_modules/.stf_npminstall/node_modules/.2.1.0@stf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
android@ubuntu:~$

**Comment by xiaobeiying** [comment]
@onlinesen  Hello, I also have this problem. Do you have resolved it?

**Comment by onlinesen** [comment]
No, the issue is not resolved. 

 

发件人: xiaobeiying [mailto:notifications@github.com] 
发送时间: 2017年2月22日 10:53
收件人: openstf/stf
抄送: onlinesen; Mention
主题: Re: [openstf/stf] [Screen shot] The image is broken when use screenshot (#460)

 

@onlinesen <https://github.com/onlinesen>  Hello, I also have this problem. Do you have resolved it?

**Comment by kennethzhu** [comment]
When running 'stf doctor', it shows
 _ERR/util:doctor 11404 [*] Current ProtoBuf version is not supported, it has to be ~2_
But the _protoc --vesion_ prints 
_libprotoc 3.2.0_
Maybe we should use the proper protobuf version to make the screenshot feature work.

**Comment by sorccu** [comment]
No it's not related. It's fine

**Comment by lukzeg** [comment]
Mostly looks like the stream which we pass to store for image storage:
lib/units/device/support/storage.js 
is bad.
The body looks:
{"stats":{"bytesTransferred":0},"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{"end":[null,null]},"_eventsCount":3,"_writableState":{"objectMode":false,"highWaterMark":16384,"needDrain":false,"ending":false,"ended":false,"finished":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"allowHalfOpen":true,"_transformState":{"needTransform":false,"transforming":false,"writecb":null,"writechunk":null,"writeencoding":null}}

but the tmp stored data located on machine in tmp folder looks okay. So that exclude issue with protobuf.

**Comment by lukzeg** [comment]
I missed one thing. My bad. The screenshot will work after we use this import.
var gm = require('gm').subClass({imageMagick: true})
I created pull request with my changes, which fix described over here issue.
https://github.com/openstf/stf/pull/738
Those changes works for me and I have that it will work for you @onlinesen, @xiaobeiying , @kennethzhu  too. I'm crossing my fingers :) .

**Comment by lukzeg** [comment]
I missed, my changes need to have installed imagemagick on stf server machine

**Comment by sorccu** [comment]
It turns out that at least the latest issue was caused by a self-compiled GraphicsMagick, which did not include JPEG support by default. Others having this issue, please run `gm convert -list format` and check if JPEG is there. Or try actually converting an image with `gm convert`.

**Comment by Otiel** [comment]
I have the same issue as reported on the first post of this issue, even though GraphicsMagick seems correctly installed:

    $ gm convert -list format
       Format L  Mode  Description
    --------------------------------------------------------------------------------
    ...
         JPEG P  rw-  Joint Photographic Experts Group JFIF format (IJG JPEG 62)
          JPG P  rw-  Joint Photographic Experts Group JFIF format (IJG JPEG 62)
    ...

Running `gm convert image.jpg result.png` works fine.

Is there anything else I could check? Where are the screenshot supposed to be stored?
