### ISSUE TITLE
I Cant use My ZenFone 2 Laser on STF

### ISSUE THREAD

**Issue by luizlohn** [openstf/stf#463]
I have a Asus ZenFone 2 Laser and i need connect to STF, but when i try this i see this error:

INF/device:resources:service 47275 [FBAZB601V860] Running version check
INF/device:resources:service 47275 [FBAZB601V860] STFService up to date
INF/device:plugins:service 47275 [FBAZB601V860] Launching agent
INF/provider 47234 [*] Providing 0 of 1 device(s); waiting for "FBAZB601V860"
INF/device:plugins:service 47275 [FBAZB601V860] Agent says: "Listening on port 1090"
INF/device:plugins:service 47275 [FBAZB601V860] Launching service
INF/device:plugins:service 47275 [FBAZB601V860] Agent says: "InputClient started"
FTL/device 47275 [FBAZB601V860] Setup had an error Error: Service had an error: "Error: Not found; no service started."
    at /usr/local/lib/node_modules/stf/lib/units/device/plugins/service.js:101:23
From previous event:
    at /usr/local/lib/node_modules/stf/lib/units/device/plugins/service.js:76:14
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
FTL/util:lifecycle 47275 [FBAZB601V860] Shutting down due to fatal error
INF/provider 47234 [*] Cleaning up device worker "FBAZB601V860"
ERR/provider 47234 [*] Device worker "FBAZB601V860" died with code 1
INF/provider 47234 [*] Restarting device worker "FBAZB601V860"
INF/device:support:push 47287 [FBAZB601V860] Sending output to "tcp://127.0.0.1:7116"
INF/device 47287 [FBAZB601V860] Preparing device
INF/device:support:sub 47287 [FBAZB601V860] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 47287 [FBAZB601V860] Subscribing to permanent channel "*ALL"
INF/device:support:properties 47287 [FBAZB601V860] Loading properties
INF/device:support:abi 47287 [FBAZB601V860] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
INF/device:resources:service 47287 [FBAZB601V860] Checking whether we need to install STFService
INF/device:resources:service 47287 [FBAZB601V860] Running version check
INF/device:resources:service 47287 [FBAZB601V860] STFService up to date
INF/device:plugins:service 47287 [FBAZB601V860] Launching agent
INF/device:plugins:service 47287 [FBAZB601V860] Launching service
INF/device:plugins:service 47287 [FBAZB601V860] Agent says: "Listening on port 1090"
INF/device:plugins:service 47287 [FBAZB601V860] Agent says: "InputClient started"
FTL/device 47287 [FBAZB601V860] Setup had an error Error: Service had an error: "Error: Not found; no service started."
    at /usr/local/lib/node_modules/stf/lib/units/device/plugins/service.js:101:23
From previous event:
    at /usr/local/lib/node_modules/stf/lib/units/device/plugins/service.js:76:14
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
FTL/util:lifecycle 47287 [FBAZB601V860] Shutting down due to fatal error
INF/provider 47234 [*] Cleaning up device worker "FBAZB601V860"
ERR/provider 47234 [*] Device worker "FBAZB601V860" died with code 1
INF/provider 47234 [*] Restarting device worker "FBAZB601V860"
INF/device:support:push 47299 [FBAZB601V860] Sending output to "tcp://127.0.0.1:7116"
INF/device 47299 [FBAZB601V860] Preparing device
INF/device:support:sub 47299 [FBAZB601V860] Receiving input from "tcp://127.0.0.1:7114"

Thanks

**Comment by luizlohn** [comment]
`INF/device:resources:service 47275 [FBAZB601V860] Running version check
INF/device:resources:service 47275 [FBAZB601V860] STFService up to date
INF/device:plugins:service 47275 [FBAZB601V860] Launching agent
INF/provider 47234 [*] Providing 0 of 1 device(s); waiting for "FBAZB601V860"
INF/device:plugins:service 47275 [FBAZB601V860] Agent says: "Listening on port 1090"
INF/device:plugins:service 47275 [FBAZB601V860] Launching service
INF/device:plugins:service 47275 [FBAZB601V860] Agent says: "InputClient started"
FTL/device 47275 [FBAZB601V860] Setup had an error Error: Service had an error: "Error: Not found; no service started."
    at /usr/local/lib/node_modules/stf/lib/units/device/plugins/service.js:101:23
From previous event:
    at /usr/local/lib/node_modules/stf/lib/units/device/plugins/service.js:76:14
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
FTL/util:lifecycle 47275 [FBAZB601V860] Shutting down due to fatal error
INF/provider 47234 [*] Cleaning up device worker "FBAZB601V860"
ERR/provider 47234 [*] Device worker "FBAZB601V860" died with code 1
INF/provider 47234 [*] Restarting device worker "FBAZB601V860"
INF/device:support:push 47287 [FBAZB601V860] Sending output to "tcp://127.0.0.1:7116"
INF/device 47287 [FBAZB601V860] Preparing device
INF/device:support:sub 47287 [FBAZB601V860] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 47287 [FBAZB601V860] Subscribing to permanent channel "*ALL"
INF/device:support:properties 47287 [FBAZB601V860] Loading properties
INF/device:support:abi 47287 [FBAZB601V860] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
INF/device:resources:service 47287 [FBAZB601V860] Checking whether we need to install STFService
INF/device:resources:service 47287 [FBAZB601V860] Running version check
INF/device:resources:service 47287 [FBAZB601V860] STFService up to date
INF/device:plugins:service 47287 [FBAZB601V860] Launching agent
INF/device:plugins:service 47287 [FBAZB601V860] Launching service
INF/device:plugins:service 47287 [FBAZB601V860] Agent says: "Listening on port 1090"
INF/device:plugins:service 47287 [FBAZB601V860] Agent says: "InputClient started"
FTL/device 47287 [FBAZB601V860] Setup had an error Error: Service had an error: "Error: Not found; no service started."
    at /usr/local/lib/node_modules/stf/lib/units/device/plugins/service.js:101:23
From previous event:
    at /usr/local/lib/node_modules/stf/lib/units/device/plugins/service.js:76:14
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
FTL/util:lifecycle 47287 [FBAZB601V860] Shutting down due to fatal error
INF/provider 47234 [*] Cleaning up device worker "FBAZB601V860"
ERR/provider 47234 [*] Device worker "FBAZB601V860" died with code 1
INF/provider 47234 [*] Restarting device worker "FBAZB601V860"
INF/device:support:push 47299 [FBAZB601V860] Sending output to "tcp://127.0.0.1:7116"
INF/device 47299 [FBAZB601V860] Preparing device
INF/device:support:sub 47299 [FBAZB601V860] Receiving input from "tcp://127.0.0.1:7114"
`

**Comment by sorccu** [comment]
Please read all of https://github.com/openstf/stf/issues/407 and see if you have a similar setting. Don't forget to post your solution here if you find one!

**Comment by prabintim** [comment]
I am having similar issue as well. Did you find out a solution?

**Comment by sorccu** [comment]
Did you go through all the settings on your device to try to find something similar to #407?

**Comment by prabintim** [comment]
It's working now. I force stopped AsusBoost. I will update if I find any other culprits. Thank you.
