### ISSUE TITLE
STFservice can't run in SUMSUNG S6 SM-G9280

### ISSUE THREAD

**Issue by 0x88l** [openstf/stf#465]
STF serivce can't run in SUMSUNG S6. STFservice haven't an ativity,and SUMSUNG OS is forbidden to this service.
The adb devicelist  is this:
0216026890651005       device product:zenltezc model:SM_G9280 device:zenltechn

errlog:
2016-11-09 11:47:30 INF/device:plugins:touch 30422 [3067e654] Launching screen service
2016-11-09 11:47:30 INF/device:plugins:touch 30422 [3067e654] Connecting to minitouch service
2016-11-09 11:47:30 INF/device:plugins:service 30437 [0216026890651005] Launching service
2016-11-09 11:47:30 INF/device:plugins:service 30437 [0216026890651005] Agent says: "Listening on @stfagent"
2016-11-09 11:47:30 INF/device:plugins:service 30437 [0216026890651005] Agent says: "InputClient started"
2016-11-09 11:47:31 INF/device:plugins:touch 30422 [3067e654] minitouch says: "Note: device /dev/input/mouse0 is not supported by libevdev"
2016-11-09 11:47:31 FTL/device 30437 [0216026890651005] Setup had an error Error: Service had an error: "Error: Not found; no service started."
    at /var/stf/lib/units/device/plugins/service.js:101:23
From previous event:
    at /var/stf/lib/units/device/plugins/service.js:76:14
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
2016-11-09 11:47:31 FTL/util:lifecycle 30437 [0216026890651005] Shutting down due to fatal error
2016-11-09 11:47:31 INF/provider 28442 [*] Cleaning up device worker "0216026890651005"

**Comment by sorccu** [comment]
Please check #407 and see if you have a similar setting. Don't forget to post your solution here if you find one!

**Comment by sorccu** [comment]
Our S6 was working fine though, so it may just be that particular model, or perhaps a software update.

**Comment by 0x88l** [comment]
I have upload the OS  and open 'OEM lock' where at Develop mode. But I don't know why or whether is this way to make it work.

**Comment by willysys** [comment]
Hello, menu key can work in your sumsung device ?
Menu key cannot work in sumsung  s6 edge SM-G9250.
