### ISSUE TITLE
Galaxy note 4 frequently disconnects when fiddling with UI

### ISSUE THREAD

**Issue by prabintim** [openstf/stf#472]
Model: SAMSUNG-SM-N910A
OS	Android
Version	5.1.1
SDK	22
ABI	armeabi-v7a
Health	Good
Connected	Yes
Airplane Mode	No
Using Fallback	No
Roaming	No
Type	WIFI
Density	XXXHDPI
FPS	60
Browser - Chrome
OSX - El Capitan
----
After 5-10 seconds of using the UI, it disconnects. Reconnection works but the issue just loops.
Remaining idle, it does not disconnect and is fine.
Thank you.

**Comment by prabintim** [comment]
Here is the log:
```
INF/device:plugins:screen:stream 19449 [1627d05a] minicap says: "INFO: (jni/minicap/minicap.cpp:444) New client connection"
WRN/device:plugins:screen:stream 19449 [1627d05a] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 19449 [1627d05a] Disconnecting from minicap service
FTL/device:plugins:screen:stream 19449 [1627d05a] Frame producer had an error Error: Failed more than 3 times in 10000ms
    at FrameProducer._failLimitExceeded (/Users/my.username/.nvm/versions/node/v5.0.0/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:220:26)
    at FailCounter.emit (/Users/my.username/.nvm/versions/node/v5.0.0/lib/node_modules/stf/node_modules/eventemitter3/index.js:73:35)
    at FailCounter.inc (/Users/my.username/.nvm/versions/node/v5.0.0/lib/node_modules/stf/lib/util/failcounter.js:29:10)
    at FrameProducer._outputEnded (/Users/my.username/.nvm/versions/node/v5.0.0/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:213:24)
    at RiskyStream.emit (/Users/my.username/.nvm/versions/node/v5.0.0/lib/node_modules/stf/node_modules/eventemitter3/index.js:71:35)
    at RiskyStream.<anonymous> (/Users/my.username/.nvm/versions/node/v5.0.0/lib/node_modules/stf/lib/util/riskystream.js:14:12)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
FTL/util:lifecycle 19449 [1627d05a] Shutting down due to fatal error
INF/provider 13279 [*] Cleaning up device worker "1627d05a"
ERR/provider 13279 [*] Device worker "1627d05a" died with code 1
INF/provider 13279 [*] Restarting device worker "1627d05a"
```

**Comment by sorccu** [comment]
And you're sure you're using the latest stf?

Can you check what the version field in `node_modules/minicap-prebuilt/package.json` says?

**Comment by prabintim** [comment]
You are right. I was wayyyy off the latest version.
