### ISSUE TITLE
stf local failed 

### ISSUE THREAD

**Issue by tobecrazy** [openstf/stf#475]
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/7.1.0/darwin/x64/zmq.node
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
FTL/cli:local 11980 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
INF/cli:local 11980 [*] Shutting down all child processes

**Comment by sorccu** [comment]
rm -rf node_modules && npm install

**Comment by tobecrazy** [comment]
Thanks！ The issue due to I uninstall python 2!
