### ISSUE TITLE
Invalid csrf token error when login stf web page

### ISSUE THREAD

**Issue by gupiao** [openstf/stf#496]
**What is the issue or idea you have?**
invalid csrf token error when login stf web page (it works good until I update stf to latest version)

**Please provide the steps to reproduce the issue.**
run rethinkdb
run stf 
run stf local --public-ip 192.168.1.196
login to webpage by http://192.168.1.196:7100
input user name and email, click login

**What is the expected behavior?**
should login succesfully

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
ForbiddenError: invalid csrf token
    at csrf (/usr/lib/node_modules/stf/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:312:13)
    at /usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:271:10)
    at /usr/lib/node_modules/stf/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/usr/lib/node_modules/stf/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/usr/lib/node_modules/stf/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/usr/lib/node_modules/stf/node_modules/body-parser/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Please run `stf doctor` and paste the output here.**
alex@alex-All-Series:~$ stf doctor
INF/util:doctor 1111 [*] OS Arch: x64
INF/util:doctor 1111 [*] OS Platform: linux
INF/util:doctor 1111 [*] OS Platform: 4.4.0-47-generic
INF/util:doctor 1111 [*] Using Node 4.5.0
INF/util:doctor 1111 [*] Using RethinkDB client 2.3.3
INF/util:doctor 1111 [*] Using ZeroMQ 4.1.4
WRN/util:doctor 1111 [*] Executable was not found
INF/util:doctor 1111 [*] Local ADB 1.0.32
INF/util:doctor 1111 [*] Local RethinkDB server 2.3.5~0xenial
/usr/lib/node_modules/stf/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 2.3.5~0xenial
    at new SemVer (/usr/lib/node_modules/stf/node_modules/semver/semver.js:293:11)
    at Range.test (/usr/lib/node_modules/stf/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/usr/lib/node_modules/stf/node_modules/semver/semver.js:1085:16)
    at unsupportedVersion (/usr/lib/node_modules/stf/lib/util/doctor.js:13:15)
    at /usr/lib/node_modules/stf/lib/util/doctor.js:95:7
    at /usr/lib/node_modules/stf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by gabcoyne** [comment]
Any progress/resolution here?

**Comment by sorccu** [comment]
Maybe you have cookies disabled or something.

**Comment by gabcoyne** [comment]
@gupiao I was not using the SESSION SECRET environment variables. Used them and function was restored. I think you can close this one.
