### ISSUE TITLE
STF installation

### ISSUE THREAD

**Issue by madangopal918** [openstf/stf#518]
tiger@ubuntu:/usr/lib/node_modules/stf$ sudo stf local
module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/stf/lib/cli.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I'm running rethinkdb in terminal 1 and trying to run stf local in terminal 2. When i run stf local i'm getting this error. Also i updated node.js  and npm, but still i'm getting this error. Please help.

**Comment by sorccu** [comment]
Most likely you did something wrong and now you have a strange installation. The newest master no longer uses commander (which might explain why it's missing) but you're using old code. Can't help with that, it's your mess.

I would simply reinstall and try again.
