### ISSUE TITLE
EventEmitter memory leak detected

### ISSUE THREAD

**Issue by anaraquelazevedo** [openstf/stf#527]
I´ve been faced an EventEmitter memory leak problem/bug

Error:
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
at Socket.addListener (events.js:239:17)
at Socket.Readable.on (_stream_readable.js:680:33)
at Parser.readBytes (/stf/node_modules/adbkit/lib/adb/parser.js:126:17)
at Parser.readAscii (/stf/node_modules/adbkit/lib/adb/parser.js:89:17)
at /stf/node_modules/adbkit/lib/adb/sync.js:249:29
at Sync._readData (/stf/node_modules/adbkit/lib/adb/sync.js:269:14)
at Sync.pull (/stf/node_modules/adbkit/lib/adb/sync.js:138:17)
at ProcStat.update (/stf/node_modules/adbkit/lib/adb/proc/stat.js:40:33)
at null._repeat (/stf/node_modules/adbkit/lib/adb/proc/stat.js:27:22)
at wrapper [as _onTimeout] (timers.js:275:11)
at Timer.listOnTimeout (timers.js:92:15)
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
at Socket.addListener (events.js:239:17)
at Socket.Readable.on (_stream_readable.js:680:33)
at Parser.readBytes (/stf/node_modules/adbkit/lib/adb/parser.js:126:17)
at Parser.readAscii (/stf/node_modules/adbkit/lib/adb/parser.js:89:17)
at /stf/node_modules/adbkit/lib/adb/sync.js:249:29
at Sync._readData (/stf/node_modules/adbkit/lib/adb/sync.js:269:14)
at Sync.pull (/stf/node_modules/adbkit/lib/adb/sync.js:138:17)
at MemStat.update (/stf/node_modules/adbkit/lib/adb/proc/meminfo.js:52:33)
at null._repeat (/stf/node_modules/adbkit/lib/adb/proc/meminfo.js:39:22)
at wrapper [as _onTimeout] (timers.js:275:11)
at Timer.listOnTimeout (timers.js:92:15)

 After a quick research i figured out that this turns out be a bug in nodejs core documented here:
https://github.com/joyent/node/issues/5108

Does anyone have a workaround for this leak problem?

Thank you all

**Comment by sorccu** [comment]
It's not necessarily a leak. Could just be that whatever you're doing is causing too many events listeners to be added. You get that warning if you have more than 10 listeners added.

**Comment by neeteshking21** [comment]
> It's not necessarily a leak. Could just be that whatever you're doing is causing too many events listeners to be added. You get that warning if you have more than 10 listeners added.

so how can we solve this error if we have more than 10 listeners? @sorccu
