### ISSUE TITLE
Cannot connect my Android with error: TouchConsumer._failLimitExceeded

### ISSUE THREAD

**Issue by wangbaomi** [openstf/stf#53]
Hi,
I'm using STF to control my Android device(it is a "thinclient", Android system, use VGA to display), get this error:

```
INF/device:plugins:touch 17628 [200.200.138.60:5555] Connecting to minitouch service
INF/device:plugins:touch 17628 [200.200.138.60:5555] minitouch says: "Unable to find a suitable touch device"
WRN/device:plugins:touch 17628 [200.200.138.60:5555] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 17628 [200.200.138.60:5555] Disconnecting from minitouch service
WRN/device:plugins:touch 17628 [200.200.138.60:5555] Will not apply desired state due to too many failures
INF/device:plugins:touch 17628 [200.200.138.60:5555] Stopping minitouch service
FTL/device 17628 [200.200.138.60:5555] Setup had an error Error: Failed more than 3 times in 10000ms
    at TouchConsumer._failLimitExceeded (/usr/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:231:26)
    at FailCounter.emit (/usr/lib/node_modules/stf/node_modules/eventemitter3/index.js:73:35)
    at FailCounter.inc (/usr/lib/node_modules/stf/lib/util/failcounter.js:29:10)
    at TouchConsumer._outputEnded (/usr/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:224:24)
    at RiskyStream.emit (/usr/lib/node_modules/stf/node_modules/eventemitter3/index.js:71:35)
    at RiskyStream.<anonymous> (/usr/lib/node_modules/stf/lib/util/riskystream.js:14:12)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
From previous event:
    at startConsumer (/usr/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:512:14)
    at /usr/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:527:12
    at SerialSyrup.ParallelSyrup.invoke (/usr/lib/node_modules/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /usr/lib/node_modules/stf/node_modules/stf-syrup/lib/serial.js:43:33
    at process._tickCallback (node.js:355:11)
FTL/util:lifecycle 17628 [200.200.138.60:5555] Shutting down due to fatal error
INF/provider 17582 [*] Cleaning up device worker "200.200.138.60:5555"
ERR/provider 17582 [*] Device worker "200.200.138.60:5555" died with code 1

```

what should I do?

**Comment by sorccu** [comment]
Well, it looks like whatever the thin client is, it doesn't expose any touch devices. Can you run `adb shell getevent -ilp` and paste the output here? I have a feeling there's probably nothing we can do, though.

**Comment by wangbaomi** [comment]
```

shell@android:/ $ getevent -ilp                                                
add device 1: /dev/input/event2
  bus:      0003
  vendor    093a
  product   2510
  version   0111
  name:     "PixArt USB Optical Mouse"
  location: "usb-usb20_host-1.2/input0"
  id:       ""
  version:  1.0.1
  events:
    KEY (0001): BTN_LEFT              BTN_RIGHT             BTN_MIDDLE           
    REL (0002): REL_X                 REL_Y                 REL_WHEEL            
    MSC (0004): MSC_SCAN             
  input props:
    <none>
add device 2: /dev/input/event0
  bus:      0019
  vendor    0001
  product   0001
  version   0100
  name:     "rk29-keypad"
  location: "gpio-keys/input0"
  id:       ""
  version:  1.0.1
  events:
    KEY (0001): KEY_POWER             KEY_WAKEUP           
  input props:
    <none>
add device 3: /dev/input/event1
  bus:      0019
  vendor    0001
  product   0001
  version   0100
  name:     "rkxx-remotectl"
  location: "gpio-keys/input0"
  id:       ""
  version:  1.0.1
  events:
    KEY (0001): KEY_ENTER             KEY_F8                KEY_F9                KEY_F10              
                KEY_F11               KEY_F12               KEY_HOME              KEY_UP               
                KEY_LEFT              KEY_RIGHT             KEY_DOWN              KEY_MUTE             
                KEY_VOLUMEDOWN        KEY_VOLUMEUP          KEY_POWER             KEY_MENU             
                KEY_WAKEUP            KEY_BACK              KEY_F13               KEY_F14              
                KEY_F15               KEY_F16               KEY_SEARCH            KEY_REPLY            
                KEY_MODE              KEY_TEXT              KEY_YELLOW            KEY_BLUE             
                KEY_CHANNELUP        
  input props:
    <none>

```

yes, it has no touch device, it use usb keyboard and mouse to input.

but, I can use ` adb shell input tap x y` to touch somewhere.

**Comment by sorccu** [comment]
Yeah, because it uses a different API that didn't support multi-touch until recently.

Unfortunately I'd have to say that we are not very interested in this issue right now, since our resources are very limited and we have so far only dealt with touch devices.

I may consider working on this at some point, but don't expect too much.

**Comment by mitoyarzun** [comment]
Hi!
I'm having the same issue with a resistive screen.

The input devices are the following:

```
add device 3: /dev/input/event2
  bus:      0018
  vendor    0000
  product   0000
  version   0000
  name:     "aw2083_input"
  location: "aw2xxx/input0"
  id:       ""
  version:  1.0.1
  events:
    KEY (0001): BTN_TOUCH            
    ABS (0003): ABS_X                 : value 2, min 0, max 480, fuzz 0, flat 0, resolution 0
                ABS_Y                 : value 2, min 0, max 800, fuzz 0, flat 0, resolution 0
                ABS_MISC              : value 0, min 0, max 0, fuzz 0, flat 0, resolution 0
  input props:
    INPUT_PROP_DIRECT
add device 4: /dev/input/event1
  bus:      0000
  vendor    0000
  product   0000
  version   0000
  name:     "adxl346"
  location: "sensor-input/input0"
  id:       ""
  version:  1.0.1
  events:
    ABS (0003): ABS_X                 : value 5, min -32768, max 32767, fuzz 0, flat 0, resolution 0
                ABS_Y                 : value -2, min -32768, max 32767, fuzz 0, flat 0, resolution 0
                ABS_Z                 : value 253, min -32768, max 32767, fuzz 0, flat 0, resolution 0
  input props:
    <none>
add device 5: /dev/input/event0
  bus:      0000
  vendor    0000
  product   0000
  version   0000
  name:     "sensor-input"
  location: "sensor-input/input0"
  id:       ""
  version:  1.0.1
  events:
  input props:
    <none>
```

Any help will be appreciated, thanks for making this project!

**Comment by sorccu** [comment]
Well, you have a touch device, but it's not a multitouch device. Currently we only support multitouch devices in [minitouch](https://github.com/openstf/minitouch), since that's all we've ever had. Can you run `adb shell getprop | grep -E '^ro\.'` and paste the output so that I can see which device it is?

**Comment by mitoyarzun** [comment]
It is a Senter PDA (custom chinese phone), here is the output: https://gist.github.com/mitoyarzun/4fccf90b448b34ff8bb9

**Comment by sorccu** [comment]
Ummm so it's something like this? http://en.senter.com.cn/products_detail/&productId=128.html

**Comment by mitoyarzun** [comment]
Exactly like that ;)

The screen is resistive and it has a custom Android 4.1 ROM.

**Comment by aiwb** [comment]
run ```getevent -ilp``` on my device,  print out
```
could not open /dev/input/event9, Permission denied
could not open /dev/input/event8, Permission denied
could not open /dev/input/event7, Permission denied
could not open /dev/input/event4, Permission denied
could not open /dev/input/mouse0, Permission denied
could not open /dev/input/event2, Permission denied
could not open /dev/input/event1, Permission denied
could not open /dev/input/mice, Permission denied
could not open /dev/input/event5, Permission denied
could not open /dev/input/event6, Permission denied
could not open /dev/input/event3, Permission denied
could not open /dev/input/event0, Permission denied
```

**Comment by sorccu** [comment]
That's a different issue. See #477.
