### ISSUE TITLE
stf start error when run the `stf local ` command 

### ISSUE THREAD

**Issue by wadeLouis** [openstf/stf#530]
* Version
```shell
[root@localhost ~]# npm install -g stf
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
/mnt/data/node-v7.5.0/bin/stf -> /mnt/data/node-v7.5.0/lib/node_modules/stf/bin/stf
/mnt/data/node-v7.5.0/lib
└── stf@2.3.0 
```
* Error
```shell
[root@localhost bin]# stf local
path.js:1142
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:391:17)
    at Function.Module._resolveFilename (module.js:461:31)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/data/node-v7.5.0/lib/node_modules/stf/bin/stf:2:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
[root@localhost bin]# 
[root@localhost bin]# stf doctor
path.js:1142
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:391:17)
    at Function.Module._resolveFilename (module.js:461:31)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/data/node-v7.5.0/lib/node_modules/stf/bin/stf:2:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

who can help me ?

**Comment by sorccu** [comment]
That's weird, possibly a bug in node. More likely though your node
installation is broken. Either way I would suggest using latest 6.x for now.

**Comment by wadeLouis** [comment]
The os: centos  7 x64
Node version : v7.5.0  this is a binary .  i will try build it from source to test the problem later .

**Comment by wadeLouis** [comment]
reinstall nodejs from source ,and stf.  
run `stf local ` ,take some  error log:
```shell
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js migrate"
INF/db 19092 [*] Connecting to 127.0.0.1:28015
INF/db:setup 19092 [*] Database "stf" already exists
INF/db:setup 19092 [*] Table "users" already exists
INF/db:setup 19092 [*] Table "accessTokens" already exists
INF/db:setup 19092 [*] Table "vncauth" already exists
INF/db:setup 19092 [*] Table "devices" already exists
INF/db:setup 19092 [*] Table "logs" already exists
INF/db:setup 19092 [*] Index "users"."adbKeys" already exists
INF/db:setup 19092 [*] Waiting for index "users"."adbKeys"
INF/db:setup 19092 [*] Index "accessTokens"."email" already exists
INF/db:setup 19092 [*] Waiting for index "accessTokens"."email"
INF/db:setup 19092 [*] Index "vncauth"."response" already exists
INF/db:setup 19092 [*] Index "vncauth"."responsePerDevice" already exists
INF/db:setup 19092 [*] Index "devices"."owner" already exists
INF/db:setup 19092 [*] Index "devices"."present" already exists
INF/db:setup 19092 [*] Index "devices"."providerChannel" already exists
INF/db:setup 19092 [*] Index "users"."adbKeys" is ready
INF/db:setup 19092 [*] Waiting for index "vncauth"."response"
INF/db:setup 19092 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 19092 [*] Waiting for index "devices"."owner"
INF/db:setup 19092 [*] Waiting for index "devices"."present"
INF/db:setup 19092 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 19092 [*] Index "accessTokens"."email" is ready
INF/db:setup 19092 [*] Index "vncauth"."response" is ready
INF/db:setup 19092 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 19092 [*] Index "devices"."owner" is ready
INF/db:setup 19092 [*] Index "devices"."present" is ready
INF/db:setup 19092 [*] Index "devices"."providerChannel" is ready
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js provider --name localhost.localdomain --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800"
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/7.5.0/linux/x64/zmq.node
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/7.5.0/linux/x64/zmq.node
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-temp --port 7102"
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/7.5.0/linux/x64/zmq.node
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/7.5.0/linux/x64/zmq.node
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 19086 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
FTL/cli:local 19086 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
INF/cli:local 19086 [*] Shutting down all child processes
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/7.5.0/linux/x64/zmq.node
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```

**Comment by sorccu** [comment]
Your installation is still screwed up. Fully remove stf and install it
again. If there are any errors during installation, fix those.
