### ISSUE TITLE
zmq.node: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by lincoln002** [openstf/stf#54]
execute the rethinkdb, then execute the command of "stf local",  error, the error info as below:

INF/util:procutil 2999 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
/usr/local/lib/node_modules/stf/node_modules/zmq/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node: wrong ELF class: ELFCLASS64
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/usr/local/lib/node_modules/stf/node_modules/zmq/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
FTL/cli:local 2999 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
INF/cli:local 2999 [*] Shutting down all child processes

**Comment by sorccu** [comment]
Hmm, perhaps you're somehow running 32-bit node with 64-bit libs? Try with 64-bit node instead.

**Comment by lincoln002** [comment]
Thanks, I have resolved the problem. My nodejs environment is not good.

**Comment by sourabhjain2208** [comment]
Hi i am still getting the error on running the following commands:

1. rethinkdb
2. stf local

error:

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/5.0.0/darwin/x64/zmq.node
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/lib/units/triproxy/index.js:1:73)
FTL/cli:local 27695 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

I have 64-bit node.
