### ISSUE TITLE
help  stf local  error~~~

### ISSUE THREAD

**Issue by scvjx** [openstf/stf#549]
stf local 

error  information

INF/util:procutil 28322 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/local/lib/node_modules/stf/node_modules/zmq/compiled/6.10.0/linux/x64/zmq.node
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
FTL/cli:local 28322 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
INF/cli:local 28322 [*] Shutting down all child processes

**Comment by Hao8816** [comment]
try npm install zmq again

**Comment by sorccu** [comment]
Closing as this is pretty old. @Hao8816 's answer is good, or alternatively you may want to `rm -rf node_modules` once.
