### ISSUE TITLE
Rethink is running, docker is working - but "No hosts left to try"

### ISSUE THREAD

**Issue by Nefariis** [openstf/stf#552]
I've made some serious strides in my understanding of docker but I am having one last problem with the final connection. 

uname -a 
`Linux odroidxu4 4.9.11-odroidxu4 #12 SMP PREEMPT Thu Feb 23 22:10:22 CET 2017 armv7l GNU/Linux`

docker run openstf/stf-armv7l stf doctor
```
INF/util:doctor 1 [*] OS Arch: arm
INF/util:doctor 1 [*] OS Platform: linux
INF/util:doctor 1 [*] OS Platform: 4.9.11-odroidxu4
INF/util:doctor 1 [*] Using Node 6.9.1
INF/util:doctor 1 [*] Using RethinkDB client 2.3.3
INF/util:doctor 1 [*] Using ZeroMQ 4.1.4
WRN/util:doctor 1 [*] Executable was not found
WRN/util:doctor 1 [*] Executable was not found
INF/util:doctor 1 [*] GraphicsMagick 1.3.25
INF/util:doctor 1 [*] ProtoBuf 2.6.1
```

rethinkdb --bind all
```
root@odroidxu4:~# rethinkdb --bind all
Running rethinkdb 2.3.0 (GCC 4.9.2)...
Running on Linux 4.9.11-odroidxu4 armv7l
Loading data from directory /root/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, 172.17.42.1, 192.168.0.8, ::1, 2601:602:8500:31b0::6, 2601:602:8500:31b0:7edd:90ff:fead:6a3a, fe80::5484:7aff:fefe:9799%4, fe80::7edd:90ff:fead:6a3a%3
Listening on driver addresses: 127.0.0.1, 172.17.42.1, 192.168.0.8, ::1, 2601:602:8500:31b0::6, 2601:602:8500:31b0:7edd:90ff:fead:6a3a, fe80::5484:7aff:fefe:9799%4, fe80::7edd:90ff:fead:6a3a%3
Listening on http addresses: 127.0.0.1, 172.17.42.1, 192.168.0.8, ::1, 2601:602:8500:31b0::6, 2601:602:8500:31b0:7edd:90ff:fead:6a3a, fe80::5484:7aff:fefe:9799%4, fe80::7edd:90ff:fead:6a3a%3
Server ready, "odroidxu4_j4s" 3d65cd30-5265-4078-a388-4490db6ce35b
```

docker run openstf/stf-armv7l stf local --public-ip 192.168.0.8:7100
```INF/triproxy 17 [app001] PUB socket bound on tcp://127.0.0.1:7111
INF/triproxy 17 [app001] DEALER socket bound on tcp://127.0.0.1:7112
INF/triproxy 17 [app001] PULL socket bound on tcp://127.0.0.1:7113
INF/triproxy 18 [dev001] PUB socket bound on tcp://127.0.0.1:7114
INF/triproxy 18 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
INF/triproxy 18 [dev001] PULL socket bound on tcp://127.0.0.1:7116
INF/reaper 21 [reaper001] Subscribing to permanent channel "*ALL"
INF/reaper 21 [reaper001] Reaping devices with no heartbeat
INF/db 21 [reaper001] Connecting to 127.0.0.1:28015
INF/reaper 21 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
INF/reaper 21 [reaper001] Sending output to "tcp://127.0.0.1:7116"
INF/db 21 [reaper001] Unable to connect to 127.0.0.1:28015
FTL/db 21 [reaper001] No hosts left to try
FTL/util:lifecycle 21 [reaper001] Shutting down due to fatal error
FTL/cli:local 1 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
INF/cli:local 1 [*] Shutting down all child processes
INF/util:lifecycle 17 [app001] Winding down for graceful exit
INF/util:lifecycle 18 [dev001] Winding down for graceful exit
```

Now it says it's unable to connect to `127.0.0.1:28015` but rethink says its listening on `port 28015`

Am I missing something? 

I've been reading other issues that have "no hosts left to try" and it's usually because rethink isn't running - but I can actually connect to it using a separate computer and `http://192.168.0.8:8080 `. So it would appear (at least to me), that it is up and working.

Also thank you for being around and answering questions, I know you must have better things to do than to help someone with their odroid testing cluster.

**Comment by sorccu** [comment]
It can't connect because the container's network is isolated from everything else by default. There are many many ways to link things together, but if you have no idea, try following https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md to have an idea of what flags you might need. An easy way to try it out is to add `--net host` an an option to `docker run`.

Note that we do not support running `stf local` w/ docker. It's for development use only and may or may not work, we never deploy with it.
