### ISSUE TITLE
errors for oppo R819T,Lenovo S890,huaweiT8951

### ISSUE THREAD

**Issue by nianliang** [openstf/stf#553]
I am sure i am using the latest version of STF
my issue is that devices(oppo R819T,Lenovo S890,huaweiT8951) have some errors as follows:
# oppo # R819T:
STF screen is not synchronized with the phone screen, after a while and the same,
## STF output:
`MP/device:plugins:group 11010 [6LQSCQSWKFNJPBTC] Now owned by "a@a.com"
INF/device:plugins:group 11010 [6LQSCQSWKFNJPBTC] Subscribing to group channel "CrAIyvSBSryaoQbOzasmoQ=="
INF/util:datautil 10960 [*] Device database does not have an entry for "6LQSCQSWKFNJPBTC" (model "R819T"/"OPPO89T_13015"). This is not an error, it only means that we don't have data for it yet.
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Setting frame producer projection to 390x521
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Requesting frame producer to start
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Launching screen service
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "PID: 4123"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: Using projection 720x1280@293x521/0"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:239) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:242) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:249) Creating virtual display"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:255) Creating CPU consumer"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:261) Creating buffer queue"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:267) Creating frame waiter"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:271) Publishing virtual display"
IMP/device:plugins:connect 11010 [6LQSCQSWKFNJPBTC] Remote Connect Started for device "6LQSCQSWKFNJPBTC" at "localhost:7401"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Connecting to minicap service
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Reading minicap banner
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (jni/minicap/minicap.cpp:448) New client connection"
Unhandled rejection TimeoutError: operation timed out
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
From previous event:
    at EventEmitter.plugin.acquireWakeLock (/home/mat/myfolder/project/STF/1stfTest/stf-master/lib/units/device/plugins/service.js:455:10)
    at EventEmitter.<anonymous> (/home/mat/myfolder/project/STF/1stfTest/stf-master/lib/units/device/plugins/group.js:103:15)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:189:7)
    at /home/mat/myfolder/project/STF/1stfTest/stf-master/lib/units/device/plugins/group.js:64:18
From previous event:
    at EventEmitter.plugin.join (/home/mat/myfolder/project/STF/1stfTest/stf-master/lib/units/device/plugins/group.js:42:15)
    at /home/mat/myfolder/project/STF/1stfTest/stf-master/lib/units/device/plugins/group.js:117:27
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Router.<anonymous> (/home/mat/myfolder/project/STF/1stfTest/stf-master/lib/units/device/plugins/group.js:116:12)
    at Router.emit (/home/mat/myfolder/project/STF/1stfTest/stf-master/node_modules/eventemitter3/index.js:118:35)
    at Router.<anonymous> (/home/mat/myfolder/project/STF/1stfTest/stf-master/lib/wire/router.js:36:12)
    at emitTwo (events.js:106:13)
    at exports.Socket.emit (events.js:192:7)
    at exports.Socket.Socket._flushRead (/home/mat/myfolder/project/STF/1stfTest/stf-master/node_modules/zmq/lib/index.js:638:15)
    at exports.Socket.Socket._flushReads (/home/mat/myfolder/project/STF/1stfTest/stf-master/node_modules/zmq/lib/index.js:676:23)
    at Object._zmq.onReadReady (/home/mat/myfolder/project/STF/1stfTest/stf-master/node_modules/zmq/lib/index.js:297:10)
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Requesting frame producer to stop
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Disconnecting from minicap service
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Stopping minicap service
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Sending SIGTERM to minicap
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (jni/minicap/minicap.cpp:197) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (jni/minicap/minicap.cpp:516) Closing client connection"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:286) Destroying virtual display"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Keeping 390x521 as current frame producer projection
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Requesting frame producer to start
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Launching screen service
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "PID: 4163"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: Using projection 720x1280@293x521/0"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:239) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:242) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:249) Creating virtual display"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:255) Creating CPU consumer"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:261) Creating buffer queue"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:267) Creating frame waiter"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (external/MY_minicap/src/minicap_17.cpp:271) Publishing virtual display"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Connecting to minicap service
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] minicap says: "INFO: (jni/minicap/minicap.cpp:448) New client connection"
INF/device:plugins:screen:stream 11010 [6LQSCQSWKFNJPBTC] Reading minicap banner`

# Lenovo S890 and huaweiT8951:
STF screen is gray, after a while the pop-up window shows someone stole your device.
I debug the code,find that device/screen/stream.js--> _ensureState function-->_connectService-->new RiskyStream,the stream is ended unexpectedEnd
## STF output:
`INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Setting frame producer projection to 390x521
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Requesting frame producer to start
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Launching screen service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "PID: 7506"
IMP/device:plugins:connect 11288 [0123456789ABCDEF] Remote Connect Started for device "0123456789ABCDEF" at "localhost:7405"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: Using projection 480x854@293x521/0"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 1246212 bytes for JPG encoder"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Connecting to minicap service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Reading minicap banner
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: (jni/minicap/minicap.cpp:448) New client connection"
WRN/device:plugins:screen:stream 11288 [0123456789ABCDEF] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Disconnecting from minicap service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Stopping minicap service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Launching screen service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "PID: 7510"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: Using projection 480x854@293x521/0"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 1246212 bytes for JPG encoder"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Connecting to minicap service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Reading minicap banner
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: (jni/minicap/minicap.cpp:448) New client connection"
WRN/device:plugins:screen:stream 11288 [0123456789ABCDEF] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Disconnecting from minicap service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Stopping minicap service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Launching screen service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "PID: 7564"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: Using projection 480x854@293x521/0"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 1246212 bytes for JPG encoder"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Connecting to minicap service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Reading minicap banner
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: (jni/minicap/minicap.cpp:448) New client connection"
WRN/device:plugins:screen:stream 11288 [0123456789ABCDEF] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Disconnecting from minicap service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Stopping minicap service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Launching screen service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "PID: 7582"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: Using projection 480x854@293x521/0"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 1246212 bytes for JPG encoder"
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Connecting to minicap service
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Reading minicap banner
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] minicap says: "INFO: (jni/minicap/minicap.cpp:448) New client connection"
WRN/device:plugins:screen:stream 11288 [0123456789ABCDEF] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 11288 [0123456789ABCDEF] Disconnecting from minicap service
FTL/device:plugins:screen:stream 11288 [0123456789ABCDEF] Frame producer had an error Error: Failed more than 3 times in 10000ms
    at FrameProducer._failLimitExceeded (/home/mat/myfolder/project/STF/1stfTest/stf-master/lib/units/device/plugins/screen/stream.js:222:26)
    at FailCounter.emit (/home/mat/myfolder/project/STF/1stfTest/stf-master/node_modules/eventemitter3/index.js:117:35)
    at FailCounter.inc (/home/mat/myfolder/project/STF/1stfTest/stf-master/lib/util/failcounter.js:29:10)
    at FrameProducer._outputEnded (/home/mat/myfolder/project/STF/1stfTest/stf-master/lib/units/device/plugins/screen/stream.js:215:24)
    at RiskyStream.emit (/home/mat/myfolder/project/STF/1stfTest/stf-master/node_modules/eventemitter3/index.js:115:35)
    at RiskyStream.<anonymous> (/home/mat/myfolder/project/STF/1stfTest/stf-master/lib/util/riskystream.js:14:12)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
FTL/util:lifecycle 11288 [0123456789ABCDEF] Shutting down due to fatal error
INF/provider 10937 [*] Cleaning up device worker "0123456789ABCDEF"
ERR/provider 10937 [*] Device worker "0123456789ABCDEF" died with code 1
INF/provider 10937 [*] Restarting device worker "0123456789ABCDEF"
INF/device:support:push 11346 [0123456789ABCDEF] Sending output to "tcp://127.0.0.1:7116"
INF/device 11346 [0123456789ABCDEF] Preparing device`

# stf doctor:
`INF/util:doctor 11668 [*] OS Arch: x64
INF/util:doctor 11668 [*] OS Platform: linux
INF/util:doctor 11668 [*] OS Platform: 4.4.0-64-generic
INF/util:doctor 11668 [*] Using Node 7.6.0
INF/util:doctor 11668 [*] Using RethinkDB client 2.3.3
INF/util:doctor 11668 [*] Using ZeroMQ 4.1.5
INF/util:doctor 11668 [*] Local ADB 1.0.32

INF/util:doctor 11668 [*] ProtoBuf 2.6.1
INF/util:doctor 11668 [*] GraphicsMagick 1.3.23
INF/util:doctor 11668 [*] Local RethinkDB server 2.3.5~0xenial
/home/mat/myfolder/project/STF/1stfTest/stf-master/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 2.3.5~0xenial
    at new SemVer (/home/mat/myfolder/project/STF/1stfTest/stf-master/node_modules/semver/semver.js:293:11)
    at Range.test (/home/mat/myfolder/project/STF/1stfTest/stf-master/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/home/mat/myfolder/project/STF/1stfTest/stf-master/node_modules/semver/semver.js:1085:16)
    at unsupportedVersion (/home/mat/myfolder/project/STF/1stfTest/stf-master/lib/util/doctor.js:13:15)
    at /home/mat/myfolder/project/STF/1stfTest/stf-master/lib/util/doctor.js:95:7
    at /home/mat/myfolder/project/STF/1stfTest/stf-master/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)`

I am very sorry for my poor english.
I really hope to get your help.
Thank you very much

**Comment by sorccu** [comment]
I can't find any of them for sale on Aliexpress or Ebay. Therefore it is unlikely that we'll ever be able to do anything about them. Physical access is needed.

**Comment by nianliang** [comment]
Thank you very much for your quick reply.
There is also a problem, some phones open camera, the STF screen is black, turn off the camera, the STF screen is normal, what might be the reason?
About that three devices ,If you have time and would like to study and solve the problem, I will express the parcel to you,ss long as you give me the address.

**Comment by sorccu** [comment]
Thank you for your kind words. I would be happy to accept the devices if you'd like to send them. I cannot guarantee that I'll be able to make them work, but I will at least try. Please send me an email to simo at openstf dot io and we'll discuss details.
