### ISSUE TITLE
adbkit-apkreader error

### ISSUE THREAD

**Issue by miss0110** [openstf/stf#554]
The following error log was printed when some apk was install.

```
Unable to read manifest of "29c0dd77-a972-450a-9522-e5acc308c934" RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readInt32LE (buffer.js:659:5)
    at BinaryXmlParser.readS32 (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/lib/apkreader/parser/binaryxml.js:105:25)
    at BinaryXmlParser.readXmlAttribute (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/lib/apkreader/parser/binaryxml.js:411:20)
    at BinaryXmlParser.readXmlElementStart (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/lib/apkreader/parser/binaryxml.js:389:35)
    at BinaryXmlParser.parse (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/lib/apkreader/parser/binaryxml.js:486:18)
    at ManifestParser.parse (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/lib/apkreader/parser/manifest.js:140:33)
    at /home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/lib/apkreader.js:103:44
    at tryCatcher (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home1/irteam/deploy/mtest2/node_modules/adbkit-apkreader/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by sorccu** [comment]
Please send the .apk to me. My address is simo at openstf dot io.

**Comment by miss0110** [comment]
I did send to mail to simo@openstf.io

**Comment by sorccu** [comment]
Ok, fixed. For some reason the manifest was slightly malformed. A field that was supposed to contain a size and is usually `8` was `0` even though the content was still there. Weird. The parser now uses a hardcoded size if that happens.
