### ISSUE TITLE
Can not locate binding file.

### ISSUE THREAD

**Issue by bisena149** [openstf/stf#565]
I cant figure out why I am getting following error while trying to run stf server locally:

INF/util:procutil 24352 [*] Forking "/home/local/ANT/xyz/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
/usr/bin/nodejs stf/lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                     [string] [default: "ufc3fdb0ff5d257f7cde7"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Could not locate the bindings file. Tried:
 → /home/local/ANT/xyz/stf/node_modules/zmq/build/zmq.node
 → /home/local/ANT/xyz/stf/node_modules/zmq/build/Debug/zmq.node
 → /home/local/ANT/xyz/stf/node_modules/zmq/build/Release/zmq.node
 → /home/local/ANT/xyz/stf/node_modules/zmq/out/Debug/zmq.node
 → /home/local/ANT/xyz/stf/node_modules/zmq/Debug/zmq.node
 → /home/local/ANT/xyz/stf/node_modules/zmq/out/Release/zmq.node
 → /home/local/ANT/xyz/stf/node_modules/zmq/Release/zmq.node
 → /home/local/ANT/xyz/stf/node_modules/zmq/build/default/zmq.node
 → /home/local/ANT/xyz/stf/node_modules/zmq/compiled/6.10.1/linux/x64/zmq.node
FTL/cli:local 24352 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/home/local/ANT/xyz/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
INF/cli:local 24352 [*] Shutting down all child processes

**Comment by bisena149** [comment]
I was able to resolve it by installing zeromq separately.
