### ISSUE TITLE
Remote Debugging is not working

### ISSUE THREAD

**Issue by limsy37** [openstf/stf#568]
Remote Debugging is not working.

Hello!
When I try to execute "adb connect 10.70.xx.xx:7577" after checking address and port on the Remote debug tab connecting device, then it always run successfully with response like "connected to 10.70.xx.xx:7577".
but I cannot find the device in the result of "adb devices". This happens only on small part of PCs including mine.

Also, my adb key can not be added in STF Web with "pbcopy < ~/.android/adbkey.pub".
~/.android/adbkey.pub file is a little different on my pc from one on another pc which works well.
If you look into my file, there is 0x00 between key and name, whereas there is only white space there in successful others' file.
Though I tried to recreate new adbkey file after deleting old adbkey file and run adb, 0x00 was included in the reulst again.

I am wondering if my issue has something to do with it.
If it is not in the case, what can I do to run adb connect?

My STF version is 2.3.0 and my adb key is same as below.
Please feel free to contact me if you need more information to figure out the cause.

I download android sdk from [tools_r25.2.3-macosx.zip](https://dl.google.com/android/repository/tools_r25.2.3-macosx.zip)

~~~
seongyeol@hehe platform-tools$ adb version
Android Debug Bridge version 1.0.39
Revision 5943271ace17-android

seongyeol@hehe platform-tools$ cat ~/.android/adbkey.pub
QAAAAHmXahk33YYcP0PF3CO5PZy338eRriVN75Oaprctcrb/IHuq9RuOMqo9kJZ2AJHw6CSPUFv2OdviODVMZixo/o0QPsCANhYOMHcE4raoQKV+i9/bwlBMTvkX01sqdI2Uic1rfekPcPc2QhCayj1PZVgU+AUpQKY25f4BOTLjEaCh51Q5A73VTb5MNPDnkIA6VyxLRkciX0tGpfqLqURgRaBQ1+qJFhL4P1qaB9YepYjXfEJ0Xj16w0RKpl4dw4fMCF4HmkkSPUXFzgngOtxhUxp8mk0ldaVWMxkwtkwlj8nG/ikgmTFdHRLH32pv4FaoD73K2l/on1YsDHgRoFfYeilMGyW7Cy3dv0ct5y46JeYqWtvnh6tIF3+wEmDd+vrw98JXhz77Gig7FnUG7lp/hbwVLLkR8NcNKogJfOxCVQFAzjinzpf9PyXkrqzeq5GNxdbwmMMdUu/E1ZfXzoMdpmv1cOp0W5TJ3KW+fpR0QrvEAZgyVMUVXtzDEMxCIu/cd+DFlV5VIefKI/Hxfc3uJ4R2ZqJrwkH+82LCem2Nm7TnrHm0ywT29j+y/uXJ+LJTHXRJaR+5DxrvfGceIWA0hqlOic5J1X0aBfnna1D+k/gTyBkwjgfJL00SeAJ8u0u4wmxvAkPN2e46Lw3lSMp5xcR4+4l3BYqvB0zhiuNlclbUEEHgjQEAAQA= seongyeol@hehe.local

seongyeol@hehe platform-tools$ xxd ~/.android/adbkey.pub 
00000000: 5141 4141 4148 6d58 6168 6b33 3359 5963  QAAAAHmXahk33YYc
00000010: 5030 5046 3343 4f35 505a 7933 3338 6552  P0PF3CO5PZy338eR
00000020: 7269 564e 3735 4f61 7072 6374 6372 622f  riVN75Oaprctcrb/
00000030: 4948 7571 3952 754f 4d71 6f39 6b4a 5a32  IHuq9RuOMqo9kJZ2
00000040: 414a 4877 3643 5350 5546 7632 4f64 7669  AJHw6CSPUFv2Odvi
00000050: 4f44 564d 5a69 786f 2f6f 3051 5073 4341  ODVMZixo/o0QPsCA
00000060: 4e68 594f 4d48 6345 3472 616f 514b 562b  NhYOMHcE4raoQKV+
00000070: 6939 2f62 776c 424d 5476 6b58 3031 7371  i9/bwlBMTvkX01sq
00000080: 6449 3255 6963 3172 6665 6b50 6350 6332  dI2Uic1rfekPcPc2
00000090: 5168 4361 796a 3150 5a56 6755 2b41 5570  QhCayj1PZVgU+AUp
000000a0: 514b 5932 3566 3442 4f54 4c6a 4561 4368  QKY25f4BOTLjEaCh
000000b0: 3531 5135 4137 3356 5462 354d 4e50 446e  51Q5A73VTb5MNPDn
000000c0: 6b49 4136 5679 784c 526b 6369 5830 7447  kIA6VyxLRkciX0tG
000000d0: 7066 714c 7155 5267 5261 4251 312b 714a  pfqLqURgRaBQ1+qJ
000000e0: 4668 4c34 5031 7161 4239 5965 7059 6a58  FhL4P1qaB9YepYjX
000000f0: 6645 4a30 586a 3136 7730 524b 706c 3464  fEJ0Xj16w0RKpl4d
00000100: 7734 664d 4346 3448 6d6b 6b53 5055 5846  w4fMCF4HmkkSPUXF
00000110: 7a67 6e67 4f74 7868 5578 7038 6d6b 306c  zgngOtxhUxp8mk0l
00000120: 6461 5657 4d78 6b77 746b 776c 6a38 6e47  daVWMxkwtkwlj8nG
00000130: 2f69 6b67 6d54 4664 4852 4c48 3332 7076  /ikgmTFdHRLH32pv
00000140: 3446 616f 4437 334b 326c 2f6f 6e31 5973  4FaoD73K2l/on1Ys
00000150: 4448 6752 6f46 6659 6569 6c4d 4779 5737  DHgRoFfYeilMGyW7
00000160: 4379 3364 7630 6374 3579 3436 4a65 5971  Cy3dv0ct5y46JeYq
00000170: 5774 766e 6836 7449 4633 2b77 456d 4464  Wtvnh6tIF3+wEmDd
00000180: 2b76 7277 3938 4a58 687a 3737 4769 6737  +vrw98JXhz77Gig7
00000190: 466e 5547 376c 702f 6862 7756 4c4c 6b52  FnUG7lp/hbwVLLkR
000001a0: 384e 634e 4b6f 674a 664f 7843 5651 4641  8NcNKogJfOxCVQFA
000001b0: 7a6a 696e 7a70 6639 5079 586b 7271 7a65  zjinzpf9PyXkrqze
000001c0: 7135 474e 7864 6277 6d4d 4d64 5575 2f45  q5GNxdbwmMMdUu/E
000001d0: 315a 6658 7a6f 4d64 706d 7631 634f 7030  1ZfXzoMdpmv1cOp0
000001e0: 5735 544a 334b 572b 6670 5230 5172 7645  W5TJ3KW+fpR0QrvE
000001f0: 415a 6779 564d 5556 5874 7a44 454d 7843  AZgyVMUVXtzDEMxC
00000200: 4975 2f63 642b 4446 6c56 3556 4965 664b  Iu/cd+DFlV5VIefK
00000210: 492f 4878 6663 3375 4a34 5232 5a71 4a72  I/Hxfc3uJ4R2ZqJr
00000220: 776b 482b 3832 4c43 656d 324e 6d37 546e  wkH+82LCem2Nm7Tn
00000230: 7248 6d30 7977 5432 396a 2b79 2f75 584a  rHm0ywT29j+y/uXJ
00000240: 2b4c 4a54 4858 524a 6152 2b35 4478 7276  +LJTHXRJaR+5Dxrv
00000250: 6647 6365 4957 4130 6871 6c4f 6963 354a  fGceIWA0hqlOic5J
00000260: 3158 3061 4266 6e6e 6131 442b 6b2f 6754  1X0aBfnna1D+k/gT
00000270: 7942 6b77 6a67 664a 4c30 3053 6541 4a38  yBkwjgfJL00SeAJ8
00000280: 7530 7534 776d 7876 416b 504e 3265 3436  u0u4wmxvAkPN2e46
00000290: 4c77 336c 534d 7035 7863 5234 2b34 6c33  Lw3lSMp5xcR4+4l3
000002a0: 4259 7176 4230 7a68 6975 4e6c 636c 6255  BYqvB0zhiuNlclbU
000002b0: 4545 4867 6a51 4541 4151 413d 0020 7365  EEHgjQEAAQA=. se
000002c0: 6f6e 6779 656f 6c40 6865 6865 2e6c 6f63  ongyeol@hehe.loc
000002d0: 616c                                     al
~~~

stf doctor
~~~
STF:~ stf$ stf doctor
INF/util:doctor 885 [*] OS Arch: x64
INF/util:doctor 885 [*] OS Platform: darwin
INF/util:doctor 885 [*] OS Platform: 16.4.0
INF/util:doctor 885 [*] Using Node 4.2.6
INF/util:doctor 885 [*] Using RethinkDB client 2.3.3
INF/util:doctor 885 [*] Using ZeroMQ 4.2.0
INF/util:doctor 885 [*] GraphicsMagick 1.3.25
INF/util:doctor 885 [*] Local ADB 1.0.36

INF/util:doctor 885 [*] ProtoBuf 3.1.0
ERR/util:doctor 885 [*] Current ProtoBuf version is not supported, it has to be ~2
INF/util:doctor 885 [*] Local RethinkDB server 2.3.5
~~~

STF local message When adding my adb key in STF web.
~~~
Unhandled rejection Error: Unrecognizable public key format
    at /Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/lib/adb/auth.js:69:23
    at tryCatcher (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:69:37)
    at Function.Auth.parsePublicKey (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/lib/adb/auth.js:62:12)
    at Object.module.exports.parsePublicKey (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/lib/adb/util.js:12:15)
    at Socket.<anonymous> (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/lib/units/websocket/index.js:370:30)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onevent (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/socket.io/lib/client.js:175:18)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onPacket (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/socket.io/node_modules/engine.io/lib/socket.js:101:14)
    at emitOne (events.js:77:13)
    at WebSocket.emit (events.js:169:7)
    at WebSocket.Transport.onPacket (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/socket.io/node_modules/engine.io/lib/transport.js:104:8)
    at WebSocket.Transport.onData (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/socket.io/node_modules/engine.io/lib/transport.js:115:8)
~~~

STF local message when adb connect
~~~
INF/device:plugins:connect 770 [ZPSOWSNN99999999] New remote ADB connection from ::ffff:10.70.9.105
FTL/util:lifecycle 770 [ZPSOWSNN99999999] Remote ADB had an error Error: Unrecognizable public key format
    at /Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/lib/adb/auth.js:69:23
    at tryCatcher (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:69:37)
    at Function.Auth.parsePublicKey (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/lib/adb/auth.js:62:12)
    at Socket._handleAuthPacket (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/lib/adb/tcpusb/socket.js:165:21)
    at /Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/lib/adb/tcpusb/socket.js:109:26
    at tryCatcher (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/method.js:31:24)
    at Socket._handle (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/lib/adb/tcpusb/socket.js:95:26)
    at emitOne (events.js:77:13)
    at PacketReader.emit (events.js:169:7)
    at PacketReader._tryRead (/Users/stf/.nvm/versions/node/v4.2.6/lib/node_modules/stf/node_modules/adbkit/lib/adb/tcpusb/packetreader.js:45:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:411:10)
    at emitReadable (_stream_readable.js:405:7)
    at readableAddChunk (_stream_readable.js:157:11)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
FTL/util:lifecycle 770 [ZPSOWSNN99999999] Shutting down due to fatal error
INF/provider 656 [*] Cleaning up device worker "ZPSOWSNN99999999"
ERR/provider 656 [*] Device worker "ZPSOWSNN99999999" died with code 1
INF/provider 656 [*] Restarting device worker "ZPSOWSNN99999999"
INF/device:support:push 814 [ZPSOWSNN99999999] Sending output to "tcp://127.0.0.1:7116"
INF/device 814 [ZPSOWSNN99999999] Preparing device
INF/device:support:sub 814 [ZPSOWSNN99999999] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 814 [ZPSOWSNN99999999] Subscribing to permanent channel "*ALL"
INF/device:support:properties 814 [ZPSOWSNN99999999] Loading properties
INF/device:support:abi 814 [ZPSOWSNN99999999] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
INF/device:resources:service 814 [ZPSOWSNN99999999] Checking whether we need to install STFService
INF/device:resources:service 814 [ZPSOWSNN99999999] Running version check
INF/device:resources:service 814 [ZPSOWSNN99999999] STFService up to date
INF/device:plugins:service 814 [ZPSOWSNN99999999] Launching agent
INF/device:plugins:service 814 [ZPSOWSNN99999999] Agent says: "Listening on @stfagent"
INF/device:plugins:service 814 [ZPSOWSNN99999999] Launching service
INF/device:plugins:service 814 [ZPSOWSNN99999999] Agent says: "InputClient started"
INF/device:plugins:display 814 [ZPSOWSNN99999999] Reading display info
INF/device:plugins:phone 814 [ZPSOWSNN99999999] Fetching phone info
INF/device:plugins:identity 814 [ZPSOWSNN99999999] Solving identity
INF/device:plugins:solo 814 [ZPSOWSNN99999999] Subscribing to permanent channel "MPVUuHr7L8sjcruJU/zmMrLSlUU="
INF/device:plugins:screen:stream 814 [ZPSOWSNN99999999] Starting WebSocket server on port 7612
WRN/device:plugins:data 814 [ZPSOWSNN99999999] Unable to find device data { serial: 'ZPSOWSNN99999999',
  platform: 'Android',
  manufacturer: 'XIAOMI',
  operator: null,
  model: 'Redmi Note 2',
  version: '5.0.2',
  abi: 'arm64-v8a',
  sdk: '21',
  product: 'hermes',
  display:
   { id: 0,
     width: 1080,
     height: 1920,
     xdpi: 403.4110107421875,
     ydpi: 403.0409851074219,
     fps: 60.10000228881836,
     density: 3,
     rotation: 0,
     secure: true,
     size: 5.464510452525597,
     url: 'ws://10.70.2.100:7612' },
  phone: { imei: '867515020845722', network: 'UNKNOWN' } }
INF/device:plugins:touch 814 [ZPSOWSNN99999999] Touch origin is top left
INF/device:plugins:touch 814 [ZPSOWSNN99999999] Requesting touch consumer to start
INF/device:plugins:touch 814 [ZPSOWSNN99999999] Launching screen service
INF/device:plugins:touch 814 [ZPSOWSNN99999999] Connecting to minitouch service
INF/device:plugins:touch 814 [ZPSOWSNN99999999] minitouch says: "Type B touch device mtk-tpd (1080x1920 with 10 contacts) detected on /dev/input/event3 (score 2100)"
INF/device:plugins:touch 814 [ZPSOWSNN99999999] minitouch says: "Connection established"
INF/device:plugins:touch 814 [ZPSOWSNN99999999] Reading minitouch banner
INF/device:plugins:vnc 814 [ZPSOWSNN99999999] Starting VNC server on port 7614
INF/device:plugins:browser 814 [ZPSOWSNN99999999] Loading browser list
INF/device:plugins:browser 814 [ZPSOWSNN99999999] Updating browser list
WRN/device:plugins:browser 814 [ZPSOWSNN99999999] Unmapped browser "com.cleanmaster.mguard"
INF/device:plugins:mute 814 [ZPSOWSNN99999999] Will not mute master volume during use
INF/device:plugins:forward 814 [ZPSOWSNN99999999] Launching reverse port forwarding service
INF/device:plugins:forward 814 [ZPSOWSNN99999999] Connecting to reverse port forwarding service
INF/device:plugins:connect 814 [ZPSOWSNN99999999] Listening on port 7613
INF/device 814 [ZPSOWSNN99999999] Fully operational
INF/util:datautil 660 [*] Device database does not have an entry for "ZPSOWSNN99999999" (model "Redmi Note 2"/"hermes"). This is not an error, it only means that we don't have data for it yet.
~~~

**Comment by sorccu** [comment]
Yes, this issue has been happening lately. I believe there may be a bug in the current version of ADB. Sometimes it adds a null byte in there, but it can also be something else like 0x03. Unfortunately, right now it means that you have to remove the invalid characters from your public key.

**Comment by sorccu** [comment]
Also, it can be more than one byte. I've seen two in one case. Possible buffer length issue in ADB's base64 encoding I suppose. However, it can also be after the space.

**Comment by limsy37** [comment]
Remote debugging is working well on my pc after removing the invalid characters from my public key. Thanks @sorccu

**Comment by sorccu** [comment]
Looking at the [code](https://github.com/android/platform_system_core/blob/9ef4417c8ea24cfe561103902a8eb9fa455d1677/adb/adb_auth_host.cpp#L93), it seems like [EVP_EncodedLength](https://commondatastorage.googleapis.com/chromium-boringssl-docs/base64.h.html#EVP_EncodedLength) and [EVP_EncodeBlock](https://commondatastorage.googleapis.com/chromium-boringssl-docs/base64.h.html#EVP_EncodeBlock) include a final null byte in the output, which was not the case before (or it was accounted for). This change seems to have been caused by the switch to BoringSSL (compared to mincrypt earlier). I don't think it's working as intended, but it's the way it is right now. Will have to adjust the validation to account for it. Does not explain the issue with multiple unexpected bytes, though. I'm thinking that EVP_EncodedLength may actually not be returning an exact number, but rather a safe upper bound. That would explain the remaining issues.

**Comment by sorccu** [comment]
For now, this specific issue has been solved by https://github.com/openstf/adbkit/commit/715ec81639b000655635b8c5fbd92baa237ca929. STF's adbkit has been updated.

However, there may be even more malformed keys out there, with multiple unexpected values. Let me know if there are any real keys that don't go through.

**Comment by ihayasaka** [comment]
Hi @sorccu 

It looks we can see the same observation `Unhandled rejection Error: Unrecognizable public key format`. Can you please check our two adb keys:
```
QAAAABf2FZ5ZXqe3kod40MBeTMnCe/2azZs4Ar6Z17iItjkXTdx42uwgrmtqIXYvR9sNLT7L4XJlaZAdOZn2EWdrOFN2EJpIPP4Y/Q0MZuIB/kN4JWklk8AHprNNVXMc3K/KhnGuI4G2LqnswpfZcA9z54YX3eNRgQXl2E7sjQehq2KHVr7CkmehdJgLlmUjI27E4yV/UY+gw41LFq51xX5QUeV+tDte3Pe8nTbO+dkoc/SiQk+O6TnoVbo+Y25Q+Njs/f9sErHhS2Db+YI1Hhih4XSGPJT+7lSW/pO0ji0o6mo5ohjry8k+VvdZDKlfqzj1MtonhUarjhW7Uiq6CeFTnk+uUcy5Z9ri/F1tshxB1RDjRs+HdqDjo8u/BZyz/JA46TnhKRfOL5oo7NawUieqyFdNkN5r01GJ994+FqhBgFj01eACBealrQQlnPGD4jy4I9QI8uldo0feHKIgMaY0oZP69kVrFsVL2A93BWWcuI9/luelORntIReImtOLSSriQJHqHNoojGyddH82rJnOY9UzEyuNAXVasin+U2bAkEVLQ7umlLKUUP7Hl/GKrE8FFjNb3I3xSOKfcwE7eEYRpWycz+4t55zaPtjj0S1rWSkTVBvkmJOKFv5L4iE+5A4j3KdPeR5TJlXaiRXwPZeIjdU8cSol1GwZz3bHFccGA6nID3k+MwEAAQA= unknown@unknown
```
```
QAAAAE8HjXFRUGh4RbmhtDH6RuO45Kpaq9dFPi3DXzoY50+pUl0eRokYa/6iMw9jenU6pYYmld9ERo3iaJF/ICw/SxTuE/PQRL6wLRnyoUWiULvOW4CvIypbYgKvqtZb20+bj21s176SmU2WjWw1Yrg5hxcyyN4Kwp3Qteymxl+GACTV6SJldc7vFdCOJcvSHEcCiWBHwnjgzn1itH7C78e8RbMI5dBk7dSU8ODhvOaT9KtE0vkiLYrrXv0/VpUs2B81CFthXkt5JrBTVxAlcLtv6ZIz6ZhHhQY/6ldnQLX1FEu7QMOznPTsR6Xl99UnHC0+RDWygMRjqdE2QwFS+z+fzTY6FCm7gKyq3gVOe2vcfXSGbLELSOuNyM7WPzbeLqp+4ap/+A2FyqeGs5n14JJAhznuQ5u3z/UorM00UKtoR7mOVqhdlZaLM1m63Tykx+YvnbXsXHK61OO4dfbzcnIOmwJWu4/iiBo7e3tVFZ6xv29zWUtz0bZ/3xZm4s28CMsIPcbF2YYtKKY3CDQUYPznmD7LnbLpvzCTpzUpy2w7I4tRBrFPa6I63eMtNGWBWhhOFCPNgINDxae/XSPzMA6N4D6k9dJfT/BJmV/a/tPekV1jybpfZMmYv5qrwmChO0+hBtSz9eeYi+VGZevDyMbAPq0f+yUJx85zMRmUUWOocvjBdYeGDgEAAQA=  @unknown
```

We are using latest stf@2.3.0 and adbkit@2.10.0.

**Comment by sorccu** [comment]
Are you 100% sure your adbkit is really up to date?

**Comment by ihayasaka** [comment]
Yes, I am 100% sure about it. We are hosting stf in docker and I just tried `npm ls --depth | grep adbkit` in docker container. Then it says:
```
+-- adbkit@2.10.0
| +-- adbkit-logcat@1.1.0
+-- adbkit-apkreader@2.1.1
+-- adbkit-monkey@1.0.1
```

**Comment by yuzhidi** [comment]
the words "Sometimes it adds a null byte in there" means like null in the line: 000002b0: 4545 4867 6a51 4541 4151 413d 0020 7365  EEHgjQEAAQA=. se , right ?

**Comment by sorccu** [comment]
Yep. With the latest STF we now ignore the null byte.
