### ISSUE TITLE
Unable to capture the screenshot

### ISSUE THREAD

**Issue by arun-krishnan-hike** [openstf/stf#569]
Using 2.3.0 of STF. Running in docker deployment. Followed the documentation present https://github.com/openstf/stf/blob/master/doc/DEPLOYMENT.md

**What is the issue or idea you have?**
When i hit the screenshot, i get the following error on console. The nginx is returning back a 301 for the screenshot upload request. All the other functionalities of being able to remote connect into a device and other options on STF works well.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
Happens for all devices.

**Please provide the steps to reproduce the issue.**
Nothing happens when trying to take screenshot

**What is the expected behavior?**
Expecting the screenshot to be captured.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
Here is the console output
1.3937bea….chunk.js:73467 Unhandled rejection TransactionError: Upload to "http://devicefarm.hikeapp.com/s/upload/image" failed: HTTP 301
    at readQueue (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:72404:30)
    at PendingTransactionResult.done (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:72432:8)
    at Socket.doneListener (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:72338:18)
    at Socket.Emitter.emit (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:53323:21)
    at Socket.onevent (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:53037:11)
    at Socket.onpacket (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:52995:13)
    at Manager.<anonymous> (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:53429:16)
    at Manager.Emitter.emit (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:53323:21)
    at Manager.ondecoded (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:48405:9)
    at Decoder.<anonymous> (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:53429:16)
    at Decoder.Emitter.emit (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:47868:21)
    at Decoder.add (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:46125:13)
    at Manager.ondata (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:48395:17)
    at Socket.<anonymous> (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:53429:16)
    at Socket.Emitter.emit (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:47868:21)
    at Socket.onPacket (http://devicefarm.hikeapp.com/static/app/build/1.3937bea4eb327ffa6730.chunk.js:49100:15)

**Please run `stf doctor` and paste the output here.**

**Comment by vbanthia** [comment]
https://github.com/openstf/stf/issues/548#issuecomment-282198766

**Comment by sorccu** [comment]
Sounds like a configuration issue. I'm guessing the HTTP 301 is for redirecting to HTTPS.

**Comment by arun-krishnan-hike** [comment]
@sorccu i am not using https on my setup and i am only using http. 

@vbanthia the issue you have related to is about upload throwing 5XX error. In my case it is 301. Some redirection to the backend from nginx is not working.

**Comment by sorccu** [comment]
This is pretty old so I'm closing this as it's probably no longer relevant. However, I'll just mention once more for anyone who may find this issue on Google that in 99% of all cases of screenshots not working, it has been caused either by a missing dependency, misconfigured environment (e.g. wrong `PATH`) or incorrectly configured STF.
