### ISSUE TITLE
cannot start stf see the outputs

### ISSUE THREAD

**Issue by dtunctuncer** [openstf/stf#570]
stf local output : 

```
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js migrate"
INF/db 2885 [*] Connecting to 127.0.0.1:28015
INF/db:setup 2885 [*] Database "stf" already exists
INF/db:setup 2885 [*] Table "users" already exists
INF/db:setup 2885 [*] Table "accessTokens" already exists
INF/db:setup 2885 [*] Table "vncauth" already exists
INF/db:setup 2885 [*] Table "devices" already exists
INF/db:setup 2885 [*] Table "logs" already exists
INF/db:setup 2885 [*] Index "users"."adbKeys" already exists
INF/db:setup 2885 [*] Waiting for index "users"."adbKeys"
INF/db:setup 2885 [*] Index "accessTokens"."email" already exists
INF/db:setup 2885 [*] Index "vncauth"."response" already exists
INF/db:setup 2885 [*] Index "vncauth"."responsePerDevice" already exists
INF/db:setup 2885 [*] Index "devices"."owner" already exists
INF/db:setup 2885 [*] Index "devices"."present" already exists
INF/db:setup 2885 [*] Index "devices"."providerChannel" already exists
INF/db:setup 2885 [*] Waiting for index "accessTokens"."email"
INF/db:setup 2885 [*] Waiting for index "vncauth"."response"
INF/db:setup 2885 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 2885 [*] Waiting for index "devices"."owner"
INF/db:setup 2885 [*] Waiting for index "devices"."present"
INF/db:setup 2885 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 2885 [*] Index "users"."adbKeys" is ready
INF/db:setup 2885 [*] Index "accessTokens"."email" is ready
INF/db:setup 2885 [*] Index "vncauth"."response" is ready
INF/db:setup 2885 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 2885 [*] Index "devices"."owner" is ready
INF/db:setup 2885 [*] Index "devices"."present" is ready
INF/db:setup 2885 [*] Index "devices"."providerChannel" is ready
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js provider --name android --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-temp --port 7102"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 2879 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: libzmq.so.5.1.3: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: libzmq.so.5.1.3: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
FTL/cli:local 2879 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
INF/cli:local 2879 [*] Shutting down all child processes
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: libzmq.so.5.1.3: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: libzmq.so.5.1.3: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: libzmq.so.5.1.3: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
```
stf doctor output  : 

```
/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: libzmq.so.5.1.3: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/local/lib/node_modules/stf/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
```

**Comment by sorccu** [comment]
It says you don't have the zeromq libs installed. Read the README, you need the required dependencies before installing.

**Comment by dtunctuncer** [comment]
@sorccu I have aldready read it and install it if you want i can prove it

**Comment by sorccu** [comment]
Sure. You can start by giving all the details about your system. Please do not remove the issue template like you've done in this case, you need to fill in the details.

**Comment by dtunctuncer** [comment]
```
root@android:/home/android# ldconfig -p | grep zmq
	libzmq.so.4 (libc6,x86-64) => /usr/local/lib/libzmq.so.4
	libzmq.so (libc6,x86-64) => /usr/local/lib/libzmq.so
```
I use this script for the install zeromq 
https://gist.github.com/cdjhlee/b8e3c927a01b0948b42d

can you check ?

**Comment by sorccu** [comment]
Try using your package manager to install it instead. Installing from source usually integrates poorly with the rest of the system. Once it's installed, reinstall stf from scratch and see if that works. If it does, you can try going back to the source install method if you like (but we won't help with that).
