### ISSUE TITLE
STF doctor

### ISSUE THREAD

**Issue by liuchang6** [openstf/stf#588]
I installed UBUNTU16.0.4 on a virtual machine.
Nodejs -v 6.10.2
npm -v 3.10.10

Zeromq  I have installed，but there is still a problem。Would you mind helping me find the problem?
I thank you very much。

stf local
/usr/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/compiled/6.10.2/linux/x64/zmq.node
    at bindings (/usr/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by 0x88l** [comment]
Reinstall zmq  and remove the node_modules at stf path. Do "npm install && npm" link again

**Comment by liuchang6** [comment]
@0x88l  I'm sorry to reply you so late, I've tried this method.
I reinstall the ZMQ, deleted node_modules. do npm install && npm again.

zmq -v 4.1.4

liuchang@ubuntu:/usr/local/lib$ sudo rm -rf node_modules/

npm install && npm
npm WARN yes@3.10.10 No repository field.

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/liuchang/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 /usr/lib/node_modules/npm

stf doctor
/usr/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/compiled/6.10.2/linux/x64/zmq.node
    at bindings (/usr/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

Forgive me for not having experience, I really can not find a problem

**Comment by sorccu** [comment]
You're using sudo. That tells me that you used sudo to install STF. Do not
do that. Use NVM or similar to install node do that you can run everything
as your own (or other) user. Otherwise modules will fail to build. There's
also an --allow-root flag (or sometjing like that, check help output) in
npm, but it doesn't always work 100%.

**Comment by liuchang6** [comment]
@sorccu 
liuchang@ubuntu:~$ nvm install 7.9.0
bash: [: 000000000700000000090000000000: integer expression expected
######################################################################## 100.0%
Checksums empty
Now using node v7.9.0
liuchang@ubuntu:~$ node -v
v7.9.0
liuchang@ubuntu:~$ npm -v
4.2.0
liuchang@ubuntu:~$ stf doctor
/usr/lib/node_modules/stf/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/compiled/7.9.0/linux/x64/zmq.node
    at bindings (/usr/lib/node_modules/stf/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/lib/node_modules/stf/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/stf/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

**Comment by vbanthia** [comment]
Follow these instructions properly. May helps, 

https://l4digital.com/wp-content/uploads/2016/11/Build-an-Android-Test-Farm-with-OpenSTF.pdf

**Comment by liuchang6** [comment]
@vbanthia 
Thank you. It would be nice if  could solve this.

**Comment by franciscocpg** [comment]
For someone else with this problem using Arch Linux [here](https://gist.github.com/franciscocpg/05d01d525aff5f34765f94121e1dc8b6) is some instructions that may help.
