### ISSUE TITLE
Setup had an error Error: Local socket "localabstract:stfagent" should be unused

### ISSUE THREAD

**Issue by BowenXiao** [openstf/stf#589]
**What is the issue or idea you have?**
Setup had an error Error: Local socket "localabstract:stfagent" should be unused

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
This issue happens on two of my android device.

**What is the expected behavior?**
I want to control my android device on the webpage and then, i got an pop-up window: "Disconnected".
but the device status is "use".

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
INF/provider 8868 [*] Restarting device worker "8da3b45"
INF/device:plugins:service 8697 [8da3b45] Agent says: "InputClient closing"
INF/device:support:push 31614 [8da3b45] Sending output to "tcp://127.0.0.1:7116"
INF/device 31614 [8da3b45] Preparing device
INF/device:support:sub 31614 [8da3b45] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 31614 [8da3b45] Subscribing to permanent channel "*ALL"
INF/device:support:properties 31614 [8da3b45] Loading properties
INF/device:support:abi 31614 [8da3b45] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
INF/device:resources:service 31614 [8da3b45] Checking whether we need to install STFService
INF/device:resources:service 31614 [8da3b45] Running version check
INF/device:resources:service 31614 [8da3b45] STFService up to date
INF/device:plugins:service 31614 [8da3b45] Launching agent
INF/device:plugins:service 8697 [8da3b45] Agent says: "InputClient started"
FTL/device 31614 [8da3b45] Setup had an error Error: Local socket "localabstract:stfagent" should be unused
    at /usr/local/lib/node_modules/stf/lib/util/devutil.js:16:13
    at tryCatcher (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
FTL/util:lifecycle 31614 [8da3b45] Shutting down due to fatal error
INF/provider 8868 [*] Cleaning up device worker "8da3b45"
ERR/provider 8868 [*] Device worker "8da3b45" died with code 1

**Please run `stf doctor` and paste the output here.**
INF/util:doctor 2041 [*] OS Arch: x64
INF/util:doctor 2041 [*] OS Platform: linux
INF/util:doctor 2041 [*] OS Platform: 4.4.0-47-generic
INF/util:doctor 2041 [*] Using Node 6.10.2
INF/util:doctor 2041 [*] Using RethinkDB client 2.3.3
INF/util:doctor 2041 [*] Using ZeroMQ 4.1.2
INF/util:doctor 2041 [*] Local ADB 1.0.36

INF/util:doctor 2041 [*] Local RethinkDB server 2.3.5~0trusty
/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 2.3.5~0trusty
    at new SemVer (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:293:11)
    at Range.test (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:1036:15)
    at Function.satisfies (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:1085:16)
    at unsupportedVersion (/usr/local/lib/node_modules/stf/lib/util/doctor.js:13:15)
    at /usr/local/lib/node_modules/stf/lib/util/doctor.js:95:7
    at /usr/local/lib/node_modules/stf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:195:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by sorccu** [comment]
Maybe you already have STF running.

**Comment by BowenXiao** [comment]
Thank you for answering me so quickly！！
But I can't find another STF process is running... terrible question..

**Comment by sorccu** [comment]
Are you perhaps using the --allow-remote option and then adding a device to
STF with `adb connect`?

**Comment by BowenXiao** [comment]
Yes, I'm using --allow-remote option, but I'm not adding any device to STF with 'adb connect',
maybe another process is using adb? I will check it..

**Comment by sorccu** [comment]
Sounds like you have the same device twice in the system. Once over USB and
once over WIFI.

**Comment by BowenXiao** [comment]
After reboot PC, STF is OK now...
