### ISSUE TITLE
Guide: Steps for adding Xiaomi devices to STF (e.g. Xiaomi Redmi 4A , MIUI 8.2.6.0)

### ISSUE THREAD

**Issue by sorccu** [openstf/stf#603]
To add Xiaomi devices to STF, there are extra steps that must be taken.

1. To enable __Developer options__, to go __Settings__ → __About phone__ and tap on __MIUI version__ until it says developer mode has been turned on.
2. Go to __Settings__ → __Mi Account__ and create or log in to a Mi account. This is __required__ for the next step.
3. Go to __Settings__ → __Additional settings__ → __Developer options__. Turn __USB debugging__ (for ADB access), __Install via USB__ (needed for installing STFService.apk) and __USB debugging (Security settings)__ (needed for running minitouch) on. You __must__ have a MI account set up to enable  _USB debugging (Security settings)_, otherwise it won't let you.
4. Connect the device to your computer. Allow the ADB key and select "Always allow."
5. Run STF. A dialog will pop up on the device confirming installation of `STFService`. You must allow the installation to go through. _Note that you may need to do this again in the future if the service is updated._
6. If STF fails to start after installing `STFService.apk`, go to __Settings__ → __Permissions__  → __Autostart__ and enable `STFService`.
7. The device should now work in STF.

Common errors:

If you see an error that says:

```
Setup had an error Error: /data/local/tmp/STFService.apk could not be installed [INSTALL_CANCELED_BY_USER]
```

It means that you haven't enabled the __Install via USB__ option.

**Comment by iqianxing** [comment]
The device requires sim card in the device.
If doesn't, **Install via USB** (needed for installing STFService.apk) and **USB debugging (Security settings)** (needed for running minitouch) can't on.

**Comment by sorccu** [comment]
Hmmmm that's weird, I don't have a SIM card in mine. Which device and MIUI version is it?

**Comment by iqianxing** [comment]
MIUI 8.5.1.0

**Comment by sorccu** [comment]
Strange... does it actually tell you that you need a SIM card?

**Comment by iqianxing** [comment]
Yes , perhaps the os is different in China.

**Comment by sorccu** [comment]
Possible. I've added your findings to the guide.

**Comment by lukassos** [comment]
Any update on this matter ? 
Same issue here. I need sim card inside the phone to install/dev apps on the phone too. 
I have unpacked new Redmi Note 5A with android 7.1.2 N2G47H (2017-12-01) and MUIU 9.2.1.0 NDFMIEK and the issue persist . 
In android studio INSTALL_FAILED_USER_RESTRICTED, which implies the admin app has not permitted such operation. And in Xiaomi phone it is part of MIUI as I recall.

**Comment by sorccu** [comment]
What kind of an update are you looking for? If the manufacturer forces you to set up a SIM card there’s nothing we can do about that.

**Comment by lukassos** [comment]
You're right. There is nothing you can add to this matter. I have researched about it a bit more and this is really an issue of MIUI 8+. They have added verification on chinese servers and gather unique id (UUID) of the phone on unlock of unknown souce apk. This  UUID is generated from sim card secure element and thus you need a sim card indeed. Foremost thanks for really fast answer 😉 So for anybody else reading this, you need any sim card inside. There is no need for sim card to be active on cellular. On the other hand internet connection is required too.

**Comment by liyaoyao6342** [comment]
I also encountered this problem on Red mi note8 pro, all the switches suggested above are turned on, can you help me see the problem?

**Comment by RmondJone** [comment]
N/device:plugins:data 90521 [7dk7ylv8feuotsfm] Unable to find device data { serial: '7dk7ylv8feuotsfm',
  platform: 'Android',
  manufacturer: 'XIAOMI',
  operator: null,
  model: ' Note 8 Pro',
  version: '9',
  abi: 'arm64-v8a',
  sdk: '28',
  product: 'begonia',
  cpuPlatform: 'mt6785',
  openGLESVersion: '3.2',
  display: 
   { id: 0,
     width: 1080,
     height: 2340,
     xdpi: 394.71600341796875,
     ydpi: 394.71600341796875,
     fps: 60.25,
     density: 2.75,
     rotation: 0,
     secure: true,
     size: 6.529271093831765,
     url: 'ws://192.168.27.180:7568' },
  phone: { imei: '99001405964062', network: 'UNKNOWN' } }
2020-03-09T05:35:33.378Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Touch origin is top left
2020-03-09T05:35:33.379Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Requesting touch consumer to start
2020-03-09T05:35:33.380Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Launching touch service
2020-03-09T05:35:33.389Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Connecting to minitouch service
2020-03-09T05:35:33.400Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "open: Permission denied"
2020-03-09T05:35:33.400Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
2020-03-09T05:35:33.401Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
2020-03-09T05:35:33.401Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device"
2020-03-09T05:35:33.402Z WRN/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Shell keeping minitouch running ended unexpectedly
2020-03-09T05:35:33.405Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Disconnecting from minitouch service
2020-03-09T05:35:33.407Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Stopping minitouch service
2020-03-09T05:35:33.408Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Launching touch service
2020-03-09T05:35:33.416Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Connecting to minitouch service
2020-03-09T05:35:33.427Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "open: Permission denied"
2020-03-09T05:35:33.427Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
2020-03-09T05:35:33.427Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
2020-03-09T05:35:33.428Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device"
2020-03-09T05:35:33.428Z WRN/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Shell keeping minitouch running ended unexpectedly
2020-03-09T05:35:33.430Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Disconnecting from minitouch service
2020-03-09T05:35:33.431Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Stopping minitouch service
2020-03-09T05:35:33.432Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Launching touch service
2020-03-09T05:35:33.440Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Connecting to minitouch service
2020-03-09T05:35:33.451Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "open: Permission denied"
2020-03-09T05:35:33.452Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
2020-03-09T05:35:33.452Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
2020-03-09T05:35:33.453Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device"
2020-03-09T05:35:33.453Z WRN/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Shell keeping minitouch running ended unexpectedly
2020-03-09T05:35:33.454Z INF/provider 88493 [*] Providing 4 of 5 device(s); waiting for "7dk7ylv8feuotsfm"
2020-03-09T05:35:33.455Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Disconnecting from minitouch service
2020-03-09T05:35:33.456Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Stopping minitouch service
2020-03-09T05:35:33.457Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Launching touch service
2020-03-09T05:35:33.465Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Connecting to minitouch service
2020-03-09T05:35:33.475Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "open: Permission denied"
2020-03-09T05:35:33.475Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
2020-03-09T05:35:33.476Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
2020-03-09T05:35:33.476Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device"
2020-03-09T05:35:33.477Z WRN/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Shell keeping minitouch running ended unexpectedly
2020-03-09T05:35:33.478Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Disconnecting from minitouch service
2020-03-09T05:35:33.480Z WRN/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Will not apply desired state due to too many failures
2020-03-09T05:35:33.481Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Stopping minitouch service
2020-03-09T05:35:33.483Z FTL/device 90521 [7dk7ylv8feuotsfm] Setup had an error Error: Failed more than 3 times in 10000ms
    at TouchConsumer._failLimitExceeded (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:230:26)
    at FailCounter.emit (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/node_modules/eventemitter3/index.js:117:35)
    at FailCounter.inc (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/util/failcounter.js:29:10)
    at TouchConsumer._outputEnded (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:223:24)
    at RiskyStream.emit (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/node_modules/eventemitter3/index.js:115:35)
    at RiskyStream.<anonymous> (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/util/riskystream.js:14:12)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
From previous event:
    at startConsumer (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:511:14)
    at /Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:526:12
    at SerialSyrup.ParallelSyrup.invoke (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/node_modules/stf-syrup/lib/serial.js:43:33
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2020-03-09T05:35:33.484Z FTL/util:lifecycle 90521 [7dk7ylv8feuotsfm] Shutting down due to fatal error
2020-03-09T05:35:33.493Z INF/provider 88493 [*] Cleaning up device worker "7dk7ylv8feuotsfm"
2020-03-09T05:35:33.493Z ERR/provider 88493 [*] Device worker "7dk7ylv8feuotsfm" died with code 1
2020-03-09T05:35:33.493Z INF/provider 88493 [*] Restarting device worker "7dk7ylv8feuotsfm"

**Comment by yuyangcq** [comment]
Linux机器使用docker搭建STF，Windows安装SDK后，使用USB连接安卓设备首先在Windows暴露5037端口
然后在Linux使用命令：stf provider --name localhost.localdomain --min-port 7400 --max-port 7700- -connect-sub tcp：//172.50.1.159：7114 --connect-push tcp：//172.50.1.159：7116 --group-timeout 900 --public-ip 172.50.1.159 --storage-url http：// 172.50.1.159:7100/ --adb主机172.17.244.11 --adb端口5037 --vnc-initial尺寸600x800-静音大师-允许远程

然后就一直停在“ tcp：//172.50.1.159：7114”接收输入，过了几分钟就报错了，这个是什么原因吗？
![2021-05-26_104418](https://user-images.githubusercontent.com/29696080/119604768-33134b00-be22-11eb-9421-22d0cd98c54e.png)
![2021-05-26_105530](https://user-images.githubusercontent.com/29696080/119604777-3575a500-be22-11eb-8cfe-b33c55bd99a3.png)

**Comment by yuyangcq** [comment]
Linux机器使用docker搭建STF，Windows安装SDK后，使用USB连接安卓设备
首先在Windows暴露5037端口
然后在Linux使用命令：stf provider --name localhost.localdomain --min-port 7400 --max-port 7700 --connect-sub tcp://172.50.1.159:7114 --connect-push tcp://172.50.1.159:7116 --group-timeout 900 --public-ip 172.50.1.159 --storage-url http://172.50.1.159:7100/ --adb-host 172.17.244.11 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never --allow-remote

就一直停在“ tcp://172.50.1.159：7114”接收输入，过了几分钟就报错了，这个是什么原因?
![2021-05-26_104418](https://user-images.githubusercontent.com/29696080/119604868-5d650880-be22-11eb-9d0d-9d9ed3cd6616.png)
![2021-05-26_105530](https://user-images.githubusercontent.com/29696080/119604876-6229bc80-be22-11eb-90b4-407c2b145ffe.png)

**Comment by namedlock** [comment]
> I did all the steps you said
> 
> ```
> N/device:plugins:data 90521 [7dk7ylv8feuotsfm] Unable to find device data { serial: '7dk7ylv8feuotsfm',
>   platform: 'Android',
>   manufacturer: 'XIAOMI',
>   operator: null,
>   model: ' Note 8 Pro',
>   version: '9',
>   abi: 'arm64-v8a',
>   sdk: '28',
>   product: 'begonia',
>   cpuPlatform: 'mt6785',
>   openGLESVersion: '3.2',
>   display: 
>    { id: 0,
>      width: 1080,
>      height: 2340,
>      xdpi: 394.71600341796875,
>      ydpi: 394.71600341796875,
>      fps: 60.25,
>      density: 2.75,
>      rotation: 0,
>      secure: true,
>      size: 6.529271093831765,
>      url: 'ws://192.168.27.180:7568' },
>   phone: { imei: '99001405964062', network: 'UNKNOWN' } }
> 2020-03-09T05:35:33.378Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Touch origin is top left
> 2020-03-09T05:35:33.379Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Requesting touch consumer to start
> 2020-03-09T05:35:33.380Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Launching touch service
> 2020-03-09T05:35:33.389Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Connecting to minitouch service
> 2020-03-09T05:35:33.400Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "open: Permission denied"
> 2020-03-09T05:35:33.400Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
> 2020-03-09T05:35:33.401Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
> 2020-03-09T05:35:33.401Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device"
> 2020-03-09T05:35:33.402Z WRN/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Shell keeping minitouch running ended unexpectedly
> 2020-03-09T05:35:33.405Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Disconnecting from minitouch service
> 2020-03-09T05:35:33.407Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Stopping minitouch service
> 2020-03-09T05:35:33.408Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Launching touch service
> 2020-03-09T05:35:33.416Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Connecting to minitouch service
> 2020-03-09T05:35:33.427Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "open: Permission denied"
> 2020-03-09T05:35:33.427Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
> 2020-03-09T05:35:33.427Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
> 2020-03-09T05:35:33.428Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device"
> 2020-03-09T05:35:33.428Z WRN/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Shell keeping minitouch running ended unexpectedly
> 2020-03-09T05:35:33.430Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Disconnecting from minitouch service
> 2020-03-09T05:35:33.431Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Stopping minitouch service
> 2020-03-09T05:35:33.432Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Launching touch service
> 2020-03-09T05:35:33.440Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Connecting to minitouch service
> 2020-03-09T05:35:33.451Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "open: Permission denied"
> 2020-03-09T05:35:33.452Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
> 2020-03-09T05:35:33.452Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
> 2020-03-09T05:35:33.453Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device"
> 2020-03-09T05:35:33.453Z WRN/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Shell keeping minitouch running ended unexpectedly
> 2020-03-09T05:35:33.454Z INF/provider 88493 [*] Providing 4 of 5 device(s); waiting for "7dk7ylv8feuotsfm"
> 2020-03-09T05:35:33.455Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Disconnecting from minitouch service
> 2020-03-09T05:35:33.456Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Stopping minitouch service
> 2020-03-09T05:35:33.457Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Launching touch service
> 2020-03-09T05:35:33.465Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Connecting to minitouch service
> 2020-03-09T05:35:33.475Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "open: Permission denied"
> 2020-03-09T05:35:33.475Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
> 2020-03-09T05:35:33.476Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
> 2020-03-09T05:35:33.476Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] minitouch says: "Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device"
> 2020-03-09T05:35:33.477Z WRN/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Shell keeping minitouch running ended unexpectedly
> 2020-03-09T05:35:33.478Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Disconnecting from minitouch service
> 2020-03-09T05:35:33.480Z WRN/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Will not apply desired state due to too many failures
> 2020-03-09T05:35:33.481Z INF/device:plugins:touch 90521 [7dk7ylv8feuotsfm] Stopping minitouch service
> 2020-03-09T05:35:33.483Z FTL/device 90521 [7dk7ylv8feuotsfm] Setup had an error Error: Failed more than 3 times in 10000ms
>     at TouchConsumer._failLimitExceeded (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:230:26)
>     at FailCounter.emit (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/node_modules/eventemitter3/index.js:117:35)
>     at FailCounter.inc (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/util/failcounter.js:29:10)
>     at TouchConsumer._outputEnded (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:223:24)
>     at RiskyStream.emit (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/node_modules/eventemitter3/index.js:115:35)
>     at RiskyStream.<anonymous> (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/util/riskystream.js:14:12)
>     at emitNone (events.js:111:20)
>     at Socket.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1064:12)
>     at _combinedTickCallback (internal/process/next_tick.js:139:11)
> From previous event:
>     at startConsumer (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:511:14)
>     at /Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/lib/units/device/plugins/touch/index.js:526:12
>     at SerialSyrup.ParallelSyrup.invoke (/Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
>     at /Users/jinwenwu/.nvm/versions/node/v8.16.2/lib/node_modules/stf/node_modules/stf-syrup/lib/serial.js:43:33
>     at _combinedTickCallback (internal/process/next_tick.js:132:7)
>     at process._tickCallback (internal/process/next_tick.js:181:9)
> 2020-03-09T05:35:33.484Z FTL/util:lifecycle 90521 [7dk7ylv8feuotsfm] Shutting down due to fatal error
> 2020-03-09T05:35:33.493Z INF/provider 88493 [*] Cleaning up device worker "7dk7ylv8feuotsfm"
> 2020-03-09T05:35:33.493Z ERR/provider 88493 [*] Device worker "7dk7ylv8feuotsfm" died with code 1
> 2020-03-09T05:35:33.493Z INF/provider 88493 [*] Restarting device worker "7dk7ylv8feuotsfm"
> ```

It seems MI OS's power saving strategy produce this error. I chose no restriction strategy for power saving, and it works.
