### ISSUE TITLE
How can i see my remote devices

### ISSUE THREAD

**Issue by whitiancai** [openstf/stf#613]
linux:192.168.31.202     with stf ,android sdk
windows:192.168.31.135     without stf, have adbkit and android sdk

devices are connect to windows

1.start stf in linux `stf local --public-ip 192.168.31.202 --allow-remote`
2.windows run `adb -a -P 5037 fork-server server`
3.linux run`stf provider --name mikezhoudeMac-mini.local --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 20000 --public-ip 192.168.31.202 --storage-url http://localhost:7100/ --adb-host 192.168.31.135 --adb-port 5037 --vnc-initial-size 600x800 --allow-remote	`

then i can see my remote device on the web page,but i want to see my devices in my adb.
when i run `adb devices`,i can see the devices like `whitiancai@whitiancai-OptiPlex-3046:~/IdeaProjects/AutoMobile$ adb devices
List of devices attached
4d00f618684d5051        device
`

i try to run `adb connect 192.168.31.202:7401`,and it doesn't work.when i run the cmd again, an error happened.
`FTL/device:plugins:touch 11369 [SODMDIQ499999999] Touch consumer had an error Error: Failed more than 3 times in 10000ms
    at TouchConsumer._failLimitExceeded (/home/whitiancai/stf/stf-master/lib/units/device/plugins/touch/index.js:230:26)
    at FailCounter.emit (/home/whitiancai/stf/stf-master/node_modules/_eventemitter3@1.2.0@eventemitter3/index.js:117:35)
    at FailCounter.inc (/home/whitiancai/stf/stf-master/lib/util/failcounter.js:29:10)
    at TouchConsumer._socketEnded (/home/whitiancai/stf/stf-master/lib/units/device/plugins/touch/index.js:217:24)
    at RiskyStream.emit (/home/whitiancai/stf/stf-master/node_modules/_eventemitter3@1.2.0@eventemitter3/index.js:115:35)
    at RiskyStream.<anonymous> (/home/whitiancai/stf/stf-master/lib/util/riskystream.js:14:12)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
FTL/util:lifecycle 11369 [SODMDIQ499999999] Shutting down due to fatal error
INF/provider 11355 [*] Cleaning up device worker "SODMDIQ499999999"
ERR/provider 11355 [*] Device worker "SODMDIQ499999999" died with code 1`

what should i do?

**Comment by thinkhy** [comment]
Did you add public key in stf web page when issue "adb connect ..." ?

**Comment by whitiancai** [comment]
you mean the key in the setting web page?How to add ?Can you show me a complete adb code

**Comment by thinkhy** [comment]
The panel will be poped out automatically when you issue the "adb connect ..." for the first time.

**Comment by whitiancai** [comment]
what panel?I see a device "192.168.31.135:7401" in my device list,but it will be offline in a few seconds.

**Comment by sorccu** [comment]
It's because you have multiple providers trying to set up the same device like I told you earlier.
