### ISSUE TITLE
At least one of these paths should exist error. 

### ISSUE THREAD

**Issue by unverb** [openstf/stf#63]
I installed requirements and STF (npm install -g stf). But I could not run properly. I created the folder as  says in error, but did not work.

Operating System -> Ubuntu 14.04.2
Node.js Version    -> v0.12.4
STF Version          -> v1.0.9

Start Rethinkdb 
    
    rethinkdb --port 8081 --bind all
Start STF          
    
    stf local --public-ip 192.168.1.5

Error message 

    FTL/device 9730 [1C1D67034F9D] Setup had an error Error: At least one of these paths should exist: /usr/local/lib/node_modules/stf/vendor/minicap/bin/armeabi/minicap-nopie
        at Object.module.exports.requiredMatch (/usr/local/lib/node_modules/stf/lib/util/pathutil.js:33:9)
        at /usr/local/lib/node_modules/stf/lib/units/device/resources/minicap.js:21:23
        at SerialSyrup.ParallelSyrup.invoke (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
        at /usr/local/lib/node_modules/stf/node_modules/stf-syrup/lib/serial.js:43:33
        at tryCatch1 (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
        at Promise$_callHandler [as _callHandler] (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
        at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
        at Promise$_settlePromiseAt [as _settlePromiseAt] (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
        at Promise$_fulfillPromises [as _fulfillPromises] (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
        at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
        at Async$consumeFunctionBuffer (/usr/local/lib/node_modules/stf/node_modules/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
        at process._tickCallback (node.js:355:11)
    FTL/util:lifecycle 19327 [1C1D67034F9D] Shutting down due to fatal error
    INF/provider 19102 [*] Cleaning up device worker "1C1D67034F9D"
    ERR/provider 19102 [*] Device worker "1C1D67034F9D" died with code 1
    INF/provider 19102 [*] Restarting device worker "1C1D67034F9D"

**Comment by sorccu** [comment]
I think your device is too old. We only support armeabi-v7a (with neon) and newer. In fact yours is the first armeabi-only device ever reported to us. Just to be sure, can you post the output of:

```bash
adb shell getprop | grep '^ro\.'
```

**Comment by mehmetboraezer** [comment]
I have many devices. This command is not valid.

**Comment by sorccu** [comment]
Then use adb's -s option with the right serial number (you can see it in
the logs).

**Comment by unverb** [comment]
The output of this command to empty all devices.

Command 
    
     adb -s [SERIAL] shell getprop | grep '^ro\.'

**Comment by sorccu** [comment]
Hmm, can you try adding -E to the grep command?

**Comment by unverb** [comment]
You are right @sorccu. There was a problem with the device. How do I exclude by using the serial number?

**Comment by sorccu** [comment]
Currently you can't exclude just one device, you'd have to actually unplug it.

**Comment by sorccu** [comment]
By the way could you let me know what device this is? I'd want to know the model number at least. Either `adb shell getprop | grep -E '^ro\.'` or `adb devices -l` should give enough information about the device, including the model number.

**Comment by mohlendo** [comment]
I have an old HTC Wildfire here which is also not supported.
The output of `adb devices -l` is:
`SH18KTR25629 device usb:338690048X`

**Comment by sorccu** [comment]
Thanks! I can take a look if someone is willing to donate one of these super old devices. I might eventually buy one myself but funds are limited right now. I've posted a small update in the README.

**Comment by sorccu** [comment]
I got a used Wildfire S off of Ebay for ~$30. Might look into it some day but no promises of any kind.
