### ISSUE TITLE
Api error 

### ISSUE THREAD

**Issue by kartikprakash1993** [openstf/stf#643]
When i try to use API for authentication using NODE.js, i get this.

    accessTokenAuth: Swagger.ApiKeyAuthorization('Authorization', 'Bearer ' + AUTH_TOKEN, 'header')
                             ^

TypeError: Swagger.ApiKeyAuthorization is not a function
    at Object.<anonymous> (/home/kartik/STestFarm/stf/test.js:11:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by vbanthia** [comment]
User swagger-client@2.x.x

https://github.com/openstf/stf/pull/601#issuecomment-305354613

**Comment by vbanthia** [comment]
Also, if you want to try v3.x.x then you will have to implement script by yourself with new syntax (API). Script provided in STF API doc is written using old syntax.

**Comment by kartikprakash1993** [comment]
Got it. Thanks
