### ISSUE TITLE
Device remains in preparation mode.

### ISSUE THREAD

**Issue by suvansh-dev** [openstf/stf#646]
Hi,
I know that emulators are not supported yet but still if anyone can help me with the following issue:

ISSUE:
The emulator remains in preparing mode and never gets connected.

**Emulator details:**
Device: Nexus 6
OS: Marshmallow android 6.0 armeabi-v7a
Ram:1536 mb
Graphics: Automatic

**Command line output while connecting the emulator with STF:**

FTL/device 12548 [emulator-5554] Setup had an error TimeoutError: operation timed out
    at afterTimeout (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:11:15)
    at timeoutTimeout (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout (timers.js:119:15)
FTL/util:lifecycle 12548 [emulator-5554] Shutting down due to fatal error
INF/provider 11474 [*] Cleaning up device worker "emulator-5554"
ERR/provider 11474 [*] Device worker "emulator-5554" died with code 1
INF/provider 11474 [*] Restarting device worker "emulator-5554"
INF/device:support:push 12567 [emulator-5554] Sending output to "tcp://127.0.0.1:7116"
INF/device 12567 [emulator-5554] Preparing device
INF/device:support:sub 12567 [emulator-5554] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 12567 [emulator-5554] Subscribing to permanent channel "*ALL"
INF/device:support:properties 12567 [emulator-5554] Loading properties
INF/device:support:abi 12567 [emulator-5554] Supports ABIs armeabi-v7a, armeabi
INF/device:resources:service 12567 [emulator-5554] Checking whether we need to install STFService
INF/device:resources:service 12567 [emulator-5554] Installing STFService
INF/provider 11474 [*] Providing 0 of 1 device(s); waiting for "emulator-5554"
INF/provider 11474 [*] Providing 0 of 1 device(s); waiting for "emulator-5554"
INF/provider 11474 [*] Providing 0 of 1 device(s); waiting for "emulator-5554"
INF/provider 11474 [*] Providing 0 of 1 device(s); waiting for "emulator-5554"
WRN/device:resources:service 12567 [emulator-5554] STFService installation is taking a long time; perhaps you have to accept 3rd party app installation on the device?
INF/provider 11474 [*] Providing 0 of 1 device(s); waiting for "emulator-5554"
INF/provider 11474 [*] Providing 0 of 1 device(s); waiting for "emulator-5554"
WRN/device:resources:service 12567 [emulator-5554] STFService installation is taking a long time; perhaps you have to accept 3rd party app installation on the device?
INF/provider 11474 [*] Providing 0 of 1 device(s); waiting for "emulator-5554"
INF/provider 11474 [*] Providing 0 of 1 device(s); waiting for "emulator-5554"
WRN/device:resources:service 12567 [emulator-5554] STFService installation is taking a long time; perhaps you have to accept 3rd party app installation on the device?
FTL/device 12567 [emulator-5554] Setup had an error TimeoutError: operation timed out
    at Timer.listOnTimeout (timers.js:119:15)
From previous event:
    at /usr/local/lib/node_modules/stf/lib/units/device/resources/service.js:84:18
    at processImmediate [as _immediateCallback] (timers.js:367:17)
FTL/util:lifecycle 12567 [emulator-5554] Shutting down due to fatal error
INF/provider 11474 [*] Cleaning up device worker "emulator-5554"
ERR/provider 11474 [*] Device worker "emulator-5554" died with code 1
INF/provider 11474 [*] Restarting device worker "emulator-5554"

**Comment by suvansh-dev** [comment]
lol just fixed it.

**Comment by suvansh-dev** [comment]
After few edits i have connected the emulator with stf but now it is disconnecting the device again and again, here is the output i get at the terminal:

INF/device:plugins:screen:stream 3000 [emulator-5554] Disconnecting from minicap service
FTL/device:plugins:screen:stream 3000 [emulator-5554] Frame producer had an error Error: Failed more than 3 times in 10000ms
    at FrameProducer._failLimitExceeded (/usr/local/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:220:26)
    at FailCounter.emit (/usr/local/lib/node_modules/stf/node_modules/eventemitter3/index.js:73:35)
    at FailCounter.inc (/usr/local/lib/node_modules/stf/lib/util/failcounter.js:29:10)
    at FrameProducer._outputEnded (/usr/local/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:213:24)
    at RiskyStream.emit (/usr/local/lib/node_modules/stf/node_modules/eventemitter3/index.js:71:35)
    at RiskyStream.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/riskystream.js:14:12)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
FTL/util:lifecycle 3000 [emulator-5554] Shutting down due to fatal error
INF/provider 2750 [*] Cleaning up device worker "emulator-5554"
ERR/provider 2750 [*] Device worker "emulator-5554" died with code 1

**Comment by suvansh-dev** [comment]
Here seems to be like some graphics issue: 
https://www.google.co.in/#q=FTL/util:lifecycle+3000+[emulator-5554]+

**Comment by sorccu** [comment]
No, FTL means "fatal". Your query shows results for "Faster Than Light", a game.

**Comment by suvansh-dev** [comment]
But isn't it a graphics issue?

**Comment by suvansh-dev** [comment]
Hi,
Today i have tried using Kitkat 4.4 armeabi-v7a image, it gets connected with stf and screen is visible too but when i click on the screen in openstf then no change occurs in the screen in openstf while in the emulator it changes. For example: if i have opened messages then it will be visible in the emulator but it will remain in home screen in openstf. Here is the command line output:

 **WARN - dea.updater.SdkComponentSource - File /root/.android/repositories.cfg could not be loaded. 
[  38395]   WARN - dea.updater.SdkComponentSource - java.io.FileNotFoundException: /tmp/StudioDownloadersys-img2-1.xml (No such file or directory) 
[  59021]   WARN - roid.tools.ndk.GradleWorkspace - NDK support for project 'MyApplication' is disabled because the project doesn't contain any valid native configurations. 
[1046913]   WARN -            #com.android.ddmlib - Emulator console auth failed (is the emulator running as a different user?) 
[1049218]   WARN -            #com.android.ddmlib - ShellCommandUnresponsiveException getting properties for device emulator-5554: null 
[1337096]   WARN - run.EmulatorConnectionListener - Timed out after 300seconds waiting for emulator to come online. 
Exception in thread "Device List Monitor" java.lang.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:188)
	at com.android.ddmlib.EmulatorConsole.checkConnection(EmulatorConsole.java:310)
	at com.android.ddmlib.EmulatorConsole.getConsole(EmulatorConsole.java:231)
	at com.android.ddmlib.DeviceMonitor.queryAvdName(DeviceMonitor.java:248)
	at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:220)
	at com.android.ddmlib.DeviceMonitor.access$400(DeviceMonitor.java:65)
	at com.android.ddmlib.DeviceMonitor$DeviceListUpdateListener.deviceListUpdate(DeviceMonitor.java:662)
	at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.processIncomingDeviceData(DeviceMonitor.java:847)
	at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.run(DeviceMonitor.java:781)
	at java.lang.Thread.run(Thread.java:745)
[1791177]   WARN - run.EmulatorConnectionListener - Timed out after 300seconds waiting for emulator to come online.**

**Comment by sorccu** [comment]
There are too many emulator issues already, let's try to focus them on a single issue. For now we do not support or provide help for emulators.
