### ISSUE TITLE
TypeError: Invalid Version

### ISSUE THREAD

**Issue by Harvey-Lin** [openstf/stf#658]
NF/util:doctor 17002 [*] OS Arch: x64
INF/util:doctor 17002 [*] OS Platform: darwin
INF/util:doctor 17002 [*] OS Platform: 15.6.0
INF/util:doctor 17002 [*] Using Node 5.9.1
INF/util:doctor 17002 [*] Using RethinkDB client 2.3.3
INF/util:doctor 17002 [*] Using ZeroMQ 4.1.4
INF/util:doctor 17002 [*] Local ADB 1.0.39
Installed as /Users/harvey/Desktop/Harvey/android-sdk-macosx/platform-tools/adb

/Users/harvey/.nvm/versions/node/v5.9.1/lib/node_modules/stf/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 1.0.39
Installed as /Users/harvey/Desktop/Harvey/android-sdk-macosx/platform-tools/adb

    at new SemVer (/Users/harvey/.nvm/versions/node/v5.9.1/lib/node_modules/stf/node_modules/semver/semver.js:293:11)
    at Range.test (/Users/harvey/.nvm/versions/node/v5.9.1/lib/node_modules/stf/node_modules/semver/semver.js:1100:15)
    at Function.satisfies (/Users/harvey/.nvm/versions/node/v5.9.1/lib/node_modules/stf/node_modules/semver/semver.js:1149:16)
    at unsupportedVersion (/Users/harvey/.nvm/versions/node/v5.9.1/lib/node_modules/stf/lib/util/doctor.js:13:15)
    at /Users/harvey/.nvm/versions/node/v5.9.1/lib/node_modules/stf/lib/util/doctor.js:143:7
    at /Users/harvey/.nvm/versions/node/v5.9.1/lib/node_modules/stf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)

**Comment by sorccu** [comment]
I would recommend building from master instead of using the NPM version.

**Comment by sorccu** [comment]
Perhaps v3.0.0 that was just published to NPM will clear this issue.
