### ISSUE TITLE
Not able to start STF from MAC Mini

### ISSUE THREAD

**Issue by mrajendrac** [openstf/stf#664]
Hi Team,

I have installed all the  pre requisites as mentioned the documents, however when i run the 'stf local' to start the stf server from terminal i am getting the below error

**NOTE :** When i type stf doctor , i see nothing in the terminal window.

NF/reaper 24112 [reaper001] Sending output to "tcp://127.0.0.1:7116"
INF/poorxy 24121 [*] Listening on port 7100

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1127:5)
    at module.exports (/usr/local/lib/node_modules/stf/lib/units/poorxy/index.js:67:10)
    at Command.program.command.description.option.option.option.option.option.option.action.require.port (/usr/local/lib/node_modules/stf/lib/cli.js:637:30)
    at Command.listener (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:300:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:635:12)
    at Command.parse (/usr/local/lib/node_modules/stf/node_modules/commander/index.js:457:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/stf/lib/cli.js:1266:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
FTL/cli:local 24106 [*] Child process had an error ExitError: Exit code "8"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)

Thanks
RajendraC

**Comment by sorccu** [comment]
99% chance you already have another copy of STF running.

**Comment by mrajendrac** [comment]
Thanks for the quick reply Sorccu, actual problem was my airdrop server was running on the localhost 7100 port, I have forcefully closed Airserver from activity monitor, then my STF is running like a charm

Regards,
RajendraC

**Comment by sorccu** [comment]
Hmm, interesting that they use the same port.

**Comment by mrajendrac** [comment]
Yes, sorccu, 
I would like to be in touch with you for the goal i am trying for using STF, I have my appium+Selenium(automation tools) automated scripts are developed and stored it my desktop, every time i am running those scripts on physical devices by connecting through USB cable. Now i would like to make a local cloud of  all my devices and would like to access those devices over the localhost to run my automated tests, 

Any help in this regard would highly help to achieve my goal

Thanks in Advance,
RajendraC

**Comment by sorccu** [comment]
That's not possible, I have no time to give detailed guidance to anyone. I
would suggest posting specific issues on GitHub and maybe someone will have
time to answer those at some point.

**Comment by mrajendrac** [comment]
Thats fine, I will post if any issues come across

Thanks,
Rajendra
