### ISSUE TITLE
Could not connect to RethinkDB, operation timed out

### ISSUE THREAD

**Issue by KungPaoChicken** [openstf/stf#667]
**What is the issue or idea you have?**
stf cannot connect to the port RethinkDB is on.  
stf is cloned, built and linked according to the instructions.

**Please provide the steps to reproduce the issue.**
`stf local --public-ip ***.***.***.***`
**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
```
stf local --public-ip ***.***.***.***
INF/util:procutil 3549 [*] Forking "/home/*****/stf/lib/cli migrate"
INF/db 3555 [*] Connecting to 127.0.0.1:28015
FTL/db 3555 [*] Could not connect to 127.0.0.1:28015, operation timed out.
FTL/util:lifecycle 3555 [*] Shutting down due to fatal error

/home/*****/stf/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/home/*****/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Please run `stf doctor` and paste the output here.**
```
stf doctor
INF/cli:doctor 3639 [*] OS Arch: x64
INF/cli:doctor 3639 [*] OS Platform: linux
INF/cli:doctor 3639 [*] OS Platform: 4.4.0-78-generic
INF/cli:doctor 3639 [*] Using Node 6.11.2
INF/cli:doctor 3639 [*] Using ZeroMQ 4.1.2
INF/cli:doctor 3639 [*] Using RethinkDB 2.3.6~0xenial
INF/cli:doctor 3639 [*] Using GraphicsMagick 1.3.23
INF/cli:doctor 3639 [*] Using ADB 1.0.39
ERR/cli:doctor 3639 [*] ProtoBuf version cannot be detected
```

**Output from `netstat`:**
```
sudo netstat -tulpn | grep rethinkdb
tcp        0      0 127.0.1.1:28015         0.0.0.0:*               LISTEN      3224/rethinkdb  
tcp        0      0 127.0.0.1:28015         0.0.0.0:*               LISTEN      3224/rethinkdb  
tcp        0      0 127.0.1.1:8080          0.0.0.0:*               LISTEN      3224/rethinkdb  
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      3224/rethinkdb  
tcp        0      0 127.0.1.1:29015         0.0.0.0:*               LISTEN      3224/rethinkdb  
tcp        0      0 127.0.0.1:29015         0.0.0.0:*               LISTEN      3224/rethinkdb  
tcp6       0      0 ::1:28015               :::*                    LISTEN      3224/rethinkdb  
tcp6       0      0 ::1:8080                :::*                    LISTEN      3224/rethinkdb  
tcp6       0      0 ::1:29015               :::*                    LISTEN      3224/rethinkdb  
```

**Comment by KungPaoChicken** [comment]
I had a quick look in the source, and it asked for `protoc`, so I ran `protoc --version` and this is the output:
```
protoc --version
libprotoc 3.2.0
```

**Comment by sorccu** [comment]
Seems OK I guess. Firewall blocking local connections maybe? Anyway we
don't really provide support at this level, as it's unlikely to be an issue
with STF itself. Hopefully you can figure out what's wrong.

**Comment by KungPaoChicken** [comment]
The error is gone, and I had another error, weird. For the future people, I had a fresh install of rethinkdb from apt, and maybe it's the test connection I tried with the Python driver for RethinkDB that 'fixed' it.

**Comment by KungPaoChicken** [comment]
Here's the new one:
```
stf local --public-ip ***.***.***.***
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli migrate"
INF/db 13688 [*] Connecting to 127.0.0.1:28015
INF/db:setup 13688 [*] Database "stf" already exists
INF/db:setup 13688 [*] Table "users" already exists
INF/db:setup 13688 [*] Table "accessTokens" already exists
INF/db:setup 13688 [*] Table "vncauth" already exists
INF/db:setup 13688 [*] Table "devices" already exists
INF/db:setup 13688 [*] Table "logs" already exists
INF/db:setup 13688 [*] Index "users"."adbKeys" already exists
INF/db:setup 13688 [*] Index "accessTokens"."email" already exists
INF/db:setup 13688 [*] Index "vncauth"."response" already exists
INF/db:setup 13688 [*] Index "vncauth"."responsePerDevice" already exists
INF/db:setup 13688 [*] Index "devices"."owner" already exists
INF/db:setup 13688 [*] Index "devices"."present" already exists
INF/db:setup 13688 [*] Index "devices"."providerChannel" already exists
INF/db:setup 13688 [*] Waiting for index "users"."adbKeys"
INF/db:setup 13688 [*] Waiting for index "accessTokens"."email"
INF/db:setup 13688 [*] Waiting for index "vncauth"."response"
INF/db:setup 13688 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 13688 [*] Waiting for index "devices"."owner"
INF/db:setup 13688 [*] Waiting for index "devices"."present"
INF/db:setup 13688 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 13688 [*] Index "users"."adbKeys" is ready
INF/db:setup 13688 [*] Index "accessTokens"."email" is ready
INF/db:setup 13688 [*] Index "vncauth"."response" is ready
INF/db:setup 13688 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 13688 [*] Index "devices"."owner" is ready
INF/db:setup 13688 [*] Index "devices"."present" is ready
INF/db:setup 13688 [*] Index "devices"."providerChannel" is ready
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli provider --name GreenLab-STF --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip ***.***.***.*** --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://***.***.***.***:7100/"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://***.***.***.***:7100/auth/mock/ --websocket-url http://***.***.***.***:7110/"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli storage-temp --port 7102"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 13682 [*] Forking "/home/*****/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
/usr/bin/nodejs stf/lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                              [string] [default: "GreenLab-STF"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Address already in use
FTL/cli:local 13682 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/home/*****/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
INF/cli:local 13682 [*] Shutting down all child processes

```

**Comment by sorccu** [comment]
That's weird, but good to hear you were able to solve the issue.
