### ISSUE TITLE
Local RethinkDB server 2.3.6~0vivid  TypeError

### ISSUE THREAD

**Issue by sgjeff** [openstf/stf#668]
INF/util:doctor 28786 [*] Local RethinkDB server 2.3.6~0vivid
/usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/node_modules/semver/semver.js:293
     throw new TypeError('Invalid Version: ' + version);
     ^

TypeError: Invalid Version: 2.3.6~0vivid
    at new SemVer (/usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/node_modules/semver/semver.js:293:12)
    at Range.test (/usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/node_modules/semver/semver.js:1099:15)
    at Function.satisfies (/usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/node_modules/semver/semver.js:1148:16)
    at unsupportedVersion (/usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/lib/util/doctor.js:13:15)
    at /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/lib/util/doctor.js:95:7
    at /usr/local/node-v6.11.0-linux-x64/lib/node_modules/stf/lib/util/doctor.js:50:22
    at ChildProcess.exithandler (child_process.js:195:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

**Comment by sgjeff** [comment]
for help

**Comment by sorccu** [comment]
Your STF is too old. The latest version hasn't been published to NPM yet, so you should build from master for now.
