### ISSUE TITLE
Shutting down due to fatal error

### ISSUE THREAD

**Issue by tares003** [openstf/stf#671]
Hi, 
I getting this error even though i have started `rethinkdb, it starts successfully: 

```
Running rethinkdb 2.3.6 (CLANG 8.0.0 (clang-800.0.42.1))...
Running on Darwin 15.6.0 x86_64
Loading data from directory /Users/pp/rethinkdb_data
warn: Cache size does not leave much memory for server and query overhead (available memory: 267 MB).
warn: Cache size is very low and may impact performance.
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, ::1
Listening on driver addresses: 127.0.0.1, ::1
Listening on http addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "pp_szg" 9b1ad1fc-ff31-4441-95e1-ef0dc4b434c0
```
This is what i get when starting the stf, i use the `stf local`  or `stf local --public-ip <COMPUTER IP>` i get this: 

```
$ Stf local
INF/util:procutil 6260 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli migrate"
INF/db 6261 [*] Connecting to 127.0.0.1:28015
INF/db 6261 [*] Unable to connect to 127.0.0.1:28015
FTL/db 6261 [*] No hosts left to try
FTL/util:lifecycle 6261 [*] Shutting down due to fatal error

/usr/local/lib/node_modules/stf/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

I have tried uninstalling the rethinkdb and stf; no luck. I have read this this issue as this parson having similar issue [#458](https://github.com/openstf/stf/issues/458) but this person had it in different ports whereas mine is the same one `28015`. I am running one MAC OS X EL Capitan

Any help would be appreciated, let me know if like any information. Thanks.

**Comment by tares003** [comment]
Just update : I have created another user on the same mac and  started all the services and it works. Can I know what is the issue or mistake I am doing?

**Comment by sorccu** [comment]
Difficult to say. However, we don't recommend installing node via homebrew
or the official installer due to permission issues with global modules. Use
nvm instead.
