### ISSUE TITLE
STF master service don't support Android 5.0?

### ISSUE THREAD

**Issue by iqianxing** [openstf/stf#702]
On master branch, I found this problem on windows:
```
WRN/device:plugins:touch 5108 [d31dd7b87d43] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 5108 [d31dd7b87d43] Disconnecting from minitouch service
INF/device:plugins:touch 5108 [d31dd7b87d43] Stopping minitouch service
INF/device:plugins:touch 5108 [d31dd7b87d43] Launching screen service
INF/device:plugins:touch 5108 [d31dd7b87d43] Connecting to minitouch service
INF/device:plugins:touch 5108 [d31dd7b87d43] minitouch says: "open: Permission denied"
INF/device:plugins:touch 5108 [d31dd7b87d43] minitouch says: "Unable to open device /dev/input/event5 for inspectionopen
: Permission denied"
INF/device:plugins:touch 5108 [d31dd7b87d43] minitouch says: "Unable to open device /dev/input/event4 for inspectionopen
: Permission denied"
INF/device:plugins:touch 5108 [d31dd7b87d43] minitouch says: "Unable to open device /dev/input/event1 for inspectionopen
: Permission denied"
INF/device:plugins:touch 5108 [d31dd7b87d43] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen
: Permission denied"
INF/device:plugins:touch 5108 [d31dd7b87d43] minitouch says: "Unable to open device /dev/input/mice for inspectionopen:
Permission denied"
INF/device:plugins:touch 5108 [d31dd7b87d43] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen
: Permission denied"
INF/device:plugins:touch 5108 [d31dd7b87d43] minitouch says: "Unable to open device /dev/input/event3 for inspectionUnab
le to find a suitable touch device"
WRN/device:plugins:touch 5108 [d31dd7b87d43] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 5108 [d31dd7b87d43] Disconnecting from minitouch service
WRN/device:plugins:touch 5108 [d31dd7b87d43] Will not apply desired state due to too many failures
INF/device:plugins:touch 5108 [d31dd7b87d43] Stopping minitouch service
FTL/device 5108 [d31dd7b87d43] Setup had an error Error: Failed more than 3 times in 10000ms
    at TouchConsumer._failLimitExceeded (D:\Projects\stf\lib\units\device\plugins\touch\index.js:230:26)
    at FailCounter.emit (D:\Projects\stf\node_modules\eventemitter3\index.js:117:35)
    at FailCounter.inc (D:\Projects\stf\lib\util\failcounter.js:29:10)
    at TouchConsumer._outputEnded (D:\Projects\stf\lib\units\device\plugins\touch\index.js:223:24)
    at RiskyStream.emit (D:\Projects\stf\node_modules\eventemitter3\index.js:115:35)
    at RiskyStream.<anonymous> (D:\Projects\stf\lib\util\riskystream.js:14:12)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
From previous event:
    at startConsumer (D:\Projects\stf\lib\units\device\plugins\touch\index.js:511:14)
    at D:\Projects\stf\lib\units\device\plugins\touch\index.js:526:12
    at SerialSyrup.ParallelSyrup.invoke (D:\Projects\stf\node_modules\stf-syrup\lib\parallel.js:54:24)
    at D:\Projects\stf\node_modules\stf-syrup\lib\serial.js:43:33
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
FTL/util:lifecycle 5108 [d31dd7b87d43] Shutting down due to fatal error
INF/provider 7884 [*] Cleaning up device worker "d31dd7b87d43"
ERR/provider 7884 [*] Device worker "d31dd7b87d43" died with code 1
INF/provider 7884 [*] Restarting device worker "d31dd7b87d43"
INF/provider 7884 [*] Providing all 0 of 1 device(s); ignoring "d31dd7b87d43"
INF/device:support:push 3376 [d31dd7b87d43] Sending output to "tcp://127.0.0.1:7116"
INF/device 3376 [d31dd7b87d43] Preparing device
INF/device:support:sub 3376 [d31dd7b87d43] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 3376 [d31dd7b87d43] Subscribing to permanent channel "*ALL"
INF/device:support:properties 3376 [d31dd7b87d43] Loading properties
INF/device:support:sdk 3376 [d31dd7b87d43] Supports SDK 23
INF/device:support:abi 3376 [d31dd7b87d43] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
INF/device:resources:minicap 3376 [d31dd7b87d43] Installing "D:\Projects\stf\node_modules\minicap-prebuilt\prebuilt\arm6
4-v8a\bin\minicap" as "/data/local/tmp/minicap"
INF/device:resources:minicap 3376 [d31dd7b87d43] Installing "D:\Projects\stf\node_modules\minicap-prebuilt\prebuilt\arm6
4-v8a\lib\android-23\minicap.so" as "/data/local/tmp/minicap.so"
INF/device:resources:service 3376 [d31dd7b87d43] Checking whether we need to install STFService
INF/device:resources:service 3376 [d31dd7b87d43] Running version check
INF/device:resources:service 3376 [d31dd7b87d43] STFService up to date
INF/device:plugins:service 3376 [d31dd7b87d43] Launching agent
INFINFINFINFINF/util:lifecycle 7588 [*] Winding down for graceful exit
/util:lifecycle 2644 [*] Winding down for graceful exit
INF/util:lifecycle 1544 [proc001] Winding down for graceful exit
/util:lifecycle 5852 [dev001] Winding down for graceful exit
/util:lifecycle 3972 [reaper001] Winding down for graceful exit
INFWRNWRN/util:lifecycle 7884 [*] Winding down for graceful exit
/db 1544 [proc001] Connection closed
/db 7588 [*] Connection closed
INF/cli:local 5548 [*] Received SIGINT, waiting for processes to terminate
FTL/cli:local 5548 [*] Child process had an error ExitError: Exit code "3221225786"
    at ChildProcess.<anonymous> (D:\Projects\stf\lib\util\procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
INF/cli:local 5548 [*] Shutting down all child processes
```

**Comment by sorccu** [comment]
It does. Please check Linux again, perhaps it'll work there. Alternatively, perhaps running into https://github.com/openstf/stf/issues/603 or similar? Look for a similar setting and report back with your findings.

Also, you need to stop removing the issue template. We need those details. For example, you should've told us which device you're using.

**Comment by iqianxing** [comment]
Thank you!
