### ISSUE TITLE
LDAP Authentication issue while accessing 

### ISSUE THREAD

**Issue by mrajendrac** [openstf/stf#714]
Hi all, 

I have configured and started STF using LDAP server authentication, when i access STF using the credentials i get the below error in STF server logs 

_```
> ERR/auth-ldap 21737 [127.0.0.1] Unexpected error InvalidCredentialsError: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db0
    at messageCallback (/usr/local/lib/node_modules/stf/node_modules/ldapjs/lib/client/client.js:1423:40)
    at Parser.onMessage (/usr/local/lib/node_modules/stf/node_modules/ldapjs/lib/client/client.js:1089:14)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Parser.write (/usr/local/lib/node_modules/stf/node_modules/ldapjs/lib/messages/parser.js:117:8)
    at Socket.onData (/usr/local/lib/node_modules/stf/node_modules/ldapjs/lib/client/client.js:1076:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
```_

Below is the step i have used to start STF


**stf local --auth-type ldap --auth-options '["--ldap-url","ldap://10.xx.x.xxx:3268","--ldap-search-dn","OU=inner_ou,OU=inner_ou,DC=inner_dc,DC=inner_dc,DC=com","--ldap-bind-dn","CN=username,OU=inner_ou,	=inner_ou,DC=inner_dc,DC=inner_dc,DC=com","--ldap-bind-credentials","username_actual_credential","--ldap-search-field","sAMAccountName"]'**

Please help me 

Thanks
RajendraC

**Comment by sorccu** [comment]
No idea. There are so many LDAP servers that if you're the only one having
a problem, it's pretty much your problem. Try to figure out what the error
means, and if it turns out we need to change something, update this issue
again with the details you've found.

**Comment by mrPsycho** [comment]
i have issue like that - i can't connect to the current LDAP server.

im tied several configs. last one is: 
```
  -e "STF_AUTH_LDAP_LDAP_BIND_CREDENTIALS=pass_for_stf_bind"\
  -e "STF_AUTH_LDAP_LDAP_BIND_DN=CN=stf bind,OU=System Users,DC=domain,DC=local" \
  -e "STF_AUTH_LDAP_LDAP_SEARCH_DN=DC=domain,DC=local" \
  -e "STF_AUTH_LDAP_LDAP_TIMEOUT=360" \
  -e "STF_AUTH_LDAP_LDAP_URL=ldap://192.168.2.100:389" \
  -e "STF_AUTH_LDAP_LDAP_USERNAME_FIELD=sAMAccountName" \
  -e "STF_AUTH_LDAP_LDAP_SEARCH_CLASS=(objectClass=*)" \
  -e "STF_AUTH_LDAP_LDAP_SEARCH_FIELD=uid" \
```

and i have that:
```
hramov-jenia-pc-autotest core # docker logs stf-auth-3200
INF/auth-ldap 1 [*] Listening on port 3000
WRN/auth-ldap 1 [::ffff:192.168.2.86] Authentication failure for "y.n"
Unhandled rejection InvalidCredentialsError
    at EventEmitter.endListener (/app/lib/util/ldaputil.js:78:25)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at sendResult (/app/node_modules/ldapjs/lib/client/client.js:1389:22)
    at messageCallback (/app/node_modules/ldapjs/lib/client/client.js:1421:16)
    at Parser.onMessage (/app/node_modules/ldapjs/lib/client/client.js:1089:14)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:111:8)
    at end (/app/node_modules/ldapjs/lib/messages/parser.js:66:19)
    at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:112:10)
    at end (/app/node_modules/ldapjs/lib/messages/parser.js:66:19)
    at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:112:10)
    at end (/app/node_modules/ldapjs/lib/messages/parser.js:66:19)
    at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:112:10)
    at Socket.onData (/app/node_modules/ldapjs/lib/client/client.js:1076:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

could you, please, give name of framework that you use for the ldap to get correct examples? 
because main confuse is about:
STF_AUTH_LDAP_LDAP_SEARCH_CLASS
STF_AUTH_LDAP_LDAP_SEARCH_FIELD
STF_AUTH_LDAP_LDAP_SEARCH_SCOPE

**Comment by sorccu** [comment]
See https://github.com/openstf/stf/blob/3b632b4314ccc28739a06a2a5de451e75fef63ca/lib/util/ldaputil.js and http://ldapjs.org/.

**Comment by mrPsycho** [comment]
thanks.

still has this error :(

what the difference between STF_AUTH_LDAP_LDAP_USERNAME_FIELD and STF_AUTH_LDAP_LDAP_SEARCH_FIELD?

**Comment by sorccu** [comment]
`STF_AUTH_LDAP_LDAP_SEARCH_FIELD` is the field name to search against for the given username. If a match is found, it will return an object with multiple properties. `STF_AUTH_LDAP_LDAP_USERNAME_FIELD` is used to select one of those properties to display in the STF UI, and to use as a unique identifier for the user.

**Comment by mrPsycho** [comment]
thanks, so i understand why `STF_AUTH_LDAP_LDAP_SEARCH_FIELD ` is required. 

but, now i totally lost in configuration... 

```
  -e "STF_AUTH_LDAP_LDAP_BIND_CREDENTIALS=pass"\
  -e "STF_AUTH_LDAP_LDAP_BIND_DN=CN=stf bind,OU=System Users,DC=domain,DC=local" \
  -e "STF_AUTH_LDAP_LDAP_SEARCH_DN=DC=domain,DC=local" \
  -e "STF_AUTH_LDAP_LDAP_TIMEOUT=360" \
  -e "STF_AUTH_LDAP_LDAP_URL=ldap://192.168.2.100:389" \
  -e "STF_AUTH_LDAP_LDAP_SEARCH_CLASS=(objectClass=person)" \
  -e "STF_AUTH_LDAP_LDAP_SEARCH_SCOPE=sub" \
  -e "STF_AUTH_LDAP_LDAP_SEARCH_FIELD=sAMAccountName" \
  -e "STF_AUTH_LDAP_LDAP_USERNAME_FIELD=displayName" \
```

this looks fully correct. 

and last one `STF_AUTH_LDAP_LDAP_BIND_DN`. this is could be wrong, but... 
if binding works well (i checked it with wrong pass and it fails), so it should be correct too.

`STF_AUTH_LDAP_LDAP_SEARCH_CLASS` as i understand, it now correct too. 
i tried `STF_AUTH_LDAP_LDAP_SEARCH_CLASS=(objectClass=*)`, but it doesn't help. 

all other configs like:
`STF_AUTH_LDAP_LDAP_SEARCH_CLASS=objectClass=person`
`STF_AUTH_LDAP_LDAP_SEARCH_CLASS=person`
are failing on start, and i think its because of syntax errors. 

where i should look deeper?

**Comment by mrPsycho** [comment]
so... i tried several configs with several servers.... and now i can say - LDAP is not working (

**Comment by sorccu** [comment]
Have you tried running the search queries manually with a command line tool to see if they’re working?

**Comment by mrPsycho** [comment]
yep, if you mean 'ldapsearch' command.

also i configured all other services (such as jenkins, nextcloud, gitlab, rednine, etc.)  in my office and they all work.

**Comment by artigomc** [comment]
@mrPsycho did you fix this issue?

**Comment by Amrkamel1** [comment]
> yep, if you mean 'ldapsearch' command.
> 
> also i configured all other services (such as jenkins, nextcloud, gitlab, rednine, etc.) in my office and they all work.



> yep, if you mean 'ldapsearch' command.
> 
> also i configured all other services (such as jenkins, nextcloud, gitlab, rednine, etc.) in my office and they all work.

@mrPsycho could you please provide your last working config cuz currently im facing same issue

**Comment by mrPsycho** [comment]
sorry, i can't help you. 
we switched off this software
