### ISSUE TITLE
How can I run stf on localhost?

### ISSUE THREAD

**Issue by unverb** [openstf/stf#74]
$ netstat -anp | grep 7100
    $ tcp6       0      0 :::7100                 :::*                    LISTEN      19521/node

How can I run stf on localhost? I would like the following output "127.0.0.1:7100". But it's not. (I see and try deployment paper)

**Comment by sorccu** [comment]
Maybe try accessing it with http://localhost:7100 instead of http://127.0.0.1:7100?

**Comment by unverb** [comment]
Yes you are right, i am accessing it. But i want to forward on nginx(proxy_pass option). They conflicts(nginx and stf -> 0.0.0.0:7100). How to fix it?

**Comment by sorccu** [comment]
Do you mean that you want to run both of them on the same port? Or that you can't use 127.0.0.1 in your proxy_pass? If the latter, you can either use `[::1]` or `localhost` instead, or tweak your system settings to somehow not discriminate against IPv4. I'm not sure how to do that so you'll have to do some googling.

**Comment by kartx22** [comment]
kartx22:~/workspace (master) $ stf local
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js migrate"
INF/db 52255 [*] Connecting to 127.0.0.1:28015
INF/db:setup 52255 [*] Database "stf" already exists
INF/db:setup 52255 [*] Table "users" already exists
INF/db:setup 52255 [*] Table "devices" already exists
INF/db:setup 52255 [*] Table "logs" already exists
INF/db:setup 52255 [*] Index "users"."adbKeys" already exists
INF/db:setup 52255 [*] Index "devices"."owner" already exists
INF/db:setup 52255 [*] Index "devices"."present" already exists
INF/db:setup 52255 [*] Index "devices"."providerChannel" already exists
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js provider --name kartx22-stf-2306377 --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js storage-temp --port 7102"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
INF/util:procutil 52250 [*] Forking "/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/stf/lib/cli.js poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
INF/triproxy 52260 [app001] PUB socket bound on tcp://127.0.0.1:7111
INF/triproxy 52260 [app001] DEALER socket bound on tcp://127.0.0.1:7112
INF/triproxy 52260 [app001] PULL socket bound on tcp://127.0.0.1:7113
INF/db 52266 [proc001] Connecting to 127.0.0.1:28015
INF/processor 52266 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
INF/processor 52266 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
INF/triproxy 52265 [dev001] PUB socket bound on tcp://127.0.0.1:7114
INF/triproxy 52265 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
INF/triproxy 52265 [dev001] PULL socket bound on tcp://127.0.0.1:7116
INF/reaper 52280 [reaper001] Subscribing to permanent channel "*ALL"
INF/reaper 52280 [reaper001] Reaping devices with no heartbeat
INF/db 52280 [reaper001] Connecting to 127.0.0.1:28015
INF/reaper 52280 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
INF/reaper 52280 [reaper001] Sending output to "tcp://127.0.0.1:7116"
INF/db 52271 [proc002] Connecting to 127.0.0.1:28015
INF/processor 52271 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
INF/poorxy 52316 [*] Listening on port 7100
INF/processor 52271 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
INF/provider 52285 [*] Subscribing to permanent channel "ys8/8DcXTMS4yjsiD1NBDA=="
INF/provider 52285 [*] Sending output to "tcp://127.0.0.1:7116"
INF/provider 52285 [*] Receiving input from "tcp://127.0.0.1:7114"
Unhandled rejection Error: spawn adb ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
INF/storage:plugins:apk 52315 [*] Listening on port 7104
INF/auth-mock 52286 [*] Listening on port 7120
INF/storage:temp 52301 [*] Listening on port 7102
INF/storage:plugins:image 52306 [*] Listening on port 7103
INF/app 52291 [*] Using pre-built resources
INF/app 52291 [*] Listening on port 7105
INF/db 52291 [*] Connecting to 127.0.0.1:28015
INF/websocket 52296 [*] Subscribing to permanent channel "*ALL"
INF/websocket 52296 [*] Listening on port 7110
INF/db 52296 [*] Connecting to 127.0.0.1:28015
INF/websocket 52296 [*] Sending output to "tcp://127.0.0.1:7113"
INF/websocket 52296 [*] Receiving input from "tcp://127.0.0.1:7111"
   


when i enter http://localhost:7100 on browser it only show blank page i try using --public-ip i got no website available on browser

**Comment by vbanthia** [comment]
@kartx22 

Is `adb` properly installed in your system?

You have to install all the prerequisites before running `stf local`.
https://github.com/openstf/stf#requirements

**Comment by kartx22** [comment]
ok ill try to reinstall adb and try again.

**Comment by goddess520** [comment]
I run the prompt on this machine, unable to enter the STF client, what happened?
Can not access this site

localhost rejected our connection request.
Please try the following:
Check the network connection
Check the proxy server and firewall
ERR_CONNECTION_REFUSED
