### ISSUE TITLE
stf local start failed

### ISSUE THREAD

**Issue by 888niannianwang** [openstf/stf#764]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
2017-11-29T03:10:46.979Z FTL/cli:local 1571 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
2017-11-29T03:10:46.979Z INF/cli:local 1571 [*] Shutting down all child processes
2017-11-29T03:10:46.987Z INF/util:lifecycle 1583 [app001] Winding down for graceful exit
2017-11-29T03:10:46.988Z INF/util:lifecycle 1589 [dev001] Winding down for graceful exit
2017-11-29T03:10:46.996Z INF/util:lifecycle 1596 [proc002] Winding down for graceful exit
2017-11-29T03:10:46.996Z INF/util:lifecycle 1608 [*] Winding down for graceful exit
2017-11-29T03:10:46.997Z INF/util:lifecycle 1595 [proc001] Winding down for graceful exit
2017-11-29T03:10:47.001Z INF/util:lifecycle 1614 [*] Winding down for graceful exit
2017-11-29T03:10:47.003Z WRN/db 1595 [proc001] Connection closed
2017-11-29T03:10:47.003Z INF/util:lifecycle 1602 [reaper001] Winding down for graceful exit
2017-11-29T03:10:47.008Z INF/auth-mock 1614 [*] Waiting for client connections to end
2017-11-29T03:10:47.012Z WRN/db 1596 [proc002] Connection closed
2017-11-29T03:10:47.014Z WRN/db 1602 [reaper001] Connection closed
2017-11-29T03:10:47.051Z INF/websocket 1632 [*] Subscribing to permanent channel "*ALL"
2017-11-29T03:10:47.057Z INF/websocket 1632 [*] Listening on port 7110
2017-11-29T03:10:47.058Z INF/util:lifecycle 1632 [*] Winding down for graceful exit
2017-11-29T03:10:47.060Z INF/db 1632 [*] Connecting to 127.0.0.1:28015

**Please run `stf doctor` and paste the output here.**
![wechatimg84](https://user-images.githubusercontent.com/18587194/33356365-0b7f36de-d4f7-11e7-8e7b-1b36d17f4cdf.jpeg)

**Comment by sorccu** [comment]
Your log is too short. I need to see at least 10, preferably 100 lines before the error.

**Comment by 888niannianwang** [comment]
2017-11-29T03:29:53.846Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli migrate"
2017-11-29T03:29:54.140Z INF/db 1714 [*] Connecting to 127.0.0.1:28015
2017-11-29T03:29:54.160Z INF/db:setup 1714 [*] Database "stf" already exists
2017-11-29T03:29:54.170Z INF/db:setup 1714 [*] Table "users" already exists
2017-11-29T03:29:54.170Z INF/db:setup 1714 [*] Table "accessTokens" already exists
2017-11-29T03:29:54.170Z INF/db:setup 1714 [*] Table "vncauth" already exists
2017-11-29T03:29:54.171Z INF/db:setup 1714 [*] Table "devices" already exists
2017-11-29T03:29:54.171Z INF/db:setup 1714 [*] Table "logs" already exists
2017-11-29T03:29:54.187Z INF/db:setup 1714 [*] Index "users"."adbKeys" already exists
2017-11-29T03:29:54.187Z INF/db:setup 1714 [*] Index "accessTokens"."email" already exists
2017-11-29T03:29:54.187Z INF/db:setup 1714 [*] Index "vncauth"."response" already exists
2017-11-29T03:29:54.187Z INF/db:setup 1714 [*] Index "vncauth"."responsePerDevice" already exists
2017-11-29T03:29:54.187Z INF/db:setup 1714 [*] Index "devices"."owner" already exists
2017-11-29T03:29:54.187Z INF/db:setup 1714 [*] Index "devices"."present" already exists
2017-11-29T03:29:54.187Z INF/db:setup 1714 [*] Index "devices"."providerChannel" already exists
2017-11-29T03:29:54.188Z INF/db:setup 1714 [*] Waiting for index "users"."adbKeys"
2017-11-29T03:29:54.189Z INF/db:setup 1714 [*] Waiting for index "accessTokens"."email"
2017-11-29T03:29:54.189Z INF/db:setup 1714 [*] Waiting for index "vncauth"."response"
2017-11-29T03:29:54.190Z INF/db:setup 1714 [*] Waiting for index "vncauth"."responsePerDevice"
2017-11-29T03:29:54.190Z INF/db:setup 1714 [*] Waiting for index "devices"."owner"
2017-11-29T03:29:54.190Z INF/db:setup 1714 [*] Waiting for index "devices"."present"
2017-11-29T03:29:54.191Z INF/db:setup 1714 [*] Waiting for index "devices"."providerChannel"
2017-11-29T03:29:54.196Z INF/db:setup 1714 [*] Index "users"."adbKeys" is ready
2017-11-29T03:29:54.196Z INF/db:setup 1714 [*] Index "accessTokens"."email" is ready
2017-11-29T03:29:54.196Z INF/db:setup 1714 [*] Index "vncauth"."response" is ready
2017-11-29T03:29:54.196Z INF/db:setup 1714 [*] Index "vncauth"."responsePerDevice" is ready
2017-11-29T03:29:54.196Z INF/db:setup 1714 [*] Index "devices"."owner" is ready
2017-11-29T03:29:54.196Z INF/db:setup 1714 [*] Index "devices"."present" is ready
2017-11-29T03:29:54.197Z INF/db:setup 1714 [*] Index "devices"."providerChannel" is ready
2017-11-29T03:29:54.205Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2017-11-29T03:29:54.209Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2017-11-29T03:29:54.211Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2017-11-29T03:29:54.213Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2017-11-29T03:29:54.222Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2017-11-29T03:29:54.234Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli provider --name aslanatc --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"
2017-11-29T03:29:54.254Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
2017-11-29T03:29:54.274Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
2017-11-29T03:29:54.285Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
2017-11-29T03:29:54.302Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2017-11-29T03:29:54.318Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-temp --port 7102"
2017-11-29T03:29:54.330Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2017-11-29T03:29:54.350Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2017-11-29T03:29:54.378Z INF/util:procutil 1708 [*] Forking "/usr/lib/node_modules/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
2017-11-29T03:29:55.372Z INF/triproxy 1726 [dev001] PUB socket bound on tcp://127.0.0.1:7114
2017-11-29T03:29:55.386Z INF/triproxy 1726 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
2017-11-29T03:29:55.397Z INF/triproxy 1726 [dev001] PULL socket bound on tcp://127.0.0.1:7116
2017-11-29T03:29:55.682Z INF/triproxy 1720 [app001] PUB socket bound on tcp://127.0.0.1:7111
2017-11-29T03:29:55.706Z INF/triproxy 1720 [app001] DEALER socket bound on tcp://127.0.0.1:7112
2017-11-29T03:29:55.720Z INF/triproxy 1720 [app001] PULL socket bound on tcp://127.0.0.1:7113
2017-11-29T03:29:56.126Z INF/poorxy 1793 [*] Listening on port 7100
2017-11-29T03:29:56.203Z INF/db 1727 [*] Connecting to 127.0.0.1:28015
2017-11-29T03:29:56.264Z INF/db 1738 [*] Connecting to 127.0.0.1:28015
2017-11-29T03:29:56.302Z INF/processor 1727 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
2017-11-29T03:29:56.309Z INF/processor 1727 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
2017-11-29T03:29:56.299Z INF/reaper 1739 [reaper001] Subscribing to permanent channel "*ALL"
2017-11-29T03:29:56.316Z INF/reaper 1739 [reaper001] Reaping devices with no heartbeat
2017-11-29T03:29:56.344Z INF/db 1739 [reaper001] Connecting to 127.0.0.1:28015
2017-11-29T03:29:56.379Z INF/processor 1738 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
2017-11-29T03:29:56.382Z INF/reaper 1739 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
2017-11-29T03:29:56.390Z INF/reaper 1739 [reaper001] Sending output to "tcp://127.0.0.1:7116"
2017-11-29T03:29:56.390Z INF/processor 1738 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
2017-11-29T03:29:56.593Z INF/storage:plugins:image 1781 [*] Listening on port 7103
2017-11-29T03:29:56.649Z INF/auth-mock 1751 [*] Listening on port 7120
2017-11-29T03:29:56.732Z INF/provider 1745 [*] Subscribing to permanent channel "FxB/KFKeT2iWeT4+Pqexzg=="
2017-11-29T03:29:56.760Z INF/storage:plugins:apk 1787 [*] Listening on port 7104
2017-11-29T03:29:56.768Z INF/provider 1745 [*] Sending output to "tcp://127.0.0.1:7116"
2017-11-29T03:29:56.771Z INF/provider 1745 [*] Receiving input from "tcp://127.0.0.1:7114"
2017-11-29T03:29:56.783Z INF/provider 1745 [*] Tracking devices
2017-11-29T03:29:56.929Z INF/storage:temp 1775 [*] Listening on port 7102
2017-11-29T03:29:57.021Z INF/app 1757 [*] Using webpack
/usr/bin/nodejs /usr/lib/node_modules/stf/lib/cli app

Options:
  -h, --help           Show help.                                      [boolean]
  -V, --version        Show version.                                   [boolean]
  --auth-url, -a       URL to the auth unit.                 [string] [required]
  --port, -p           The port to bind to.             [number] [default: 7105]
  --secret, -s         The secret to use for auth JSON Web Tokens. Anyone who
                       knows this token can freely enter the system if they
                       want, so keep it safe.                [string] [required]
  --ssid, -i           The name of the session ID cookie.
                                                      [string] [default: "ssid"]
  --user-profile-url   URL to an external user profile page.            [string]
  --websocket-url, -w  URL to the websocket unit.            [string] [required]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_APP_` (e.g. `STF_APP_AUTH_URL`).

Cannot find module './../../../webpack.config'
2017-11-29T03:29:57.045Z FTL/cli:local 1708 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
2017-11-29T03:29:57.045Z INF/cli:local 1708 [*] Shutting down all child processes
2017-11-29T03:29:57.050Z INF/util:lifecycle 1720 [app001] Winding down for graceful exit
2017-11-29T03:29:57.050Z INF/util:lifecycle 1726 [dev001] Winding down for graceful exit
2017-11-29T03:29:57.058Z INF/util:lifecycle 1727 [proc001] Winding down for graceful exit
2017-11-29T03:29:57.061Z INF/util:lifecycle 1738 [proc002] Winding down for graceful exit
2017-11-29T03:29:57.064Z WRN/db 1727 [proc001] Connection closed
2017-11-29T03:29:57.065Z INF/util:lifecycle 1745 [*] Winding down for graceful exit
2017-11-29T03:29:57.066Z INF/util:lifecycle 1751 [*] Winding down for graceful exit
2017-11-29T03:29:57.073Z WRN/db 1738 [proc002] Connection closed
2017-11-29T03:29:57.073Z INF/auth-mock 1751 [*] Waiting for client connections to end
2017-11-29T03:29:57.065Z INF/util:lifecycle 1739 [reaper001] Winding down for graceful exit
2017-11-29T03:29:57.080Z WRN/db 1739 [reaper001] Connection closed
2017-11-29T03:29:57.097Z INF/websocket 1769 [*] Subscribing to permanent channel "*ALL"
2017-11-29T03:29:57.102Z INF/websocket 1769 [*] Listening on port 7110
2017-11-29T03:29:57.103Z INF/util:lifecycle 1769 [*] Winding down for graceful exit
2017-11-29T03:29:57.105Z INF/db 1769 [*] Connecting to 127.0.0.1:28015

this is all my log ,please help

**Comment by mrPsycho** [comment]
look like you don't have `./../../../webpack.config`

so it could be related to #651 or #40. 
i'd suggest to check these two issues for solution and give more information it it doesn't help.

**Comment by 888niannianwang** [comment]
My problem is similar to #651，If I install webpack by running "sudo npm install webpack", I get the following warnings and the problem of missing webpack.config is still unresolved.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/home/qiniu/package.json'
npm WARN qiniu No description
npm WARN qiniu No repository field.
npm WARN qiniu No README data
npm WARN qiniu No license field.

but in my device bower and gulp were there
qiniu@aslanatc:~$ bower --version
1.8.2
qiniu@aslanatc:~$ gulp --version
[09:35:38] CLI version 3.9.1

I don't know what's wrong ，please help me ,thanks

**Comment by sorccu** [comment]
If you install stf from npm, you don't need webpack. It ships with prebuilt assets.

**Comment by 888niannianwang** [comment]
Yes,i install stf from npm , sudo npm install -g stf.   But,why the log  display " Cannot find module './../../../webpack.config'  "

**Comment by sorccu** [comment]
Please guys, stop using sudo. I know it's convenient to install Node from your package manager, but it truly sucks and can make so many things not work. Set up [nvm](https://github.com/creationix/nvm) and try again with that. If at any point you use sudo, you're doing something wrong.

When everything goes as expected, you should see the following line in the STF output:

```
INF/app 13302 [*] Using pre-built resources
```

Just to make sure that things are not broken, I ran `npm install -g stf` followed by `stf local` and everything went well.

**Comment by 888niannianwang** [comment]
My problem was resolved. I ran **npm install -g stf**  and  sudo chown the directory
everything went well. 
Thanks @sorccu

**Comment by sorccu** [comment]
Great! I would still recommend using nvm though.

**Comment by sorccu** [comment]
Please search past issues, this happens quite a lot. Basically you either didn’t install all dependencies and/or you need to nuke node_modules and reinstall.
