### ISSUE TITLE
gyp rebuild failed

### ISSUE THREAD

**Issue by 6a209** [openstf/stf#77]
sudo npm install -g stf

Mac 10.10   node 4.0.0

make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
 stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/stf/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0

**Comment by gunta** [comment]
Node 4.0.0 was released two days ago, we still don't support it.
Try to use the previous node 0.12 version until we add support for the new node.js.

**Comment by 6a209** [comment]
OK

**Comment by edess** [comment]
I spent last 2 days trying to run "npm install opencv" but it was working because my used node version was the 4.0.0. 
But thank to you guys, I came back to use node 0.12.7 and now , the command succeeded to install opencv. 

thanks a lot!!!

**Comment by plessbd** [comment]
```diff
diff --git a/package.json b/package.json
index 1635d21..087fd3c 100644
--- a/package.json
+++ b/package.json
@@ -56,12 +56,12 @@
     "lodash": "^3.10.1",
     "markdown-serve": "^0.3.2",
     "mime": "^1.3.4",
-    "minimatch": "^2.0.10",
+    "minimatch": "^3.0.0",
     "my-local-ip": "^1.0.0",
     "node-uuid": "^1.4.3",
     "passport": "^0.3.0",
     "passport-oauth2": "^1.1.2",
-    "protobufjs": "^3.8.2",
+    "protobufjs": "^4.1.1",
     "proxy-addr": "^1.0.7",
     "request": "^2.61.0",
     "request-progress": "^0.3.1",
```
that fixed it for me

however, it produced a new error

```
WRN/device:plugins:data 75973 [DEVICE SERIAL] Unable to find device data { serial: 'DEVICE SERIAL',
  platform: 'Android',
  manufacturer: 'MOTOROLA',
  operator: '',
  model: 'XT1049',
  version: '4.4.4',
  abi: 'armeabi-v7a',
  sdk: '19',
  product: 'ghost_repw',
  display:
   { id: 0,
     width: 720,
     height: 1280,
     xdpi: 315.6499938964844,
     ydpi: 315.30999755859375,
     fps: 60,
     density: 2,
     rotation: 90,
     secure: true,
     size: 4.656448360854734,
     url: 'ws://localhost:7400' },
  phone:
   { imei: 'VALID IMEI',
     phoneNumber: 'VALID PHONE',
     iccid: 'VALID ICCID',
     network: 'LTE' } }
INF/device:plugins:touch 75973 [DEVICE SERIAL] Touch origin is top left
INF/device:plugins:touch 75973 [DEVICE SERIAL] Requesting touch consumer to start
INF/device:plugins:touch 75973 [DEVICE SERIAL] Launching screen service
INF/device:plugins:touch 75973 [DEVICE SERIAL] Connecting to minitouch service
INF/device:plugins:touch 75973 [DEVICE SERIAL] minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
INF/device:plugins:touch 75973 [DEVICE SERIAL] minitouch says: "Type B touch device synaptics_dsx_i2c (719x1279 with 10 contacts) detected on /dev/input/event2 (score 1100)"
INF/webpack:config 75967 [*] Build progress 64% (108/120 build modules)
INF/device:plugins:touch 75973 [DEVICE SERIAL] Reading minitouch banner
INF/device:plugins:touch 75973 [DEVICE SERIAL] minitouch says: "Connection established"
INF/device:plugins:vnc 75973 [DEVICE SERIAL] Starting VNC server on port 7402
INF/device:plugins:browser 75973 [DEVICE SERIAL] Loading browser list
INF/device:plugins:browser 75973 [DEVICE SERIAL] Updating browser list
INF/device:plugins:mute 75973 [DEVICE SERIAL] Will not mute master volume during use
INF/device:plugins:forward 75973 [DEVICE SERIAL] Launching reverse port forwarding service
INF/device:plugins:forward 75973 [DEVICE SERIAL] Connecting to reverse port forwarding service
INF/device:plugins:connect 75973 [DEVICE SERIAL] Listening on port 7401
INF/device 75973 [DEVICE SERIAL] Fully operational
INF/webpack:config 75967 [*] Build progress 67% (116/121 build modules)
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: keyOrObj.hasOwnProperty is not a function
    at MessagePrototype.set (/Users/name/stf/node_modules/protobufjs/dist/ProtoBuf.js:2444:42)
    at Message (/Users/name/stf/node_modules/protobufjs/dist/ProtoBuf.js:2374:34)
    at Router.<anonymous> (/Users/name/stf/lib/units/device/plugins/solo.js:43:11)
    at Router.emit (/Users/name/stf/node_modules/eventemitter3/index.js:74:35)
    at Router.<anonymous> (/Users/name/stf/lib/wire/router.js:36:12)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket._flush (/Users/name/stf/node_modules/zmq/lib/index.js:554:17)
    at _zmq.onReady (/Users/name/stf/node_modules/zmq/lib/index.js:203:12)
INF/provider 75965 [*] Cleaning up device worker "DEVICE SERIAL"
ERR/provider 75965 [*] Device worker "DEVICE SERIAL" died with code 1
```

**Comment by sorccu** [comment]
Actually Node 4 is supported since a few weeks ago, you don't have to modify package.json. We're currently developing with 4.1.2. And please don't update random modules, there's a reason why some of them are not using their latest versions. The error you're seeing is #106.
