### ISSUE TITLE
Cannot connect emulator based devices to STF

### ISSUE THREAD

**Issue by elphienn** [openstf/stf#789]
Hi,
I am using STF 3.2.0 version. and There's issues during attaching emulators to STF.
I wanted to attach android emulators on server version of centos. 
So when I ran the emulator, I used  -no-skin -no-audio -no-window options. 

I have the 2 questions for this errors. and details are described on below.
- When I clicked the device from STF main screen, Error was occurred. 
- Attaching arm based emulator was failed.

<br><br>

## development environment
- Centos7.4 VM, 64bit
- hardware machine : x86_64
- server mode, no UI
- AVD info
  Name: testAVD3
  Target: Google APIs (Google Inc.)
          Based on: Android 6.0 (Marshmallow) Tag/ABI: google_apis/x86

  Name: testAVD7
  Target: Google APIs (Google Inc.)
          Based on: Android 7.0 (Nougat) Tag/ABI: google_apis/armeabi-v7a

## stf doctor
2018-01-03T02:16:06.250Z INF/cli:doctor 110396 [*] OS Arch: x64
2018-01-03T02:16:06.253Z INF/cli:doctor 110396 [*] OS Platform: linux
2018-01-03T02:16:06.253Z INF/cli:doctor 110396 [*] OS Platform: 3.10.0-693.2.2.el7.x86_64
2018-01-03T02:16:06.253Z INF/cli:doctor 110396 [*] Using Node 6.12.0
2018-01-03T02:16:06.303Z INF/cli:doctor 110396 [*] Using ZeroMQ 4.1.4
2018-01-03T02:16:06.323Z INF/cli:doctor 110396 [*] Using ADB 1.0.31
2018-01-03T02:16:06.470Z INF/cli:doctor 110396 [*] Using GraphicsMagick 1.3.27a
2018-01-03T02:16:06.476Z ERR/cli:doctor 110396 [*] Unexpected error checking GraphicsMagick: TypeError: Invalid Version: 1.3.27a
2018-01-03T02:16:06.558Z INF/cli:doctor 110396 [*] Using RethinkDB 2.3.6
2018-01-03T02:16:06.567Z INF/cli:doctor 110396 [*] Using ProtoBuf 3.5.0
<br><br>
## 1. When I clicked the device from STF main screen, the device is disconnected. 

* Case description : x86 based emulator
> ./avdmanager create avd --force --name testAVD3 --abi google_apis/x86 --package 'system-images;android-26;google_apis;x86'
> ./emulator -avd testAVD3 -no-skin -no-audio -no-window &
- log : [log_x86_case1.txt](https://github.com/openstf/stf/files/1599399/log_x86_case1.txt)
* part of error message on log
2018-01-03T03:50:29.365Z WRN/device:plugins:screen:stream 120143 
[emulator-5554] Shell keeping minicap running ended unexpectedly
2018-01-03T03:50:29.367Z INF/device:plugins:screen:stream 120143 [emulator-5554] Disconnecting from minicap service
2018-01-03T03:50:29.368Z FTL/device:plugins:screen:stream 120143 [emulator-5554] Frame producer had an error Error: Failed more than 3 times in 10000ms
    at FrameProducer._failLimitExceeded (/usr/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:222:26)
    at FailCounter.emit (/usr/lib/node_modules/stf/node_modules/eventemitter3/index.js:117:35)
    at FailCounter.inc (/usr/lib/node_modules/stf/lib/util/failcounter.js:29:10)
    at FrameProducer._outputEnded (/usr/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:215:24)
    at RiskyStream.emit (/usr/lib/node_modules/stf/node_modules/eventemitter3/index.js:115:35)
    at RiskyStream.<anonymous> (/usr/lib/node_modules/stf/lib/util/riskystream.js:14:12)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
2018-01-03T03:50:29.370Z FTL/util:lifecycle 120143 [emulator-5554] Shutting down due to fatal error
2018-01-03T03:50:29.399Z INF/provider 116273 [*] Cleaning up device worker "emulator-5554"
2018-01-03T03:50:29.401Z ERR/provider 116273 [*] Device worker "emulator-5554" died with code 1
2018-01-03T03:50:29.401Z INF/provider 116273 [*] Restarting device worker "emulator-5554"
2018-01-03T03:50:30.780Z INF/device:support:push 120217 [emulator-5554] Sending output to "tcp://127.0.0.1:7116"

<br><br>
## 2. Attaching arm based emulator was failed. 

* Case description : armeabi-v7a based emulator
> ./avdmanager create avd --name testAVD7 --abi google_apis/armeabi-v7a --package 'system-images;android-24;google_apis;armeabi-v7a'
> ./emulator  -avd testAVD7 -no-skin -no-audio -no-window &
- log :  [log_arm_emul.txt](https://github.com/openstf/stf/files/1599479/log_arm_emul.txt)
- test result : Keep waiting for completion of booting for more than 20 mins

Thanks in advance.

**Comment by sorccu** [comment]
Thanks for the detailed description, but I’m going to have to ask you to look at old issues. In general, emulators are not supported, but some people have managed to get them to work. Please see past issues for their reports.
