### ISSUE TITLE
Disconnection from some minicap failures

### ISSUE THREAD

**Issue by paulirish** [openstf/stf#8]
I had two devices up and running. Tried to do adb connect on one of them. It seemed to work but then I had a failure.
Looks like it came from minicap but STF disconnected as a result.

Feel free to close, but figured you'd appreciate the report.

Cheers guys. (This project is blowing my mind)

```
INF/device:plugins:connect 80128 [T076001226] New remote ADB connection from ::ffff:127.0.0.1
INF/provider 80100 [*] Found device "localhost:7403" (offline)
INF/reaper 80099 [reaper001] Device "localhost:7403" is present
INF/provider 80100 [*] Registered device "localhost:7403"
INF/provider 80100 [*] Providing all 2 of 3 device(s); ignoring "localhost:7403"
INF/provider 80100 [*] Device "localhost:7403" is now "device" (was "offline")
INF/device:support:push 80167 [localhost:7403] Sending output to "tcp://127.0.0.1:7116"
INF/device 80167 [localhost:7403] Preparing device
INF/device:support:sub 80167 [localhost:7403] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 80167 [localhost:7403] Subscribing to permanent channel "*ALL"
INF/device:support:properties 80167 [localhost:7403] Loading properties
INF/device:support:abi 80167 [localhost:7403] Supports ABIs armeabi-v7a, armeabi
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (jni/minicap/minicap.cpp:176) Received SIGTERM, stopping"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (jni/minicap/minicap.cpp:478) Closing client connection"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:280) Destroying virtual display"
WRN/device:plugins:screen:stream 80128 [T076001226] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 80128 [T076001226] Disconnecting from minicap service
INF/device:plugins:screen:stream 80128 [T076001226] Stopping minicap service
INF/device:plugins:screen:stream 80128 [T076001226] Launching screen service
INF/device:plugins:screen:stream 80128 [T076001226] Connecting to minicap service
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "PID: 19794"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: Using projection 720x1280@377x670/0"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:236) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:239) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:246) Creating virtual display"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:252) Creating buffer queue"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:257) Creating CPU consumer"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:261) Creating frame waiter"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:265) Publishing virtual display"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
INF/device:plugins:screen:stream 80128 [T076001226] Reading minicap banner
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (jni/minicap/minicap.cpp:423) New client connection"
WRN/device:plugins:screen:stream 80128 [T076001226] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 80128 [T076001226] Disconnecting from minicap service
INF/device:plugins:screen:stream 80128 [T076001226] Stopping minicap service
INF/device:plugins:screen:stream 80128 [T076001226] Launching screen service
INF/device:plugins:screen:stream 80128 [T076001226] Connecting to minicap service
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "PID: 19843"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: Using projection 720x1280@377x670/0"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:236) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:239) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:246) Creating virtual display"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:252) Creating buffer queue"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:257) Creating CPU consumer"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:261) Creating frame waiter"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:265) Publishing virtual display"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
INF/device:plugins:screen:stream 80128 [T076001226] Reading minicap banner
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (jni/minicap/minicap.cpp:423) New client connection"
WRN/device:plugins:screen:stream 80128 [T076001226] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 80128 [T076001226] Disconnecting from minicap service
INF/device:plugins:screen:stream 80128 [T076001226] Stopping minicap service
INF/device:plugins:screen:stream 80128 [T076001226] Launching screen service
INF/device:plugins:screen:stream 80128 [T076001226] Connecting to minicap service
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "PID: 19892"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: Using projection 720x1280@377x670/0"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:236) Creating SurfaceComposerClient"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:239) Performing SurfaceComposerClient init check"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:246) Creating virtual display"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:252) Creating buffer queue"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:257) Creating CPU consumer"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:261) Creating frame waiter"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (external/MY_minicap/src/minicap_22.cpp:265) Publishing virtual display"
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
INF/device:plugins:screen:stream 80128 [T076001226] Reading minicap banner
INF/device:plugins:screen:stream 80128 [T076001226] minicap says: "INFO: (jni/minicap/minicap.cpp:423) New client connection"
WRN/device:plugins:screen:stream 80128 [T076001226] Shell keeping minicap running ended unexpectedly
INF/device:plugins:screen:stream 80128 [T076001226] Disconnecting from minicap service
FTL/device:plugins:screen:stream 80128 [T076001226] Frame producer had an error Error: Failed more than 3 times in 10000ms
    at FrameProducer._failLimitExceeded (/Users/paulirish/.homebrew/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:219:26)
    at FailCounter.emit (/Users/paulirish/.homebrew/lib/node_modules/stf/node_modules/eventemitter3/index.js:73:35)
    at FailCounter.inc (/Users/paulirish/.homebrew/lib/node_modules/stf/lib/util/failcounter.js:29:10)
    at FrameProducer._outputEnded (/Users/paulirish/.homebrew/lib/node_modules/stf/lib/units/device/plugins/screen/stream.js:212:24)
    at RiskyStream.emit (/Users/paulirish/.homebrew/lib/node_modules/stf/node_modules/eventemitter3/index.js:71:35)
    at RiskyStream.<anonymous> (/Users/paulirish/.homebrew/lib/node_modules/stf/lib/util/riskystream.js:13:12)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
FTL/util:lifecycle 80128 [T076001226] Shutting down due to fatal error

INF/provider 80100 [*] Lost device "localhost:7403" (device)
INF/provider 80100 [*] Shutting down device worker "localhost:7403"
INF/provider 80100 [*] Gracefully killing device worker "localhost:7403"
INF/provider 80100 [*] Cleaning up device worker "T076001226"
ERR/provider 80100 [*] Device worker "T076001226" died with code 1
INF/provider 80100 [*] Restarting device worker "T076001226"
FTL/device 80167 [localhost:7403] Setup had an error FailError: Failure: 'device not found'
    at /Users/paulirish/.homebrew/lib/node_modules/stf/node_modules/adbkit/lib/adb/parser.js:226:31
From previous event:
    at Parser.readError (/Users/paulirish/.homebrew/lib/node_modules/stf/node_modules/adbkit/lib/adb/parser.js:225:31)
    at /Users/paulirish/.homebrew/lib/node_modules/stf/node_modules/adbkit/lib/adb/command/host/transport.js:25:35
From previous event:
    at HostTransportCommand.execute (/Users/paulirish/.homebrew/lib/node_modules/stf/node_modules/adbkit/lib/adb/command/host/transport.js:19:39)
    at /Users/paulirish/.homebrew/lib/node_modules/stf/node_modules/adbkit/lib/adb/client.js:257:47
From previous event:
    at Client.transport (/Users/paulirish/.homebrew/lib/node_modules/stf/node_modules/adbkit/lib/adb/client.js:256:32)
    at Client.shell (/Users/paulirish/.homebrew/lib/node_modules/stf/node_modules/adbkit/lib/adb/client.js:262:19)
    at devutil.listPidsByComm (/Users/paulirish/.homebrew/lib/node_modules/stf/lib/util/devutil.js:69:14)
    at devutil.killProcsByComm (/Users/paulirish/.homebrew/lib/node_modules/stf/lib/util/devutil.js:106:18)
    at /Users/paulirish/.homebrew/lib/node_modules/stf/lib/util/devutil.js:122:26
From previous event:
    at /Users/paulirish/.homebrew/lib/node_modules/stf/lib/util/devutil.js:121:15
From previous event:
    at devutil.killProcsByComm (/Users/paulirish/.homebrew/lib/node_modules/stf/lib/util/devutil.js:107:6)
    at /Users/paulirish/.homebrew/lib/node_modules/stf/lib/util/devutil.js:122:26
    at processImmediate [as _immediateCallback] (timers.js:358:17)
FTL/util:lifecycle 80167 [localhost:7403] Shutting down due to fatal error
INF/provider 80100 [*] Device worker "localhost:7403" has retired
```

**Comment by sorccu** [comment]
Hi!

Be sure to use 1.0.3 or later (and do `npm install` for updated deps) if you want to try `adb connect`. We had a bug in our implementation that newer versions of ADB brought up.

The error you're seeing is actually a bit different. You see, STF also supports `adb connect`ed devices. So what happens is that STF sets up your local USB device first. Then do you `adb connect` and it sees a second device, and tries to set it up too. However because you already had STF running on that device it fails because of the "double-setup". I'm currently thinking about perhaps disabling `localhost` sources from being set up automatically without some command line option, but what you can do right now is to give `stf local` the serial numbers you want to use, and it will ignore the rest (incl. the `adb connect`ed device`), like this: `stf local T076001226`.

You should be able to see both your USB device and the remote device in your chrome developer tools. However, Android Studio is somewhat buggy and will not let you have the same device connected twice, causing random freezes and/or broken functionality in the UI. This happens with the non-STF `adb connect` too if you leave your USB device connected after `adb tcpip 5555`.

Also, since you're testing things out I'll just quickly mention that there's a bug in our reverse port forwarding implementation (Node.js side), causing occasional process deaths if you use that feature. I'm rewriting that part right now.

**Comment by sorccu** [comment]
By the way it would be super awesome if we could get built-in support for `adb connect` in Chrome. There's an open ticket for it but it's being ignored because of the low performance of the native implementation. But it's not the only implementation ;)

**Comment by paulirish** [comment]
I gotcha. Yeah definitely using 1.0.3
In my case I'm running it all on my macbookair. I'll have a moto x and nexus 5 connected by default, maybe more. But then if i `adb connect` for one of these devices, both connections end up failing.  

I see the LOCALHOST entry in chrome:inspect briefly but about 3 seconds later STF dumps it and the `connect` instance is gone from both chrome:inspect and "Disconnected" on the STF device list.  

> I'm currently thinking about perhaps disabling localhost sources from being set up automatically without some command line option

ah no!  that would make it super hard for me.  plus these days the chrome remote debug doesnt need an ADB lock on the devices. so it can share with STF.

I would recommend that for a localhost device, in the Remote Debug block you leave out the `adb connect` field and just say: "hey go to chrome://inspect".  That'd work for me.


>   built-in support for adb connect in Chrome. 

can you point me to the ticket?  

(speaking of performance, the perf of minicap is amazing.)

**Comment by gunta** [comment]
Hi! 

>>   built-in support for adb connect in Chrome. 
>can you point me to the ticket?  
I've opened a [Chromium ticket here](https://code.google.com/p/chromium/issues/detail?id=388206) 1 year ago, but current status is WontFix because "We are experimenting with alternative ways of implementing wireless debugging." Do you have any update on this? 
If there is any work we can do to add support for Chrome directly (without needing to install ADB) we would gladly do it, and it would be awesome.
I've opened the #10 STF ticket to keep track of this.

> (speaking of performance, the perf of minicap is amazing.)
We are planning to make it even faster, the goal is 60fps on any decent device.

**Comment by sorccu** [comment]
Hi, I may be mistaken here but I believe what you're doing right now is:

1. Running `stf local` without any extra args
2. Then on the same machine, running `adb connect localhost:7401`

Doing this causes STF to see the same device twice (because ADB is seeing it twice). Then it tries to set up the same device using both the USB serial and the IP/port pair (which is used as the remote serial). Then it fails since they try to set up the same resources.

With 1.0.3, you can prevent this by running `stf local <your_device_serial_here>` instead of just `stf local`. This will cause STF to ignore the "new" device that `adb connect` adds.

Anyway, I just pushed a change to `master` to require an `--allow-remote` option if you really, really want STF to try and set up remote devices too. This should solve the problem, can you check and confirm? You'll of course still be able to see the device in your chrome developer tools.

**Comment by paulirish** [comment]
Cool. Thanks for working this out with me. I gotta run but will give this a shot tomorrow.

Cheers!
