### ISSUE TITLE
Screen Capture error

### ISSUE THREAD

**Issue by olivierWWB** [openstf/stf#816]
I have two PC use the same codes, one is OK, but another when I use the Screen Capture feature it show this log.
Screen capture failed Error: Upload to "http://localhost:7100/s/upload/image" failed: HTTP 404
    at Request._callback (/Users/my/avatar/lib/units/device/support/storage.js:29:27)
    at Request.self.callback (/Users/my/avatar/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/my/avatar/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/my/avatar/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
Does anybody know the reason?

**Comment by thinkhy** [comment]
Seems your nginx config is incorrect so that you got 404(page not found)

**Comment by seeramzan** [comment]
i am also facing same error
