### ISSUE TITLE
STF setup on CentOS 7 got failure when uploading a apk file

### ISSUE THREAD

**Issue by jonqchk** [openstf/stf#831]
Yes, i am using v.3.2.0
**What is the issue or idea you have?**
STF setup on CentOS 7 got failure when uploading a apk file
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
happened on every devide
**Please provide the steps to reproduce the issue.**
connected to a device, and drag a file to the screen to install
**What is the expected behavior?**
can upload and install the apk
**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
2018-03-21T06:06:15.420Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Keeping 922x922 as current frame producer projection
2018-03-21T06:06:15.421Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Requesting frame producer to start
2018-03-21T06:06:15.421Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Launching screen service
2018-03-21T06:06:15.543Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "PID: 16777"
2018-03-21T06:06:15.543Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: Using projection 1440x2560@519x922/0"
2018-03-21T06:06:15.544Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:241) Creating SurfaceComposerClient"
2018-03-21T06:06:15.545Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Connecting to minicap service
2018-03-21T06:06:15.553Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:244) Performing SurfaceComposerClient init check"
2018-03-21T06:06:15.555Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:255) Creating virtual display"
2018-03-21T06:06:15.555Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:261) Creating buffer queue"
2018-03-21T06:06:15.556Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:264) Setting buffer options"
2018-03-21T06:06:15.557Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:268) Creating CPU consumer"
2018-03-21T06:06:15.557Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:272) Creating frame waiter"
2018-03-21T06:06:15.558Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:276) Publishing virtual display"
2018-03-21T06:06:15.574Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 11061252 bytes for JPG encoder"
2018-03-21T06:06:15.653Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Reading minicap banner
2018-03-21T06:06:15.656Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (jni/minicap/minicap.cpp:448) New client connection"
2018-03-21T06:06:16.899Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Requesting frame producer to stop
2018-03-21T06:06:16.900Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Disconnecting from minicap service
2018-03-21T06:06:16.902Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Stopping minicap service
2018-03-21T06:06:16.902Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Sending SIGTERM to minicap
2018-03-21T06:06:16.947Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (jni/minicap/minicap.cpp:197) Received SIGTERM, stopping"
2018-03-21T06:06:17.001Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (jni/minicap/minicap.cpp:516) Closing client connection"
2018-03-21T06:06:17.001Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:291) Destroying virtual display"
2018-03-21T06:06:23.284Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Keeping 922x922 as current frame producer projection
2018-03-21T06:06:23.284Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Requesting frame producer to start
2018-03-21T06:06:23.285Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Launching screen service
2018-03-21T06:06:23.404Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "PID: 16789"
2018-03-21T06:06:23.405Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: Using projection 1440x2560@519x922/0"
2018-03-21T06:06:23.405Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Connecting to minicap service
2018-03-21T06:06:23.407Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:241) Creating SurfaceComposerClient"
2018-03-21T06:06:23.409Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:244) Performing SurfaceComposerClient init check"
2018-03-21T06:06:23.409Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:255) Creating virtual display"
2018-03-21T06:06:23.411Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:261) Creating buffer queue"
2018-03-21T06:06:23.412Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:264) Setting buffer options"
2018-03-21T06:06:23.412Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:268) Creating CPU consumer"
2018-03-21T06:06:23.412Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:272) Creating frame waiter"
2018-03-21T06:06:23.413Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:276) Publishing virtual display"
2018-03-21T06:06:23.423Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 11061252 bytes for JPG encoder"
2018-03-21T06:06:23.513Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Reading minicap banner
2018-03-21T06:06:23.514Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (jni/minicap/minicap.cpp:448) New client connection"
**2018-03-21T06:06:27.391Z ERR/storage:temp 31497 [*] Error storing resource Error: maxFileSize exceeded, received 2102732 bytes of file data
    at Stream.<anonymous> (/usr/lib/node_modules/stf/node_modules/formidable/lib/incoming_form.js:222:19)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at MultipartParser.parser.onPartData (/usr/lib/node_modules/stf/node_modules/formidable/lib/incoming_form.js:387:14)
    at callback (/usr/lib/node_modules/stf/node_modules/formidable/lib/multipart_parser.js:102:31)
    at dataCallback (/usr/lib/node_modules/stf/node_modules/formidable/lib/multipart_parser.js:115:11)
    at MultipartParser.write (/usr/lib/node_modules/stf/node_modules/formidable/lib/multipart_parser.js:237:15)
    at IncomingForm.write (/usr/lib/node_modules/stf/node_modules/formidable/lib/incoming_form.js:159:34)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/stf/node_modules/formidable/lib/incoming_form.js:125:12)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at IncomingMessage.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at /usr/lib/node_modules/stf/lib/units/storage/temp.js:90:40
    at Layer.handle [as handle_request] (/usr/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/stf/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/stf/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:281:22
    at param (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:275:10)
    at /usr/lib/node_modules/stf/node_modules/express-validator/lib/express_validator.js:291:5
    at Layer.handle [as handle_request] (/usr/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:317:13)
    at /usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/usr/lib/node_modules/stf/node_modules/body-parser/lib/types/json.js:118:7)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:317:13)
    at /usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/lib/node_modules/stf/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/stf/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:317:13)
    at /usr/lib/node_modules/stf/node_modules/express/lib/router/index.js:284:7**
2018-03-21T06:06:47.045Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Requesting frame producer to stop
2018-03-21T06:06:47.045Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Disconnecting from minicap service
2018-03-21T06:06:47.047Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Stopping minicap service
2018-03-21T06:06:47.048Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] Sending SIGTERM to minicap
2018-03-21T06:06:47.092Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (jni/minicap/minicap.cpp:197) Received SIGTERM, stopping"
2018-03-21T06:06:47.199Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (jni/minicap/minicap.cpp:516) Closing client connection"
2018-03-21T06:06:47.200Z INF/device:plugins:screen:stream 31540 [CVH7N16401001220] minicap says: "INFO: (external/MY_minicap/src/minicap_26.cpp:291) Destroying virtual display"

**Please run `stf doctor` and paste the output here.**
2018-03-21T06:17:04.792Z INF/cli:doctor 31609 [*] OS Arch: x64
2018-03-21T06:17:04.794Z INF/cli:doctor 31609 [*] OS Platform: linux
2018-03-21T06:17:04.794Z INF/cli:doctor 31609 [*] OS Platform: 3.10.0-693.el7.x86_64
2018-03-21T06:17:04.794Z INF/cli:doctor 31609 [*] Using Node 8.10.0
2018-03-21T06:17:04.808Z INF/cli:doctor 31609 [*] Using ZeroMQ 4.1.6
2018-03-21T06:17:04.819Z INF/cli:doctor 31609 [*] Using RethinkDB 2.3.6
2018-03-21T06:17:04.820Z INF/cli:doctor 31609 [*] Using GraphicsMagick 1.3.28
2018-03-21T06:17:04.820Z INF/cli:doctor 31609 [*] Using ProtoBuf 3.5.1
2018-03-21T06:17:04.820Z INF/cli:doctor 31609 [*] Using ADB 1.0.31

**Comment by jonqchk** [comment]
Just find it was duplicated with #826 .checking if it can resolve my problem

**Comment by jonqchk** [comment]
fixed after i revert formidable module to v1.1.1. close this issue
