### ISSUE TITLE
 Tracker had an error Error: Connection closed

### ISSUE THREAD

**Issue by fightingAries** [openstf/stf#836]
3.2.0

**What is the issue or idea you have?**
when i try to run provider in other computer, the provider fails to run because of the error that Tracker had an error Error: Connection closed?
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
miuireport@miuireport:~/remote-device/StfProject/stf_agent$ adb devices -l
List of devices attached
4a719d85               device usb:1-8.2.1 product:sirius model:sirius device:sirius
6e89d803               device usb:1-8.2.4 product:polaris model:MIX_2S device:polaris
4a48ac23               device usb:1-8.3.3 product:whyred model:Redmi_Note_5 device:whyred
62a0ca8                device usb:1-6.2.1 product:jason model:Mi_Note_3 device:jason
2087b5eb               device usb:1-6.2.2 product:hydrogen model:MI_MAX device:hydrogen
cac9b7a5               device usb:1-8.3.1 product:sagit model:MI_6 device:sagit
391db2                 device usb:1-6.3.3 product:nitrogen model:Nitrogen device:nitrogen
f39179db               device usb:1-8.2.3 product:chiron model:MIX_2 device:chiron
313ca0                 device usb:1-6.2.3 product:nitrogen model:Nitrogen device:nitrogen
a81fc24f               device usb:1-6.2.4 product:wayne model:WAYNE device:wayne
bd53db41               device usb:1-6.3.1 product:polaris model:MIX_2S device:polaris
69074d0                offline usb:1-8.3.4

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

2018-03-24T07:01:11.750Z FTL/util:lifecycle 23495 [4a48ac23] Forward shell ended; we shall share its fate
2018-03-24T07:01:11.750Z FTL/util:lifecycle 23532 [a81fc24f] Forward shell ended; we shall share its fate
2018-03-24T07:01:11.750Z FTL/util:lifecycle 23489 [62a0ca8] Forward shell ended; we shall share its fate
2018-03-24T07:01:11.751Z FTL/util:lifecycle 23520 [f39179db] Forward shell ended; we shall share its fate
2018-03-24T07:01:11.751Z FTL/util:lifecycle 23479 [4a719d85] Forward shell ended; we shall share its fate
2018-03-24T07:01:11.751Z FTL/util:lifecycle 23489 [62a0ca8] Shutting down due to fatal error
2018-03-24T07:01:11.751Z FTL/util:lifecycle 23520 [f39179db] Shutting down due to fatal error
2018-03-24T07:01:11.751Z FTL/util:lifecycle 23479 [4a719d85] Shutting down due to fatal error
2018-03-24T07:01:11.751Z FTL/util:lifecycle 23495 [4a48ac23] Shutting down due to fatal error
2018-03-24T07:01:11.751Z FTL/util:lifecycle 23532 [a81fc24f] Shutting down due to fatal error
2018-03-24T07:01:11.751Z FTL/util:lifecycle 23513 [bd53db41] Forward shell ended; we shall share its fate
2018-03-24T07:01:11.751Z WRN/device:plugins:touch 23501 [2087b5eb] Shell keeping minitouch running ended unexpectedly
2018-03-24T07:01:11.751Z FTL/util:lifecycle 23513 [bd53db41] Shutting down due to fatal error
2018-03-24T07:01:11.751Z FTL/util:lifecycle 23526 [313ca0] Forward shell ended; we shall share its fate
2018-03-24T07:01:11.752Z FTL/util:lifecycle 23526 [313ca0] Shutting down due to fatal error
2018-03-24T07:01:11.752Z INF/device:plugins:touch 23501 [2087b5eb] Disconnecting from minitouch service
2018-03-24T07:01:11.752Z FTL/util:lifecycle 23519 [cac9b7a5] Forward shell ended; we shall share its fate
2018-03-24T07:01:11.752Z FTL/util:lifecycle 23519 [cac9b7a5] Shutting down due to fatal error
2018-03-24T07:01:11.753Z FTL/util:lifecycle 23501 [2087b5eb] Forward shell ended; we shall share its fate
2018-03-24T07:01:11.753Z FTL/util:lifecycle 23501 [2087b5eb] Shutting down due to fatal error
2018-03-24T07:01:11.753Z FTL/util:lifecycle 23488 [6e89d803] Forward shell ended; we shall share its fate
2018-03-24T07:01:11.754Z FTL/util:lifecycle 23488 [6e89d803] Shutting down due to fatal error
2018-03-24T07:01:11.758Z FTL/util:lifecycle 23538 [391db2] Forward shell ended; we shall share its fate
2018-03-24T07:01:11.759Z FTL/util:lifecycle 23538 [391db2] Shutting down due to fatal error
2018-03-24T07:01:11.762Z FTL/util:lifecycle 23467 [*] Tracker had an error Error: Connection closed
    at /home/miuireport/remote-device/StfProject/stf_agent/assets/package/node_modules/_adbkit@2.11.0@adbkit/lib/adb/tracker.js:21:13
    at tryCatcher (/home/miuireport/remote-device/StfProject/stf_agent/assets/package/node_modules/_bluebird@2.9.34@bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/home/miuireport/remote-device/StfProject/stf_agent/assets/package/node_modules/_bluebird@2.9.34@bluebird/js/main/catch_filter.js:40:36)
    at CatchFilter.tryCatcher (/home/miuireport/remote-device/StfProject/stf_agent/assets/package/node_modules/_bluebird@2.9.34@bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/miuireport/remote-device/StfProject/stf_agent/assets/package/node_modules/_bluebird@2.9.34@bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/miuireport/remote-device/StfProject/stf_agent/assets/package/node_modules/_bluebird@2.9.34@bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/miuireport/remote-device/StfProject/stf_agent/assets/package/node_modules/_bluebird@2.9.34@bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/miuireport/remote-device/StfProject/stf_agent/assets/package/node_modules/_bluebird@2.9.34@bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/miuireport/remote-device/StfProject/stf_agent/assets/package/node_modules/_bluebird@2.9.34@bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/miuireport/remote-device/StfProject/stf_agent/assets/package/node_modules/_bluebird@2.9.34@bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
2018-03-24T07:01:11.762Z FTL/util:lifecycle 23467 [*] Shutting down due to fatal error

**Please run `stf doctor` and paste the output here.**

**Comment by sorccu** [comment]
You have too many devices connected on one machine. Read the README.

**Comment by fightingAries** [comment]
How many devices can I connect to a single machine?

**Comment by tayyab-sarwar** [comment]
@sorccu How many devices can I connect to a single machine?
