### ISSUE TITLE
phone meitu 6.0 can not be online when connect to stf with usb

### ISSUE THREAD

**Issue by qingranfjj** [openstf/stf#840]
I have tried to set something in settings, ,but useless,the phone is meitu MP1602,version 6.0,this is the log:
INF/provider 39615 [*] Restarting device worker "K50LHMB790144"
INF/device:support:push 39977 [K50LHMB790144] Sending output to "tcp://127.0.0.1:7116"
INF/device 39977 [K50LHMB790144] Preparing device
INF/device:support:sub 39977 [K50LHMB790144] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 39977 [K50LHMB790144] Subscribing to permanent channel "*ALL"
INF/device:support:properties 39977 [K50LHMB790144] Loading properties
INF/device:support:sdk 39977 [K50LHMB790144] Supports SDK 23
INF/device:support:abi 39977 [K50LHMB790144] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
INF/device:resources:minicap 39977 [K50LHMB790144] Installing "/Users/mtp/stf/dy_stf/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
INF/device:resources:minicap 39977 [K50LHMB790144] Installing "/Users/mtp/stf/dy_stf/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-23/minicap.so" as "/data/local/tmp/minicap.so"
INF/device:resources:service 39977 [K50LHMB790144] Checking whether we need to install STFService
INF/device:resources:service 39977 [K50LHMB790144] Running version check
INF/device:resources:service 39977 [K50LHMB790144] STFService up to date
INF/device:plugins:service 39977 [K50LHMB790144] Launching agent
INF/device:plugins:service 39977 [K50LHMB790144] Launching service
INF/device:plugins:service 39977 [K50LHMB790144] Agent says: "Listening on @stfagent"
INF/device:plugins:service 39977 [K50LHMB790144] Agent says: "InputClient started"
FTL/device 39977 [K50LHMB790144] Setup had an error Error: Service had an error: "Error: Requires permission private to package"
    at /Users/mtp/stf/dy_stf/lib/units/device/plugins/service.js:101:23
From previous event:
    at /Users/mtp/stf/dy_stf/lib/units/device/plugins/service.js:76:14
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
FTL/util:lifecycle 39977 [K50LHMB790144] Shutting down due to fatal error
INF/provider 39615 [*] Cleaning up device worker "K50LHMB790144"
ERR/provider 39615 [*] Device worker "K50LHMB790144" died with code 1

**Comment by sorccu** [comment]
Too expensive, I’m not going to buy it. Sounds like it’s a permission issue. Perhaps there’s an “allow auto launch” setting somewhere in there. @thinkhy do you have this device?

**Comment by qingranfjj** [comment]
it is ok now,I  just try these steps:
adb uninstall jp.co.cyberagent.stf 
adb install d:/xxx/STFService.apk 
adb shell am start -n jp.co.cyberagent.stf/.IdentityActivity
adb shell am startservice  -n jp.co.cyberagent.stf/.Service

**Comment by thinkhy** [comment]
@sorccu I have a MeiTu device, which can't self-start STFService, so we should start it with adb command. Some of Meizu and LeTV devices have similar problem.
