### ISSUE TITLE
Device screen is not refreshed on STF,Interaction worksfine

### ISSUE THREAD

**Issue by terminalone** [openstf/stf#847]
Latest Docker Image of openstf
**What is the issue or idea you have?**
Device screen is not refreshed on STF,Interaction worksfine

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
I dont have the device right now,will add adb devices -l output tommorow.

Not a Device specific issue.
I check with 3 devices
Pixel 
Samsung 
and a Samsung nexus tab 

**Please provide the steps to reproduce the issue.**
1.Connect device to a stf provider located at remote location.
2.Interact with the device from local machine with mouse from STF console

**What is the expected behavior?**
Action performed by mouse device on screen shoudl be refelected on STF device screen.
When I click browser refresh button the next screen is seen on the open STF device screen.
On the Actual device ,Interactions are working fine,no delay.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
stf local has no errors in stf app docker container

**Please run `stf doctor` and paste the output here.**
stf@pune-mobilefarm:/app$ stf doctor
2018-04-04T11:40:50.582Z INF/cli:doctor 31 [*] OS Arch: x64
2018-04-04T11:40:50.584Z INF/cli:doctor 31 [*] OS Platform: linux
2018-04-04T11:40:50.585Z INF/cli:doctor 31 [*] OS Platform: 4.4.0-116-generic
2018-04-04T11:40:50.585Z INF/cli:doctor 31 [*] Using Node 6.11.2
2018-04-04T11:40:50.665Z INF/cli:doctor 31 [*] Using ZeroMQ 4.1.4
2018-04-04T11:40:50.695Z ERR/cli:doctor 31 [*] RethinkDB is not installed (`rethinkdb` is missing)
2018-04-04T11:40:50.695Z ERR/cli:doctor 31 [*] ProtoBuf is not installed (`protoc` is missing)
2018-04-04T11:40:50.695Z ERR/cli:doctor 31 [*] ADB is not installed (`adb` is missing)
2018-04-04T11:40:51.090Z INF/cli:doctor 31 [*] Using GraphicsMagick 1.3.23

Setup
Machine A : Master
mobile@pune-mobilefarm:~/deploy-stf-docker-master$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                    PORTS                    NAMES
e9581ea3e722        nginx               "nginx"                  25 minutes ago      Up 25 minutes                                      nginx
0f32394fcf3b        openstf/stf         "stf provider --na..."   12 days ago         Up 6 days                                          provider1
60d9c445318c        openstf/stf         "stf reaper dev --..."   12 days ago         Up 6 days                                          reaper
ff7aacb0bf39        openstf/stf         "stf websocket --p..."   12 days ago         Up 6 days                                          websocket
4cd99ffcf5b0        openstf/stf         "stf processor stf..."   12 days ago         Up 6 days                                          stf-processor
355a235774a2        openstf/stf         "stf app --port 31..."   12 days ago         Up 6 days                                          stf-app-3100
eeb5c76b9a7c        openstf/stf         "stf api --port 37..."   12 days ago         Up 6 days                                          stf-api
57ff20dc63ec        openstf/stf         "stf auth-mock --p..."   12 days ago         Up 6 days                 0.0.0.0:3200->3000/tcp   stf-auth-3200
13d4c20e3955        openstf/stf         "stf triproxy dev ..."   12 days ago         Up 6 days                                          triproxy-dev
8abc2f57c071        openstf/stf         "stf triproxy app ..."   12 days ago         Up 6 days                                          triproxy-app
7016cdf82f8a        openstf/stf         "stf storage-temp ..."   12 days ago         Exited (255) 6 days ago   0.0.0.0:3500->3000/tcp   storage-temp-3500
8ee3fea4eb0c        openstf/stf         "stf storage-plugi..."   12 days ago         Up 6 days                 0.0.0.0:3400->3000/tcp   storage-plugin-image-3400
bbf52afd19d3        openstf/stf         "stf storage-plugi..."   12 days ago         Up 6 days                 0.0.0.0:3300->3000/tcp   storage-plugin-apk-3300
ca7574e3e691        openstf/stf         "stf migrate"            12 days ago         Exited (0) 12 days ago                             stf-migrate
0c32aa221283        rethinkdb           "rethinkdb --bind ..."   12 days ago         Up 6 days                                          rethinkdb

Slave/Remote machine:
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
c99e65f0767a        openstf/stf         "stf provider --na..."   25 hours ago        Up 25 hours                             provider2
55e1c6bc1b4b        nginx               "nginx"                  25 hours ago        Created                                 nginx

Provider command on Slave:
docker rm -f lasvegas
docker run -d --name lasvegas --net host openstf/stf stf provider --name "lasvegas" --connect-sub tcp://${MASTERIP}:7250 --connect-push tcp://${MASTERIP}:7270 --storage-url http://${MASTERIP} min-port=15000 --max-port=25000 --heartbeat-interval 20000 --screen-ws-url-pattern "ws://${MASTERIP}/d/mumbai/<%= serial %>/<%= publicPort %>/"

nginx docker configuration is:

  # Handle stf-provider@pune
    location ~ "^/d/losangeles/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://10.20.5.15:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Handle stf-provider@mumbai
    location ~ "^/d/lasvegas/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://10.21.4.151:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }

**Comment by sorccu** [comment]
You’re the only one with this issue. I would try running on a different machine. If your Docker host OS is Windows (could be, I don’t know) try using Mac or Linux instead.

You ahould also look at the network tab in your browser’s developer tools panel and see if you can find any clues there. There should be two WebSockets connections, check wgat’s going on with the screen websocket (usually last one). It could be timing out or the connection could be dropped by a firewall, for example (wouldn’t be the first time - especially on Windows).

**Comment by terminalone** [comment]
@sorccu both the linux boxes are linux machines,
I checked the developer console and i see this message: 

The connection to ws://nginxserverip/d/pune1/5200531fc6119421/15004/ was interrupted while the page was loading.
1.507a928fe996d2944a92.chunk.js:79842:18
the provider logs show:


```
2018-04-17T06:02:25.460Z IMP/device:plugins:group 25 [5200531fc6119421] No longer owned by "tets@BEST.COM"
2018-04-17T06:02:25.461Z INF/device:plugins:group 25 [5200531fc6119421] Unsubscribing from group channel "HGunOy/9SFmkk244uS43eA=="
2018-04-17T06:02:26.030Z IMP/device:plugins:group 25 [5200531fc6119421] Now owned by "tets@BEST.COM"
2018-04-17T06:02:26.031Z INF/device:plugins:group 25 [5200531fc6119421] Subscribing to group channel "HGunOy/9SFmkk244uS43eA=="
2018-04-17T06:02:26.160Z INF/device:plugins:screen:stream 25 [5200531fc6119421] Setting frame producer projection to 461x461
2018-04-17T06:02:26.162Z INF/device:plugins:screen:stream 25 [5200531fc6119421] Requesting frame producer to start
2018-04-17T06:02:26.162Z INF/device:plugins:screen:stream 25 [5200531fc6119421] Launching screen service
2018-04-17T06:02:26.165Z IMP/device:plugins:connect 25 [5200531fc6119421] Remote Connect Started for device "5200531fc6119421" at "masterip:15005"
2018-04-17T06:02:26.291Z INF/device:plugins:screen:stream 25 [5200531fc6119421] minicap says: "PID: 17806"
2018-04-17T06:02:26.292Z INF/device:plugins:screen:stream 25 [5200531fc6119421] minicap says: "INFO: Using projection 720x1280@259x461/0"
2018-04-17T06:02:26.292Z INF/device:plugins:screen:stream 25 [5200531fc6119421] minicap says: "INFO: (external/MY_minicap/src/minicap_24.cpp:240) Creating SurfaceComposerClient"
2018-04-17T06:02:26.293Z INF/device:plugins:screen:stream 25 [5200531fc6119421] minicap says: "INFO: (external/MY_minicap/src/minicap_24.cpp:243) Performing SurfaceComposerClient init check"
2018-04-17T06:02:26.293Z INF/device:plugins:screen:stream 25 [5200531fc6119421] minicap says: "INFO: (external/MY_minicap/src/minicap_24.cpp:250) Creating virtual display"
2018-04-17T06:02:26.294Z INF/device:plugins:screen:stream 25 [5200531fc6119421] Connecting to minicap service
2018-04-17T06:02:26.295Z INF/device:plugins:screen:stream 25 [5200531fc6119421] minicap says: "INFO: (external/MY_minicap/src/minicap_24.cpp:256) Creating buffer queue"
2018-04-17T06:02:26.295Z INF/device:plugins:screen:stream 25 [5200531fc6119421] minicap says: "INFO: (external/MY_minicap/src/minicap_24.cpp:261) Creating CPU consumer"
2018-04-17T06:02:26.295Z INF/device:plugins:screen:stream 25 [5200531fc6119421] minicap says: "INFO: (external/MY_minicap/src/minicap_24.cpp:265) Creating frame waiter"
2018-04-17T06:02:26.297Z INF/device:plugins:screen:stream 25 [5200531fc6119421] minicap says: "INFO: (external/MY_minicap/src/minicap_24.cpp:269) Publishing virtual display"
2018-04-17T06:02:26.313Z INF/device:plugins:screen:stream 25 [5200531fc6119421] minicap says: "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"
2018-04-17T06:02:26.405Z INF/device:plugins:screen:stream 25 [5200531fc6119421] minicap says: "INFO: (jni/minicap/minicap.cpp:448) New client connection"
2018-04-17T06:02:26.407Z INF/device:plugins:screen:stream 25 [5200531fc6119421] Reading minicap banner
Unhandled rejection Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
From previous event:
    at send (/app/lib/units/device/plugins/screen/stream.js:508:20)
    at Object.wsFrameNotifier [as onFrame] (/app/lib/units/device/plugins/screen/stream.js:546:20)
    at /app/lib/units/device/plugins/screen/stream.js:490:43
    at Array.map (native)
    at FrameProducer.next (/app/lib/units/device/plugins/screen/stream.js:489:49)
    at FrameProducer.emit (/app/node_modules/eventemitter3/index.js:115:35)
    at FrameProducer._maybeEmitReadable (/app/lib/units/device/plugins/screen/stream.js:413:14)
    at FrameProducer._readableListener (/app/lib/units/device/plugins/screen/stream.js:419:12)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
Unhandled rejection Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
From previous event:
    at send (/app/lib/units/device/plugins/screen/stream.js:508:20)
    at Object.wsFrameNotifier [as onFrame] (/app/lib/units/device/plugins/screen/stream.js:546:20)
    at /app/lib/units/device/plugins/screen/stream.js:490:43
    at Array.map (native)
    at FrameProducer.next (/app/lib/units/device/plugins/screen/stream.js:489:49)
    at FrameProducer.emit (/app/node_modules/eventemitter3/index.js:115:35)
    at FrameProducer._maybeEmitReadable (/app/lib/units/device/plugins/screen/stream.js:413:14)
    at FrameProducer._readableListener (/app/lib/units/device/plugins/screen/stream.js:419:12)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
Unhandled rejection Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
From previous event:
    at send (/app/lib/units/device/plugins/screen/stream.js:508:20)
    at Object.wsFrameNotifier [as onFrame] (/app/lib/units/device/plugins/screen/stream.js:546:20)
    at /app/lib/units/device/plugins/screen/stream.js:490:43
    at Array.map (native)
    at FrameProducer.next (/app/lib/units/device/plugins/screen/stream.js:489:49)
    at FrameProducer.emit (/app/node_modules/eventemitter3/index.js:115:35)
    at FrameProducer._maybeEmitReadable (/app/lib/units/device/plugins/screen/stream.js:413:14)
    at FrameProducer._readableListener (/app/lib/units/device/plugins/screen/stream.js:419:12)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
2018-04-17T06:02:53.209Z INF/device:plugins:screen:stream 25 [5200531fc6119421] Keeping 461x461 as current frame producer projection
2018-04-17T06:02:53.859Z IMP/device:plugins:connect 25 [5200531fc6119421] Remote Connect Started for device "5200531fc6119421" at "10.20.5.15:15005"
Unhandled rejection Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
From previous event:
    at send (/app/lib/units/device/plugins/screen/stream.js:508:20)
    at Object.wsStartNotifier [as onStart] (/app/lib/units/device/plugins/screen/stream.js:535:20)
    at /app/lib/units/device/plugins/screen/stream.js:482:41
    at Array.map (native)
    at FrameProducer.<anonymous> (/app/lib/units/device/plugins/screen/stream.js:481:31)
    at FrameProducer.emit (/app/node_modules/eventemitter3/index.js:115:35)
    at FrameProducer.<anonymous> (/app/lib/units/device/plugins/screen/stream.js:97:20)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Unhandled rejection Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
From previous event:
    at send (/app/lib/units/device/plugins/screen/stream.js:508:20)
    at Object.wsStartNotifier [as onStart] (/app/lib/units/device/plugins/screen/stream.js:535:20)
    at /app/lib/units/device/plugins/screen/stream.js:482:41
    at Array.map (native)
    at FrameProducer.<anonymous> (/app/lib/units/device/plugins/screen/stream.js:481:31)
    at FrameProducer.emit (/app/node_modules/eventemitter3/index.js:115:35)
    at FrameProducer.<anonymous> (/app/lib/units/device/plugins/screen/stream.js:97:20)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Unhandled rejection Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
From previous event:
    at send (/app/lib/units/device/plugins/screen/stream.js:508:20)
    at Object.wsStartNotifier [as onStart] (/app/lib/units/device/plugins/screen/stream.js:535:20)
    at /app/lib/units/device/plugins/screen/stream.js:482:41
    at Array.map (native)
    at FrameProducer.<anonymous> (/app/lib/units/device/plugins/screen/stream.js:481:31)
    at FrameProducer.emit (/app/node_modules/eventemitter3/index.js:115:35)
    at FrameProducer.<anonymous> (/app/lib/units/device/plugins/screen/stream.js:97:20)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)


```

**Comment by terminalone** [comment]
my unit files are exactly the same as in the documentation with ipaddress changed.Only difference is I am using http and not https.Also thera there are tow providers.
machine A; all stf process,adb and provider1,rethinkdb
machine B; adb and provider2

**Comment by terminalone** [comment]
![screenshot from 2018-04-17 11-47-53](https://user-images.githubusercontent.com/13177288/38851869-3549dc8e-4235-11e8-99a1-afcfe45e8ee9.png)

**Comment by terminalone** [comment]
![screenshot from 2018-04-17 11-47-53](https://user-images.githubusercontent.com/13177288/38852345-1f006036-4237-11e8-8ba5-6a9783a79859.png)

**Comment by terminalone** [comment]
@sorcuu ok will change port in nginx conf.Is there any other place where i need to make the port changes??

**Comment by terminalone** [comment]
changed nginx port to 8181 in nginx.conf and restarted nginx and providers
Firefox can’t establish a connection to the server at ws:/masterip/socket.io/?uip=masterip&EIO=3&transport=websocket.
Also see the pop disconnected and no device screen on stf console now.
Would switching to https solve the issues????

**Comment by terminalone** [comment]
@sorccu the docker lolgs adb on provider 2 show

adb I 04-13 09:16:10     7     7 adb_auth_host.cpp:416] adb_auth_init...
adb I 04-13 09:16:10     7     7 adb_auth_host.cpp:174] read_key_file '/root/.android/adbkey'...
adb I 04-13 09:16:10     7     7 adb_auth_host.cpp:391] adb_auth_inotify_init...
adb I 04-13 09:16:10     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb I 04-13 09:16:38     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-13 09:16:39     7    15 transport_usb.cpp:160] remote usb: 1 - write terminated: Connection timed out
adb I 04-13 09:16:40     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb I 04-13 09:16:51     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb I 04-13 09:17:31     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb I 04-13 09:17:54     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb I 04-13 09:17:59     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb I 04-13 09:18:05     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb I 04-13 09:18:26     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb I 04-13 09:18:50     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb I 04-17 05:13:57     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb I 04-17 05:59:55     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-17 06:00:00     7    35 transport_usb.cpp:160] remote usb: 1 - write terminated: Invalid argument
adb I 04-17 06:00:02     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-17 06:46:24     7    37 transport_usb.cpp:160] remote usb: 1 - write terminated: Invalid argument
adb I 04-17 07:07:48     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-17 07:08:07     7    39 transport_usb.cpp:160] remote usb: 1 - write terminated: Invalid argument
adb I 04-17 07:08:09     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-17 07:18:57     7    41 transport_usb.cpp:160] remote usb: 1 - write terminated: Invalid argument
adb I 04-17 07:19:01     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-17 07:19:07     7    43 transport_usb.cpp:160] remote usb: 1 - write terminated: Invalid argument
adb I 04-17 07:19:08     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-17 10:15:51     7    45 transport_usb.cpp:160] remote usb: 1 - write terminated: Invalid argument
adb I 04-17 10:19:15     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-17 10:19:18     7    47 transport_usb.cpp:160] remote usb: 1 - write terminated: Invalid argument
adb I 04-17 10:19:20     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-17 10:44:48     7    49 transport_usb.cpp:160] remote usb: 1 - write terminated: Invalid argument
adb I 04-17 12:20:37     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-17 12:20:43     7    51 transport_usb.cpp:160] remote usb: 1 - write terminated: Invalid argument
adb I 04-17 12:20:44     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-17 12:28:55     7    53 transport_usb.cpp:160] remote usb: 1 - write terminated: Invalid argument
adb I 04-17 12:29:02     7     7 adb_auth_host.cpp:467] Calling send_auth_response
adb E 04-17 12:29:08     7    55 transport_usb.cpp:160] remote usb: 1 - write terminated: Invalid argument
adb I 04-17 12:29:10     7     7 adb_auth_host.cpp:467] Calling send_auth_response


Is this a problem??

**Comment by terminalone** [comment]
@sorccu changed listen port in nginx.conf 
Error
WebSocket connection to 'ws://masterip/socket.io/?uip=10.20.4.82&EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Do i Need to make any other changes??

**Comment by sorccu** [comment]
You have to update some of the units to match the changed port. Sounds like your `--ws-screen-url-pattern` is one of the options that's out of date.

In general, I don't have time to help with configuration issues. You know your network, I don't.

**Comment by terminalone** [comment]
@sorccu Thanks for your reply sorcuu.I checked with networking team and they say trafficis not blocked on port 80.But still i wanted to implement your suggestion and change the port.Can you please tell me which unit files need to be changed if the port is changed from 80.
Also would migrating from http to https solve the problem?
Please let me know.

**Comment by sorccu** [comment]
Switch to HTTPS.

**Comment by Shruti11S** [comment]
We tried switching to Https but we don't see any change in behavior.
Observation :- stf screen gets immediately refreshed when we refresh the browser.

Now we need to refresh stf screen on browser every time after performing action on device so that both should remain in sync.

Please let us know if there is any parameter we need to update for auto refreshing browser screen.

**Comment by habeebshk** [comment]
hey guys, i am trying to set this up as well. but i am having trouble setting up the provider client in my remote laptop, i tried everything but in the end it shows that the devices are ignored. can you guy help me on this.

**Comment by terminalone** [comment]
@habeebshk Can you post your provider file.
