### ISSUE TITLE
Unexpected error checking ZeroMQ

### ISSUE THREAD

**Issue by ckJIag** [openstf/stf#848]
Hello GitHub community,

after running
stf local --public-ip <my_public_ip> --allow-remote
I got following error:

(...)
The module '/usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
2018-04-04T19:30:12.824Z FTL/cli:local 1276 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
2018-04-04T19:30:12.824Z INF/cli:local 1276 [*] Shutting down all child processes

I have tried both suggested options - npm install and npm rebuild but the problem remains. I use nvm to manage NodeJS and I currently use latest LTS release (NodeJS 8.11.1).

Here is output from stf doctor:

2018-04-04T19:34:12.751Z INF/cli:doctor 1412 [*] OS Arch: x64
2018-04-04T19:34:12.753Z INF/cli:doctor 1412 [*] OS Platform: linux
2018-04-04T19:34:12.753Z INF/cli:doctor 1412 [*] OS Platform: 4.9.0-6-amd64
2018-04-04T19:34:12.753Z INF/cli:doctor 1412 [*] Using Node 9.10.1
2018-04-04T19:34:12.786Z ERR/cli:doctor 1412 [*] Unexpected error checking ZeroMQ: Error: The module '/usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
2018-04-04T19:34:12.787Z INF/cli:doctor 1412 [*] Using RethinkDB 2.3.5~0stretch
2018-04-04T19:34:12.787Z INF/cli:doctor 1412 [*] Using GraphicsMagick 1.3.25
2018-04-04T19:34:12.787Z INF/cli:doctor 1412 [*] Using ProtoBuf 3.5.1
2018-04-04T19:34:12.788Z INF/cli:doctor 1412 [*] Using ADB 1.0.36

Thank you for any info, I have tried many different possible ways to solve it on my own, but after spending nearly two afternoons on this issue, I feel kinda helpless.

Many thanks.

**Comment by ckJIag** [comment]
Ok, so it seems I have finally found the solution in:
nvm install 8.11.1 --reinstall-packages-from=8.11.1
nvm use 8.11.1
npm install zmq
but when I try to manage devices, they are disconnected
(or
List of devices attached
10.8.0.5:5555   offline
).
Any idea where could be the problem?

**Comment by ckJIag** [comment]
Ok

**Comment by poisonivy0** [comment]
I know this is old but can you tell me the step you took to solve this. i am having the same issues :-(

**Comment by mukkumukesh** [comment]
Hi,

I was also facing that issue when starting STF on a local machine. I tried much time and finally got the solution and it was pretty simple like remove nodejs and npm completely from ubuntu machine and re-install again 
Remove node completely from the machine
1. sudo apt-get remove nodejs
2. sudo apt-get remove npm

Then go to /etc/apt/sources.list.d and remove any node list if you have. Then do a
Check for any .npm or .node folder in your home folder and delete those.

1. sudo rm -rf /usr/local/lib/node*
2. sudo rm -rf /usr/local/include/node*
3. sudo rm -rf /usr/local/bin/node*
4. sudo apt-get update

And finally, install

~ $ sudo apt-get install python-software-properties
~ $ sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash –
~ $ sudo apt-get install nodejs
~$ sudo apt-get install npm

It works for me. May be helpful to all guys as well.
