### ISSUE TITLE
please help,i get this error

### ISSUE THREAD

**Issue by pahnpiseth** [openstf/stf#856]
STF 3.3.0
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
root@piseth-Latitude-E6320:/home/piseth/Desktop/stf/stf# stf local
2018-04-19T17:38:05.576Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli migrate"
2018-04-19T17:38:05.859Z INF/db 19029 [*] Connecting to 127.0.0.1:28015
2018-04-19T17:38:05.880Z INF/db:setup 19029 [*] Database "stf" already exists
2018-04-19T17:38:05.887Z INF/db:setup 19029 [*] Table "users" already exists
2018-04-19T17:38:05.887Z INF/db:setup 19029 [*] Table "accessTokens" already exists
2018-04-19T17:38:05.887Z INF/db:setup 19029 [*] Table "vncauth" already exists
2018-04-19T17:38:05.887Z INF/db:setup 19029 [*] Table "devices" already exists
2018-04-19T17:38:05.888Z INF/db:setup 19029 [*] Table "logs" already exists
2018-04-19T17:38:05.903Z INF/db:setup 19029 [*] Index "users"."adbKeys" already exists
2018-04-19T17:38:05.903Z INF/db:setup 19029 [*] Index "accessTokens"."email" already exists
2018-04-19T17:38:05.903Z INF/db:setup 19029 [*] Index "vncauth"."response" already exists
2018-04-19T17:38:05.904Z INF/db:setup 19029 [*] Index "vncauth"."responsePerDevice" already exists
2018-04-19T17:38:05.904Z INF/db:setup 19029 [*] Index "devices"."owner" already exists
2018-04-19T17:38:05.904Z INF/db:setup 19029 [*] Index "devices"."present" already exists
2018-04-19T17:38:05.904Z INF/db:setup 19029 [*] Index "devices"."providerChannel" already exists
2018-04-19T17:38:05.904Z INF/db:setup 19029 [*] Waiting for index "users"."adbKeys"
2018-04-19T17:38:05.905Z INF/db:setup 19029 [*] Waiting for index "accessTokens"."email"
2018-04-19T17:38:05.905Z INF/db:setup 19029 [*] Waiting for index "vncauth"."response"
2018-04-19T17:38:05.906Z INF/db:setup 19029 [*] Waiting for index "vncauth"."responsePerDevice"
2018-04-19T17:38:05.906Z INF/db:setup 19029 [*] Waiting for index "devices"."owner"
2018-04-19T17:38:05.906Z INF/db:setup 19029 [*] Waiting for index "devices"."present"
2018-04-19T17:38:05.907Z INF/db:setup 19029 [*] Waiting for index "devices"."providerChannel"
2018-04-19T17:38:05.910Z INF/db:setup 19029 [*] Index "users"."adbKeys" is ready
2018-04-19T17:38:05.910Z INF/db:setup 19029 [*] Index "accessTokens"."email" is ready
2018-04-19T17:38:05.910Z INF/db:setup 19029 [*] Index "vncauth"."response" is ready
2018-04-19T17:38:05.912Z INF/db:setup 19029 [*] Index "vncauth"."responsePerDevice" is ready
2018-04-19T17:38:05.912Z INF/db:setup 19029 [*] Index "devices"."owner" is ready
2018-04-19T17:38:05.912Z INF/db:setup 19029 [*] Index "devices"."present" is ready
2018-04-19T17:38:05.912Z INF/db:setup 19029 [*] Index "devices"."providerChannel" is ready
2018-04-19T17:38:05.918Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2018-04-19T17:38:05.920Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2018-04-19T17:38:05.924Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2018-04-19T17:38:05.937Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2018-04-19T17:38:05.943Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2018-04-19T17:38:05.949Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli provider --name piseth-Latitude-E6320 --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"
2018-04-19T17:38:05.957Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
2018-04-19T17:38:05.969Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
2018-04-19T17:38:05.980Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
2018-04-19T17:38:05.985Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2018-04-19T17:38:05.997Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-temp --port 7102"
2018-04-19T17:38:06.005Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2018-04-19T17:38:06.017Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2018-04-19T17:38:06.026Z INF/util:procutil 19023 [*] Forking "/usr/lib/node_modules/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
/usr/lib/node_modules/stf/lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                     [string] [default: "piseth-Latitude-E6320"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/compiled/9.11.1/linux/x64/zmq.node
2018-04-19T17:38:07.334Z FTL/cli:local 19023 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
2018-04-19T17:38:07.335Z INF/cli:local 19023 [*] Shutting down all child processes
/usr/lib/node_modules/stf/lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                     [string] [default: "piseth-Latitude-E6320"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/compiled/9.11.1/linux/x64/zmq.node
**Please run `stf doctor` and paste the output here.**
root@piseth-Latitude-E6320:/home/piseth/Desktop/stf/stf# stf doctor
2018-04-19T17:40:28.254Z INF/cli:doctor 19150 [*] OS Arch: x64
2018-04-19T17:40:28.258Z INF/cli:doctor 19150 [*] OS Platform: linux
2018-04-19T17:40:28.258Z INF/cli:doctor 19150 [*] OS Platform: 4.13.0-37-generic
2018-04-19T17:40:28.258Z INF/cli:doctor 19150 [*] Using Node 9.11.1
2018-04-19T17:40:28.311Z ERR/cli:doctor 19150 [*] Unexpected error checking ZeroMQ: Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/compiled/9.11.1/linux/x64/zmq.node
2018-04-19T17:40:28.312Z INF/cli:doctor 19150 [*] Using RethinkDB 2.3.6~0xenial
2018-04-19T17:40:28.313Z INF/cli:doctor 19150 [*] Using GraphicsMagick 1.3.23
2018-04-19T17:40:28.313Z INF/cli:doctor 19150 [*] Using ProtoBuf 3.2.0
2018-04-19T17:40:28.313Z INF/cli:doctor 19150 [*] Using ADB 1.0.32

**Comment by sorccu** [comment]
Read the README and search for past issues. If you’re sure you have all the dependencies installed, nuke your node_modules folder once and install again.
