### ISSUE TITLE
openstf can't connect to Orange Pi One Plus

### ISSUE THREAD

**Issue by gounthar** [openstf/stf#865]
/usr/local/bin/stf --version
3.3.0
**What is the issue or idea you have?**
Can't connect to Orange Pi One Plus

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
20080411               device usb:337641472X product:petrel_fvd_p1 model:molly device:petrel-p1 transport_id:10

**Please provide the steps to reproduce the issue.**
Just connect the Orange Pi One Plus to the STF local.

**What is the expected behavior?**
Well, being able to launch applications on the device.

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
2018-05-03T08:03:48.816Z INF/device:support:push 2893 [20080411] Sending output to "tcp://127.0.0.1:7116"
2018-05-03T08:03:48.821Z INF/device 2893 [20080411] Preparing device
2018-05-03T08:03:49.589Z INF/device:support:sub 2893 [20080411] Receiving input from "tcp://127.0.0.1:7114"
2018-05-03T08:03:49.591Z INF/device:support:sub 2893 [20080411] Subscribing to permanent channel "*ALL"
2018-05-03T08:03:49.664Z INF/device:support:properties 2893 [20080411] Loading properties
2018-05-03T08:03:49.709Z INF/device:support:sdk 2893 [20080411] Supports SDK 24
2018-05-03T08:03:49.710Z INF/device:support:abi 2893 [20080411] Supports ABIs armeabi-v7a, armeabi
2018-05-03T08:03:49.790Z INF/device:resources:minicap 2893 [20080411] Installing "/Users/openstf/local/stf/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/bin/minicap" as "/data/local/tmp/minicap"
2018-05-03T08:03:49.791Z INF/device:resources:minicap 2893 [20080411] Installing "/Users/openstf/local/stf/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/lib/android-24/minicap.so" as "/data/local/tmp/minicap.so"
2018-05-03T08:03:49.874Z INF/device:resources:service 2893 [20080411] Checking whether we need to install STFService

2018-05-03T08:03:50.577Z INF/device:resources:service 2893 [20080411] Running version check
2018-05-03T08:03:51.328Z INF/device:resources:service 2893 [20080411] STFService up to date
2018-05-03T08:03:51.333Z INF/device:plugins:service 2893 [20080411] Launching agent
2018-05-03T08:03:52.170Z INF/device:plugins:service 2893 [20080411] Launching service
2018-05-03T08:03:52.229Z INF/device:plugins:service 2893 [20080411] Agent says: "Listening on @stfagent"
2018-05-03T08:03:52.229Z INF/device:plugins:service 2893 [20080411] Agent says: "InputClient started"
2018-05-03T08:03:52.900Z INF/device:plugins:display 2893 [20080411] Reading display info
2018-05-03T08:03:52.913Z INF/device:plugins:phone 2893 [20080411] Fetching phone info
2018-05-03T08:03:52.924Z INF/device:plugins:identity 2893 [20080411] Solving identity
2018-05-03T08:03:52.925Z INF/device:plugins:solo 2893 [20080411] Subscribing to permanent channel "t3aRBtU4pcakPT94k1nnxInAnAI="
2018-05-03T08:03:52.928Z INF/device:plugins:screen:stream 2893 [20080411] Starting WebSocket server on port 7416
2018-05-03T08:03:52.989Z INF/device:resources:minitouch 2893 [20080411] Installing "/Users/openstf/local/stf/node_modules/minitouch-prebuilt/prebuilt/armeabi-v7a/bin/minitouch" as "/data/local/tmp/minitouch"
2018-05-03T08:03:53.029Z WRN/device:plugins:data 2893 [20080411] Unable to find device data { serial: '20080411',
  platform: 'Android',
  manufacturer: 'ALLWINNER',
  operator: null,
  model: 'molly',
  version: '7.0',
  abi: 'armeabi-v7a',
  sdk: '24',
  product: 'petrel_fvd_p1',
  cpuPlatform: 'petrel',
  openGLESVersion: '2.0',
  display:
   { id: 0,
     width: 1280,
     height: 1024,
     xdpi: 213,
     ydpi: 213,
     fps: 50,
     density: 1,
     rotation: 0,
     secure: true,
     size: 7.6957737313746915,
     url: 'ws://10.24.73.106:7416' },
  phone: { network: 'UNKNOWN' } }
2018-05-03T08:03:53.034Z INF/device:plugins:touch 2893 [20080411] Touch origin is top left
2018-05-03T08:03:53.035Z INF/device:plugins:touch 2893 [20080411] Requesting touch consumer to start
2018-05-03T08:03:53.036Z INF/device:plugins:touch 2893 [20080411] Launching touch service
2018-05-03T08:03:53.043Z INF/device:plugins:touch 2893 [20080411] Connecting to minitouch service
2018-05-03T08:03:53.177Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mouse1 is not supported by libevdev"
2018-05-03T08:03:53.424Z INF/provider 2880 [*] Providing 1 of 2 device(s); waiting for "20080411"
2018-05-03T08:03:53.497Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mouse0 is not supported by libevdev"
2018-05-03T08:03:53.617Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
2018-05-03T08:03:53.778Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Unable to find a suitable touch device"
2018-05-03T08:03:53.779Z WRN/device:plugins:touch 2893 [20080411] Shell keeping minitouch running ended unexpectedly
2018-05-03T08:03:53.781Z INF/device:plugins:touch 2893 [20080411] Disconnecting from minitouch service
2018-05-03T08:03:53.784Z INF/device:plugins:touch 2893 [20080411] Stopping minitouch service
2018-05-03T08:03:53.785Z INF/device:plugins:touch 2893 [20080411] Launching touch service
2018-05-03T08:03:53.792Z INF/device:plugins:touch 2893 [20080411] Connecting to minitouch service
2018-05-03T08:03:53.907Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mouse1 is not supported by libevdev"
2018-05-03T08:03:53.915Z INF/reaper 2879 [reaper001] Reaping device "20080411" due to heartbeat timeout
2018-05-03T08:03:54.307Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mouse0 is not supported by libevdev"
2018-05-03T08:03:54.457Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
2018-05-03T08:03:54.608Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Unable to find a suitable touch device"
2018-05-03T08:03:54.609Z WRN/device:plugins:touch 2893 [20080411] Shell keeping minitouch running ended unexpectedly
2018-05-03T08:03:54.610Z INF/device:plugins:touch 2893 [20080411] Disconnecting from minitouch service
2018-05-03T08:03:54.612Z INF/device:plugins:touch 2893 [20080411] Stopping minitouch service
2018-05-03T08:03:54.613Z INF/device:plugins:touch 2893 [20080411] Launching touch service
2018-05-03T08:03:54.619Z INF/device:plugins:touch 2893 [20080411] Connecting to minitouch service
2018-05-03T08:03:54.726Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mouse1 is not supported by libevdev"
2018-05-03T08:03:54.927Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mouse0 is not supported by libevdev"
2018-05-03T08:03:55.047Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
2018-05-03T08:03:55.208Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Unable to find a suitable touch device"
2018-05-03T08:03:55.209Z WRN/device:plugins:touch 2893 [20080411] Shell keeping minitouch running ended unexpectedly
2018-05-03T08:03:55.211Z INF/device:plugins:touch 2893 [20080411] Disconnecting from minitouch service
2018-05-03T08:03:55.212Z INF/device:plugins:touch 2893 [20080411] Stopping minitouch service
2018-05-03T08:03:55.213Z INF/device:plugins:touch 2893 [20080411] Launching touch service
2018-05-03T08:03:55.220Z INF/device:plugins:touch 2893 [20080411] Connecting to minitouch service
2018-05-03T08:03:55.337Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mouse1 is not supported by libevdev"
2018-05-03T08:03:55.527Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mouse0 is not supported by libevdev"
2018-05-03T08:03:55.647Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
2018-05-03T08:03:55.797Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Unable to find a suitable touch device"
2018-05-03T08:03:55.798Z WRN/device:plugins:touch 2893 [20080411] Shell keeping minitouch running ended unexpectedly
2018-05-03T08:03:55.801Z INF/device:plugins:touch 2893 [20080411] Disconnecting from minitouch service
2018-05-03T08:03:55.804Z WRN/device:plugins:touch 2893 [20080411] Will not apply desired state due to too many failures
2018-05-03T08:03:55.807Z INF/device:plugins:touch 2893 [20080411] Stopping minitouch service
2018-05-03T08:03:55.810Z FTL/device 2893 [20080411] Setup had an error Error: Failed more than 3 times in 10000ms
    at TouchConsumer._failLimitExceeded (/Users/openstf/local/stf/lib/units/device/plugins/touch/index.js:230:26)
    at FailCounter.emit (/Users/openstf/local/stf/node_modules/eventemitter3/index.js:117:35)
    at FailCounter.inc (/Users/openstf/local/stf/lib/util/failcounter.js:29:10)
    at TouchConsumer._outputEnded (/Users/openstf/local/stf/lib/units/device/plugins/touch/index.js:223:24)
    at RiskyStream.emit (/Users/openstf/local/stf/node_modules/eventemitter3/index.js:115:35)
    at RiskyStream.<anonymous> (/Users/openstf/local/stf/lib/util/riskystream.js:14:12)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
From previous event:
    at startConsumer (/Users/openstf/local/stf/lib/units/device/plugins/touch/index.js:511:14)
    at /Users/openstf/local/stf/lib/units/device/plugins/touch/index.js:526:12
    at SerialSyrup.ParallelSyrup.invoke (/Users/openstf/local/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /Users/openstf/local/stf/node_modules/stf-syrup/lib/serial.js:43:33
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Please run `stf doctor` and paste the output here.**
 /usr/local/bin/stf doctor
2018-05-03T08:08:01.775Z INF/cli:doctor 2910 [*] OS Arch: x64
2018-05-03T08:08:01.778Z INF/cli:doctor 2910 [*] OS Platform: darwin
2018-05-03T08:08:01.778Z INF/cli:doctor 2910 [*] OS Platform: 15.6.0
2018-05-03T08:08:01.778Z INF/cli:doctor 2910 [*] Using Node 8.11.1
2018-05-03T08:08:01.887Z INF/cli:doctor 2910 [*] Using ZeroMQ 4.3.1
2018-05-03T08:08:01.942Z INF/cli:doctor 2910 [*] Using ADB 1.0.39
2018-05-03T08:08:02.544Z INF/cli:doctor 2910 [*] Using GraphicsMagick 1.3.28
2018-05-03T08:08:02.589Z INF/cli:doctor 2910 [*] Using ProtoBuf 3.5.1
2018-05-03T08:08:02.598Z INF/cli:doctor 2910 [*] Using RethinkDB 2.3.6

**Comment by gounthar** [comment]
Thanks @thinkhy. I used the OrangePi_OnePlus_Android_7.0_en_gapps_v1.3.img ROM.
I'm trying to compile a version myself (but not with much luck for the time being).
If you ever have some documentation about minitouch, I will see if I can make anything to get it to work for this board/ROM.

**Comment by thinkhy** [comment]
Is there any security option in setup panel of Android 7.0? If yes, you can attempt to enable it.
BTW, I've booked an Orange Pi One Plus online, will update this issue after trying out it:)

**Comment by gounthar** [comment]
Wow, thanks a lot! I will have a look at the security option if it ever exists.

**Comment by koral--** [comment]
This issue seems to be similar to: https://github.com/openstf/stf/issues/599 
This part of the log:
```
2018-05-03T08:03:55.337Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mouse1 is not supported by libevdev"
2018-05-03T08:03:55.527Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mouse0 is not supported by libevdev"
2018-05-03T08:03:55.647Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
2018-05-03T08:03:55.797Z INF/device:plugins:touch 2893 [20080411] minitouch says: "Unable to find a suitable touch device"
```
suggests that there is no touchscreen.
At the time of writing multitouch capability is required for minitouch to work.

**Comment by gounthar** [comment]
Yes, it looks like the source of the error is the same. I was thinking of buying an Odroid C2 to get rid of this issue as this card is way more supported than Orange Pi, but thanks to #599, I know it won't solve this issue.
I'll clone the minitouch repo, and see what I can do.
Thanks @koral-- .

**Comment by nateby** [comment]
@gounthar please provide the steps you made to install it on pi

**Comment by gounthar** [comment]
@nateby : sorry for not understanding. What do you want to know? How I installed Android on the OrangePi One Plus, or how I installed openSTF?
Thanks.

**Comment by nateby** [comment]
@gounthar I noticed that you made it with docker and docker-compose on a Raspberry 3B and it works flawlessly,I try hard and useless,I can't find docker images for 32bits and ARM
please provide the steps,thanks

**Comment by gounthar** [comment]
There's not much effort put into this: just a few images modified and built on the pi. I'll try to set it up in a repo and give you the link. Thanks for your interest @nateby.

**Comment by gounthar** [comment]
@nateby : I wrote a quick documentation about my use of hypriotOS and openSTF local there: https://github.com/gounthar/openstf-armv7-behind-proxy-with-hypriot.
I haven't done much, just gathered some information.
I will someday write another one regarding hypriotOS and openSTF provider (with some images of my own).

**Comment by nateby** [comment]
@gounthar thanks for your help ~^o^~~^o^~
