### ISSUE TITLE
STF Service dies a few seconds after starting

### ISSUE THREAD

**Issue by dhartwich1991** [openstf/stf#878]
Hello I need need help with making our STF run again.
Whenever I start it, it just shuts itself down after a few seconds.
My first guess was that it is related to adb somehow (see ./stf doctor output below) but I am not sure. Hope you can help!

**What is the issue or idea you have?**
STF Service just dies randomly.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
```
List of devices attached
07b93f3b               device usb:337772544X product:razor model:Nexus_7 device:flo transport_id:6
d99b466e15602841       device usb:336723968X product:gt510wifixx model:SM_T550 device:gt510wifi transport_id:5
3300abaa519163d7       device usb:337903616X product:a5xeltexx model:SM_A510F device:a5xelte transport_id:4
TA348002FQ             device usb:336670720X product:peregrine_retde model:XT1039 device:peregrine transport_id:3
04422fa825191c4c       device usb:336666624X product:hammerhead model:Nexus_5 device:hammerhead transport_id:2
05fd39fc006c065c       device usb:336662528X product:hammerhead model:Nexus_5 device:hammerhead transport_id:1
```

**Please provide the steps to reproduce the issue.**
1. Start rethinkdb
2. `./stf local 04422fa825191c4c`
3. After a few seconds the service just closes itself.

**What is the expected behavior?**
The devices / service should be accessible

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

```
 7110
2018-05-25T08:40:06.014Z INF/storage:plugins:apk 618 [*] Listening on port 7104
2018-05-25T08:40:06.018Z INF/db 615 [*] Connecting to 127.0.0.1:28015
2018-05-25T08:40:06.027Z INF/websocket 615 [*] Sending output to "tcp://127.0.0.1:7113"
2018-05-25T08:40:06.029Z INF/websocket 615 [*] Receiving input from "tcp://127.0.0.1:7111"
2018-05-25T08:40:06.553Z INF/app 613 [*] Using pre-built resources
2018-05-25T08:40:06.569Z INF/app 613 [*] Listening on port 7105
2018-05-25T08:40:06.571Z INF/db 613 [*] Connecting to 127.0.0.1:28015
2018-05-25T08:40:07.929Z INF/device:support:sub 623 [04422fa825191c4c] Receiving input from "tcp://127.0.0.1:7114"
2018-05-25T08:40:07.931Z INF/device:support:sub 623 [04422fa825191c4c] Subscribing to permanent channel "*ALL"
2018-05-25T08:40:07.973Z INF/device:support:properties 623 [04422fa825191c4c] Loading properties
2018-05-25T08:40:08.038Z INF/device:support:sdk 623 [04422fa825191c4c] Supports SDK 23
2018-05-25T08:40:08.040Z INF/device:support:abi 623 [04422fa825191c4c] Supports ABIs armeabi-v7a, armeabi
2018-05-25T08:40:08.146Z INF/device:resources:minicap 623 [04422fa825191c4c] Installing "/Users/android.manager/.npm-packages/lib/node_modules/stf/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/bin/minicap" as "/data/local/tmp/minicap"
2018-05-25T08:40:08.147Z INF/device:resources:minicap 623 [04422fa825191c4c] Installing "/Users/android.manager/.npm-packages/lib/node_modules/stf/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/lib/android-23/minicap.so" as "/data/local/tmp/minicap.so"
2018-05-25T08:40:08.337Z INF/device:resources:service 623 [04422fa825191c4c] Checking whether we need to install STFService
2018-05-25T08:40:09.031Z INF/device:resources:service 623 [04422fa825191c4c] Running version check
2018-05-25T08:40:09.897Z INF/device:resources:service 623 [04422fa825191c4c] STFService up to date
2018-05-25T08:40:09.899Z INF/device:plugins:service 623 [04422fa825191c4c] Launching agent
2018-05-25T08:40:10.679Z INF/device:plugins:service 623 [04422fa825191c4c] Agent says: "Listening on @stfagent"
2018-05-25T08:40:10.737Z INF/api 614 [*] Subscribing to permanent channel "*ALL"
2018-05-25T08:40:10.743Z INF/device:plugins:service 623 [04422fa825191c4c] Launching service
2018-05-25T08:40:10.745Z INF/device:plugins:service 623 [04422fa825191c4c] Agent says: "InputClient started"
2018-05-25T08:40:10.828Z INF/api 614 [*] Listening on port 7106
2018-05-25T08:40:10.840Z INF/api 614 [*] Sending output to "tcp://127.0.0.1:7113"
2018-05-25T08:40:10.842Z INF/api 614 [*] Receiving input from "tcp://127.0.0.1:7111"
2018-05-25T08:40:11.252Z INF/db 614 [*] Connecting to 127.0.0.1:28015
2018-05-25T08:40:11.630Z INF/device:plugins:display 623 [04422fa825191c4c] Reading display info
2018-05-25T08:40:11.641Z INF/device:plugins:phone 623 [04422fa825191c4c] Fetching phone info
2018-05-25T08:40:11.656Z INF/device:plugins:identity 623 [04422fa825191c4c] Solving identity
2018-05-25T08:40:11.657Z INF/device:plugins:solo 623 [04422fa825191c4c] Subscribing to permanent channel "NXF66aJA+8DzNYlBV73t2Pvelyk="
2018-05-25T08:40:11.659Z INF/device:plugins:screen:stream 623 [04422fa825191c4c] Starting WebSocket server on port 7400
2018-05-25T08:40:11.747Z INF/device:resources:minitouch 623 [04422fa825191c4c] Installing "/Users/android.manager/.npm-packages/lib/node_modules/stf/node_modules/minitouch-prebuilt/prebuilt/armeabi-v7a/bin/minitouch" as "/data/local/tmp/minitouch"
2018-05-25T08:40:11.796Z INF/device:plugins:touch 623 [04422fa825191c4c] Touch origin is top left
2018-05-25T08:40:11.798Z INF/device:plugins:touch 623 [04422fa825191c4c] Requesting touch consumer to start
2018-05-25T08:40:11.800Z INF/device:plugins:touch 623 [04422fa825191c4c] Launching touch service
2018-05-25T08:40:11.808Z INF/device:plugins:touch 623 [04422fa825191c4c] Connecting to minitouch service
2018-05-25T08:40:11.839Z INF/device:plugins:touch 623 [04422fa825191c4c] minitouch says: "Type B touch device touch_dev (1079x1919 with 10 contacts) detected on /dev/input/event1 (score 22447)"
2018-05-25T08:40:11.918Z INF/device:plugins:touch 623 [04422fa825191c4c] Reading minitouch banner
2018-05-25T08:40:11.919Z INF/device:plugins:touch 623 [04422fa825191c4c] minitouch says: "Connection established"
2018-05-25T08:40:11.924Z INF/device:plugins:vnc 623 [04422fa825191c4c] Starting VNC server on port 7402
2018-05-25T08:40:11.928Z INF/device:plugins:browser 623 [04422fa825191c4c] Loading browser list
2018-05-25T08:40:11.932Z INF/device:plugins:browser 623 [04422fa825191c4c] Updating browser list
2018-05-25T08:40:11.934Z INF/device:plugins:mute 623 [04422fa825191c4c] Will not mute master volume
2018-05-25T08:40:12.003Z INF/device:resources:minirev 623 [04422fa825191c4c] Installing "/Users/android.manager/.npm-packages/lib/node_modules/stf/vendor/minirev/armeabi-v7a/minirev" as "/data/local/tmp/minirev"
2018-05-25T08:40:12.068Z INF/device:plugins:forward 623 [04422fa825191c4c] Launching reverse port forwarding service
2018-05-25T08:40:12.072Z INF/device:plugins:forward 623 [04422fa825191c4c] Connecting to reverse port forwarding service
2018-05-25T08:40:12.955Z INF/device:plugins:connect 623 [04422fa825191c4c] Listening on port 7401
2018-05-25T08:40:12.957Z INF/device 623 [04422fa825191c4c] Fully operational
2018-05-25T08:40:13.817Z INF/provider 611 [*] Providing all 1 device(s)
2018-05-25T08:40:31.001Z INF/reaper 610 [reaper001] Reaping device "R32D300H43M" due to heartbeat timeout
2018-05-25T08:40:31.001Z INF/reaper 610 [reaper001] Reaping device "07b93f3b" due to heartbeat timeout
2018-05-25T08:40:31.001Z INF/reaper 610 [reaper001] Reaping device "TA348002FQ" due to heartbeat timeout
2018-05-25T08:40:31.001Z INF/reaper 610 [reaper001] Reaping device "3300abaa519163d7" due to heartbeat timeout
2018-05-25T08:40:31.002Z INF/reaper 610 [reaper001] Reaping device "05fd39fc006c065c" due to heartbeat timeout
2018-05-25T08:40:31.002Z INF/reaper 610 [reaper001] Reaping device "d99b466e15602841" due to heartbeat timeout
2018-05-25T08:40:35.536Z INF/auth-mock 612 [::ffff:127.0.0.1] Authenticated "abc@mgl.com"
2018-05-25T08:40:36.574Z INF/util:lifecycle 623 [04422fa825191c4c] Winding down for graceful exit
2018-05-25T08:40:36.575Z INF/util:lifecycle 615 [*] Winding down for graceful exit
2018-05-25T08:40:36.577Z INF/util:lifecycle 614 [*] Winding down for graceful exit
2018-05-25T08:40:36.578Z INF/util:lifecycle 613 [*] Winding down for graceful exit
2018-05-25T08:40:36.580Z INF/util:lifecycle 612 [*] Winding down for graceful exit
2018-05-25T08:40:36.580Z INF/auth-mock 612 [*] Waiting for client connections to end
2018-05-25T08:40:36.584Z INF/util:lifecycle 611 [*] Winding down for graceful exit
2018-05-25T08:40:36.584Z INF/util:lifecycle 610 [reaper001] Winding down for graceful exit
2018-05-25T08:40:36.588Z INF/util:lifecycle 609 [proc002] Winding down for graceful exit
2018-05-25T08:40:36.589Z INF/util:lifecycle 608 [proc001] Winding down for graceful exit
2018-05-25T08:40:36.590Z INF/provider 611 [*] Cleaning up device worker "04422fa825191c4c"
2018-05-25T08:40:36.591Z INF/util:lifecycle 607 [dev001] Winding down for graceful exit
2018-05-25T08:40:36.591Z INF/provider 611 [*] Gracefully killing device worker "04422fa825191c4c"
2018-05-25T08:40:36.593Z INF/util:lifecycle 606 [app001] Winding down for graceful exit
2018-05-25T08:40:36.594Z INF/cli:local 604 [*] Received SIGTERM, waiting for processes to terminate
2018-05-25T08:40:36.594Z INF/device:plugins:screen:stream 623 [04422fa825191c4c] Requesting frame producer to stop
2018-05-25T08:40:36.599Z WRN/db 609 [proc002] Connection closed
2018-05-25T08:40:36.601Z INF/util:lifecycle 611 [*] Winding down for graceful exit
2018-05-25T08:40:36.602Z INF/util:lifecycle 608 [proc001] Winding down for graceful exit
2018-05-25T08:40:36.603Z INF/util:lifecycle 610 [reaper001] Winding down for graceful exit
2018-05-25T08:40:36.603Z INF/util:lifecycle 613 [*] Winding down for graceful exit
2018-05-25T08:40:36.604Z WRN/db 608 [proc001] Connection closed
2018-05-25T08:40:36.605Z WRN/db 613 [*] Connection closed
2018-05-25T08:40:36.605Z WRN/db 610 [reaper001] Connection closed
2018-05-25T08:40:36.606Z INF/util:lifecycle 614 [*] Winding down for graceful exit
2018-05-25T08:40:36.606Z INF/util:lifecycle 615 [*] Winding down for graceful exit
2018-05-25T08:40:36.608Z WRN/db 614 [*] Connection closed
2018-05-25T08:40:36.608Z WRN/db 615 [*] Connection closed
Unhandled rejection CancellationError: cancellation error
    at Promise.cancel (/Users/android.manager/.npm-packages/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/cancel.js:21:40)
    at Tracker.end (/Users/android.manager/.npm-packages/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:81:17)
    at /Users/android.manager/.npm-packages/lib/node_modules/stf/lib/util/lifecycle.js:42:15
    at /Users/android.manager/.npm-packages/lib/node_modules/stf/lib/util/lifecycle.js:55:12
    at Array.map (native)
    at Lifecycle.graceful (/Users/android.manager/.npm-packages/lib/node_modules/stf/lib/util/lifecycle.js:54:41)
    at emitNone (events.js:105:13)
    at process.emit (events.js:207:7)
    at Signal.wrap.onsignal (internal/process.js:207:44)

```

**Please run `stf doctor` and paste the output here.**

Sometimes ADB version cannot be detected ( I think the issue is related to this)
```
mac-android:bin android.manager$ ./stf doctor
2018-05-25T08:46:34.627Z INF/cli:doctor 862 [*] OS Arch: x64
2018-05-25T08:46:34.630Z INF/cli:doctor 862 [*] OS Platform: darwin
2018-05-25T08:46:34.630Z INF/cli:doctor 862 [*] OS Platform: 15.6.0
2018-05-25T08:46:34.630Z INF/cli:doctor 862 [*] Using Node 8.1.2
2018-05-25T08:46:34.661Z INF/cli:doctor 862 [*] Using ZeroMQ 4.2.5
2018-05-25T08:46:34.698Z INF/cli:doctor 862 [*] Using RethinkDB 2.3.6
2018-05-25T08:46:34.699Z INF/cli:doctor 862 [*] Using GraphicsMagick 1.3.29
2018-05-25T08:46:34.699Z INF/cli:doctor 862 [*] Using ProtoBuf 3.3.0
2018-05-25T08:46:34.700Z ERR/cli:doctor 862 [*] ADB version cannot be detected

```

Sometimes it works as expected.
```
mac-android:bin android.manager$ ./stf doctor
2018-05-25T08:46:35.363Z INF/cli:doctor 867 [*] OS Arch: x64
2018-05-25T08:46:35.365Z INF/cli:doctor 867 [*] OS Platform: darwin
2018-05-25T08:46:35.365Z INF/cli:doctor 867 [*] OS Platform: 15.6.0
2018-05-25T08:46:35.365Z INF/cli:doctor 867 [*] Using Node 8.1.2
2018-05-25T08:46:35.389Z INF/cli:doctor 867 [*] Using ZeroMQ 4.2.5
2018-05-25T08:46:35.410Z INF/cli:doctor 867 [*] Using RethinkDB 2.3.6
2018-05-25T08:46:35.411Z INF/cli:doctor 867 [*] Using GraphicsMagick 1.3.29
2018-05-25T08:46:35.412Z INF/cli:doctor 867 [*] Using ProtoBuf 3.3.0
2018-05-25T08:46:35.414Z INF/cli:doctor 867 [*] Using ADB 1.0.39
```

**Comment by danielknott** [comment]
Still having this issue :(. @sorccu any idea what can cause this ?

**Comment by danielknott** [comment]
Ok, after a complete re-installation of everything including Android SDK it is up and running again. No, idea what was causing this...

**Comment by ysxAAA** [comment]
did you fix this?can you help me?
