### ISSUE TITLE
[Websocket] Browser cannot display the device screen

### ISSUE THREAD

**Issue by goswings** [openstf/stf#888]
I already use the latest docker version
[Docker Environment]
1. STF 
2. ADB
3. RethinkDB

[Issue]
Step1. Click any Product
![image](https://user-images.githubusercontent.com/26316763/41453004-bf650be2-70a6-11e8-9c39-3bf212af1cce.png)

Step2. Display screen normally
![image](https://user-images.githubusercontent.com/26316763/41453089-fc10cd1a-70a6-11e8-80ec-02e35817e82f.png)

Step3. Click "x" to stop using and back to home page
Step4. Click the previous product, but no screen display
![image](https://user-images.githubusercontent.com/26316763/41453219-736a1614-70a7-11e8-90e4-1b0fdc18019f.png)
 
Step5. Click "x", then pop up "No device found"
![image](https://user-images.githubusercontent.com/26316763/41453240-9535084e-70a7-11e8-88ac-08fc68c613bd.png)

from Chrome develop tools:
{Normal case}
![image](https://user-images.githubusercontent.com/26316763/41453329-eba03faa-70a7-11e8-85fd-5b821d862b6b.png)

{error case}
![image](https://user-images.githubusercontent.com/26316763/41453350-fd9fa16e-70a7-11e8-891d-7f166f560621.png)

seems no "websocket" pop up?
Any idea for this?

**Comment by sorccu** [comment]
You should see two WebSockets when the screen is active. One for the app itself, and one just for the screen data.

**Comment by goswings** [comment]
Hi Sorccu,
From DEVtools, I only see 1 websockets when the screen is active.

**Comment by goswings** [comment]
Hi Sorccu,
We found this issue only happened in Win10.
If user site is win10, then access the STF will encounter this issue

**Comment by goswings** [comment]
The error log as below
-----------------------------------------------------------------------------------------------------------------
018-06-19T18:13:46.821Z INF/device:plugins:group 121 [8SGIKVIZGEZDPV5L] Unsubscribing from group channel "ohcMtwovRNyNuNgoYC0yrg=="
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26)
2018-06-19T18:13:46.867Z INF/provider 43 [*] Cleaning up device worker "8SGIKVIZGEZDPV5L"
2018-06-19T18:13:46.868Z ERR/provider 43 [*] Device worker "8SGIKVIZGEZDPV5L" died with code 1
2018-06-19T18:13:46.868Z INF/provider 43 [*] Restarting device worker "8SGIKVIZGEZDPV5L"
---------------------------------------------------------------------------------------------------------------

**Comment by TachunLin** [comment]
Hi @sorccu, 

We also encounter the same 100% reproducible issue on Windows 10. 


By using any type of browser (chrome, firefox, IE, ...) in control page. 
Click the X button or right click to stop using device 

![image](https://user-images.githubusercontent.com/29251855/63158034-f6aa9c80-c04a-11e9-9341-2e313aa5880a.png)

Then open this device again, it will show grey out page with "device not found" message

![image](https://user-images.githubusercontent.com/29251855/63158405-c1eb1500-c04b-11e9-9313-5739ede1a856.png)

Comparing the passed and failed log 

![image](https://user-images.githubusercontent.com/29251855/63158995-12af3d80-c04d-11e9-8e40-0c93adfd284d.png)

Since more and more user are using windows 10 machine and report this issue to us. 
We are looking foward to your suggestion on how to solve this issue. 

Attached log file for your reference.
[stf_win7_disct.txt](https://github.com/openstf/stf/files/3509002/stf_win7_disct.txt)
[stf_win10_disct.txt](https://github.com/openstf/stf/files/3509003/stf_win10_disct.txt)

Thank you in advance.

**Comment by TachunLin** [comment]
Hi @sorccu , 

We check and found the error message may caused by the compatibility between node server and win10 client. Which make the websocket connection closed by peer.  

We find a workaround is to change ws module from default 3.1.2 to 3.3.2. 
By updating the "ws" version in package.json and run install the connection will not be terminated. '

Hope a better solution can be updated in the future release.

**Comment by offshore2** [comment]
Hi @sorccu 

We are using Open STF tool for handset testing and currently we are facing similar issue as described above. After clicking on "Use" option from the device list the device screen is not displaying instead showing Grey color.

We are using Windows 10 OS.

The very first time when we faced the issue we just enabled the respective port number and it started working. 
But now again the port number has been changed to different DHCP series and unable to access devices. It is very difficult to enable a port of different range every time, which is time consuming and blocking deliverable.

Can you please let me know if any other way to solve this issue.

**Comment by offshore2** [comment]
Hi @sorccu 

Can you please provide solution.
