### ISSUE TITLE
reconnection problem

### ISSUE THREAD

**Issue by chinkw** [openstf/stf#907]
when the smartphone change, there is error below
then device isn't recognized

reinstalling nodejs, protobuf etc..
 
Unhandled rejection Error: Illegal value for Message.Field .DeviceIntroductionMessage.status of type enum: undefined (not a valid enum value)
    at Error (native)
    at T.<anonymous> (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
    at T.ProtoBuf.Reflect.FieldPrototype.verifyValue (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2738:25)
    at MessagePrototype.set (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1799:63)
    at Message (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1728:42)
    at /usr/lib/node_modules/stf/lib/units/provider/index.js:165:29
    at /usr/lib/node_modules/stf/lib/units/provider/index.js:161:22
    at Tracker.<anonymous> (/usr/lib/node_modules/stf/lib/units/provider/index.js:144:16)
    at emitOne (events.js:96:13)
    at Tracker.emit (events.js:188:7)
    at Tracker.update (/usr/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:62:14)
    at /usr/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:38:15
Unhandled rejection Error: Illegal value for Message.Field .DeviceIntroductionMessage.status of type enum: undefined (not a valid enum value)
    at Error (native)
    at T.<anonymous> (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
    at T.ProtoBuf.Reflect.FieldPrototype.verifyValue (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2738:25)
    at MessagePrototype.set (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1799:63)
    at Message (/usr/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1728:42)
    at /usr/lib/node_modules/stf/lib/units/provider/index.js:165:29
    at /usr/lib/node_modules/stf/lib/units/provider/index.js:161:22
    at Tracker.<anonymous> (/usr/lib/node_modules/stf/lib/units/provider/index.js:144:16)
    at emitOne (events.js:96:13)
    at Tracker.emit (events.js:188:7)
    at Tracker.update (/usr/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:62:14)
    at /usr/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:38:15

**Comment by sorccu** [comment]
How does it change? Please provide the full output from STF. You can run `stf local 2>&1  | tee -a out.log` to capture the entire output.

**Comment by obrie** [comment]
I appear to get this error because the device's `type` is set to `connecting` and there's no corresponding status here: https://github.com/openstf/stf/blob/616d4407ce1494a7a89ed6c1a17677b88e15e455/lib/wire/util.js#L10-L17

**Comment by obrie** [comment]
Looks like some new states have been added in the latest version of ADB: https://github.com/aosp-mirror/platform_system_core/commit/704494b0707a49e064b63192619a73336c1be05a

Specifically "connecting" and "authorizing"
