### ISSUE TITLE
Way to resync new phones without restarting STF

### ISSUE THREAD

**Issue by KingHueyy** [openstf/stf#912]
I have STF up and running just fine without any issues. It is very stable and works great. My only question is if there is a way to refresh STF without having to restart it to pick up new phones. Whenever I plug in a new phone, STF attempts to read it and then throws some error. To get it to register, I have to close the CLI and re-run STF to get the server back up which then reads the phone just fine. 

Note: I am running stf local - public IP (which I know is not recommended) for testing reasons. 

Outside of having to restart STF to pick up newly plugged in devices, the system works great. Thanks for all the hard work put into this.

**Comment by sorccu** [comment]
That shouldn't happen. You should be able to just plug in new devices without having to restart. What's the error you're seeing? Please provide as much context as possible.

**Comment by mr-sour** [comment]
My issue had todo with how I was passing the USB devices in docker and not a problem with STF itself.

**Comment by KingHueyy** [comment]
I connect a phone and get this error, then it ignores the phones. Once I restart though it picks it up and works fine. 

```
Unhandled rejection Error: Illegal value for Message.Field .DeviceIntroductionMessage.status of type enum: undefined (not a valid enum value)
    at Field.<anonymous> (/usr/local/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/usr/local/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:2738:25)
    at MessagePrototype.set (/usr/local/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1799:63)
    at new Message (/usr/local/lib/node_modules/stf/node_modules/protobufjs/dist/ProtoBuf.js:1728:42)
    at /usr/local/lib/node_modules/stf/lib/units/provider/index.js:165:29
    at /usr/local/lib/node_modules/stf/lib/units/provider/index.js:161:22
    at Tracker.<anonymous> (/usr/local/lib/node_modules/stf/lib/units/provider/index.js:144:16)
    at emitOne (events.js:116:13)
    at Tracker.emit (events.js:211:7)
    at Tracker.update (/usr/local/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:62:14)
    at /usr/local/lib/node_modules/stf/node_modules/adbkit/lib/adb/tracker.js:38:15
    at runCallback (timers.js:810:20)
```

**Comment by sorccu** [comment]
Your STF is probably too old. This was fixed a while ago.
