### ISSUE TITLE
Zeromq error : Undefined Symbol

### ISSUE THREAD

**Issue by JayMac87** [openstf/stf#927]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**
I Have Installed All Dependencies And Now Only Receiving One Error. Will Paste Below

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

---MY STF LOCAL OUTPUT

postpilots@PostPilots:~$ stf local
2018-08-08T03:51:05.301Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli migrate"
2018-08-08T03:51:06.550Z INF/db 7193 [*] Connecting to 127.0.0.1:28015
2018-08-08T03:51:06.640Z INF/db:setup 7193 [*] Database "stf" already exists
2018-08-08T03:51:06.677Z INF/db:setup 7193 [*] Table "users" already exists
2018-08-08T03:51:06.677Z INF/db:setup 7193 [*] Table "accessTokens" already exists
2018-08-08T03:51:06.678Z INF/db:setup 7193 [*] Table "vncauth" already exists
2018-08-08T03:51:06.678Z INF/db:setup 7193 [*] Table "devices" already exists
2018-08-08T03:51:06.678Z INF/db:setup 7193 [*] Table "logs" already exists
2018-08-08T03:51:06.746Z INF/db:setup 7193 [*] Index "users"."adbKeys" already exists
2018-08-08T03:51:06.747Z INF/db:setup 7193 [*] Index "accessTokens"."email" already exists
2018-08-08T03:51:06.748Z INF/db:setup 7193 [*] Index "vncauth"."response" already exists
2018-08-08T03:51:06.749Z INF/db:setup 7193 [*] Index "vncauth"."responsePerDevice" already exists
2018-08-08T03:51:06.749Z INF/db:setup 7193 [*] Index "devices"."owner" already exists
2018-08-08T03:51:06.749Z INF/db:setup 7193 [*] Waiting for index "users"."adbKeys"
2018-08-08T03:51:06.752Z INF/db:setup 7193 [*] Waiting for index "accessTokens"."email"
2018-08-08T03:51:06.753Z INF/db:setup 7193 [*] Waiting for index "vncauth"."response"
2018-08-08T03:51:06.754Z INF/db:setup 7193 [*] Waiting for index "vncauth"."responsePerDevice"
2018-08-08T03:51:06.755Z INF/db:setup 7193 [*] Waiting for index "devices"."owner"
2018-08-08T03:51:06.771Z INF/db:setup 7193 [*] Index "devices"."present" already exists
2018-08-08T03:51:06.772Z INF/db:setup 7193 [*] Index "devices"."providerChannel" already exists
2018-08-08T03:51:06.773Z INF/db:setup 7193 [*] Waiting for index "devices"."present"
2018-08-08T03:51:06.775Z INF/db:setup 7193 [*] Waiting for index "devices"."providerChannel"
2018-08-08T03:51:06.782Z INF/db:setup 7193 [*] Index "users"."adbKeys" is ready
2018-08-08T03:51:06.791Z INF/db:setup 7193 [*] Index "accessTokens"."email" is ready
2018-08-08T03:51:06.791Z INF/db:setup 7193 [*] Index "vncauth"."response" is ready
2018-08-08T03:51:06.792Z INF/db:setup 7193 [*] Index "vncauth"."responsePerDevice" is ready
2018-08-08T03:51:06.792Z INF/db:setup 7193 [*] Index "devices"."owner" is ready
2018-08-08T03:51:06.798Z INF/db:setup 7193 [*] Index "devices"."present" is ready
2018-08-08T03:51:06.798Z INF/db:setup 7193 [*] Index "devices"."providerChannel" is ready
2018-08-08T03:51:06.834Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2018-08-08T03:51:06.845Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2018-08-08T03:51:06.863Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2018-08-08T03:51:06.874Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2018-08-08T03:51:06.885Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2018-08-08T03:51:06.910Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli provider --name PostPilots --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"
2018-08-08T03:51:06.926Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
2018-08-08T03:51:06.955Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
2018-08-08T03:51:06.986Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
2018-08-08T03:51:07.025Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2018-08-08T03:51:07.079Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli storage-temp --port 7102"
2018-08-08T03:51:07.130Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2018-08-08T03:51:07.177Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2018-08-08T03:51:07.218Z INF/util:procutil 7187 [*] Forking "/usr/local/lib/node_modules/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
/usr/local/lib/node_modules/stf/lib/cli triproxy [name]

Options:
  -h, --help         Show help.                              [boolean]
  -V, --version      Show version.                           [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint
                     to.            [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                    [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                    [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                      [string] [default: "PostPilots"]

Each option can be be overwritten with an environment variable by
converting the option to uppercase, replacing dashes with underscores
and prefixing it with `STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

/usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node: undefined symbol: _ZNK2v85Value9ToIntegerEv
2018-08-08T03:51:17.578Z FTL/cli:local 7187 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
2018-08-08T03:51:17.615Z INF/cli:local 7187 [*] Shutting down all child processes
/usr/local/lib/node_modules/stf/lib/cli triproxy [name]

Options:
  -h, --help         Show help.                              [boolean]
  -V, --version      Show version.                           [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint
                     to.            [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                    [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                    [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                      [string] [default: "PostPilots"]

Each option can be be overwritten with an environment variable by
converting the option to uppercase, replacing dashes with underscores
and prefixing it with `STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

/usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node: undefined symbol: _ZNK2v85Value9ToIntegerEv

**Please run `stf doctor` and paste the output here.**

--STF DOCTOR OUTPUT:

postpilots@PostPilots:~$ stf doctor
2018-08-08T03:57:39.022Z INF/cli:doctor 7348 [*] OS Arch: ia32
2018-08-08T03:57:39.029Z INF/cli:doctor 7348 [*] OS Platform: linux
2018-08-08T03:57:39.032Z INF/cli:doctor 7348 [*] OS Platform: 4.15.0-29-generic
2018-08-08T03:57:39.032Z INF/cli:doctor 7348 [*] Using Node 6.9.2
2018-08-08T03:57:39.257Z ERR/cli:doctor 7348 [*] Unexpected error checking ZeroMQ: Error: /usr/local/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node: undefined symbol: _ZNK2v85Value9ToIntegerEv
2018-08-08T03:57:39.284Z INF/cli:doctor 7348 [*] Using GraphicsMagick 1.3.30
2018-08-08T03:57:39.292Z ERR/cli:doctor 7348 [*] ProtoBuf version cannot be detected
2018-08-08T03:57:39.293Z ERR/cli:doctor 7348 [*] ADB version cannot be detected
2018-08-08T03:57:39.302Z INF/cli:doctor 7348 [*] Using RethinkDB 2.3.6

Sometimes It Detects The ProtoBuf version and sometimes it doesn't. I Dont Know Why Or If That Is A Problem. But, It Seems Like The Real Problem Is With Zeromq. I Would Appreciate Any Help. Thanks.

**Comment by hhnisenbaum** [comment]
I resolved this issue changing Node version. Im using node9 at the moment.
Cheers.

**Comment by thinkhy** [comment]
Seems you don't install zmq module correctly, suggest to re-compile zmq code and re-install related npm modules.
