### ISSUE TITLE
Error when initiating stf "Could not locate the bindings file."

### ISSUE THREAD

**Issue by mygit00** [openstf/stf#928]
I'm using v3.3.0 because v3.3.1 is not getting update

**What is the issue or idea you have?**
Error when initiating stf "Could not locate the bindings file."

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
Not applicable because we did not reach this far. Error is occurring before we get to do this.

**Please provide the steps to reproduce the issue.**
from command line, we give this command, stf local --public-ip 10.0.0.37

**What is the expected behavior?**
server should start without any error

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
root@user-HVM-domU:/usr/lib/node_modules/stf/node_modules# stf local --public-ip 10.0.0.37
2018-08-08T09:47:02.169Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli migrate"
2018-08-08T09:47:02.558Z INF/db 31043 [*] Connecting to 127.0.0.1:28015
2018-08-08T09:47:02.588Z INF/db:setup 31043 [*] Database "stf" already exists
2018-08-08T09:47:02.600Z INF/db:setup 31043 [*] Table "users" already exists
2018-08-08T09:47:02.601Z INF/db:setup 31043 [*] Table "accessTokens" already exists
2018-08-08T09:47:02.601Z INF/db:setup 31043 [*] Table "vncauth" already exists
2018-08-08T09:47:02.601Z INF/db:setup 31043 [*] Table "devices" already exists
2018-08-08T09:47:02.601Z INF/db:setup 31043 [*] Table "logs" already exists
2018-08-08T09:47:02.629Z INF/db:setup 31043 [*] Index "users"."adbKeys" already exists
2018-08-08T09:47:02.629Z INF/db:setup 31043 [*] Index "accessTokens"."email" already exists
2018-08-08T09:47:02.630Z INF/db:setup 31043 [*] Index "vncauth"."response" already exists
2018-08-08T09:47:02.630Z INF/db:setup 31043 [*] Index "vncauth"."responsePerDevice" already exists
2018-08-08T09:47:02.630Z INF/db:setup 31043 [*] Index "devices"."owner" already exists
2018-08-08T09:47:02.630Z INF/db:setup 31043 [*] Index "devices"."present" already exists
2018-08-08T09:47:02.630Z INF/db:setup 31043 [*] Index "devices"."providerChannel" already exists
2018-08-08T09:47:02.631Z INF/db:setup 31043 [*] Waiting for index "users"."adbKeys"
2018-08-08T09:47:02.633Z INF/db:setup 31043 [*] Waiting for index "accessTokens"."email"
2018-08-08T09:47:02.634Z INF/db:setup 31043 [*] Waiting for index "vncauth"."response"
2018-08-08T09:47:02.635Z INF/db:setup 31043 [*] Waiting for index "vncauth"."responsePerDevice"
2018-08-08T09:47:02.637Z INF/db:setup 31043 [*] Waiting for index "devices"."owner"
2018-08-08T09:47:02.638Z INF/db:setup 31043 [*] Waiting for index "devices"."present"
2018-08-08T09:47:02.641Z INF/db:setup 31043 [*] Waiting for index "devices"."providerChannel"
2018-08-08T09:47:02.649Z INF/db:setup 31043 [*] Index "users"."adbKeys" is ready
2018-08-08T09:47:02.649Z INF/db:setup 31043 [*] Index "accessTokens"."email" is ready
2018-08-08T09:47:02.649Z INF/db:setup 31043 [*] Index "vncauth"."response" is ready
2018-08-08T09:47:02.650Z INF/db:setup 31043 [*] Index "vncauth"."responsePerDevice" is ready
2018-08-08T09:47:02.650Z INF/db:setup 31043 [*] Index "devices"."owner" is ready
2018-08-08T09:47:02.650Z INF/db:setup 31043 [*] Index "devices"."present" is ready
2018-08-08T09:47:02.650Z INF/db:setup 31043 [*] Index "devices"."providerChannel" is ready
2018-08-08T09:47:02.658Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.-bind-pull tcp://127.0.0.1:7113"
2018-08-08T09:47:02.662Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.-bind-pull tcp://127.0.0.1:7116"
2018-08-08T09:47:02.668Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-de://127.0.0.1:7115"
2018-08-08T09:47:02.672Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-de://127.0.0.1:7115"
2018-08-08T09:47:02.676Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp:/111"
2018-08-08T09:47:02.688Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli provider --name user-HVM-domU --min-port 7400 --max-port 7700 --connect-7.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip 10.0.0.37 --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vize 600x800 --mute-master never"
2018-08-08T09:47:02.696Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://10.0.0.37:
2018-08-08T09:47:02.704Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://10.0.0.37:7100/-websocket-url http://10.0.0.37:7110/"
2018-08-08T09:47:02.720Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:71-sub tcp://127.0.0.1:7111"
2018-08-08T09:47:02.732Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhconnect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2018-08-08T09:47:02.744Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-temp --port 7102"
2018-08-08T09:47:02.756Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2018-08-08T09:47:02.772Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2018-08-08T09:47:02.784Z INF/util:procutil 31037 [*] Forking "/usr/lib/node_modules/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://lo/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storak-url http://localhost:7104/"
../lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                             [string] [default: "user-HVM-domU"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

../lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                             [string] [default: "user-HVM-domU"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Module version mismatch. Expected 48, got 46.
2018-08-08T09:47:07.902Z FTL/cli:local 31037 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
2018-08-08T09:47:07.912Z INF/cli:local 31037 [*] Shutting down all child processes
Module version mismatch. Expected 48, got 46.
root@user-HVM-domU:/usr/lib/node_modules/stf/node_modules#
root@user-HVM-domU:/usr/lib/node_modules/stf/node_modules#
root@user-HVM-domU:/usr/lib/node_modules/stf/node_modules# mv zmq .t
root@user-HVM-domU:/usr/lib/node_modules/stf/node_modules# mv zmq_new/ zmq
root@user-HVM-domU:/usr/lib/node_modules/stf/node_modules# stf local --public-ip 10.0.0.37
2018-08-08T09:48:32.861Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli migrate"
2018-08-08T09:48:33.225Z INF/db 31165 [*] Connecting to 127.0.0.1:28015
2018-08-08T09:48:33.257Z INF/db:setup 31165 [*] Database "stf" already exists
2018-08-08T09:48:33.270Z INF/db:setup 31165 [*] Table "users" already exists
2018-08-08T09:48:33.270Z INF/db:setup 31165 [*] Table "accessTokens" already exists
2018-08-08T09:48:33.270Z INF/db:setup 31165 [*] Table "vncauth" already exists
2018-08-08T09:48:33.271Z INF/db:setup 31165 [*] Table "devices" already exists
2018-08-08T09:48:33.271Z INF/db:setup 31165 [*] Table "logs" already exists
2018-08-08T09:48:33.300Z INF/db:setup 31165 [*] Index "users"."adbKeys" already exists
2018-08-08T09:48:33.300Z INF/db:setup 31165 [*] Index "accessTokens"."email" already exists
2018-08-08T09:48:33.301Z INF/db:setup 31165 [*] Index "vncauth"."response" already exists
2018-08-08T09:48:33.301Z INF/db:setup 31165 [*] Index "vncauth"."responsePerDevice" already exists
2018-08-08T09:48:33.301Z INF/db:setup 31165 [*] Index "devices"."owner" already exists
2018-08-08T09:48:33.301Z INF/db:setup 31165 [*] Index "devices"."present" already exists
2018-08-08T09:48:33.301Z INF/db:setup 31165 [*] Index "devices"."providerChannel" already exists
2018-08-08T09:48:33.302Z INF/db:setup 31165 [*] Waiting for index "users"."adbKeys"
2018-08-08T09:48:33.304Z INF/db:setup 31165 [*] Waiting for index "accessTokens"."email"
2018-08-08T09:48:33.305Z INF/db:setup 31165 [*] Waiting for index "vncauth"."response"
2018-08-08T09:48:33.306Z INF/db:setup 31165 [*] Waiting for index "vncauth"."responsePerDevice"
2018-08-08T09:48:33.308Z INF/db:setup 31165 [*] Waiting for index "devices"."owner"
2018-08-08T09:48:33.309Z INF/db:setup 31165 [*] Waiting for index "devices"."present"
2018-08-08T09:48:33.312Z INF/db:setup 31165 [*] Waiting for index "devices"."providerChannel"
2018-08-08T09:48:33.320Z INF/db:setup 31165 [*] Index "users"."adbKeys" is ready
2018-08-08T09:48:33.320Z INF/db:setup 31165 [*] Index "accessTokens"."email" is ready
2018-08-08T09:48:33.320Z INF/db:setup 31165 [*] Index "vncauth"."response" is ready
2018-08-08T09:48:33.320Z INF/db:setup 31165 [*] Index "vncauth"."responsePerDevice" is ready
2018-08-08T09:48:33.320Z INF/db:setup 31165 [*] Index "devices"."owner" is ready
2018-08-08T09:48:33.320Z INF/db:setup 31165 [*] Index "devices"."present" is ready
2018-08-08T09:48:33.321Z INF/db:setup 31165 [*] Index "devices"."providerChannel" is ready
2018-08-08T09:48:33.329Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.-bind-pull tcp://127.0.0.1:7113"
2018-08-08T09:48:33.333Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.-bind-pull tcp://127.0.0.1:7116"
2018-08-08T09:48:33.340Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-de://127.0.0.1:7115"
2018-08-08T09:48:33.344Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-de://127.0.0.1:7115"
2018-08-08T09:48:33.348Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp:/111"
2018-08-08T09:48:33.352Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli provider --name user-HVM-domU --min-port 7400 --max-port 7700 --connect-7.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip 10.0.0.37 --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vize 600x800 --mute-master never"
2018-08-08T09:48:33.360Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://10.0.0.37:
2018-08-08T09:48:33.372Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://10.0.0.37:7100/-websocket-url http://10.0.0.37:7110/"
2018-08-08T09:48:33.380Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:71-sub tcp://127.0.0.1:7111"
2018-08-08T09:48:33.392Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhconnect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2018-08-08T09:48:33.400Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-temp --port 7102"
2018-08-08T09:48:33.412Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2018-08-08T09:48:33.424Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2018-08-08T09:48:33.440Z INF/util:procutil 31159 [*] Forking "/usr/lib/node_modules/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://lo/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storak-url http://localhost:7104/"
../lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                             [string] [default: "user-HVM-domU"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/compiled/6.14.3/linux/x64/zmq.node
../lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                             [string] [default: "user-HVM-domU"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/compiled/6.14.3/linux/x64/zmq.node
2018-08-08T09:48:38.487Z FTL/cli:local 31159 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
2018-08-08T09:48:38.504Z INF/cli:local 31159 [*] Shutting down all child processes
root@user-HVM-domU:/usr/lib/node_modules/stf/node_modules# stf local --public-ip 10.0.0.37
2018-08-08T10:01:40.510Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli migrate"
2018-08-08T10:01:41.024Z INF/db 31274 [*] Connecting to 127.0.0.1:28015
2018-08-08T10:01:41.055Z INF/db:setup 31274 [*] Database "stf" already exists
2018-08-08T10:01:41.068Z INF/db:setup 31274 [*] Table "users" already exists
2018-08-08T10:01:41.069Z INF/db:setup 31274 [*] Table "accessTokens" already exists
2018-08-08T10:01:41.069Z INF/db:setup 31274 [*] Table "vncauth" already exists
2018-08-08T10:01:41.069Z INF/db:setup 31274 [*] Table "devices" already exists
2018-08-08T10:01:41.069Z INF/db:setup 31274 [*] Table "logs" already exists
2018-08-08T10:01:41.098Z INF/db:setup 31274 [*] Index "users"."adbKeys" already exists
2018-08-08T10:01:41.098Z INF/db:setup 31274 [*] Index "accessTokens"."email" already exists
2018-08-08T10:01:41.098Z INF/db:setup 31274 [*] Index "vncauth"."response" already exists
2018-08-08T10:01:41.099Z INF/db:setup 31274 [*] Index "vncauth"."responsePerDevice" already exists
2018-08-08T10:01:41.099Z INF/db:setup 31274 [*] Index "devices"."owner" already exists
2018-08-08T10:01:41.099Z INF/db:setup 31274 [*] Index "devices"."present" already exists
2018-08-08T10:01:41.099Z INF/db:setup 31274 [*] Index "devices"."providerChannel" already exists
2018-08-08T10:01:41.100Z INF/db:setup 31274 [*] Waiting for index "users"."adbKeys"
2018-08-08T10:01:41.101Z INF/db:setup 31274 [*] Waiting for index "accessTokens"."email"
2018-08-08T10:01:41.103Z INF/db:setup 31274 [*] Waiting for index "vncauth"."response"
2018-08-08T10:01:41.104Z INF/db:setup 31274 [*] Waiting for index "vncauth"."responsePerDevice"
2018-08-08T10:01:41.105Z INF/db:setup 31274 [*] Waiting for index "devices"."owner"
2018-08-08T10:01:41.107Z INF/db:setup 31274 [*] Waiting for index "devices"."present"
2018-08-08T10:01:41.109Z INF/db:setup 31274 [*] Waiting for index "devices"."providerChannel"
2018-08-08T10:01:41.117Z INF/db:setup 31274 [*] Index "users"."adbKeys" is ready
2018-08-08T10:01:41.117Z INF/db:setup 31274 [*] Index "accessTokens"."email" is ready
2018-08-08T10:01:41.118Z INF/db:setup 31274 [*] Index "vncauth"."response" is ready
2018-08-08T10:01:41.118Z INF/db:setup 31274 [*] Index "vncauth"."responsePerDevice" is ready
2018-08-08T10:01:41.118Z INF/db:setup 31274 [*] Index "devices"."owner" is ready
2018-08-08T10:01:41.118Z INF/db:setup 31274 [*] Index "devices"."present" is ready
2018-08-08T10:01:41.118Z INF/db:setup 31274 [*] Index "devices"."providerChannel" is ready
2018-08-08T10:01:41.127Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2018-08-08T10:01:41.130Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2018-08-08T10:01:41.136Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2018-08-08T10:01:41.140Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2018-08-08T10:01:41.148Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2018-08-08T10:01:41.156Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli provider --name user-HVM-domU --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip 10.0.0.37 --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"
2018-08-08T10:01:41.164Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://10.0.0.37:7100/"
2018-08-08T10:01:41.172Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli app --port 7105 --secret kute kittykat --auth-url http://10.0.0.37:7100/auth/mock/ --websocket-url http://10.0.0.37:7110/"
2018-08-08T10:01:41.184Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
2018-08-08T10:01:41.196Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2018-08-08T10:01:41.208Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-temp --port 7102"
2018-08-08T10:01:41.216Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2018-08-08T10:01:41.232Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2018-08-08T10:01:41.248Z INF/util:procutil 31268 [*] Forking "/usr/lib/node_modules/stf/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
../lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                             [string] [default: "user-HVM-domU"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/compiled/6.14.3/linux/x64/zmq.node
2018-08-08T10:01:46.323Z FTL/cli:local 31268 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/usr/lib/node_modules/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
2018-08-08T10:01:46.340Z INF/cli:local 31268 [*] Shutting down all child processes
../lib/cli triproxy [name]

Options:
  -h, --help         Show help.                                        [boolean]
  -V, --version      Show version.                                     [boolean]
  --bind-dealer, -d  The address to bind the ZeroMQ DEALER endpoint to.
                                              [string] [default: "tcp://*:7112"]
  --bind-pub, -u     The address to bind the ZeroMQ PUB endpoint to.
                                              [string] [default: "tcp://*:7111"]
  --bind-pull, -p    The address to bind the ZeroMQ PULL endpoint to.
                                              [string] [default: "tcp://*:7113"]
  --name             An easily identifiable name for log output.
                                             [string] [default: "user-HVM-domU"]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_TRIPROXY_` (e.g. `STF_TRIPROXY_BIND_PUB`).

Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/compiled/6.14.3/linux/x64/zmq.node

**Please run `stf doctor` and paste the output here.**
root@user-HVM-domU:/usr/lib/node_modules/stf# stf doctor
2018-08-08T10:18:33.776Z INF/cli:doctor 1274 [*] OS Arch: x64
2018-08-08T10:18:33.779Z INF/cli:doctor 1274 [*] OS Platform: linux
2018-08-08T10:18:33.780Z INF/cli:doctor 1274 [*] OS Platform: 4.10.0-28-generic
2018-08-08T10:18:33.780Z INF/cli:doctor 1274 [*] Using Node 6.14.3
2018-08-08T10:18:34.045Z ERR/cli:doctor 1274 [*] Unexpected error checking ZeroMQ: Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/stf/node_modules/zmq/build/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Debug/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/out/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/Release/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/build/default/zmq.node
 → /usr/lib/node_modules/stf/node_modules/zmq/compiled/6.14.3/linux/x64/zmq.node
2018-08-08T10:18:34.056Z INF/cli:doctor 1274 [*] Using ADB 1.0.32
2018-08-08T10:18:34.076Z INF/cli:doctor 1274 [*] Using GraphicsMagick 1.3.30
2018-08-08T10:18:34.121Z INF/cli:doctor 1274 [*] Using ProtoBuf 3.2.0
2018-08-08T10:18:34.325Z INF/cli:doctor 1274 [*] Using RethinkDB 2.3.6~0xenial

**Comment by openjon9** [comment]
sudo uninstall -g stf

sudo npm install -g cnpm --registry=https://registry.npm.taobao.org

sudo cnpm install -g stf

rethinkdb

stf local

**Comment by rakib-amin** [comment]
Just run `npm install zmq`
