### ISSUE TITLE
404 error in the console

### ISSUE THREAD

**Issue by habeebshk** [openstf/stf#980]
**What is the issue or idea you have?**
I am deploying STF using the official script but when i complete and everything and connect a device it shows up for a second and diasppers, and i see this 404 error in the console, can you please explain what it is and is it related to STF-API
**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
![image](https://user-images.githubusercontent.com/36462909/47946298-5e3e9380-dee0-11e8-9518-3b4ceff91298.png)

**Please run `stf doctor` and paste the output here.**

**Comment by koral--** [comment]
Please follow issue template and provide more info.
Hint: **Do you see errors or warnings in the stf local output? If so, please paste them or the full log here.** this point is the most important here.

**Comment by habeebshk** [comment]
The only error i see the local output is this one right here ```2018-11-05T20:33:34.380Z INF/db:setup 44 [*] Waiting for index "devices"."providerChannel"
2018-11-05T20:33:34.409Z INF/db:setup 44 [*] Index "users"."adbKeys" is ready
2018-11-05T20:33:34.418Z INF/db:setup 44 [*] Index "accessTokens"."email" is ready
2018-11-05T20:33:34.418Z INF/db:setup 44 [*] Index "vncauth"."response" is ready
2018-11-05T20:33:34.419Z INF/db:setup 44 [*] Index "vncauth"."responsePerDevice" is ready
2018-11-05T20:33:34.419Z INF/db:setup 44 [*] Index "devices"."owner" is ready
2018-11-05T20:33:34.458Z INF/db:setup 44 [*] Index "devices"."present" is ready
2018-11-05T20:33:34.459Z INF/db:setup 44 [*] Index "devices"."providerChannel" is ready
2018-11-05T20:33:34.468Z INF/util:procutil 38 [*] Forking "/app/lib/cli triproxy app001 --bind-pub tcp://127.0.0.1:7111 --bind-dealer tcp://127.0.0.1:7112 --bind-pull tcp://127.0.0.1:7113"
2018-11-05T20:33:34.476Z INF/util:procutil 38 [*] Forking "/app/lib/cli triproxy dev001 --bind-pub tcp://127.0.0.1:7114 --bind-dealer tcp://127.0.0.1:7115 --bind-pull tcp://127.0.0.1:7116"
2018-11-05T20:33:34.484Z INF/util:procutil 38 [*] Forking "/app/lib/cli processor proc001 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2018-11-05T20:33:34.492Z INF/util:procutil 38 [*] Forking "/app/lib/cli processor proc002 --connect-app-dealer tcp://127.0.0.1:7112 --connect-dev-dealer tcp://127.0.0.1:7115"
2018-11-05T20:33:34.507Z INF/util:procutil 38 [*] Forking "/app/lib/cli reaper reaper001 --connect-push tcp://127.0.0.1:7116 --connect-sub tcp://127.0.0.1:7111"
2018-11-05T20:33:34.516Z INF/util:procutil 38 [*] Forking "/app/lib/cli provider --name c0e4124b1a1c --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip localhost --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"
2018-11-05T20:33:34.527Z INF/util:procutil 38 [*] Forking "/app/lib/cli auth-mock --port 7120 --secret kute kittykat --app-url http://localhost:7100/"
2018-11-05T20:33:34.542Z INF/util:procutil 38 [*] Forking "/app/lib/cli app --port 7105 --secret kute kittykat --auth-url http://localhost:7100/auth/mock/ --websocket-url http://localhost:7110/"
2018-11-05T20:33:34.560Z INF/util:procutil 38 [*] Forking "/app/lib/cli api --port 7106 --secret kute kittykat --connect-push tcp://127.0.0.1:7113 --connect-sub tcp://127.0.0.1:7111"
2018-11-05T20:33:34.579Z INF/util:procutil 38 [*] Forking "/app/lib/cli websocket --port 7110 --secret kute kittykat --storage-url http://localhost:7100/ --connect-sub tcp://127.0.0.1:7111 --connect-push tcp://127.0.0.1:7113"
2018-11-05T20:33:34.596Z INF/util:procutil 38 [*] Forking "/app/lib/cli storage-temp --port 7102"
2018-11-05T20:33:34.619Z INF/util:procutil 38 [*] Forking "/app/lib/cli storage-plugin-image --port 7103 --storage-url http://localhost:7100/"
2018-11-05T20:33:34.650Z INF/util:procutil 38 [*] Forking "/app/lib/cli storage-plugin-apk --port 7104 --storage-url http://localhost:7100/"
2018-11-05T20:33:34.671Z INF/util:procutil 38 [*] Forking "/app/lib/cli poorxy --port 7100 --app-url http://localhost:7105/ --auth-url http://localhost:7120/ --api-url http://localhost:7106/ --websocket-url http://localhost:7110/ --storage-url http://localhost:7102/ --storage-plugin-image-url http://localhost:7103/ --storage-plugin-apk-url http://localhost:7104/"
2018-11-05T20:33:40.051Z INF/triproxy 50 [app001] PUB socket bound on tcp://127.0.0.1:7111
2018-11-05T20:33:40.103Z INF/triproxy 50 [app001] DEALER socket bound on tcp://127.0.0.1:7112
2018-11-05T20:33:40.121Z INF/triproxy 50 [app001] PULL socket bound on tcp://127.0.0.1:7113
2018-11-05T20:33:40.098Z INF/triproxy 51 [dev001] PUB socket bound on tcp://127.0.0.1:7114
2018-11-05T20:33:40.140Z INF/triproxy 51 [dev001] DEALER socket bound on tcp://127.0.0.1:7115
2018-11-05T20:33:40.168Z INF/triproxy 51 [dev001] PULL socket bound on tcp://127.0.0.1:7116
2018-11-05T20:33:41.750Z INF/poorxy 118 [*] Listening on port 7100
2018-11-05T20:33:42.047Z INF/db 57 [*] Connecting to 172.17.0.2:28015
2018-11-05T20:33:42.133Z INF/db 58 [*] Connecting to 172.17.0.2:28015
2018-11-05T20:33:42.180Z INF/reaper 69 [reaper001] Subscribing to permanent channel "*ALL"
2018-11-05T20:33:42.229Z INF/reaper 69 [reaper001] Reaping devices with no heartbeat
2018-11-05T20:33:42.285Z INF/db 69 [reaper001] Connecting to 172.17.0.2:28015
2018-11-05T20:33:42.337Z INF/processor 57 [proc001] App dealer connected to "tcp://127.0.0.1:7112"
2018-11-05T20:33:42.353Z INF/processor 57 [proc001] Device dealer connected to "tcp://127.0.0.1:7115"
2018-11-05T20:33:42.374Z INF/reaper 69 [reaper001] Receiving input from "tcp://127.0.0.1:7111"
2018-11-05T20:33:42.384Z INF/reaper 69 [reaper001] Sending output to "tcp://127.0.0.1:7116"
2018-11-05T20:33:42.456Z INF/processor 58 [proc002] App dealer connected to "tcp://127.0.0.1:7112"
2018-11-05T20:33:42.471Z INF/processor 58 [proc002] Device dealer connected to "tcp://127.0.0.1:7115"
2018-11-05T20:33:43.656Z INF/storage:plugins:image 106 [*] Listening on port 7103
2018-11-05T20:33:43.910Z INF/storage:plugins:apk 112 [*] Listening on port 7104
2018-11-05T20:33:43.911Z INF/provider 70 [*] Subscribing to permanent channel "zZDjPu2MTpSnFj/36tFSmQ=="
2018-11-05T20:33:43.930Z INF/auth-mock 76 [*] Listening on port 7120
2018-11-05T20:33:44.047Z INF/provider 70 [*] Sending output to "tcp://127.0.0.1:7116"
2018-11-05T20:33:44.061Z INF/provider 70 [*] Receiving input from "tcp://127.0.0.1:7114"
Unhandled rejection Error: spawn adb ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
2018-11-05T20:33:44.390Z INF/storage:temp 100 [*] Listening on port 7102
2018-11-05T20:33:44.876Z INF/app 82 [*] Using pre-built resources
2018-11-05T20:33:44.972Z INF/app 82 [*] Listening on port 7105
2018-11-05T20:33:44.982Z INF/db 82 [*] Connecting to 172.17.0.2:28015
2018-11-05T20:33:45.113Z INF/websocket 94 [*] Subscribing to permanent channel "*ALL"
2018-11-05T20:33:45.129Z INF/websocket 94 [*] Listening on port 7110
2018-11-05T20:33:45.134Z INF/db 94 [*] Connecting to 172.17.0.2:28015
2018-11-05T20:33:45.148Z INF/websocket 94 [*] Sending output to "tcp://127.0.0.1:7113"
2018-11-05T20:33:45.150Z INF/websocket 94 [*] Receiving input from "tcp://127.0.0.1:7111"
2018-11-05T20:33:45.475Z INF/api 88 [*] Subscribing to permanent channel "*ALL"
2018-11-05T20:33:45.546Z INF/api 88 [*] Listening on port 7106
2018-11-05T20:33:45.557Z INF/api 88 [*] Sending output to "tcp://127.0.0.1:7113"
2018-11-05T20:33:45.559Z INF/api 88 [*] Receiving input from "tcp://127.0.0.1:7111"
2018-11-05T20:33:45.865Z INF/db 88 [*] Connecting to 172.17.0.2:28015``` just to tell you i am running these in the docker

**Comment by sorccu** [comment]
Seems like a configuration  issue to me. The output you've posted doesn't match the screenshot, as the non-default port 3100 isn't  visible anywhere in it.
